### ISSUE TITLE
[components] Preview Toolbar has scrollbar

### ISSUE THREAD

**Issue by stefanprobst** [storybookjs/storybook#10207]
**Describe the bug**
The DocsPage Preview component Toolbar has a scrollbar when the IconButton's `box-sizing` is not reset to `border-box` somewhere else.

[Toolbar has height 40](https://github.com/storybookjs/storybook/blob/47a932d850a0460f101c69a9c4d09e98bb483a4a/lib/components/src/blocks/Preview.tsx#L132), and [IconButton has height: 40 + 3 border](https://github.com/storybookjs/storybook/blob/next/lib/components/src/bar/button.tsx#L80-L88)

**Screenshots**
![preview-header](https://user-images.githubusercontent.com/20753323/77467806-e93d6800-6e0c-11ea-9f8d-180619665e6f.png)

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.30 containing PR #11055 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by stevenpetryk** [comment]
That PR did not fix this issue—it's still present in the docs view in 6.4.9.

**Comment by ndelangen** [comment]
@matheo can you confirm the issue is still present, and if so investigate an improved fix? 🙏

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
