### ISSUE TITLE
background addon no longer has event support?

### ISSUE THREAD

**Issue by scoorey** [storybookjs/storybook#10604]
If you are reporting a bug or requesting support, start here:
### Bug or support request summary

I want to be notified when the user changes background colours in an event. I saw in the history of the readme file it used to be possible like this (in  .storybook/preview.js:) :

```
import '@storybook/addon-backgrounds/register';
import { addons, types } from '@storybook/addons';
const ADDON_ID = 'background-addon-detectable';

addons.register(ADDON_ID, api => {
  console.log('Background color');
  
  api.getChannel().on('storybook/background/update', (bg) => {
  console.log('Background color', `bg.selected);`
  console.log('Background name', bg.name);
});

});

```
```
addParameters({
  options: {
    name: 'UI Web Components',
    theme: {}
  },
  backgrounds: [
    { name: 'Light', value: '#ffffff', default: true },
    { name: 'Dark', value: '#303030' },
  ],
});
```
When I try to debug this, I don't get the log messages and it never steps into the addons.register statements. Is there another way to do this now? Am I doing something wrong? I want this to be for all stories.

### Steps to reproduce

as per summary. The addParameters works, then when i switch background colours, i expect to see a log message but there is none.

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/react x.x.x
- @storybook/addon-something x.x.x

import '@storybook/addon-knobs/register';
import '@storybook/addon-backgrounds/register';
import { addParameters, configure } from '@storybook/html';
import { boolean, withKnobs, text, number, optionsKnob as options } from '@storybook/addon-knobs';
import { addons, types } from '@storybook/addons';

### Affected platforms 

- _If UI related, please indicate browser, OS, and version_
chrome, windows 10
@storybook/html v5.0.11
Storybook 5.0.11

End bug report support request - delete the rest below

**Comment by shilman** [comment]
Working for me:

https://next--storybookjs.netlify.app/angular-cli/?path=/story/addon-background--background-component

Are you showing verbose logs in your browser console?

**Comment by scoorey** [comment]
That one works for me too (i can see the log messages in my console),
When I look at the source, it doesn't seem to subscribe to storybook/background/update events like the readme file used to say. 

I think it does this instead:
```
  .add('background component', () => ({
    component: AppComponent,
    props: {},
  }))
  .add('background template', () => ({
    template: `<storybook-button-component [text]="text" (onClick)="onClick($event)"></storybook-button-component>`,
    props: {
      text: 'Hello Button',
      onClick: (event: Event) => {
        console.log('some bindings work');
        console.log(event);
      },
    },
  }));
```

I don't understand how that hooks into the dropdown menu's selection events - is it creating an event on a new button for the facebook and twitter options? I already have that dropdown showing and those options without having to explicitly add them to the .js file. Sorry, I'm new to all this.

**Comment by shilman** [comment]
I'm not sure I understand your question.

- The background addon should send events on the channel automatically when you register it. All of our example repos use it. You should see an event logging in the console.
- Writing an addon to consume that event is a separate issue (and one we can help with).

Which one is it?

**Comment by scoorey** [comment]
So the example I've been following is here:
[https://github.com/storybookjs/storybook/tree/master/addons/backgrounds](https://github.com/storybookjs/storybook/tree/master/addons/backgrounds)

I have registered it in my plain old javascript repo like this:
import '@storybook/addon-backgrounds/register';

and added the two backgrounds like the example says:
addParameters({
  backgrounds: [
    { name: 'Light', value: '#ffffff', default: true },
    { name: 'Dark', value: '#303030' },
  ],
});

When I run storybook I can see the options drop down in my application and I can successfully change background colours in the iframe in the middle using it. My goal is to know when the user switches between the background colours. The readme file in the link above no longer has an 'Events' section to show how to listen for when it is switched, but I found old examples by going through the history, which is where I got this from:
```
addons.register(ADDON_ID, api => {  
    api.getChannel().on('storybook/background/update', (bg) => {
    console.log('Background color', `bg.selected);`
    console.log('Background name', bg.name);
   });
});
```
I didnt see any code like that in the source link you posted - is this still the right way to do it? I'm not writing an addon, I just want to switch my own css when the background colour switches, which means I need to consume that event somehow.

Thanks

**Comment by shilman** [comment]
Thanks for the clarification.

In the example I linked to, you can see the events being logged to the console in `verbose` mode. There is no consumer code in that example, those debug messages just get logged as part of the example.

I suspect you'll see the same messages in your setup, which means that the addon is working as expected. If that's the case, your question is really about how to consume the events. And if you're consuming the events, you're effectively writing a second addon. Try running your code snippet in `manager.js`? That might not be exactly what you want, but I'd expect it to work and we can go from there.

**Comment by scoorey** [comment]
So I didn't have verbose logging ticked, but now I do and I still see no log messages. I took a quick video so you can see what I mean: 
https://youtu.be/fgkLlHIAzmE

You'll also see in the video in my .Storybook folder I have a config.js and addons.js as well as a preview-head.html.
The addons.js just registers the addons (backgrounds and knobs) and config.js uses them (addParameters for the backgrounds, and loads each story - I assume this is what you mean by manager,js, but I tried creating a manager.js too and there was no change).

**Comment by shilman** [comment]
Do you have a repro?

**Comment by scoorey** [comment]
I just installed storybook and the addon from scratch on my home pc and it logged out the verbose messages like you said (so it has a main.js and a preview.js instead of the addons.js and config.js at work). I read another of your posts that says that config.js and addons.js are obsolete and you provided a migration guide, so I'll try doing that in the work repository tomorrow. Maybe upgrading the addon to the latest version will help too.

**Comment by scoorey** [comment]
Ok I've done the migration and updated storybook and the addons and now I am seeing the verbose log message in my project, thanks!

I was then able to consume the event by using the code i originally pasted in Manager.js as you suggested, but I had to correct the ADDON_ID to be 'addon-backgrounds'. 

The final step to achieve my goal is to be able to swap the css file used in preview-head.html, and I tried to do it like this:
```

import { addons, types } from '@storybook/addons';

addons.register('addon-backgrounds', api => {
  api.getChannel().on('storybook/background/update', (bg) => {
    if (bg.name == "Dark")
    {
      console.log('bgname is dark');
        changeCSS('../primitives-dark.css', 0);
    }
    else
    {
      console.log('bgname is light');
        changeCSS('../primitives-light.css', 0);
    }

  });
});

function changeCSS(cssFile, cssLinkIndex) {

    var oldlink = document.getElementsByTagName("link").item(cssLinkIndex);

    console.log('the old link is ' + oldlink);

    var newlink = document.createElement("link");
    newlink.setAttribute("rel", "stylesheet");
    newlink.setAttribute("type", "text/css");
    newlink.setAttribute("href", cssFile);

    document.getElementsByTagName("head").item(0).replaceChild(newlink, oldlink);
}

```

It returns the old link as being null because document refers to the individual story inside the iframe, rather than preview-head which has the css link. Is there a way of accessing preview-head document from manager.js? (document.parent is also null)

**Comment by scoorey** [comment]
Solved by accessing the iFrame by id:
document.getElementById("storybook-preview-iframe").contentDocument;

Thanks for your help @shilman

**Comment by rahulvchandwani** [comment]
This is still not working for me in storybookjs version 6.3.8

I am not able to listen to "/storybook/background/update" event.
