### ISSUE TITLE
"Singleton client API not yet initialized"

### ISSUE THREAD

**Issue by gforrest-bw** [storybookjs/storybook#10887]
**Describe the bug**
Page crashes after a successful build, with the message in console:

```
Uncaught Error: Singleton client API not yet initialized, cannot call addParameters
    at addParameters (vendors~main.0d0c22069a536e53e511.bundle.js:67491)
    at Object../node_modules/@storybook/addon-docs/dist/frameworks/common/config.js-generated-other-entry.js (vendors~main.0d0c22069a536e53e511.bundle.js:56317)
    at __webpack_require__ (runtime~main.0d0c22069a536e53e511.bundle.js:849)
    at fn (runtime~main.0d0c22069a536e53e511.bundle.js:151)
    at Object.0 (main.0d0c22069a536e53e511.bundle.js:45532)
    at __webpack_require__ (runtime~main.0d0c22069a536e53e511.bundle.js:849)
    at checkDeferredModules (runtime~main.0d0c22069a536e53e511.bundle.js:46)
    at Array.webpackJsonpCallback [as push] (runtime~main.0d0c22069a536e53e511.bundle.js:33)
    at main.0d0c22069a536e53e511.bundle.js:1
```

I encountered this error while upgrading our 5.x repo to the latest 6 beta, in hopes of discovering if the new default behaviors would help fix our prop tables for Typescript components.

**To Reproduce**
I'm afraid I'm in a private repo. 

I've attempted to reproduce the error with the exact same package versions and configuration in a clean project, to no avail. If a lack of repro is a problem, I understand - I mainly wanted to see if someone familiar with the codebase might be able to give me a hint as to why I'd ever see the error posted above, or how to debug.

**Expected behavior**
I expected Storybook to load in the browser after building.

**Screenshots**

**Code snippets**

*main.js*

```
module.exports = {
  stories: ['../src/**/*.stories.(ts|tsx|js|jsx|mdx)'],
  addons: [
    '@storybook/addon-actions',
    '@storybook/addon-links',
    '@storybook/addon-docs',
  ],
  typescript: {
    check: false,
  },
};
```

I've removed all other configuration for Storybook to try to isolate the problem and test default 'no config' behaviors.

**System:**

```
Environment Info:

  System:
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.13.4 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.1.0
  npmPackages:
    @storybook/addon-actions: ^6.0.0-beta.12 => 6.0.0-beta.12
    @storybook/addon-docs: ^6.0.0-beta.12 => 6.0.0-beta.12
    @storybook/addon-links: ^6.0.0-beta.12 => 6.0.0-beta.12
    @storybook/addons: ^6.0.0-beta.12 => 6.0.0-beta.12
    @storybook/react: ^6.0.0-beta.12 => 6.0.0-beta.12
    @storybook/theming: ^6.0.0-beta.12 => 6.0.0-beta.12
```

**Additional context**

**Comment by shilman** [comment]
have you tried clearing node_modules, and possibly regenerating your lock file?

**Comment by matheo** [comment]
@gforrest-bw check inside your lock file too
it could contain different versions of the same package giving trouble.

**Comment by gforrest-bw** [comment]
I did clear node_modules. I didn't try deleting the lockfile though, good call.

FWIW `npm ls` doesn't appear to turn up duplicates of any Storybook modules.

**Comment by gforrest-bw** [comment]
Deleting the lockfile has at least gotten me to a different error (a React invalid hook call). I'll spend some time investigating it and open a new issue if I can't get past it.

**Comment by tskarhed** [comment]
I can reproduce this in https://github.com/grafana/grafana/tree/storybook-build-optimization
The project root can be found [here](https://github.com/grafana/grafana/tree/master/packages/grafana-ui)


Have tried cleaning lockfile and node_modules - had some version issues

**Comment by shilman** [comment]
@tskarhed can you remove these lines?

https://github.com/grafana/grafana/blob/storybook-build-optimization/packages/grafana-ui/.storybook/preview.ts#L60-L61

They should be implemented in `main.js`:

https://github.com/grafana/grafana/blob/storybook-build-optimization/packages/grafana-ui/.storybook/main.ts#L8

**Comment by matheo** [comment]
@shilman I just got this error while trying to symlink a storybook package of my project to the development dist folder.
To make it work again I just removed the symlink and copied the files manually. So this blocks any possibility to use npm link it seems.

**Comment by tskarhed** [comment]
We found the issue. Using `addon-actions/preset` caused the error, doing `addon-actions/register` fixed it. Very unclear why, though. This was after moving stuff around a lot so it might be something else.

**Comment by shilman** [comment]
@tskarhed that sounds a bit fishy to me, but I'm glad you got it sorted. @tmeasday do you see anything weird here? They are still using `addParameters`/`addDecorators` rather than the named exports -- I just want to make sure we haven't regressed on that.

**Comment by tmeasday** [comment]
@shilman, I'm not sure, this code has been refactored a bit since I worked on it.

This is the important entry that we add to initialize the client API: https://github.com/storybookjs/storybook/blob/next/lib/core/src/server/preview/entries.js#L40

I wonder if [this sorting](https://github.com/storybookjs/storybook/blob/e1880cc7f6045c458dee2d6ff33a2822fd141146/lib/core/src/server/preview/entries.js#L8-L28) is incorrect and doesn't ensure it stays at the top. @ndelangen?

**Comment by ndelangen** [comment]
I'll take a look

**Comment by ndelangen** [comment]
@tskarhed I ran locally, and navigated to a few stories, I'm not seeing the error described in this report. Could you tel me what to do?

The branch is not on the latest version. Could I ask you to try the latest beta and see if the issue is resolved?

**Comment by tskarhed** [comment]
@ndelangen Yeah, we pushed the fix. If you change `addon-actions/register` to `addon-actions/preset` the error will appear in the browser. I will try the latest beta today.

**Comment by MarcusNotheis** [comment]
We are facing the exact same issue in https://github.com/SAP/ui5-webcomponents-react/tree/storybook-issue-repro.
If we add `addon-actions/register` to our main.js the error is gone and Storybook is working perfectly fine. If we just use `addon-actions`, we are facing the Singleton API error as well:
![image](https://user-images.githubusercontent.com/8775211/84001557-25da2380-a967-11ea-8847-ee74c57c3dbd.png)

**Comment by ndelangen** [comment]
@MarcusNotheis I'm taking a look at your repro now.

**Comment by MarcusNotheis** [comment]
> @MarcusNotheis I'm taking a look at your repro now.

Thanks @ndelangen.
I also just recognized that the actions are also not longer working (also tried with beta.23), but I'm not sure whether this is related to that issue as well or a totally different story.

**Comment by matheo** [comment]
@MarcusNotheis I can confirm that Actions work on `beta.23`

**Comment by tmeasday** [comment]
> I also just recognized that the actions are also not longer working (also tried with beta.23), but I'm not sure whether this is related to that issue as well or a totally different story.

If the decorator can't be added that would explain why the actions aren't working I expect?

**Comment by ndelangen** [comment]
The problem is that there are multiple instances of the ClientApi package:
![Screenshot 2020-06-09 at 09 43 43](https://user-images.githubusercontent.com/3070389/84120193-c26af700-aa35-11ea-9982-de372f827c4a.png)

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.24 containing PR #11092 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by MarcusNotheis** [comment]
just upgraded to beta.26 and our Storybook is now working perfectly fine again! Thanks @ndelangen and @shilman!

**Comment by MacRayy** [comment]
I still have the same issue 😢
I updated my storybook packages to the latest version:
```tsx
    "@storybook/addon-actions": "^6.3.6",
    "@storybook/addon-controls": "^6.3.6",
    "@storybook/addon-docs": "^6.3.6",
    "@storybook/addon-knobs": "^6.2.9",
    "@storybook/addon-links": "^6.3.6",
    "@storybook/addon-measure": "^2.0.0",
    "@storybook/addon-options": "^5.3.21",
    "@storybook/addon-toolbars": "^6.3.6",
    "@storybook/addon-viewport": "^6.3.6",
    "@storybook/addons": "^6.3.6",
    "@storybook/builder-webpack5": "^6.3.6",
    "@storybook/react": "^6.3.6",
    "@storybook/storybook-deployer": "^2.8.10",
    "@storybook/theming": "^6.3.6",
    "@storybook/builder-webpack5": "^6.3.6",
    "@storybook/manager-webpack5": "^6.3.6",
```
And I'm using `"react": "^17.0.2"` and `"webpack": "^5.37.1"` with `"dotenv-webpack": "^7.0.2",`.

**Comment by MacRayy** [comment]
The issue is gone after running:
```bash
npm ls | grep client-api

npm dedupe
```

**Comment by gavmck** [comment]
I was also getting this after upgrading to `6.3.6`. `@storybook/addon-knobs` does not update when coming from `6.2.9` as it's deprecated and it still requires `@storybook/client-api` `6.2.9` which causes the conflict.

Just ended up rolling back to 6.2.9 :(

**Comment by shilman** [comment]
@gavmck There's a `@storybook/addon-knobs@6.3.0` that should be compatible with the 6.3 stack

**Comment by gavmck** [comment]
@shilman Yeah I tried that, but no luck unfortunately. I'll come back to it later. Thanks!

**Comment by develar** [comment]
The solution for vite builder — force dedupe (see https://github.com/eirslett/storybook-builder-vite#customize-vite-config):

```
async viteFinal(config, {configType}) {
    config.resolve.dedupe = ["@storybook/client-api"]
    return config
  },
```

**Comment by penx** [comment]
I'm getting this when upgrading to 6.3.8, more info in #16097

**Comment by marksy** [comment]
Hi @penx

**Comment by avennn** [comment]
I had this problem because I had two versions of @storybook/client-api. @storybook/client-api@6.4.9 is dependency of @storybook/builder-webpack5@6.4.9，@storybook/client-api@6.4.8 is dependency of @storybook/*@6.4.8. I updated @storybook/* to v6.4.9，and this problem resolved.
