### ISSUE TITLE
Prop groups for addon-controls panels

### ISSUE THREAD

**Issue by sami616** [storybookjs/storybook#10979]
Similar to `addon-knobs` it would be fantastic to be able to split props up into different tabs, this comes in very useful for components that use sub components, ie: `Accordion` and `AccordionItem`.

Would a similar approach to `addon-knobs` of assigning a `groupId` would work?

**Comment by shilman** [comment]
I think you can do this already with an undocumented API. I'd like to think it through and make sure it's a coherent design before documenting it and committing to support it though.

Right now there are so many different possible groupings:
- by component (via tabs, but only the first tab gets controls currently)
- by interface for typescript inheritance in #9110 (not yet merged)
- by category (e.g. inputs/slots/events/etc. in various frameworks, "just props" in react)
- by user grouping potentially according to this issue

This might end up being more of a design issue than a technical one @domyen @tmeasday. I think we're in a pretty good place technically to have the data we need to do something interesting here, both automatically and also user controlled.

**Comment by sami616** [comment]
Oh okay I tried passing ‘groupId’ as a property in ‘argTypes’ but nada!

**Comment by shilman** [comment]
Yeah that’s not the undocumented API 😈

**Comment by domyen** [comment]
Will do a pass at Storybook design stuff this week. Will try to fit the groupings/tabs in depending on scope.

**Comment by sami616** [comment]
Thank you @domyen !!!!

**Comment by domyen** [comment]
Working on this issue here https://github.com/storybookjs/storybook/pull/11216

**Comment by sami616** [comment]
Just wondering if there is any documentation kicking around for how to handle subcomponent controls in SB6? @shilman mentioned some kind of "undocumented API" for this.

**Comment by shilman** [comment]
Did I? At one point I'd implemented something for that, but I removed it for simplicity. Right now you can either get autogenerated controls for the top-level component (in frameworks that support it) and/or you can manually define args/controls and how those values get translated into subcomponent instances. But there's no explicit support for subcomponent controls.

Related: https://github.com/storybookjs/storybook/issues/11525

**Comment by sami616** [comment]
Okay, good to know. Is it worth me reopening this issue as a feature request? 🤔

**Comment by shilman** [comment]
Sure, that would be awesome. The more you can specify the desired behavior, the better. I can't actually think of a well-defined version of the feature, which is why I removed what I'd implemented.

**Comment by philipbordallo** [comment]
My team ran into this as well when trying to move from `addon-knobs` to `addon-controls`.

Some thoughts:
- `addon-knobs` are much more freeform, it's all on the developer to make the decision about what is a knob and what is grouped together. 
- `addon-controls` feel linked directly to the component because the `args` are generated from the components definition that is set in the story config. It can be customized, but that ends up being more of secondary addition/action.

If `addon-controls` are more about being linked to a component then the act of defining additional panels/groups should be linked to them as well. What if it's based on `subcomponents`? This is already a defined with `addon-docs` which will give you a tab panel for each subcomponent in the documentation. 

Here is rough concept of how this would play out with a List component that ends up having two other components that can be composed with it:
```js
export default {
  title: 'List',
  component: List,
  subcomponents: [ListItem, ListLink],
};

// Custom args as consts so they can be more descriptive, re-used, and differentiate themselves from normal args
const ITEM_TYPE = 'Item Type'

const ITEM_LABEL = 'Item Label (children)'
const ITEM_ICON = 'Item Icon (children)'

// Example story with a 3rd parameter that is an array of subArgs which can be destructured 
// listItemArgs would end up having all the defined props of subcomponents[0] aka ListItem plus anything defined in Example.subArgs[0]
// listLinkArgs would end up having all the defined props of subcomponents[1] aka ListLink plus anything defined in Example.subArgs[1]
export const Example = (args, context, [ listItemArgs, listLinkArgs ]) => (
  <List {...args}>
    { args[ITEM_TYPE] === 'link' ? (
      <ListItem { ...listItemArgs }>
        { listItemArgs[ITEM_ICON] && (
          <Icon name={listItemArgs[ITEM_ICON]} />
        ) }
        { listItemArgs[ITEM_LABEL] }
      </ListItem>
    ) : (
      <ListLink { ...listLinkArgs }>
        { listLinkArgs[ITEM_ICON] && (
          <Icon name={listLinkArgs[ITEM_ICON]} />
        ) }
        { listLinkArgs[ITEM_LABEL] }
      </ListLink>
    ) }
  </List>
)

Example.args = {
  [ITEM_TYPE]: 'normal',
}

Example.argTypes = {
  [ITEM_TYPE]: {
    control: {
      type: 'select',
      options: [null, 'normal', 'link'],
    },
  },
}

// The subArgs would end up modeling themselves after args but instead be an array that matches up to the subcomponents passed. 
// So subArgs[0] is describing subcomponents[0], subArgs[1] is describing subcomponents[1], etc.
Example.subArgs = [
  // ListItem
  {
    [ITEM_LABEL]: 'Item',
    [ITEM_ICON]: null,
  },
  //ListLink
  {
    [ITEM_LABEL]: 'Item',
    [ITEM_ICON]: null,
  },
]

// Just like args have argTypes, subArgs should have subArgTypes with the similar array pattern
Example.subArgTypes = [
  // ListItem
  {
    [ITEM_LABEL]: {
      control: {
        type: 'text',
      },
    },
    [ITEM_ICON]: {
      control: {
        type: 'select',
        options: [null, 'external', 'home', 'settings'],
      },
    },
  },
  // ListLink
  {
    [ITEM_LABEL]: {
      control: {
        type: 'text',
      },
    },
    [ITEM_ICON]: {
      control: {
        type: 'select',
        options: [null, 'external', 'home', 'settings'],
      },
    },
  },
]
```

**Comment by sami616** [comment]
Great to see some activity again here. This is still the one feature I feel is missing with controls. I suggested an api like this a while ago, not sure how plausible it is but I quite like it's simplicity.

![image](https://user-images.githubusercontent.com/21065581/94360539-e5cdb680-00a5-11eb-8058-0f7f2b4db15a.png)

**Comment by monolithed** [comment]
@sami616 There is an alternative proposal https://github.com/storybookjs/storybook/issues/12871

**Comment by christianwiedemann** [comment]
Hi all, just want to know if this will be part of 6.2. 

Thanks for the info!

**Comment by sami616** [comment]
Did this ever make it onto the roadmap for a future release?

**Comment by shilman** [comment]
@sami616 was hoping to get it into 6.2 but we ran out of time. We plan to continue to work on all this in 6.3, but haven't prioritized yet.

**Comment by DaniGuardiola** [comment]
My two cents: I'd love to be able to combine the automatic controls inference with this. For example, I'd like to be able to process the generated controls data and add some kind of groupId property to them, using my own logic. I'd also like to be able to define an order for the groups somehow. This'd give me a lot of freedom and the API would be very minimal.

In my specific case, for example, among other things I'd like to be able to group all `aria-` props in an `a11y` group and put it at the end of the controls -or as the last tab, I don't really care about the UI that much. Other categories that come to mind are "appearance", "events", "state" or "config". The subcomponent use case that was already mentioned is also relevant for some components.

Just sharing a few suggestions / examples, hopefully this helps with the design!

**Comment by RicardJoenck** [comment]
Any updates on this work?

**Comment by ericfirth** [comment]
:+1:  to this feature. This would really help. We've kept both knobs and controls because of the lack of this feature.

An example of the usecase I have is that we have a story for a specific card component that is associated with one of our domain models (in this case it's the card for real estate listing to go to the show page for said listing). So we want to group the controls so that there are 3 groupings that are able to be kept separate:
* attributes of our domain model 
* props that are specific to how the user can interact with the card (based on their permissions and access)
* props that are about the appearance of the card.

**Comment by shilman** [comment]
@thany Migrating from knobs to controls has been a challenge for storybook users and maintainers alike. 

Some things that were easy to do in knobs, like manually specify a grouping, are less clear in controls, where the controls are automatically inferred from your components and grouping is done automatically for most frameworks (e.g. "props" vs "events" vs "slots").

Reconciling all this is at the top of the list when it comes to controls. However, our focus has been on improving Storybook's performance and migrating to webpack5, which has been even more pressing.

> Why is it taking MONTHS to build a feature that already existed? This feature shouldn't have been removed in the first place. Who thought this was a good idea?

Complaining about the development speed of a software project that's completely free to use, free to modify, and that you have made zero contributions to is one of the most entitled things you can do in open source.

If controls doesn't do what you need, please feel free to continue to use knobs, or even fork the package and maintain it yourself.

**Comment by estubmo** [comment]
Would like an update on whether this is a planned feature or not.

**Comment by EliezerB123** [comment]
> I think you can do this already with an undocumented API. I'd like to think it through and make sure it's a coherent design before documenting it and committing to support it though.
> 
> Right now there are so many different possible groupings:
> 
> * by component (via tabs, but only the first tab gets controls currently)
> * by interface for typescript inheritance in [Addon-docs: Typescript inherited prop types #9110](https://github.com/storybookjs/storybook/pull/9110) (not yet merged)
> * by category (e.g. inputs/slots/events/etc. in various frameworks, "just props" in react)
> * by user grouping potentially according to this issue


@shilman 
Can you tell us more about the undocumented API you mentioned a few years ago?

At this point, a work-around would be great.

**Comment by thany** [comment]
> Would like an update on whether this is a planned feature or not.

Personally I don't care if it's a planned feature or not. If it's not planned, then plan it.

**Comment by DaveLak** [comment]
@shilman Please correct me if I'm wrong, but it seems the request at the root of this issue has been addressed with [ArgsTable Grouping](https://storybook.js.org/docs/react/writing-docs/doc-block-argstable#grouping) support? Based on the commit that updated the ArgsTable docs (195faebb255ed3d95a06c8e5c0b8c629c3fb3c6c), this has been available since `v6.5.0-alpha.43`.

If that's the case, this issue can probably be closed.

**Comment by shilman** [comment]
Thanks @DaveLak ! Closing

**Comment by EdenEdk** [comment]
I think it still doesn't solves the requirment mentioned above.
The grouping is a mare UI grouping but no logical..
Correct me if im wrong but, how can you receive the args by category when rendering the component?

Lets say i have 2 properties with the same name in 2 different categories.

It wont work.

**Comment by dtaub** [comment]
Sorry to comment on an old issue, I can open a new one if necessary but... was this ever actually added? I don't see anything documented about anything equivalent to `groupId` from addon-knobs. I'm happy to be corrected if I'm mistaken. 🙏

**Comment by nickadamson** [comment]
for @dtaub & anyone else that stumbles across this issue:
(using  storybook*@8.0.0-alpha.16)
```tsx
const meta: Meta<typeof Component> = {
  title: "Component",
  component: Component,
  tags: ["autodocs", "a11y"],
  argTypes: {
    prop1: {
      type: "boolean",
      table: {
        category: "foo",
        subcategory: "bar",
      },
    },
    prop2: {
      type: "boolean",
      table: {
        category: "foo",
        subcategory: "baz",
      },
    },
  },
};
```
![image](https://github.com/storybookjs/storybook/assets/80008674/a5e3887a-b9ca-4a21-84a7-a48703f87ef5)
