### ISSUE TITLE
Controls: select control not showing default value on dropdown input when first loaded

### ISSUE THREAD

**Issue by davidbq** [storybookjs/storybook#11007]
**Describe the bug**
I'm replacing `knobs` by the new addon `controls` version `6.0.0-beta.20`. I'm using the control type `select` and, for `options`, I'm passing an `object` so I can set custon names for the different alternatives. Everything seems to be working fine but when I assign the `defaultValue`, the option set as default is not displayed on the dropdown-input when first loaded, instead, it displays an empty string/white backgorund (the default value is set properly though):

```javascript
  data: {
    control: {
      type: 'select',
      options: { WithData: ['data'], WithoutData: [], WithWrongData: 'data' },
    },
    defaultValue: ['data'],
  },
```

**Actual behavior**
![actual](https://user-images.githubusercontent.com/6732229/83446540-1e8ab580-a44f-11ea-92f1-57ea9056c2eb.jpg)

**Expected behavior**
![expected](https://user-images.githubusercontent.com/6732229/83446966-efc10f00-a44f-11ea-8e57-124531f1db4b.jpg)

**System:**
```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.13.4 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Safari: 13.1.1
  npmPackages:
    @storybook/addon-actions: 6.0.0-beta.20 => 6.0.0-beta.20 
    @storybook/addon-controls: 6.0.0-beta.20 => 6.0.0-beta.20 
    @storybook/addon-docs: 6.0.0-beta.20 => 6.0.0-beta.20 
    @storybook/addon-links: 6.0.0-beta.20 => 6.0.0-beta.20 
    @storybook/addon-storyshots: 6.0.0-beta.20 => 6.0.0-beta.20 
    @storybook/addons: 6.0.0-beta.20 => 6.0.0-beta.20 
    @storybook/react: 6.0.0-beta.20 => 6.0.0-beta.20 
```

**Comment by shilman** [comment]
Closing as dupe to #10855

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.21 containing PR #11024 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by raulmontejo** [comment]
Still seeing this behavior in `6.0.27`

**Comment by AurelienDud** [comment]
Dunno what changed but the selector still doesn't work correctly. Even with the example given by the official documentation
