### ISSUE TITLE
@storybook/vue floods my console with peer dependency warnings on every upgrade

### ISSUE THREAD

**Issue by vvanpo** [storybookjs/storybook#11492]
**Describe the bug**

Installing `@storybook/vue` 6 generates a lot of peer dependency warnings, mostly for React and Typescript dependencies. My project uses neither of those things, so it's odd that I'm expected to supply them. If `@storybook/core` or the like has a dependency on React, it would be reasonable for `@storybook/vue` to fulfill that dependency in its package definition, rather than propagating the missing dependency upwards. I'm also confused about the Typescript dependency, because I would hope that Storybook isn't depending on its consumer to compile its Typescript files?

**To Reproduce**

1. `mkdir temp; cd temp;`
2. Follow the [documented manual install steps](https://storybook.js.org/docs/guides/guide-vue/#step-1-add-dependencies), but use the `next` tag: `yarn add -D @storybook/vue@next vue-loader vue-template-compiler @babel/core babel-loader babel-preset-vue`
3. Observe warnings:
```
warning "@storybook/vue > ts-loader@6.2.2" has unmet peer dependency "typescript@*".                                                                                              
warning "@storybook/vue > @storybook/addons@6.0.0-rc.1" has unmet peer dependency "react@*".                                                                                      
warning "@storybook/vue > @storybook/addons@6.0.0-rc.1" has unmet peer dependency "react-dom@*".                                                                                  
warning "@storybook/vue > @storybook/addons > @storybook/router@6.0.0-rc.1" has unmet peer dependency "react@*".                                                                  
warning "@storybook/vue > @storybook/addons > @storybook/router@6.0.0-rc.1" has unmet peer dependency "react-dom@*".                                                              
warning "@storybook/vue > @storybook/addons > @storybook/api@6.0.0-rc.1" has unmet peer dependency "react-dom@*".                                                                 
warning "@storybook/vue > @storybook/addons > @storybook/theming@6.0.0-rc.1" has unmet peer dependency "react@*".                                                                 
warning "@storybook/vue > @storybook/addons > @storybook/theming@6.0.0-rc.1" has unmet peer dependency "react-dom@*".                                                             
warning "@storybook/vue > @storybook/core@6.0.0-rc.1" has unmet peer dependency "react@*".                                                                                        
warning "@storybook/vue > @storybook/core@6.0.0-rc.1" has unmet peer dependency "react-dom@*".                                                                                    
warning "@storybook/vue > @storybook/addons > @storybook/router > @reach/router@1.3.4" has unmet peer dependency "react@15.x || 16.x || 16.4.0-alpha.0911da3".                    
warning "@storybook/vue > @storybook/addons > @storybook/router > @reach/router@1.3.4" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".                
warning "@storybook/vue > @storybook/addons > @storybook/theming > @emotion/core@10.0.28" has unmet peer dependency "react@>=16.3.0".                                             
warning "@storybook/vue > @storybook/addons > @storybook/theming > @emotion/styled@10.0.27" has unmet peer dependency "react@>=16.3.0".                                           
warning "@storybook/vue > @storybook/addons > @storybook/theming > emotion-theming@10.0.27" has unmet peer dependency "react@>=16.3.0".                                           
warning " > babel-loader@8.1.0" has unmet peer dependency "webpack@>=2".                                                                                                          
warning "@storybook/vue > @storybook/core > @storybook/client-api@6.0.0-rc.1" has unmet peer dependency "react@*".                                                                
warning "@storybook/vue > @storybook/core > @storybook/client-api@6.0.0-rc.1" has unmet peer dependency "react-dom@*".                                                            
warning "@storybook/vue > @storybook/core > @storybook/components@6.0.0-rc.1" has unmet peer dependency "react@*".                                                                
warning "@storybook/vue > @storybook/core > @storybook/components@6.0.0-rc.1" has unmet peer dependency "react-dom@*".                                                            
warning "@storybook/vue > @storybook/addons > @storybook/router > @reach/router > create-react-context@0.3.0" has unmet peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".    
warning "@storybook/vue > @storybook/addons > @storybook/theming > @emotion/styled > @emotion/styled-base@10.0.31" has unmet peer dependency "react@>=16.3.0".                    
warning " > @storybook/vue@6.0.0-rc.1" has unmet peer dependency "css-loader@*".                                                                                                  
warning " > @storybook/vue@6.0.0-rc.1" has unmet peer dependency "react@*".                                                                                                       
warning " > @storybook/vue@6.0.0-rc.1" has unmet peer dependency "react-dom@*".                                                                                                   
warning " > @storybook/vue@6.0.0-rc.1" has unmet peer dependency "ts-loader@^6.2.2".                                                                                              
warning " > @storybook/vue@6.0.0-rc.1" has unmet peer dependency "vue@^2.6.8".                                                                                                    
warning " > vue-loader@15.9.3" has unmet peer dependency "css-loader@*".                                                                                                          
warning " > vue-loader@15.9.3" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".                                                                                  
warning " > babel-loader@8.1.0" has unmet peer dependency "webpack@>=2".
```

**Comment by vvanpo** [comment]
I should also note that the `babel-preset-vue` dependency in the documentation isn't actually listed as a peer dependency: https://github.com/storybookjs/storybook/blob/v6.0.0-rc.1/app/vue/package.json#L54
It's also unmaintained and only relevant for JSX, so I don't think most users will actually need it.

**Comment by vvanpo** [comment]
I should also note that these warnings appear to be unnecessary, I've been using Storybook 6 for a while and have just ignored those warnings, I'm just reminded of them every time I `yarn upgrade`.

If I do `yarn why react`, it'll tell me it's being hoisted from a number of sources:
```
=> Found "react@16.13.1"
info Reasons this module exists
   - "@storybook#vue#@storybook#core#@storybook#ui" depends on it
   - Hoisted from "@storybook#vue#@storybook#core#@storybook#ui#react"
   - Hoisted from "@storybook#vue#@storybook#core#@storybook#components#react"
   - Hoisted from "@storybook#vue#@storybook#core#@storybook#api#react"
```

What's even more odd is that `@storybook/vue` lists `ts-loader` both as a dependency and a peer dependency: https://github.com/storybookjs/storybook/blob/v6.0.0-rc.1/app/vue/package.json#L44-L60

It complains about not having `typescript`, which is legit because `yarn why typescript` comes up empty. But Storybook has been working just fine without it, so clearly it is not needed.

**Comment by BPScott** [comment]
Tagging various peer dependencies as optional I think would help some of the warnings under storybook's control: https://github.com/yarnpkg/rfcs/blob/master/accepted/0000-optional-peer-dependencies.md

I think the inverse

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.7 containing PR #11628 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by allanlewis** [comment]
We just upgraded from 5.x to 6.1.21 and we're still getting a bunch of warnings from `yarn` like this:

    warning "@storybook/addon-actions > @storybook/addons@6.1.21" has unmet peer dependency "react@^16.8.0 || ^17.0.0".

This is despite `react@16.13.1` being installed, so I'm not sure what's going on.

**Comment by gburning** [comment]
Problem remains here as well in 6.1.21. Our project uses neither typescript, react nor react-dom but I still get flooded with warnings about missing peer dependencies for those.

```
warning "workspace-aggregator-xxx > flattr-shared > @storybook/addon-a11y > @storybook/theming > @emotion/core@10.1.1" has unmet peer dependency "react@>=16.3.0".
```

Could this be a problem with yarn? https://github.com/yarnpkg/yarn/issues/5810

Unfortunately we're unable to upgrade to the latest version of yarn until we can upgrade 
to webpack 5. Which I believe will be possible once storybook 6.2 is out?

Either way, any input on this would be appreciated. Because of the flood of warnings I find myself easily missing any legitimate ones.

**Comment by Narretz** [comment]
I think this has to do with how yarn handles peerDependencies: https://github.com/yarnpkg/yarn/issues/5347#issuecomment-463038189

Basically, even though package A depends directly on B and C, and B also has a peer dependency on C, yarn will say that the peer dep isn't fulfilled, because hoisting C isn't guaranteed.

In storybook's case, the problem with an example:

```
package.json
@storybook/vue
@storybook/addon-actions
```
will give you: 
`warning "@storybook/addon-actions > @storybook/api@6.2.9" has unmet peer dependency "rea
ct@^16.8.0 || ^17.0.0".` (and others)

That's because `@storybook/vue` has a direct dependency on `react` while `@storybook/api` has a peer dependency on it.
And what about `@storybook/addon-actions` ? This package has its peer dependency on react marked as optional.

```
  "peerDependencies": {
    "react": "^16.8.0 || ^17.0.0",
    "react-dom": "^16.8.0 || ^17.0.0"
  },
  "peerDependenciesMeta": {
    "react": {
      "optional": true
    },
    "react-dom": {
      "optional": true
    }
  },
```

This was done in https://github.com/storybookjs/storybook/commit/89d0ed9b7d008284f6db3252dabe50408c809424, I guess as a fix for this issue.

So I think `@storybook/api` etc. also need this peer dependency as marked optional.

Meanwhile, you can silence these warnings by depending on the packages directly in your own project. react and react-dom silence 95% of the warnings for me.

**Comment by ndelangen** [comment]
> So I think @storybook/api etc. also need this peer dependency as marked optional or marked as a direct dependency because the package quite clearly uses react directly.

Yes, Reasoning is that we try and prevent multiple versions to be installed.

**Comment by Narretz** [comment]
So that means these additional packages can be fixed in the same way, right? Should I open a new issue for this? Or should this ticket be reopenend?

**Comment by ndelangen** [comment]
I don't know what to do here, honestly.

@shilman any advice?

**Comment by daviddelusenet** [comment]
I'm also experiencing this issue, getting this:

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   peerOptional react@"^16.8.0 || ^17.0.0" from @storybook/addon-actions@6.2.9
npm ERR!   node_modules/@storybook/addon-actions
npm ERR!     dev @storybook/addon-actions@"^6.2.9" from the root project
npm ERR!     @storybook/addon-actions@"6.2.9" from @storybook/addon-essentials@6.2.9
npm ERR!     node_modules/@storybook/addon-essentials
npm ERR!       dev @storybook/addon-essentials@"^6.2.9" from the root project
npm ERR!   peerOptional react@"^16.8.0 || ^17.0.0" from @storybook/addon-essentials@6.2.9
npm ERR!   node_modules/@storybook/addon-essentials
npm ERR!     dev @storybook/addon-essentials@"^6.2.9" from the root project
npm ERR!   14 more (@storybook/addon-links, @storybook/addons, react-dom, ...)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"15.x || 16.x || 16.4.0-alpha.0911da3" from @reach/router@1.3.4
npm ERR! node_modules/@storybook/api/node_modules/@reach/router
npm ERR!   @reach/router@"^1.3.4" from @storybook/api@6.2.9
npm ERR!   node_modules/@storybook/api
npm ERR!     @storybook/api@"6.2.9" from @storybook/addon-actions@6.2.9
npm ERR!     node_modules/@storybook/addon-actions
npm ERR!       dev @storybook/addon-actions@"^6.2.9" from the root project
npm ERR!       1 more (@storybook/addon-essentials)
npm ERR!     7 more (@storybook/addon-essentials, @storybook/addons, ...)
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Not even using React...

**Comment by shilman** [comment]
@merceyz does @Narretz 's description of the situation make sense? https://github.com/storybookjs/storybook/issues/11492#issuecomment-829082201

If so, would it be reasonable to mark the `react`/`react-dom` peer dependencies as optional in our addons just to silence the warnings?

**Comment by merceyz** [comment]
It would for sure silence them but if the user is installing the addons and the resolve happens from there it will be rely on hoisting, but since you have an alias for `react` and `react-dom` to an absolute path it should be fine™ either way

**Comment by Ashimriat** [comment]
It's kinda offtopic, but currently I'm using storybook@vue3 package with yarn 2, and it just fails with following:
```
WARN   Failed to load preset: "C:\\Users\\ya\\Desktop\\projects\\web-editor-client\\.yarn\\$$virtual\\@storybook-manager-webpack5-virtual-0d65fcb9a2\\0\\cache\\@storybook-manager-webpack5-npm-6.3.2-e0d5734b2d-8dc042f35f.zip\\node_modules\\@storybook\\manager-webpack5\\dist\\cjs\\presets\\manager-preset.js"
ERR! Error: @storybook/ui tried to access react (a peer dependency) but it isn't provided by your application; this makes the require call ambiguous and unsound.
ERR! 
ERR! Required package: react (via "react\package.json")
```
To me it seems kinda related to this issue. Any ideas on fix?

**Comment by ryanmstokes** [comment]
Was this issue ever resolved? I also have many storybook peer dependencies errors...

**Comment by daemswibowo** [comment]
I'm facing this issue too on addons, im running this with @storybook/vue 
```
warning "@storybook/addon-actions > @storybook/addons@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/addons@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/api@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/api@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/theming@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/theming@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-links > @storybook/router@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-links > @storybook/router@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components > markdown-to-jsx@7.1.3" has unmet peer dependency "react@>= 0.14.0".
warning "@storybook/addon-actions > @storybook/components > react-popper-tooltip@3.1.1" has unmet peer dependency "react@^16.6.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components > react-popper-tooltip@3.1.1" has unmet peer dependency "react-dom@^16.6.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components > react-syntax-highlighter@13.5.3" has unmet peer dependency "react@>= 0.14.0".
warning "@storybook/addon-actions > @storybook/components > react-textarea-autosize@8.3.3" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components > react-popper-tooltip > react-popper@2.2.5" has unmet peer dependency "react@^16.8.0 || ^17".
warning "@storybook/addon-actions > @storybook/components > react-colorful@5.4.0" has unmet peer dependency "react@>=16.8.0".
warning "@storybook/addon-actions > @storybook/components > react-colorful@5.4.0" has unmet peer dependency "react-dom@>=16.8.0".
warning "@storybook/addon-actions > @storybook/components > react-textarea-autosize > use-composed-ref@1.1.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components > react-textarea-autosize > use-latest@1.2.0" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > react-inspector@5.1.1" has unmet peer dependency "react@^16.8.4 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/components > react-textarea-autosize > use-latest > use-isomorphic-layout-effect@1.1.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/client-api@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-actions > @storybook/client-api@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > storybook-addon-outline@1.4.1" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > storybook-addon-outline@1.4.1" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-measure@2.0.0" has unmet peer dependency "@storybook/components@^6.3.0".
warning "@storybook/addon-essentials > @storybook/addon-measure@2.0.0" has unmet peer dependency "@storybook/core-events@^6.3.0".
warning "@storybook/addon-essentials > @storybook/addon-measure@2.0.0" has unmet peer dependency "@storybook/theming@^6.3.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > react-element-to-jsx-string@14.3.2" has unmet peer dependency "react@^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1".
warning "@storybook/addon-essentials > @storybook/addon-docs > react-element-to-jsx-string@14.3.2" has unmet peer dependency "react-dom@^0.14.8 || ^15.0.1 || ^16.0.0 || ^17.0.1".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @mdx-js/react@1.6.22" has unmet peer dependency "react@^16.13.1 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/source-loader@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/source-loader@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/core-server@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/core-server@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/builder-webpack4 > @storybook/ui@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/core-client@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/core-client@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/core-client@6.3.8" has unmet peer dependency "webpack@*".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/core-server > @storybook/manager-webpack4@6.3.8" has unmet peer dependency "react@^16.8.0 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/core > @storybook/core-server > @storybook/manager-webpack4@6.3.8" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0".
warning "@storybook/manager-webpack5 > @storybook/ui > react-draggable@4.4.4" has unmet peer dependency "react@>= 16.3.0".
warning "@storybook/manager-webpack5 > @storybook/ui > react-draggable@4.4.4" has unmet peer dependency "react-dom@>= 16.3.0".
warning "@storybook/manager-webpack5 > @storybook/ui > downshift@6.1.7" has unmet peer dependency "react@>=16.12.0".
```

**Comment by doutatsu** [comment]
This has been an issue for ages now. Bumping this up again, I'd like to stop seeing this useless warnings

**Comment by vidyakin** [comment]
The problem is still here

**Comment by wadefletch** [comment]
Checking in again in September.

**Comment by nikki-cat** [comment]
We're having this issue. 

Installed storybook in my vue3 project with Yarn, and I'm getting Peer Dependency warnings. Note: I installed the version: 7.0.0-alpha.35.

**Comment by gduliscouet-ubitransport** [comment]
I think the issue was closed by mistake (because maybe the issue was only partially fixed) ?

@shilman @merceyz if those stroybook addons are used on a Vue project, and it works, then for me yes it seems reasonable to mark `react` and `react-dom` dependencies as optionnal. But maybe I'm missing something ?

For now, the only workaround we have, if we want to keep yarn warnings readable, is to install `react` and `react-dom` in our Vue project. Which is not ideal, it slows the install step and will for sure confuse other devs.

It would be great if we can continue the discussion on this issue :)

**Comment by Psycarlo** [comment]
Still have the issue. So annoying...

`
warning " > @storybook/addons@6.5.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning " > @storybook/addons@6.5.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/api@6.5.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/api@6.5.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components@6.5.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > @storybook/components@6.5.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning " > @storybook/theming@6.5.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning " > @storybook/theming@6.5.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-actions > react-inspector@5.1.1" has unmet peer dependency "react@^16.8.4 || ^17.0.0".
warning "@storybook/addon-links > @storybook/router@6.5.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-links > @storybook/router@6.5.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-essentials > @storybook/core-common@6.5.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-essentials > @storybook/core-common@6.5.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @mdx-js/react@1.6.22" has unmet peer dependency "react@^16.13.1 || ^17.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/preview-web@6.5.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/preview-web@6.5.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/source-loader@6.5.14" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/addon-essentials > @storybook/addon-docs > @storybook/source-loader@6.5.14" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning " > babel-loader@8.2.3" has unmet peer dependency "webpack@>=2".
warning "@storybook/builder-vite > @storybook/core-common@6.5.12" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/builder-vite > @storybook/core-common@6.5.12" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/builder-vite > @storybook/source-loader@6.5.12" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/builder-vite > @storybook/source-loader@6.5.12" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/builder-vite > @vitejs/plugin-react@2.1.0" has incorrect peer dependency "vite@^3.0.0".
warning "@storybook/builder-vite > @storybook/source-loader > @storybook/addons@6.5.12" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/builder-vite > @storybook/source-loader > @storybook/addons@6.5.12" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/builder-vite > @storybook/source-loader > @storybook/addons > @storybook/api@6.5.12" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/builder-vite > @storybook/source-loader > @storybook/addons > @storybook/api@6.5.12" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/builder-vite > @storybook/source-loader > @storybook/addons > @storybook/router@6.5.12" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/builder-vite > @storybook/source-loader > @storybook/addons > @storybook/router@6.5.12" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/builder-vite > @storybook/source-loader > @storybook/addons > @storybook/theming@6.5.12" has unmet peer dependency "react@^16.8.0 || ^17.0.0 || ^18.0.0".
warning "@storybook/builder-vite > @storybook/source-loader > @storybook/addons > @storybook/theming@6.5.12" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
warning " > @storybook/vue3@6.5.14" has unmet peer dependency "@vue/compiler-sfc@^3.0.0".
warning " > vue-loader@16.8.3" has unmet peer dependency "webpack@^4.1.0 || ^5.0.0-0".
warning " > @vitejs/plugin-vue@4.0.0" has incorrect peer dependency "vue@^3.2.25".
warning " > @vue/eslint-config-prettier@6.0.0" has incorrect peer dependency "eslint-plugin-prettier@^3.1.0".
warning " > @vue/eslint-config-typescript@9.0.0" has incorrect peer dependency "eslint-plugin-vue@^7.17.0".
`
