### ISSUE TITLE
Storybook 6.0: viewport not being set on initial load

### ISSUE THREAD

**Issue by lifeiscontent** [storybookjs/storybook#11548]
**Describe the bug**
Viewport is not set on. the story on initial load:

https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-viewport-custom-default-kindle-fire-2--overridden-via-with-viewport-parameterized-decorator

**To Reproduce**
1. Go to link
2. see the viewport not being set

**Expected behavior**
I expect viewport addon to set proper viewport

**Screenshots**
<img width="577" alt="Screen Shot 2020-07-14 at 7 32 18 PM" src="https://user-images.githubusercontent.com/180963/87496605-c8da2900-c608-11ea-8fb0-34a528b7f4c6.png">
<img width="1475" alt="Screen Shot 2020-07-14 at 7 32 28 PM" src="https://user-images.githubusercontent.com/180963/87496608-c972bf80-c608-11ea-897d-a8d77bee65f4.png">

**Code snippets**
```js
  viewport: {
    viewports: {
      mobile: {
        name: 'Mobile',
        styles: {
          width: '360px',
          height: '640px',
        },
        type: 'mobile',
      },
    },
    defaultViewport: 'mobile',
  },
```

**System:**
Please paste the results of `npx -p @storybook/cli@next sb info` here.

**Additional context**

**Comment by shilman** [comment]
Confirmed that this is a regression 6.0. Here's the 5.3 version https://storybookjs.netlify.app/official-storybook/?path=/story/addons-viewport-custom-default-kindle-fire-2--overridden-via-with-viewport-parameterized-decorator

**Comment by ndelangen** [comment]
I'm on it

**Comment by smilelmz** [comment]
I also encountered this problem in version 6.0.3. Has this problem been fixed

**Comment by shilman** [comment]
nope, still open ☝️

**Comment by trustthe27** [comment]
Sometimes the initialization of the viewport works, some times it doesn't.

What is reproducible for me is, that calling the storybook root path switches to the configured default path ('iphone6'), but reloading on a specific component (or entering the URL of a specific component) defaults to 'responsive'.

**Example**

Works: https://www.egonoid.com/storybook/
Doesn't work: https://www.egonoid.com/storybook/?path=/story/components-content-bio--default

**Comment by agrohs** [comment]
Any update/projected release or ETA on this by chance? (not rushing, just asking for planning purposes)

**Comment by ndelangen** [comment]
yeah, should be good

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.24 containing PR #11627 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by hmarchadour** [comment]
![cap 99](https://user-images.githubusercontent.com/1506357/99184850-3e384080-2746-11eb-833c-a42cab4a199b.png)

**Comment by tregoning** [comment]
Just heads up that it looks like this problem persist in MDX. (6.1.6)

e.g. 

```
<Story
    name="responsive"
    parameters={{
        viewport: {defaultViewport: 'ipad'}
    }}
>
    {Template.bind({})}
</Story>
```

**Comment by ibrahimgabsi** [comment]
@shilman I'm on 6.5.10 version but I still have this issue, can you give some updates about it?
