### ISSUE TITLE
Addon-docs: Error: Evaluation failed: TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by FabianSellmann** [storybookjs/storybook#11554]
**Describe the bug**
The error `Error: Evaluation failed: TypeError: Cannot convert a Symbol value to a string` is thrown at runtime for a story under the cirucmenstance described below.
**To Reproduce**

1. Have story wrapped in a  React.Profiler 
1. Have docs addon enabled
1. Open story in story book
**Expected behavior**
It should not throw this error

Using storybook v6.0-rc3

Traced it down that the error originates here: https://github.com/algolia/react-element-to-jsx-string/blob/c4908bbb52e58e104c9d42d1ceaff80d53fd4bdf/src/formatter/formatReactElementNode.js#L122

The `react-element-to-jsx-string` package is a dependency is a dependency of the docs addon.

While I dont have the time to build a repro case right now, I think it should be fairly easy to do with the information provided. Hope this helps. Best regards.

**Comment by shilman** [comment]
As a workaround you can set the `docs.source.type` story parameter to `"code"`.

**Comment by shilman** [comment]
NOTE: this is needed to put a `<React.Suspense>` wrapper for performance optimizations (h/t @sokra) -- will see if i can expedite a fix.

**Comment by Shane32** [comment]
I am having the same problem as listed in #14020 

Here's my workaround so the 'view code' sample looks right:
```ts
import React, { Suspense } from 'react';
import { Story, Meta } from '@storybook/react';

import AppLazyLoadedTemp from './AppLazyLoaded';

const AppLazyLoaded = (props: any) => {
  return <Suspense fallback={<p>Please wait...</p>}><AppLazyLoadedTemp {...props} /></Suspense>;
}

export default {
  title: 'AppLazyLoaded',
  component: AppLazyLoaded,
  argTypes: {
  },
} as Meta;

const Template: Story<{}> = (args) => <AppLazyLoaded {...args} />;

export const Demo = Template.bind({});
Demo.args = {};
```

**Comment by xyy94813** [comment]
> As a workaround you can set the `docs.source.type` story parameter to `"code"`.

It is not friendly for using template mode.
The code will be displayed as

```
(args) => <Component {...args} />;
```

How to write stories if set type to `code`???

**Comment by shilman** [comment]
@xyy94813 that's why it's a workaround an not a solution. But you can set the code to whatever string you want.

**Comment by xyy94813** [comment]
Someone is try to fix it...
https://github.com/algolia/react-element-to-jsx-string/pull/515

**Comment by danielthedifficult** [comment]
> > As a workaround you can set the `docs.source.type` story parameter to `"code"`.
> 
> It is not friendly for using template mode.
> The code will be displayed as
> 
> ```
> (args) => <Component {...args} />;
> ```
> 
> How to write stories if set type to `code`???

Here's how, it doesn't affect the story, only the "Docs" page/addon.

```
  export const MyStory = Template.bind({});
MyStory.args = {
    key: "Property",
}
/* 👇🏻 here is the workaround */
  MyStory.parameters = {
    docs: {
      source: {
        code: "Disabled for this story, see https://github.com/storybookjs/storybook/issues/11554"
      }
    }
  }
```

**Comment by xyy94813** [comment]
it will resolve by https://github.com/algolia/react-element-to-jsx-string/pull/617.

**Comment by xyy94813** [comment]
For `@storybook/addon-docs`, i think react-element to source code is not correct way.
It will make more complex when use Lazy component.

**Comment by davidmenendez** [comment]
Has there been any progress with this? I'm still currently experiencing this problem with 6.3.12

**Comment by rdotg** [comment]
@davidmenendez yes here is a babel plugin I added which works. You might have to adjust the replace functions with something that works better for your code:

```javascript
const template = require('@babel/template')

/**
 * Adding this babel transformer supports the src code view with Suspense
 * Until this issue is resolved, we have to add the src code docs ourselves:
 * https://github.com/storybookjs/storybook/issues/11554
 * The approach is to grab the src code for the entire file, and then strip out unecessary things
 * like large file header helpers that storybook injects so we only show the essentials.
 */
module.exports = () => {
  return {
    visitor: {
      Program(path, state) {
        if (state.file.opts.filename.endsWith('.stories.tsx')) {
          const srcCode = path.hub.file.code
            .trim()
            .replace(
              /(.*((__(STORY|LOCATIONS_MAP)__)|(\/\/)|(\/\*)|(@storybook\/react)|(Template\.parameters =))|(Template\.storyName)).*/g,
              ''
            )
            .replace(/.*React\.Suspense.*\n/gm, '')
            .replace(/export default.*Meta/s, '')
            .replace(/\n\s*\n/g, '\n\n')

          path.node.body.push(
            template.default.ast(`
Template.parameters = {
    ...Template.parameters,
    docs: {
        source: {
            code: \`${srcCode}\`
        }
    }
};`)
          )
        }
      }
    }
  }
}
```


In your `main.js` file:

```javascript
module.exports = {
  stories: ['../src/**/*.stories.mdx', '../src/**/*.stories.@(js|jsx|ts|tsx)'],
  addons: ['@storybook/addon-essentials'],
  babel: async config => {
    return {
      ...config,
      plugins: [
        ...config.plugins,
        path.resolve(__dirname, './babel-docs-plugin.js')
      ]
    }
  },

```

**Comment by donaldpipowitch** [comment]
I saw this error after upgrading to 6.4. It worked fine previously. I created an example repository for [this](https://github.com/donaldpipowitch/storybook-issue-11554). Is this actually Storybook problem or `react-element-to-jsx-string` or something completely else? Are we doing something wrong?

(Note: This [workaround](https://github.com/storybookjs/storybook/issues/11554#issuecomment-893438099) helps.)

**Comment by MarkLyck** [comment]
I'm still running into this issue over 2 years later 😞 

I wanted to add a `withSuspense` decorator so any storybook components I have that relies on `Suspense` would be able to render.

But getting the same error:

```
Cannot convert a Symbol value to a string
```

[The workaround](https://github.com/storybookjs/storybook/issues/11554#issuecomment-893438099) works for individual components. However it would be better if there was a "global" solution.

I'm now having to go through all of our stories to:
- `import { Suspense } from 'react'`
- wrap the component in the story with `<Suspense>...</Suspense>
- Define and override parameters for that story:

```
story.parameters = {
  docs: {
    source: {
      code: 'Disabled for this story, see https://github.com/storybookjs/storybook/issues/11554',
    },
  },
}
``` 

x100 for all our of storybook components that rely on Suspense after upgrading.

Does anyone know of a way to solve this problem at the storybook level instead of individual stories? in `preview` or `main` files?

**Comment by zhyd1997** [comment]
Submitted a PR here: https://github.com/storybookjs/storybook/pull/19004

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-alpha.46 containing PR #19004 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by sirganya** [comment]
This issue still exists using 7.0.0-alpha.48

`decorators: [(Story) => <Suspense>{Story()}</Suspense>]`

**Comment by zhyd1997** [comment]
Maybe we need to find a way let https://github.com/storybookjs/storybook/blob/9a07fcba8a581558d0fa8262989ef83b70a507a0/code/renderers/react/src/docs/jsxDecorator.tsx#L77 inherit this: https://github.com/algolia/react-element-to-jsx-string/blob/984f26908c17cea134fa53d17ac51f179e5195b2/src/parser/parseReactElement.js#L74

**Comment by zhyd1997** [comment]
Handled by PR #19785

**Comment by triglian** [comment]
Hello, the PR #19785 has not been merged and this is still an issue. Using i18next in a global decorator is a common use case where the current issue occurs. Any plans to fix this?

**Comment by shulcsm** [comment]
Issue persists in 7.0.0-beta.64

**Comment by fizz3r** [comment]
> #19785

@zhyd1997 and @shilman , any update on this PR as the issue is still remaining as mentioned above.

**Comment by KorySchneider** [comment]
I am seeing this error with Storybook 7.0.18. Haven't been able to pin down what exactly what is causing the problem. Using the docs workaround until this gets fixed.

@shilman Can we re-open this issue? I see the PR mentioned above is still open.

**Comment by jclarkcisco** [comment]
I am also seeing this issue in SB7 + React.

**Comment by alexgorbatchev** [comment]
Here's another workaround

```tsx
const ReactSuspense = ({ children }: { children: React.ReactNode }) => <React.Suspense>{children}</React.Suspense>;

export function withSuspense<TFramework extends AnyFramework = AnyFramework, TArgs = Args>(
  story: PartialStoryFn<TFramework, TArgs>,
  ctx: StoryContext<TFramework, TArgs>,
) {
  return (
    <ReactSuspense>
      <>{story(ctx)}</>
    </ReactSuspense>
  );
}
```

**Comment by RowinVanAmsterdam** [comment]
I noticed this issue is happening only when there are arguments in a story. For example, this will throw the error ` Cannot convert a Symbol value to a string`:

```
    render: (args) => {
        const iconName =  args.icon;
        const Icon = useMemo(() => lazy(() => import(`../../../foundation/Icons/tsx/${iconName}`).then((module) => ({ default: module[iconName] }))), [iconName]);
```

But without "args", it work flawlessly: 
```
    render: () => {
        const iconName =  "Homeline";
        const Icon = useMemo(() => lazy(() => import(`../../../foundation/Icons/tsx/${iconName}`).then((module) => ({ default: module[iconName] }))), [iconName]);
```

**Comment by jaens** [comment]
This is still an issue in  7.6.16. 

Using a `<Suspense>` or anything related inside a `render` functions seems to trigger it, which is pretty bad, considering this is fairly common.

**Comment by Viktor727** [comment]
I had this code: 

```
export const NoIcon: StoryObj = {
  args: {
    className: 'max-w-[68px]',
    text: '',
    size: 'none',
    placeholder: '100%',
    defaultValue: 'option3',
    onValueChange: (val: string) => console.log('Selected:', val),
    children: (
      <>
        <SelectItem value="option1">50%</SelectItem>
        <SelectItem value="option2">75%</SelectItem>
        <SelectItem value="option3">100%</SelectItem>
        <SelectItem value="option4">125%</SelectItem>
        <SelectItem value="option5">150%</SelectItem>
      </>
    ),
  },
};
```


and I just deleted children

```
children: (
      <>
        <SelectItem value="option1">50%</SelectItem>
        <SelectItem value="option2">75%</SelectItem>
        <SelectItem value="option3">100%</SelectItem>
        <SelectItem value="option4">125%</SelectItem>
        <SelectItem value="option5">150%</SelectItem>
      </>
    ),
```

and it is again work for me

**Comment by studnik18** [comment]
There is no workaround needed. You have to pass all other React components you use inside the story as args to meta.subcomponents.

https://storybook.js.org/docs/writing-stories/stories-for-multiple-components

In the example above, it will be:

`
const meta = { component: NoIcon, subcomponents: { SelectItem }, ... }
`

Should work properly.
