### ISSUE TITLE
rc30: <Props /> render as "nothing found". 

### ISSUE THREAD

**Issue by dpouliot** [storybookjs/storybook#11870]
**Describe the bug**
I updated from rc20 to rc30 this morning and all of my `<Props />` show up as "nothing found". 
(This is a Lerna monorepo)

```mdx
import { Props } from '@storybook/addon-docs/blocks';
import Card from 'path/to/Card';

## Props
<Props of={Card} />
```

I also tried

```mdx
import { ArgsTable } from '@storybook/addon-docs/blocks';
import Card from 'path/to/Card';

## Props
<ArgsTable />
<ArgsTable of='.' />
```

and got the same "Nothing found" result.

**System:**
```bash
$ npx -p @storybook/cli@next sb info

Environment Info:
(node:30336) UnhandledPromiseRejectionWarning: TypeError: (e || []).filter is not a function
    at /Users/n0271009/.npm/_npx/30223/lib/node_modules/@storybook/cli/node_modules/envinfo/dist/envinfo.js:1:73314
(node:30336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by shilman** [comment]
Did you try removing `node_modules` and/or lockfiles and reinstalling?

**Comment by gcofficial** [comment]
Hey guys 👋🏻

We have the same problem...
![image](https://user-images.githubusercontent.com/8502021/89872500-b5978a80-dbc1-11ea-91da-8f9fb424193c.png)

and

![image](https://user-images.githubusercontent.com/8502021/89872567-ccd67800-dbc1-11ea-99c6-baaa955f0c7f.png)


The result is always nothing 
![image](https://user-images.githubusercontent.com/8502021/89872636-e8418300-dbc1-11ea-8d97-27a448a5d94c.png)

**Comment by shilman** [comment]
Anybody have a reproduction I can look at?

**Comment by gcofficial** [comment]
I'll try to create a separate repo with a small example

**Comment by Dangoo** [comment]
We have a maybe similar issue but with expected props not being present.
While the args table on `Properties.stories.tsx` works just fine…

#### Text.stories.mdx
```typescript
<ArgsTable of={Text} />
```

#### Text.tsx
```typescript
export const Text: React.FC<{ id?: string }> = React.forwardRef(function Text(
  { children, id, ...restProps },
  ref
) {
  return (
    <p ref={ref} id={id} {...restProps}>
      {children}
    </p>
  );
});
```

#### Args Table
![image](https://user-images.githubusercontent.com/1252204/89875171-37d18000-dbbd-11ea-9577-5e2c623800db.png)

**Comment by shilman** [comment]
OK, repro'd. Investigating!

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.1 containing PR #11889 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
I think that fixes it. Please give it a try and let me know if not!

**Comment by dpouliot** [comment]
`<Props />` now works once again, thanks so much! 

( `<ArgsTable />` and `<ArgsTable of='.' />` still don't work. )

**Comment by shilman** [comment]
@dpouliot that's surprising that `ArgsTable` doesn't work. do you have a repro?

**Comment by dpouliot** [comment]
> @dpouliot that's surprising that `ArgsTable` doesn't work. do you have a repro?

https://drive.google.com/file/d/1b_eJxwruAeddJFNeylmBwDbb59mOTsSY/view?usp=sharing

Let me know when you have it so I can take it down.

**Comment by shilman** [comment]
Got it, thanks! @dpouliot
