### ISSUE TITLE
Typings issue when custom version of history package is in dependencies

### ISSUE THREAD

**Issue by ajkl2533** [storybookjs/storybook#11928]
**Describe the bug**
When a custom version of `history` package is present in `package.json` dependencies and in `tsconfig.json` is configured to not skip library checks (`skipLibCheck: false`), then type check script (`tsc --noEmit`) is failing with:
```
##[error]node_modules/@types/reach__router/index.d.ts(13,33): error TS2305: Module '"../../history"' has no exported member 'LocationState'.
##[error]node_modules/@types/reach__router/index.d.ts(14,80): error TS2344: Type 'S' does not satisfy the constraint 'object'.
```

**To Reproduce**

1. Clone https://github.com/ajkl2533/storybook-repros/tree/history-types-issue
2. `yarn install`
3. `yarn run types`

**Expected behavior**
Type check should end without error

**System:**
  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v12.13.1/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-actions: ^6.0.3 => 6.0.4
    @storybook/addon-essentials: ^6.0.3 => 6.0.4
    @storybook/addon-links: ^6.0.3 => 6.0.4
    @storybook/node-logger: ^6.0.3 => 6.0.4
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4
    @storybook/react: ^6.0.3 => 6.0.4

**Comment by parkjh** [comment]
@ajkl2533 yea we are getting the same issue too...

**Comment by parkjh** [comment]
are there any workaround for this yet?

**Comment by antoniosZ** [comment]
same issue

**Comment by Fredx87** [comment]
This is actually a bug of the `@types/reach__router` package, that incorrectly depends on the `@types/history` package. The latest version solves this issue, I made a PR to fix this.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.18 containing PR #13703 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.15 containing PR #13703 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by antoniosZ** [comment]
@shilman I still get the same issue when trying to use `history` `v5`.
