### ISSUE TITLE
Docgen: Errors on components whose names are keywords

### ISSUE THREAD

**Issue by preciselywilliam** [storybookjs/storybook#11980]
The storybook project builds fine:
![image](https://user-images.githubusercontent.com/33222967/90145960-c93d1f80-dd80-11ea-8809-54c3e09cb923.png)

When I load the page I get a cryptic Javascript error:
![image](https://user-images.githubusercontent.com/33222967/90146030-dbb75900-dd80-11ea-8337-59464e3cce3b.png)

My deps are as below (let me know if there are other relevant deps):
```
    "@storybook/addon-a11y": "^6.0.5",
    "@storybook/addon-actions": "^6.0.5",
    "@storybook/addon-knobs": "^6.0.5",
    "@storybook/addon-links": "^6.0.5",
    "@storybook/addons": "^6.0.5",
    "@storybook/react": "^6.0.5",
    "@storybook/source-loader": "^6.0.5",
    "react": "16.13.1",
```

Not really sure where to start debugging, any ideas on what could be wrong?

**Comment by shilman** [comment]
do you have a repro i can look at? i recently updated that part of the code and it's possible that you're hitting some kind of corner case bug

**Comment by preciselywilliam** [comment]
> do you have a repro i can look at? i recently updated that part of the code and it's possible that you're hitting some kind of corner case bug

I went through and disabled story by story until I found the one causing the crash. It was below, where Toaster is a function which has to be called as `Toaster.create();`

```
export default {
	title: 'Toaster',
	component: Toaster,
};
```

My mistake, thanks for having a look at the issue. I'll leave the issue open if you want to take further action. @shilman

**Comment by TheKnarf** [comment]
I had a similare problem in a project, turned out I head a react component called `delete` in a file called `delete.tsx` and at some point Storybook tried to generate some code that looked something like `delete.module = ...` which caused the SyntaxError. Renaming the component and the file solved it (never checked which one was the problem).

**Comment by shilman** [comment]
@TheKnarf 

![](https://imgs.xkcd.com/comics/exploits_of_a_mom.png)

**Comment by svvitale** [comment]
@TheKnarf nailed this one. A file named `delete.tsx` causes this failure mode.

**Comment by pladaria** [comment]
Same issue here. 
In my case instead of having a file `delete.tsx` I had a `switch.tsx` and reproduced the same problem: `(SyntaxError: Unexpected token '.')`

**Comment by boakenfull** [comment]
Yep, exactly the same issue here - I have `switch.tsx` which causes the same problem. Changing the file name to `somethingElse.tsx` everything compiles fine

**Comment by loelsonk** [comment]
Same issue, `(SyntaxError: Unexpected token '.')` and `switch.tsx` :D

**Comment by kilinkis** [comment]
`switch.tsx` too!

**Comment by svvitale** [comment]
Still a bug

**Comment by Doenja** [comment]
Same issue. For me it was a folder called **switch** with an index.tsx. Renaming the folder solved the issue.

**Comment by shilman** [comment]
If you want this fixed, please upvote by adding a 👍 to the issue description. We use this to help prioritize!

**Comment by shilman** [comment]
Please upvote https://github.com/styleguidist/react-docgen-typescript/pull/313

**Comment by Deboracgs** [comment]
> Same issue. For me it was a folder called **switch** with an index.tsx. Renaming the folder solved the issue.

same here

**Comment by jorgenbuilder** [comment]
> Manually set the display name solved this for me
> 
> switch.tsx ... Switch.displayName = 'Switch'; ...

Confirming this solution worked in my case. Nice fix @PetterRuud!

**Comment by ndelangen** [comment]
I think this got fixed in 7.0 beta.

**Comment by reify-benjamin-solum** [comment]
As of 7.6.4 I'm still seeing this issue in Storybook. Above fixes work.

**Comment by andreyna1808** [comment]
Yeps, versions 7.6.12

If you had a problem with the switch component in the storybook, try changing it to "toogle", or similar names. The problem itself is the name guys
