### ISSUE TITLE
Storysource previews missing when using TypeScript syntax

### ISSUE THREAD

**Issue by petermikitsh** [storybookjs/storybook#11994]
**Describe the bug**

The following change will break storysources:

`Button.stories.tsx`:
```diff
export default {
  title: "Example/Button",
  component: Button,
  argTypes: {
    backgroundColor: { control: "color" },
  },
-}
+} as Meta;
```
Without `as Meta`:
<img width="1390" alt="Screen Shot 2020-08-13 at 9 47 05 AM" src="https://user-images.githubusercontent.com/1571918/90162792-03d79580-dd4a-11ea-96a2-949608b22dd6.png">

With `as Meta`:
<img width="1390" alt="Screen Shot 2020-08-13 at 9 47 22 AM" src="https://user-images.githubusercontent.com/1571918/90162802-076b1c80-dd4a-11ea-959e-faa25abb8c3b.png">

**To Reproduce**

**Demo Repo**: https://github.com/petermikitsh/sb-source-error

Roughly how I did it:
- `npx init storybook`
- `npm i @storybook/addon-storysource`

main.js:

```diff
module.exports = {
  stories: [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)",
  ],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
+    "@storybook/addon-storysource",
  ],
+  webpackFinal: async (config) => {
+    // remove existing source-loader in place
+    config.module.rules.splice(6, 1);
+    console.log(config.module.rules);
+    config.module.rules = [
+      ...config.module.rules,
+      {
+        test: /\.stories\.[jt]sx?$/,
+        loaders: [
+          {
+            loader: require.resolve("@storybook/source-loader"),
+            options: { parser: "typescript", injectStoryParameters: false },
+          },
+        ],
+        enforce: "pre",
+      },
+    ];
+    return config;
+  },
};
````

- Updated the `Button.js` and `Button.stories.jsx` to be `Button.tsx` and `Button.stories.tsx`, respectively.

**Expected behavior**

TypeScript syntax shouldn't break storysources when `injectStoryParameters` is set to false (so we get the full source code).

**Comment by shilman** [comment]
Does it work with `injectStoryParameters: true`?

**Comment by petermikitsh** [comment]
Behavior when `injectStoryParameters: true`:

<img width="1390" alt="Screen Shot 2020-08-13 at 10 02 03 AM" src="https://user-images.githubusercontent.com/1571918/90164277-105ced80-dd4c-11ea-8569-8f74629576b8.png">

It works, but my preference is for the complete raw source file (first image in bug report).

**Comment by shilman** [comment]
Understood, was just curious!

**Comment by Hypnosphi** [comment]
Got same problem with Flow type annotations

**Comment by petermikitsh** [comment]
The issue appears to be in story-loader. I inspected the transpiled source code for a single story file (button.stories.tsx) from the `react-ts` example project, with light edits. Here's what I learned:

<details>
  <summary>Diff</summary>

### With 'as Meta' commented:

```tsx

      /* eslint-disable */
      // @ts-nocheck
      // @ts-ignore
      var __STORY__ = "\n      \n      // @ts-nocheck\n      // @ts-ignore\n      var __STORY__ = \"import React from 'react';\\nimport { Meta } from '@storybook/react/types-6-0';\\nimport { Button } from './button';\\n\\nexport default { component: Button, title: 'Examples / Button' } /* as Meta */;\\n\\nexport const WithArgs = (args: any) => <Button {...args} />;\\nWithArgs.args = { label: 'With args' };\\nexport const Basic = () => <Button label=\\\"Click me\\\" />;\\n\";\n      // @ts-ignore\n      var __LOCATIONS_MAP__ = {\"WithArgs\":{\"startLoc\":{\"col\":24,\"line\":7},\"endLoc\":{\"col\":59,\"line\":7},\"startBody\":{\"col\":24,\"line\":7},\"endBody\":{\"col\":59,\"line\":7}},\"Basic\":{\"startLoc\":{\"col\":21,\"line\":9},\"endLoc\":{\"col\":54,\"line\":9},\"startBody\":{\"col\":21,\"line\":9},\"endBody\":{\"col\":54,\"line\":9}}};\n    \nimport React from 'react';\nimport { Meta } from '@storybook/react/types-6-0';\nimport { Button } from './button';\n\nexport default {parameters: {\"storySource\":{\"source\":\"import React from 'react';\\nimport { Meta } from '@storybook/react/types-6-0';\\nimport { Button } from './button';\\n\\nexport default { component: Button, title: 'Examples / Button' } /* as Meta */;\\n\\nexport const WithArgs = (args: any) => <Button {...args} />;\\nWithArgs.args = { label: 'With args' };\\nexport const Basic = () => <Button label=\\\"Click me\\\" />;\\n\",\"locationsMap\":{\"with-args\":{\"startLoc\":{\"col\":24,\"line\":7},\"endLoc\":{\"col\":59,\"line\":7},\"startBody\":{\"col\":24,\"line\":7},\"endBody\":{\"col\":59,\"line\":7}},\"basic\":{\"startLoc\":{\"col\":21,\"line\":9},\"endLoc\":{\"col\":54,\"line\":9},\"startBody\":{\"col\":21,\"line\":9},\"endBody\":{\"col\":54,\"line\":9}}}},}, component: Button, title: 'Examples / Button' } /* as Meta */;\n\nexport const WithArgs = (args: any) => <Button {...args} />;;\nWithArgs.args = { label: 'With args' };\nexport const Basic = () => <Button label=\"Click me\" />;\n";
      // @ts-ignore
      var __LOCATIONS_MAP__ = {"WithArgs":{"startLoc":{"col":24,"line":15},"endLoc":{"col":59,"line":15},"startBody":{"col":24,"line":15},"endBody":{"col":59,"line":15}},"Basic":{"startLoc":{"col":21,"line":17},"endLoc":{"col":54,"line":17},"startBody":{"col":21,"line":17},"endBody":{"col":54,"line":17}}};
    

      /* eslint-disable */
      // @ts-nocheck
      // @ts-ignore
      var __STORY__ = "import React from 'react';\nimport { Meta } from '@storybook/react/types-6-0';\nimport { Button } from './button';\n\nexport default { component: Button, title: 'Examples / Button' } /* as Meta */;\n\nexport const WithArgs = (args: any) => <Button {...args} />;\nWithArgs.args = { label: 'With args' };\nexport const Basic = () => <Button label=\"Click me\" />;\n";
      // @ts-ignore
      var __LOCATIONS_MAP__ = {"WithArgs":{"startLoc":{"col":24,"line":7},"endLoc":{"col":59,"line":7},"startBody":{"col":24,"line":7},"endBody":{"col":59,"line":7}},"Basic":{"startLoc":{"col":21,"line":9},"endLoc":{"col":54,"line":9},"startBody":{"col":21,"line":9},"endBody":{"col":54,"line":9}}};
    
import React from 'react';
import { Meta } from '@storybook/react/types-6-0';
import { Button } from './button';

export default {parameters: {"storySource":{"source":"\n      \n      // @ts-nocheck\n      // @ts-ignore\n      var __STORY__ = \"import React from 'react';\\nimport { Meta } from '@storybook/react/types-6-0';\\nimport { Button } from './button';\\n\\nexport default { component: Button, title: 'Examples / Button' } /* as Meta */;\\n\\nexport const WithArgs = (args: any) => <Button {...args} />;\\nWithArgs.args = { label: 'With args' };\\nexport const Basic = () => <Button label=\\\"Click me\\\" />;\\n\";\n      // @ts-ignore\n      var __LOCATIONS_MAP__ = {\"WithArgs\":{\"startLoc\":{\"col\":24,\"line\":7},\"endLoc\":{\"col\":59,\"line\":7},\"startBody\":{\"col\":24,\"line\":7},\"endBody\":{\"col\":59,\"line\":7}},\"Basic\":{\"startLoc\":{\"col\":21,\"line\":9},\"endLoc\":{\"col\":54,\"line\":9},\"startBody\":{\"col\":21,\"line\":9},\"endBody\":{\"col\":54,\"line\":9}}};\n    \nimport React from 'react';\nimport { Meta } from '@storybook/react/types-6-0';\nimport { Button } from './button';\n\nexport default {parameters: {\"storySource\":{\"source\":\"import React from 'react';\\nimport { Meta } from '@storybook/react/types-6-0';\\nimport { Button } from './button';\\n\\nexport default { component: Button, title: 'Examples / Button' } /* as Meta */;\\n\\nexport const WithArgs = (args: any) => <Button {...args} />;\\nWithArgs.args = { label: 'With args' };\\nexport const Basic = () => <Button label=\\\"Click me\\\" />;\\n\",\"locationsMap\":{\"with-args\":{\"startLoc\":{\"col\":24,\"line\":7},\"endLoc\":{\"col\":59,\"line\":7},\"startBody\":{\"col\":24,\"line\":7},\"endBody\":{\"col\":59,\"line\":7}},\"basic\":{\"startLoc\":{\"col\":21,\"line\":9},\"endLoc\":{\"col\":54,\"line\":9},\"startBody\":{\"col\":21,\"line\":9},\"endBody\":{\"col\":54,\"line\":9}}}},}, component: Button, title: 'Examples / Button' } /* as Meta */;\n\nexport const WithArgs = (args: any) => <Button {...args} />;;\nWithArgs.args = { label: 'With args' };\nexport const Basic = () => <Button label=\"Click me\" />;\n","locationsMap":{"with-args":{"startLoc":{"col":24,"line":15},"endLoc":{"col":59,"line":15},"startBody":{"col":24,"line":15},"endBody":{"col":59,"line":15}},"basic":{"startLoc":{"col":21,"line":17},"endLoc":{"col":54,"line":17},"startBody":{"col":21,"line":17},"endBody":{"col":54,"line":17}}}},"storySource":{"source":"import React from 'react';\nimport { Meta } from '@storybook/react/types-6-0';\nimport { Button } from './button';\n\nexport default { component: Button, title: 'Examples / Button' } /* as Meta */;\n\nexport const WithArgs = (args: any) => <Button {...args} />;\nWithArgs.args = { label: 'With args' };\nexport const Basic = () => <Button label=\"Click me\" />;\n","locationsMap":{"with-args":{"startLoc":{"col":24,"line":7},"endLoc":{"col":59,"line":7},"startBody":{"col":24,"line":7},"endBody":{"col":59,"line":7}},"basic":{"startLoc":{"col":21,"line":9},"endLoc":{"col":54,"line":9},"startBody":{"col":21,"line":9},"endBody":{"col":54,"line":9}}}},}, component: Button, title: 'Examples / Button' } /* as Meta */;

export const WithArgs = (args: any) => <Button {...args} />;;;
WithArgs.args = { label: 'With args' };
export const Basic = () => <Button label="Click me" />;

``` 

### With 'as Meta' uncommented:

```tsx

      /* eslint-disable */
      // @ts-nocheck
      // @ts-ignore
      var __STORY__ = "\n      \n      // @ts-nocheck\n      // @ts-ignore\n      var __STORY__ = \"import React from 'react';\\nimport { Meta } from '@storybook/react/types-6-0';\\nimport { Button } from './button';\\n\\nexport default { component: Button, title: 'Examples / Button' } as Meta;\\n\\nexport const WithArgs = (args: any) => <Button {...args} />;\\nWithArgs.args = { label: 'With args' };\\nexport const Basic = () => <Button label=\\\"Click me\\\" />;\\n\";\n      // @ts-ignore\n      var __LOCATIONS_MAP__ = {\"WithArgs\":{\"startLoc\":{\"col\":24,\"line\":7},\"endLoc\":{\"col\":59,\"line\":7},\"startBody\":{\"col\":24,\"line\":7},\"endBody\":{\"col\":59,\"line\":7}},\"Basic\":{\"startLoc\":{\"col\":21,\"line\":9},\"endLoc\":{\"col\":54,\"line\":9},\"startBody\":{\"col\":21,\"line\":9},\"endBody\":{\"col\":54,\"line\":9}}};\n    \nimport React from 'react';\nimport { Meta } from '@storybook/react/types-6-0';\nimport { Button } from './button';\n\nexport default { component: Button, title: 'Examples / Button' } as Meta;\n\nexport const WithArgs = (args: any) => <Button {...args} />;;\nWithArgs.args = { label: 'With args' };\nexport const Basic = () => <Button label=\"Click me\" />;\n";
      // @ts-ignore
      var __LOCATIONS_MAP__ = {"WithArgs":{"startLoc":{"col":24,"line":15},"endLoc":{"col":59,"line":15},"startBody":{"col":24,"line":15},"endBody":{"col":59,"line":15}},"Basic":{"startLoc":{"col":21,"line":17},"endLoc":{"col":54,"line":17},"startBody":{"col":21,"line":17},"endBody":{"col":54,"line":17}}};
    

      /* eslint-disable */
      // @ts-nocheck
      // @ts-ignore
      var __STORY__ = "import React from 'react';\nimport { Meta } from '@storybook/react/types-6-0';\nimport { Button } from './button';\n\nexport default { component: Button, title: 'Examples / Button' } as Meta;\n\nexport const WithArgs = (args: any) => <Button {...args} />;\nWithArgs.args = { label: 'With args' };\nexport const Basic = () => <Button label=\"Click me\" />;\n";
      // @ts-ignore
      var __LOCATIONS_MAP__ = {"WithArgs":{"startLoc":{"col":24,"line":7},"endLoc":{"col":59,"line":7},"startBody":{"col":24,"line":7},"endBody":{"col":59,"line":7}},"Basic":{"startLoc":{"col":21,"line":9},"endLoc":{"col":54,"line":9},"startBody":{"col":21,"line":9},"endBody":{"col":54,"line":9}}};
    
import React from 'react';
import { Meta } from '@storybook/react/types-6-0';
import { Button } from './button';

export default { component: Button, title: 'Examples / Button' } as Meta;

export const WithArgs = (args: any) => <Button {...args} />;;;
WithArgs.args = { label: 'With args' };
export const Basic = () => <Button label="Click me" />;

```

</details>

When 'as Meta' is present, the default export object loses its `parameters` property.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.13 containing PR #12099 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by Hypnosphi** [comment]
It still doesn't work with Flow type annotations. Should I open another issue?

**Comment by shilman** [comment]
cc @phated ☝️

**Comment by phated** [comment]
@Hypnosphi can you provide a simple example of what you are doing with your story? I've not encountered this yet. I also think having a flow issue created would be helpful to separate from typescript since they are separate code paths.

**Comment by Hypnosphi** [comment]
@phated it turned out not to be directly caused by type annotations: https://github.com/storybookjs/storybook/issues/12467
