### ISSUE TITLE
Source: Dynamic snippets includes decorators

### ISSUE THREAD

**Issue by Quadriphobs1** [storybookjs/storybook#12022]
**Describe the bug**
When using decorator, viewing of the story would show the wrapper markup of the decorator and `<No Display name />` for the story.

**Expected behavior**
It should only render the Story and not show the markup of the decorator

**Screenshots**
<img width="1180" alt="Screenshot 2020-08-14 at 13 09 08" src="https://user-images.githubusercontent.com/20229808/90247837-58087580-de2f-11ea-8640-24396cef0500.png">

**Code snippets**
```ts
export default {
  title: "Atom/Input/Helper",
  component: Helper,


  decorators: [
    (Story: any) => (
      <div style={{ position: "relative" }}>
        <Story />
      </div>
    ),
  ],
};

const Template: Story<HelperProps> = (args) => (
  <Helper {...args} />
);

export const Default = Template.bind({});
Default.args = {
  message: "Please do this as soon as you do that.",
};

```

**System:**
```
Environment Info:
  Binaries:
    Node: 14.2.0 - ~/.nvm/versions/node/v14.2.0/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - ~/.nvm/versions/node/v14.2.0/bin/npm
  Browsers:
    Chrome: 84.0.4147.125
    Firefox: 77.0.1
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-docs: ^6.0.6 => 6.0.6 
    @storybook/addon-essentials: ^6.0.6 => 6.0.6 
    @storybook/addon-knobs: ^6.0.6 => 6.0.6 
    @storybook/addon-links: ^6.0.6 => 6.0.6 
    @storybook/addon-notes: ^5.3.19 => 5.3.19 
    @storybook/addon-storysource: ^6.0.6 => 6.0.6 
    @storybook/addon-viewport: ^6.0.6 => 6.0.6 
    @storybook/addons: ^6.0.6 => 6.0.6 
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4 
    @storybook/react: ^6.0.6 => 6.0.6 
```

**Comment by shilman** [comment]
Unrelated, but this is probably not a good idea:

```
    @storybook/addon-notes: ^5.3.19 => 5.3.19 
```

**Comment by mauricioblum** [comment]
I'm having the exact same issue.

**Comment by vineethk123** [comment]
To add some info, if I use my decorator in the following format, it works:
```js
decorators: [
  story => <div style={{height: "50vh"}}>{story()}</div>
]
```
Hope this might help in debugging 🙂

**Comment by Quadriphobs1** [comment]
Actually that seems to work... but it still wraps the story in the provided decorator, isn't it meant to only show the story

**Comment by shilman** [comment]
As a workaround you can set the `docs.source.type` story parameter to `"code"`.

**Comment by Quadriphobs1** [comment]
@shilman  doesn't work

**Comment by shilman** [comment]
@Quadriphobs1 do you have a repro i can look at?

**Comment by darswright** [comment]
> As a workaround you can set the `docs.source.type` story parameter to `"code"`.

Where can this be set?

**Comment by shilman** [comment]
Something like:

```
export default {
  title: "Atom/Input/Helper",
  component: Helper,
  parameters: { docs: { source: { type: 'code' } } }
}
```

**Comment by Quadriphobs1** [comment]
@shilman   Using that produces no code available actually when the decorator is still provided 
```
export default {
  title: "Atom/Component",
  component: Component,
  decorators: [
    (story: any) => {
      return <div>{story()}</div>;
    },
  ],
  parameters: { docs: { source: { type: 'code' } } }
};
```

**Comment by darswright** [comment]
When setting parameters as above "Show Code" window returns `(args) => <Component {...args} />` for me. Same whether using a decorator or not.

**Comment by lewisccx** [comment]
I'm still facing this issue, any workaround available

**Comment by SimonErich** [comment]
Me too. What is the reason for that problem? Maybe a tsconfig or webpack problem?
The examples run perfectly fine though.

**Comment by paulcuth** [comment]
A bit hacky, but I got around this by adding a decorator to wrap what I wanted with known strings. We can then use `transformSource` to extract just that bit...

```
export default {
  title: 'Atom/Input/Helper',
  component: Helper,

  decorators: [
    story => (
      <>
        <span data-begin-source />
        {story()}
        <span data-end-source />
      </>
    ),
    (story: any) => <div style={{ position: 'relative' }}>{story()}</div>,
  ],

  parameters: {
    docs: {
      transformSource: source => {
        const [, output] =
          source.match(
            /<span data-begin-source \/>([\s\S]*?)<span data-end-source \/>/,
          ) ?? []
        return output
      },
    },
  },
}
```

<img width="510" alt="Screenshot 2020-11-10 at 17 28 03" src="https://user-images.githubusercontent.com/132676/98709446-4a08b900-237a-11eb-8d73-ff2a62b578df.png">

**Comment by 4lejandrito** [comment]
Hi 👋 ,

I fixed this by replacing:
```
<Story />
```
by:

```js
{Story()}
```

**Comment by njcaballero** [comment]
I got this to work but only globally by adding a decorator to the .storybook/preview.js file. Mine looks like this. I needed to include global styles available for all components but was running into the same issue. I get the same "No Display Name" issue when trying to add to decorators at the individual story level. Using Storybook version 6.1.4.

`
import React from 'react';

import { GlobalStyle } from '../src/styles/styles';
import { Icons } from '../src/components/Icons';

// Global decorator to apply the styles to all stories
export const decorators = [
  (Story) => (
    <>
      <GlobalStyle />
      <Story />
    </>
  ),
];

export const parameters = {
  actions: { argTypesRegex: '^on[A-Z].*' },
};
`

**Comment by kylemh** [comment]
None of the workarounds work for when trying to provide a decorator where a render prop occurs.

You can replicate this yourself easily when trying to document primitives for forms while using Formik.

```tsx
import React from 'react';
import { Story, Meta } from '@storybook/react';
import { Formik, Form } from 'formik';
import * as Yup from 'yup';
import { noop } from 'lodash';
import { StoryFnReactReturnType } from '@storybook/react/dist/client/preview/types';
import { Button } from '../../src/Button';
import { Input, InputProps } from '../../src/Forms/Input';

const fieldName = 'test';

const FormikDecorator = (Story: () => StoryFnReactReturnType) => {
  const validationSchema = Yup.object({
    [fieldName]: Yup.string().required().default(''),
  }).required();
  const initialValues = validationSchema.cast({});

  return (
    <Formik validationSchema={validationSchema} initialValues={initialValues} onSubmit={noop}>
      {() => (
        <Form>
          <Story />

          <Button type="submit" variant="button-filled-blue">
            Submit
          </Button>
        </Box>
      )}
    </Formik>
  );
};

const meta: Meta<InputProps> = {
  title: 'Zephyr/Forms/Input',
  component: Input,
  decorators: [FormikDecorator],
};

export default meta;

const Template: Story<InputProps> = (args) => (
  <Input {...args} label="Some Input" name={fieldName} data-testid={meta.title} />
);

export const Default = Template.bind({}) as typeof Template;

Default.args = {
  type: 'text',
  isLabelHidden: false,
  required: false,
  autoComplete: 'off',
};

Default.parameters = {
  docs: {
    description: {
      story: 'An input!',
    },
  },
};

```

The resultant visible source code:
```jsx
<Formik
  initialValues={{
    test: ''
  }}
  onSubmit={() => {}}
  validationSchema={[object Object]}
/>

```

**Comment by shilman** [comment]
@kylemh are you using `addon-storysource`? If so, can you try removing it?

**Comment by kylemh** [comment]
I'm not using that addon.

**Comment by shilman** [comment]
Hey @kylemh there's a bug in `source-loader` when it comes to casting the result of `Template.bind({})`. Here's the workaround:

```ts
export const Default = Template.bind({}); // as typeof Template;
```

**Comment by kylemh** [comment]
Still the same problem, but I didn't mean to have that - so thanks for the spot!

**Comment by kylemh** [comment]
Ended up just doing:

```js
Default.parameters = {
  docs: {
    source: {
      code: `/**
 * Unfortunately, we can't render source code correctly on the initial story.
 * Please see https://github.com/storybookjs/storybook/issues/12022
 */`,
    },
  },
};
```

For a reproduction, I have a PR/branch [here](https://github.com/AirLabsTeam/air-core/pull/67), you need only delete `Default.parameters` and see that the source code for the default story ONLY renders the decorator:

```tsx
<Formik
  initialValues={{
    test: ''
  }}
  onSubmit={() => {}}
  validationSchema={[object Object]}
/>
```

while the following stories dont have the decorator at all.

**Comment by as-zlynn-philipps** [comment]
Yeah, looks like Storybook's dynamic snippets don't know what to do with a function as a child. Trying to use a similar Formik wrapper to @kylemh except it's not a decorator, it's a Template and I'm using Template.bind(). Same result.

```jsx
<Formik
  initialValues={{
    input: ''
  }}
  validationSchema={[object Object]}
/>
```

when it should be:

```jsx
<Formik
  initialValues={{
    input: '',
  }}
  validationSchema={Yup.object().shape({
    input: Yup.string(),
  })}
>
  {() => (
    <Form>
      <Box maxWidth={250}>
        <FormGroup id="input">
          <FormGroup.Label>label</FormGroup.Label>
          <FormGroup.InputGroup>
            <FormGroup.InputGroup.Input placeholder="placeholder" />
          </FormGroup.InputGroup>
          <FormGroup.Caption />
        </FormGroup>
      </Box>
    </Form>
  )}
</Formik>
```

However, if I don't use Template and just write the code directly in the Story, it works. Just results in a LOT of repetitive code.

**Comment by KaiVandivier** [comment]
> are you using `addon-storysource`? If so, can you try removing it?

When I use `docs.source.type = 'code'`, I get 'No code available' in the docs page, but removing `addon-storysource` makes the code snippets on the docs page work again.  Is there a way to have both addon-storysource and the 'code' type source code snippets in the docs page?

Thanks for all your support on storybook @shilman!

**Comment by shilman** [comment]
We want to address this in 6.3. If you want to contribute to Storybook, we'll prioritize PR review for any fixes here. And if you'd like any help getting started, please jump into the #support channel on our Discord: https://discord.gg/storybook

**Comment by gabiseabra** [comment]
Storybook's printing of elements to jsx in dynamic mode has a couple of quirks causing these problems:
(1) It picks one point in the component tree and renders all of its children, somewhere before global and after component decorators, at `jsxDecorator`. Some examples here would be manageable if there was a way to configure this — an option to skip or filter nodes that get printed from the component tree, for example —, but AFAIK there is not.
(2) It all falls apart when function children are involved. Dynamic mode is configured to not render the contents of functions at all, making function children unviable. And there is also a bug in `react-element-jsx-string` preventing function children from being parsed.

Function children are tricky because the AST stops when it reaches one. There are no more children to traverse unless it is called and its return value parsed, which may not be desirable in all cases.
Alternatively, `dynamic` mode could just print functions' contents normally instead of parsing (or doing nothing as it does now), similar to how `code` mode works, but then decorators like: `(story) => <Consumer>{story}</Consumer>` wouldn't print anything useful.

I propose the following solution:
(1) Allow users to configure where printing begins by providing an option to change the position of `jsxDecorator` in a story's decorator list.

(2) Regarding function children, `react-element-jsx-string` provides an option to map function props to any other value (`functionValue(fn: Function)` option).
Assuming that a given prop is a pure function that returns react elements, you should be able map it to actual react elements with this option and resume parsing by just replacing it by its result.
But these are bold assumptions, and printing function props like this would be a breaking change, so there should be a way opt-in to this while keeping the current behavior as default. This could be done by "flagging" functions that should be rendered and parsed with an extra parameter:

```ts
const ContextDecorator = (story) => <Consumer>{dynamic(ctx => story(ctx))}</Consumer>
// ...
const dynamic = (fn) => Object.assign((...args) => fn(...args), { sourceType: 'dynamic' })
```

Other modes could also be configurable:

```ts
type Mode = "dynamic" | "code" | "none"

const docMode = (mode: Mode, fn: Function) => Object.assign((...args) => fn(...args), { sourceType: mode })
```

Then `react-element-jsx-string` could be configured as such (not tested):

```js
{
  showFunctions: true,
  functionValue(fn) {
    const sourceType = fn.sourceType || 'none' // This is the current behavior for all functions
    switch(sourceType) {
      case 'dynamic': return fn({})
      case 'none': return () => {}
      case 'code': return fn
    }
  }
}
```

**Comment by rahul-ranjan-solutelabs** [comment]
[https://github.com/storybookjs/storybook/issues/12022#issuecomment-724855720](https://github.com/storybookjs/storybook/issues/12022#issuecomment-724855720)

This worked for me.

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.41 containing PR #14652 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by mike-han** [comment]
Hi @shilman, I have upgraded to the latest version(`6.3.0-rc.2`), but this problem still exists:

Here is my stories:

```tsx
export default {
  title: 'Components/Badge',
  component: Badge,
  decorators:[(Story) => <div className='wrapper'><Story/></div>],
  parameters: {
    docs: {
      source: {
        type: 'dynamic'
      }
    }
  },
} as Meta

const Template: Story<BadgeProps> = (args) => (
  <Badge {...args}>
    <Box size='sm' />
  </Badge>
)

export const Basic = Template.bind({})
```

The code in docs:
![image](https://user-images.githubusercontent.com/16368087/121665505-f8283d00-cada-11eb-8fac-b04f2a4268c3.png)

**Comment by shilman** [comment]
@mike-han you need to opt-out

```
        docs: {
          source: {
            type: 'dynamic',
            excludeDecorators: true,
          },
        },
```

**Comment by mike-han** [comment]
@shilman It works well, thanks!

**Comment by kinoli** [comment]
Solution: My issue doesn't seem to be decorator related but seeing `No Display Name`. So, replacing that text with the last segment of the title is a simple solution and most, if not all, titles should be named the same as the component.

This fixes it for me.

```javascript
docs: {
    transformSource: (source, { title }) => {
      return source.replaceAll('No Display Name', title.substring(title.lastIndexOf('/') + 1));
    }
}
```

**Comment by 365kim** [comment]
Only @kinoli's solution worked for me. Thank you 👍
