### ISSUE TITLE
[Question] When I toggle "show code" in preview, it show just 'Template.bind({})'

### ISSUE THREAD

**Issue by mulder21c** [storybookjs/storybook#12054]
### Bug or support request summary

When I toggle "show code" in preview, it show just 'Template.bind({})'
But what I want is the actual component code to be printed.

I expected the following code snippet to print either 

```html
<default-button :type="type">This is a Button</default-button>
```

Or
```javascript
{
  props: Object.keys(argTypes),
  components: {DefaultButton},
  template: `<default-button :type="type">This is a Button</default-button>`,
}
```

What am I missing? How do I get the output as expected?

### Steps to reproduce

Here is my code 

```mdx
import { Meta, Story, Canvas, ArgsTable, Source } from '@storybook/addon-docs/blocks';
import DefaultButton from './index.vue';

<Meta
  title="Atoms/Buttons"
  component={DefaultButton}
  argTypes={{
    type: {
      description: `value of type attribute for button element`,
      control: {
        type: `select`,
        options: [`button`, `submit`, `reset`],
      },
    },
  }}
/>

export const Template = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: {DefaultButton},
  template: `<default-button :type="type">This is a Button</default-button>`,
});

# Default Button

This is default button component

<Canvas>
  <Story
    name="DefaultButton"
    args = {{
      type: `button`
    }}
  >
    { Template.bind({}) }
  </Story>
</Canvas>

<ArgsTable story="DefaultButton" />
```

Before the toggle it looks like this,

![Atoms-Buttons-DefaultButton-⋅-Storybook](https://user-images.githubusercontent.com/14821565/90328950-9cd10f80-dfdb-11ea-92e4-f12b99ad9fdf.png)

After the toggle it looks like this:

![Atoms-Buttons-DefaultButton-⋅-Storybook (1)](https://user-images.githubusercontent.com/14821565/90328961-aa869500-dfdb-11ea-951d-04aa713fb54e.png)

### Please specify which version of Storybook and optionally any affected addons that you're running

- @storybook/vue 6.0.7
- @storybook/addon-essentials 6.0.7
- @storybook/source-loader 6.0.10
- react-is 16.13.1

### Affected platforms 

- Vue 2.6.11
- Nuxt 2.14.1

**Comment by nckrtl** [comment]
I'm also experiencing this issue. And I'm also using Vue (2.6.11). As this issue already has the bug and tracked labels I suppose it's a confirmed bug?

**Comment by shilman** [comment]
Yep fix is on the way today

**Comment by shilman** [comment]
ZOMG!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.13 containing PR #12107 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by kbhutiya** [comment]
I still see this error on mine at 6.0.21 for @storybook/web-components! I am using mdx!

**Comment by shilman** [comment]
@kbhutiya Do you have a repro repo you can share?

**Comment by kbhutiya** [comment]
@shilman Since its inside our company's repo i dont have a public repo to share ! But below are the screenshots of the config and how component looks! I am using @storybook/web-components at 6.0.21! 

main.js

![Screen Shot 2020-10-02 at 2 13 21 PM](https://user-images.githubusercontent.com/32903432/94956321-fde47200-04b9-11eb-8984-9d59cd47dda2.png)

component's mdx file

![Screen Shot 2020-10-02 at 2 13 48 PM](https://user-images.githubusercontent.com/32903432/94956384-12286f00-04ba-11eb-958c-19ab6896d146.png)

component's template file
![Screen Shot 2020-10-02 at 2 14 24 PM](https://user-images.githubusercontent.com/32903432/94956410-1b194080-04ba-11eb-9b59-720e0c3227aa.png)

storybook demo 
![Screen Shot 2020-10-02 at 2 15 07 PM](https://user-images.githubusercontent.com/32903432/94956427-253b3f00-04ba-11eb-8aef-eb4c49631c35.png)

**Comment by kbhutiya** [comment]
@shilman Is there anything wrong with what i am doing above? Looks like i followed the same pattern as storybook documentation!

**Comment by yairEO** [comment]
I see `<Template.bind({})` in my `Addons` toolbar's **Stroy** tab:

![image](https://user-images.githubusercontent.com/845031/121943883-51e66c80-cd52-11eb-904a-d2e5fed386b5.png)

But see the "correct" story within the *docs* page:

![image](https://user-images.githubusercontent.com/845031/121943999-72aec200-cd52-11eb-9a84-353a34ba357a.png)
