### ISSUE TITLE
Storybook 6.0.16 shows unnecessary upgrade message

### ISSUE THREAD

**Issue by trustthe27** [storybookjs/storybook#12183]
**Describe the bug**
Storybook 6.0.16 displays itself as Storybook 6.0.15 and offers to upgrade, even if it is the latest version.

**To Reproduce**

1. Go to 'your-storybook/?path=/settings/about'
4. See upgrade message

**Expected behavior**
Confirmation, that I'm at the latest version, without any upgrade options.

**Screenshots**

Screenshot for Storybook 6.0.16:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/1700328/90879095-aaedaa00-e3a6-11ea-91fc-9f575ccf45b2.png">

**System:**

  System:
    OS: macOS 10.15.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 14.8.0 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 84.0.4147.135
    Firefox: 78.0.2
    Safari: 13.1.2
  npmPackages:
    @storybook/addon-a11y: ^6.0.16 => 6.0.16
    @storybook/addon-actions: ^6.0.16 => 6.0.16
    @storybook/addon-backgrounds: ^6.0.16 => 6.0.16
    @storybook/addon-knobs: ^6.0.16 => 6.0.16
    @storybook/addon-links: ^6.0.16 => 6.0.16
    @storybook/addon-viewport: ^6.0.16 => 6.0.16
    @storybook/addons: ^6.0.16 => 6.0.16
    @storybook/preset-create-react-app: ^3.1.4 => 3.1.4
    @storybook/react: ^6.0.16 => 6.0.16

**Comment by ndelangen** [comment]
@shilman is versions.json outdated on docs page?

**Comment by shilman** [comment]
@ndelangen Looks fine to me

https://storybook.js.org/versions.json

**Comment by ndelangen** [comment]
maybe this wasn't updated when you released?
https://github.com/storybookjs/storybook/blob/b5d2b2b6519e5e11f908c19d5a5a298c66806038/lib/api/src/version.ts#L1

**Comment by AlanGreene** [comment]
Seeing the same thing with 6.0.18 reporting itself as 6.0.17.

**Comment by shilman** [comment]
argh. thought i fixed that in the publishing script. will give it another try on 6.0.19.

**Comment by cone56** [comment]
This still isn't fixed. I'm running 6.0.26 which is reporting itself as 6.0.25 on the 'about' page.

**Comment by Spielboerg** [comment]
In v6.1.18 the version number is off by 5 patch versions:

<img width="653" alt="Bildschirmfoto 2021-02-18 um 08 40 45@2x" src="https://user-images.githubusercontent.com/7893762/108322154-6a3fe380-71c5-11eb-8ccd-945800a64c3a.png">

**Comment by shilman** [comment]
I fixed this in the release process. Versions 6.2.1 and above should no longer exhibit this behavior.

**Comment by Cheddam** [comment]
Hitting this again on Storybook 6.2.7 😕 

![image](https://user-images.githubusercontent.com/242621/114496303-c11ce300-9c73-11eb-9781-5023346b67d3.png)
