### ISSUE TITLE
Support for Node 14

### ISSUE THREAD

**Issue by daveisfera** [storybookjs/storybook#12425]
**Is your feature request related to a problem? Please describe.**
There are warnings about `chokidar` and `fsevents` breaking with node 14:
```
warning @storybook/react > react-dev-utils > fork-ts-checker-webpack-plugin > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @storybook/react > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @storybook/react > react-dev-utils > fork-ts-checker-webpack-plugin > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
```

**Describe the solution you'd like**
Ability to use Storybook with node 14

**Describe alternatives you've considered**
Update to `webpack` 5 (which is scheduled to be [released soon](https://github.com/webpack/webpack/issues/11406))

**Are you able to assist bring the feature to reality?**
Potentially

**Additional context**
node 14 will become the LTS soon so being able to support it would be really nice

**Comment by shilman** [comment]
Related: https://github.com/storybookjs/storybook/pull/11326

**Comment by daveisfera** [comment]
Node 14 will become the LTS soon, so this is still a relevant issue

**Comment by shilman** [comment]
Node 14 goes LTS at the end of this month, bumping this to P0

**Comment by shilman** [comment]
Looks like there's a webpack 4 that upgrades chokidar. I think we just need to update that and also react-dev-tools @ndelangen

**Comment by ndelangen** [comment]
just upgrade to the latest version of webpack 4 for now?

**Comment by ndelangen** [comment]
We depend on webpack 4.x here:
https://github.com/storybookjs/storybook/blob/77ccd1190922d766553d28f23893408c5db099fa/lib/core/package.json#L129-L130

So a user should already be able to upgrade by themselves, right now.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-beta.3 containing PR #13019 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by daveisfera** [comment]
I hate to be the bearer of bad news, but I just tried updating to `6.1.0-beta.3` and I'm still getting these warnings:
```
warning @storybook/react > webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
warning @storybook/react > webpack > watchpack > watchpack-chokidar2 > chokidar > fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
```

**Comment by ndelangen** [comment]
@daveisfera here's a section from our lockfile:
```
watchpack@^1.7.4:
  version "1.7.4"
  resolved "https://registry.yarnpkg.com/watchpack/-/watchpack-1.7.4.tgz#6e9da53b3c80bb2d6508188f5b200410866cd30b"
  integrity sha512-aWAgTW4MoSJzZPAicljkO1hsi1oKj/RRq/OJQh2PKI2UKL04c2Bs+MBOB+BBABHTXJpf9mCwHN7ANCvYsvY2sg==
  dependencies:
    graceful-fs "^4.1.2"
    neo-async "^2.5.0"
  optionalDependencies:
    chokidar "^3.4.1"
    watchpack-chokidar2 "^2.0.0"
```

I investigted: watchpack@^1.7 wants to be backwards compatible and so it depends on both chokidar 2 & 3 at the same time:

```
var v3Err;
try {
	module.exports = require("chokidar");
	return;
} catch(e) {
	v3Err = e;
}

var v2Err;
try {
	module.exports = require("watchpack-chokidar2");
	return;
} catch(e) {
	v2Err = e;
}
```

Storybook will work just fine in Node 14 thanks to this. Sadly the warning is unnecessary, but not something we can control or remove on our end.

I propose you raise an issue at [watchpack](https://github.com/webpack/watchpack) maybe

**Comment by daveisfera** [comment]
Thanks for the clarification and looking forward to the [upgrade to webpack 5](#9216) to resolve this completely
