### ISSUE TITLE
Docs Generation - No inputs found for this component | Typescript | React

### ISSUE THREAD

**Issue by jamesdalel** [storybookjs/storybook#13304]
**Describe the bug**
I'm trying to get the storybook to auto implement the docs using the `@storybook/addon-docs`. The project consists of react and typescript. So far I have updated the `npx sb upgrade` and added `@storybook/addon-docs` to the `addons` in `main.js`. From the documentation I just expected this to work however I'm seeing `No inputs found for this component. 
Read the docs` when I access the docs page within my storybook application.

I have tried a few things including trying to set `docgen: 'react-docgen-typescript'`

**To Reproduce**
I have an existing storybook app, which has various components.

1. Go to Docs section of a component 

**Expected behavior**
The Docs page should show the correct props

**Screenshots**
![image](https://user-images.githubusercontent.com/25770994/100394511-48571a80-3035-11eb-85c6-8cb6d3829318.png)

**Code snippets**
Current Addons
```  
addons: [
    '@storybook/addon-knobs/register',
    '@storybook/addon-actions/register',
    '@storybook/addon-viewport/register',
    '@storybook/addon-docs',
 ],
````

Current Packages
```
    ...
    "@storybook/addon-actions": "6.1.7",
    "@storybook/addon-info": "5.3.21",
    "@storybook/addon-knobs": "6.1.7",
    "@storybook/addon-viewport": "6.1.7",
    "@storybook/react": "6.1.7",
   "@storybook/addon-docs": "6.1.7",
   "react": "16.12.0",
   ...
````
Example Story
```
import React, { useState } from 'react';
import { text, boolean } from '@storybook/addon-knobs';
import { action } from '@storybook/addon-actions';
import Checkbox from '.';

export const normal = () => (
  <Checkbox
    id="someId"
    onChange={action('Checkbox changed')}
    checked={boolean('checked', false)}
  >
    {text('children', 'Check Me Out')}
  </Checkbox>
);

export default {
  component: Checkbox,
  title: 'Checkbox',
  decorators: [withKnobs],
};
````

```
interface Props extends InputHTMLAttributes<HTMLInputElement> {
  id: string
  onChange?: (event: ChangeEvent<HTMLInputElement>) => void
  checked?: boolean
  name?: string
}
const Checkbox: FC<Props> = ({
  name, id, onChange, checked, children, ...props
}) => (
                <input
                  type="checkbox"
                  id={id}
                  name={name}
                  checked={checked}
                  onChange={(event) => {
                    handleOnChange(event)
                  }}
                />
)

export default Checkbox
````

**System**
```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.18.3 - /usr/local/bin/node
    Yarn: 1.22.4 - /usr/local/bin/yarn
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.67
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-actions: 6.1.7 => 6.1.7 
    @storybook/addon-docs: ^6.1.7 => 6.1.7 
    @storybook/addon-info: 5.3.21 => 5.3.21 
    @storybook/addon-knobs: 6.1.7 => 6.1.7 
    @storybook/addon-viewport: 6.1.7 => 6.1.7 
    @storybook/react: 6.1.7 => 6.1.7 
````

**Additional context**

The app also uses CSS Modules, not sure if that affects how everything is put together

**Comment by shilman** [comment]
Can you remove `addon-info` from package.json and reinstall? If that doesn't work, do you have a repro repo you can share?

**Comment by pauliusef** [comment]
I'm experiencing similar issue where Storybook doesn't generate Docs for a component story. I have a simple example repo based on the latest Storybook packages (installed with `npx sb init`. The Docs aren't properly generated for components that are export as `default export` from a file that is named using `kebab-case`.

I did run `DEBUG=docgen:* yarn storybook` to get some debug output from `react-docgen-typescript` and noticed the difference in setting `displayName`. For default exports it's set all lowercase, which probably doesn't match with what Storybook is looking for when generating Docs page for that components story.

```
 docgen:docs try {
  docgen:docs     // @ts-ignore
  docgen:docs     ButtonNamed.displayName = "ButtonNamed";
  docgen:docs     // @ts-ignore
  docgen:docs     ButtonNamed.__docgenInfo = { "description": "Primary UI component for user interaction", "displayName": "ButtonNamed", "props": { "primary": { "defaultValue": { value: false }, "description": "Is this the principal call to action on the page?", "name": "primary", "required": false, "type": { "name": "boolean" } }, "backgroundColor": { "defaultValue": null, "description": "What background color to use", "name": "backgroundColor", "required": false, "type": { "name": "string" } }, "size": { "defaultValue": { value: "medium" }, "description": "How large should the button be?", "name": "size", "required": false, "type": { "name": "\"small\" | \"medium\" | \"large\"" } }, "label": { "defaultValue": null, "description": "Button contents", "name": "label", "required": true, "type": { "name": "string" } }, "onClick": { "defaultValue": null, "description": "Optional click handler", "name": "onClick", "required": false, "type": { "name": "(() => void)" } } } };
  docgen:docs     // @ts-ignore
  docgen:docs     if (typeof STORYBOOK_REACT_CLASSES !== "undefined")
  docgen:docs         // @ts-ignore
  docgen:docs         STORYBOOK_REACT_CLASSES["src/components/button-named.tsx#ButtonNamed"] = { docgenInfo: ButtonNamed.__docgenInfo, name: "ButtonNamed", path: "src/components/button-named.tsx#ButtonNamed" };
  docgen:docs }
  docgen:docs catch (__react_docgen_typescript_loader_error) { } +0ms
  docgen:docs try {
  docgen:docs     // @ts-ignore
  docgen:docs     buttondefault.displayName = "buttondefault";
  docgen:docs     // @ts-ignore
  docgen:docs     buttondefault.__docgenInfo = { "description": "Primary UI component for user interaction", "displayName": "buttondefault", "props": { "primary": { "defaultValue": { value: false }, "description": "Is this the principal call to action on the page?", "name": "primary", "required": false, "type": { "name": "boolean" } }, "backgroundColor": { "defaultValue": null, "description": "What background color to use", "name": "backgroundColor", "required": false, "type": { "name": "string" } }, "size": { "defaultValue": { value: "medium" }, "description": "How large should the button be?", "name": "size", "required": false, "type": { "name": "\"small\" | \"medium\" | \"large\"" } }, "label": { "defaultValue": null, "description": "Button contents", "name": "label", "required": true, "type": { "name": "string" } }, "onClick": { "defaultValue": null, "description": "Optional click handler", "name": "onClick", "required": false, "type": { "name": "(() => void)" } } } };
  docgen:docs     // @ts-ignore
  docgen:docs     if (typeof STORYBOOK_REACT_CLASSES !== "undefined")
  docgen:docs         // @ts-ignore
  docgen:docs         STORYBOOK_REACT_CLASSES["src/components/button-default.tsx#buttondefault"] = { docgenInfo: buttondefault.__docgenInfo, name: "buttondefault", path: "src/components/button-default.tsx#buttondefault" };
  docgen:docs }
  docgen:docs catch (__react_docgen_typescript_loader_error) { } +5ms
```

Example repo: https://github.com/pauliusef/sb-ts-doc-test

**Comment by pauliusef** [comment]
I think this could probably be raised as an issue with `react-docgen-typescript` package. Let me know what you think and I'll share this issue on their repo as well.

**Comment by CraigCowling79** [comment]
One thing we found recently when we had some stories documenting props and some not was that those those that were working were using components that were exported when they were declared and those that didn't did not include this.

e.g 
export const Widget: React.FC<WidgetProps> = ({ 
vs
const Widget: React.FC<WidgetProps> = ({

After adding export to the beginning of all of our components, all stories began documenting as expected.

**Comment by Lueton** [comment]
> One thing we found recently when we had some stories documenting props and some not was that those those that were working were using components that were exported when they were declared and those that didn't did not include this.
> 
> e.g
> `export const Widget: React.FC<WidgetProps> = ({ `
> vs
> `const Widget: React.FC<WidgetProps> = ({`x
> 
> After adding export to the beginning of all of our components, all stories began documenting as expected.

That was exactly my problem! That should be fixed, right?

**Comment by coreybruyere** [comment]
I have components that are exported later as a default that **do** work and others written the same way that **don't**

**Comment by william-will-angi** [comment]
Thank you @CraigCowling79! Took me forever to figure that out.

Would be cool if we could write components as 
```
const Component: React.FC<Prop> = ({
...
export default Component
```

and still have the controls inferred

**Comment by penx** [comment]
I'm finding that documentation will generate for this:


```tsx
import React from 'react';

export const Button = (props: ButtonOwnProps) => <div />;
export interface ButtonOwnProps {
  /**
   * Some prop
   */
  someProp?: boolean;
}

export default Button;
```

but if I add a type declaration (`: React.FC<CheckboxProps>`), the docs generation fails:

```tsx
import React from 'react';

export const Button: React.FC<CheckboxProps> = (props: ButtonOwnProps) => <div />;
export interface ButtonOwnProps {
  /**
   * Some prop
   */
  someProp?: boolean;
}

export default Button;
```

This is fairly hard to recreate as you have to restart storybook between each change - the docs generation seems to cache some info, so it isn't clear what changes result in breakages.

**Comment by penx** [comment]
I'm finding that docs will generate for this:

```tsx
import React from 'react';

export const Button = (props: ButtonOwnProps) => <div />;
export interface ButtonOwnProps {
  /**
   * Some prop
   */
  someProp?: boolean;
}

export default Button;
```

But docs gen will fail if I add a type declaration (`: React.FC<ButtonOwnProps>`):


```tsx
import React from 'react';

export const Button: React.FC<ButtonOwnProps> = (props: ButtonOwnProps) => <div />;
export interface ButtonOwnProps {
  /**
   * Some prop
   */
  someProp?: boolean;
}

export default Button;
```

This can be resolved by replacing `import React from 'react';` with `import * as React from 'react';`

**Comment by shilman** [comment]
Thanks @penx -- very interesting. We rely on a dependency called `react-docgen-typescript` to produce good types, which in turn relies on the TypeScript compiler. We're in the process of rearchitecting the Storybook side of the equation to make ArgType extraction faster and simpler. After the refactor I'd like to invest time in improving or replacing `react-docgen-typescript` to better handle all the edge cases.

**Comment by penx** [comment]
It seems that react-docgen-typescript is not respecting `allowSyntheticDefaultImports: true` if you have it in your project's tsconfig.json:

> When set to true, allowSyntheticDefaultImports allows you to write an import like:
> 
> ```ts
> import React from "react";
> ```
> 
> instead of:
> 
> ```ts
> import * as React from "react";
> ```

https://www.typescriptlang.org/tsconfig#Interop_Constraints_6252

**Comment by rwieruch** [comment]
Can it be that subcomponents are not inferred at all?

```
storiesOf('First Steps/Table', module)
  .addParameters({
    component: Table,
    subcomponents: {
      Row,
      Cell,
    },
  })
```

If I put Row or Cell  as `component`, I see their inferred props. But not when I put them as `subcomponents`.

**Comment by ciampo** [comment]
We may have incurred in the same issue in https://github.com/WordPress/gutenberg/pull/39468#discussion_r827137147

**Comment by tgshell** [comment]
same issue

**Comment by smellai** [comment]
We have this issue in components with generics. The args table is restored if we force the typecast in this way (last row):

```
import React, { ComponentPropsWithRef, ElementType, forwardRef } from 'react';

type OverridableLinkBaseProps<C extends ElementType = 'a'> = ComponentPropsWithRef<'a'> & {
  component?: C;
};

export type OverridableLinkProps<C extends ElementType = 'a'> = OverridableLinkBaseProps<C> &
  Omit<ComponentPropsWithRef<C>, keyof OverridableLinkBaseProps<C>>;

function OverridableLinkBase<C extends React.ElementType>(
  props: OverridableLinkProps<C>,
  ref: ComponentPropsWithRef<C>['ref']
) {
  const { component: Component = 'a', ...rest } = props;

  return <Component ref={ref} {...rest} />;
}

// We use typecasting to force args table to show up in Storybook
export const OverridableLink = forwardRef(OverridableLinkBase) as typeof OverridableLinkBase;
```

**Comment by allypalanzi** [comment]
Same issue here; workarounds aren't working either.

**Comment by katerberg** [comment]
Same issue here.

**Comment by Maysjtu** [comment]
Same issue here.

**Comment by mhgamble1** [comment]
Same issue here.

**Comment by lucasmaffazioli** [comment]
In my case, if its default export **doesn't** work. I have a polymorphic component.

**Comment by ChangHyun2** [comment]
storybook : 6.5.16
addon-docs : 6.5.16 

NOT work

``tsx
const Checkbox: React.FC<CheckboxProps> = ({ children }) => {
  return (
    <>
      <input type="checkbox" className={s.checkbox}>
        {children}
      </input>
    </>
  );
};

export default Checkbox;

```

**Comment by ivanzamarro** [comment]
This issue has been open for 2 years, and this bug has persisted until version 7. It's not normal for Storybook to force an export pattern for my components. This issue should escalate in priority or at least for the maintainers to give us a solution.

**Comment by ivanzamarro** [comment]
@sag1v In our case, we have decided to stick with version 6 for the same problem, even having to do some hacks in the rendering of component props, but that's another separate issue.

If there's anything we can help you with, feel free to reach out.

**Comment by sag1v** [comment]
@ivanzamarro See[ my comment here](https://github.com/storybookjs/storybook/issues/18137#issuecomment-1559023906). I think i found the issue or at least a part of it and a possible way to workaround it.

**Comment by katerberg** [comment]
What other information is needed for this one?
