### ISSUE TITLE
Controls - type array of objects displayed wrongly

### ISSUE THREAD

**Issue by mayashavin** [storybookjs/storybook#13503]
**Describe the bug**
If use argTypes control type `array` for array of object, in the UI it will display [object Object] instead of proper value, because it tries to "serialize array into a comma-separated string inside a textbox" .

**To Reproduce**

1. Set the `argTypes` of the component doc
  ```js
  argTypes: {
    breadcrumbs: {
      control: "array",
      table: {
        category: "Props",
      },
    },
  },
  ```
2. Set the args of the specific story to array of object
  ```
  Template.args = {
    breadcrumbs: [
      { text: "Home", link: "#" },
      { text: "Category", link: "#" },
      { text: "Pants", link: "#" },
    ],
  };
  ```
3. Go to Storybook page of that component, it prints `[object Object],[object Object],[object Object]`

**Expected behavior**
It should display `{ text: "Home", link: "#" }, { text: "Category", link: "#" }, { text: "Pants", link: "#" }`

**Screenshots**
<img width="1226" alt="Screen Shot 2020-12-22 at 14 57 19" src="https://user-images.githubusercontent.com/6650139/102891032-31ee8400-4466-11eb-8151-3ccebbeccc5c.png">

**System**
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.13.0 - /usr/local/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 76.0.1
    Safari: 14.0

**Comment by shilman** [comment]
You'll want to use `control: 'object'` for anything other than scalar array values.

**Comment by mayashavin** [comment]
@shilman Thanks a lot for the clarification. I would suggest to make a note in the docs regarding this case until a new version is released :)

**Comment by hydrosquall** [comment]
If all the objects in the array have the same keys, it could make sense to have a "table" display type (like the chrome `console.table` instead of using a JSON tree. We could have the option of either trying to infer the keys by default using the first object in the array, or letting the user pass in an explicit list of properties to use in the table.

**Comment by ghengeveld** [comment]
I really like the `console.table` suggestion. Like Chrome, it should automatically infer the right columns (based on all the rows rather than the first, so partial objects just have empty cells). I'm going to update this ticket to be a feature request for that.

As of Storybook 6.2, arrays are inferred to use the `object` control type, which renders the JSON editor, regardless of whether the values are primitive or not.

**Comment by ghengeveld** [comment]
Closing this because the original bug (displaying `[object Object]`) was resolved in Storybook 6.2.

**Comment by MarkiyanPyts** [comment]
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/6214703/164736443-89ae6330-bb99-4241-b764-ece327de0908.png">

For default value issue is still valid
