### ISSUE TITLE
Failed to load the Angular CLI config after updating angular to 11.1 version

### ISSUE THREAD

**Issue by Nicoss54** [storybookjs/storybook#13689]
**Describe the bug**
After migration to its last version (11.1.0), when you launch storybook cli command, you got a warning:
```sh
 Failed to load the Angular CLI config. Using Storybook's default config instead.
WARN TypeError: Cannot read property 'minify' of undefined
WARN     at getCommonConfig (C:\DEV\Projects\Tranversal\ChdNgLibComponents\node_modules\@angular-devkit\build-angular\src\webpack\configs\common.js:298:28)
WARN     at Object.getAngularCliParts (C:\DEV\Projects\Tranversal\ChdNgLibComponents\node_modules\@storybook\angular\dist\server\angular-cli_utils.js:83:30)
WARN     at Object.applyAngularCliWebpackConfig (C:\DEV\Projects\Tranversal\ChdNgLibComponents\node_modules\@storybook\angular\dist\server\angular-cli_config.js:134:40)
WARN     at Object.webpackFinal (C:\DEV\Projects\Tranversal\ChdNgLibComponents\node_modules\@storybook\angular\dist\server\framework-preset-angular-cli.js:10:33)
WARN     at C:\DEV\Projects\Tranversal\ChdNgLibComponents\node_modules\@storybook\core\dist\server\presets.js:259:28
WARN  TypeError: Cannot read property 'minify' of undefined
WARN     at getCommonConfig (C:\DEV\Projects\Tranversal\ChdNgLibComponents\node_modules\@angular-devkit\build-angular\src\webpack\configs\common.js:298:28)
WARN     at Object.getAngularCliParts (C:\DEV\Projects\Tranversal\ChdNgLibComponents\node_modules\@storybook\angular\dist\server\angular-cli_utils.js:83:30)
WARN     at Object.applyAngularCliWebpackConfig (C:\DEV\Projects\Tranversal\ChdNgLibComponents\node_modules\@storybook\angular\dist\server\angular-cli_config.js:134:40)
WARN     at Object.webpackFinal (C:\DEV\Projects\Tranversal\ChdNgLibComponents\node_modules\@storybook\angular\dist\server\framework-preset-angular-cli.js:10:33)
WARN     at C:\DEV\Projects\Tranversal\ChdNgLibComponents\node_modules\@storybook\core\dist\server\presets.js:259:28
WARN => Failed to get angular-cli webpack config.
```

**To Reproduce**
- Angular version 11.1
- storybook version 6.1.14

**Comment by mgameover** [comment]
Hi guys,
I am getting exact the same issue after updating Angular from v11.0.9 to v11.1.0
```
  System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Core(TM) i7-4940MX CPU @ 3.10GHz
  Binaries:
    Node: 14.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.9 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.75)
  npmPackages:
    @storybook/addon-a11y: ^6.1.11 => 6.1.11
    @storybook/addon-actions: ^6.1.11 => 6.1.11
    @storybook/addon-docs: ^6.1.11 => 6.1.11
    @storybook/addon-knobs: ^6.1.11 => 6.1.11
    @storybook/addon-links: ^6.1.11 => 6.1.11
    @storybook/addon-storysource: ^6.1.11 => 6.1.11
    @storybook/addon-viewport: ^6.1.11 => 6.1.11
    @storybook/addons: ^6.1.11 => 6.1.11
    @storybook/angular: ^6.1.11 => 6.1.11
    @storybook/source-loader: ^6.1.11 => 6.1.11
```

**Comment by literalpie** [comment]
I'm seeing this too. Keeping `"@angular-devkit/build-angular": "~0.1100.0",` and upgrading the other deps seems to work for me. Hopefully that narrows down the problem

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.18 containing PR #13704 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by jlabaj** [comment]
still cant find the angular.json even after the update npx sb upgrade --prerelease
