### ISSUE TITLE
`children` is missing from the props table in the Docs tab

### ISSUE THREAD

**Issue by kaiyoma** [storybookjs/storybook#13870]
**Describe the bug**
I have a component whose only prop is `children`, but the docs add-on is not showing this prop, which causes the props table to be missing entirely.

**To Reproduce**

1. Write a component whose only prop is `children`
2. Configure the docs add-on and view the docs for the component

**Expected behavior**
`children` should show up like any other prop.

**Screenshots**
![image](https://user-images.githubusercontent.com/10719780/107580142-fbea9800-6baa-11eb-9618-e8f3f4153681.png)

**Code snippets**
```jsx
export interface Props {
  children: ReactNode;
}

export const Foo = (props) => (
  <div>{props.children}</div>
);

Foo.propTypes = {
  children: PropTypes.node.isRequired,
};
```

**System**
```
Environment Info:

  System:
    OS: Windows 10 10.0.19042
    CPU: (4) x64 Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz
  Binaries:
    Node: 14.15.0 - C:\Program Files\Node.js\node.EXE
    Yarn: 1.22.5 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\Node.js\npm.CMD
  Browsers:
    Chrome: 88.0.4324.150
    Edge: Spartan (44.19041.423.0), Chromium (88.0.705.63)
  npmPackages:
    @storybook/addon-actions: 6.1.15 => 6.1.15
    @storybook/addon-knobs: 6.1.15 => 6.1.15
    @storybook/addons: 6.1.15 => 6.1.15
    @storybook/core: 6.1.15 => 6.1.15
    @storybook/react: 6.1.15 => 6.1.15
    @storybook/theming: 6.1.15 => 6.1.15
```

**Comment by shilman** [comment]
Possibly being fixed in #13911

**Comment by kaiyoma** [comment]
@shilman I'm on a decently recent version of Storybook (6.1.20) and this is still broken. In fact, I think the problem is even worse than originally reported: if the props of a component inherit props from another component, those props are missing as well.

For instance, if you have this:

```
type InheritedProps = Pick<OtherComponentProps, 'foo'>;

interface Props extends InheritedProps {
  bar: string;
}
```

then `bar` will appear in the props table, but `foo` will not.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid.

Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).
