### ISSUE TITLE
Webpack5: ProgressPlugin missing compilation.hooks[name].intercept

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#14006]
Hello, thanks for the hard work. I followed the instructions in the gist mentioned above and I am getting this error:

```
$ yarn storybook
[...]

to be executed: start-storybook -p 9001 -c stories/setup --quiet
info @storybook/react v6.2.0-alpha.34
info
info => Loading presets
info => Loading 1 config file in "/Users/william/projects/mozilla/addons-frontend/stories/setup"
info => Loading 2 other files in "/Users/william/projects/mozilla/addons-frontend/stories/setup"
info => Adding stories defined in "/Users/william/projects/mozilla/addons-frontend/stories/setup/main.js"
info => Using implicit CSS loaders
info => Using default Webpack setup
<i> [webpack-dev-middleware] wait until bundle finished
/Users/william/projects/mozilla/addons-frontend/node_modules/@storybook/core-server/node_modules/webpack/lib/ProgressPlugin.js:242
                                        compilation.hooks[name].intercept({
                                                                ^

TypeError: Cannot read property 'intercept' of undefined
    at /Users/william/projects/mozilla/addons-frontend/node_modules/@storybook/core-server/node_modules/webpack/lib/ProgressPlugin.js:242:30
    at Array.forEach (<anonymous>)
    at /Users/william/projects/mozilla/addons-frontend/node_modules/@storybook/core-server/node_modules/webpack/lib/ProgressPlugin.js:239:24
[...]
```

(same error with and without `--quiet`)

_Originally posted by @willdurand in https://github.com/storybookjs/storybook/issues/9216#issuecomment-783254218_

**Comment by shilman** [comment]
Huzzah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.0-alpha.35 containing PR #14007 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
@gaetanmaisse @willdurand can you upgrade and try out the fix?

```
npx sb upgrade --prerelease
```

**Comment by willdurand** [comment]
@shilman thanks, it works for me. I am still seeing a babel error I wasnt seeing before but that could be something else. thanks!
