### ISSUE TITLE
Webpack Building Constantly

### ISSUE THREAD

**Issue by myyellowshoe** [storybookjs/storybook#14342]
**Describe the bug**
Webpack constantly builds/rebuilds storybook on `6.2.0-rc.9`

**To Reproduce**

1. Install Storybook 6.2.0-rc.9.
1. Start storybook

**Expected behavior**
Should only rebuild when I update a file.

**Code snippets**

```
│   Storybook 6.2.0-rc.9 started                      
│   43 s for preview                                  
│                                                     
│    Local:            http://localhost:6006/         
│    On your network:  http://192.168.125.52:6006/    
│                                                     
webpack building...
webpack built preview 0f3021e86c6e6ac83984 in 20383ms
webpack building...
webpack built preview 0f3021e86c6e6ac83984 in 11474ms
webpack building...
webpack built preview 0f3021e86c6e6ac83984 in 5409ms
webpack building...
webpack built preview 0f3021e86c6e6ac83984 in 7213ms
webpack building...
webpack built preview 0f3021e86c6e6ac83984 in 4904ms
webpack building...
webpack built preview 0f3021e86c6e6ac83984 in 5029ms
webpack building...
```

**System**

```
Environment Info:

  System:
    OS: macOS 11.2.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.13.0 - ~/.nodenv/shims/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.8 - ~/.nodenv/shims/npm
  Browsers:
    Chrome: 89.0.4389.90
    Firefox: 86.0.1
    Safari: 14.0.3
  npmPackages:
    @storybook/addon-actions: ^6.2.0-rc.9 => 6.2.0-rc.9
    @storybook/addon-essentials: ^6.2.0-rc.9 => 6.2.0-rc.9
    @storybook/addon-links: ^6.2.0-rc.9 => 6.2.0-rc.9
    @storybook/preset-scss: ^1.0.3 => 1.0.3
    @storybook/react: ^6.2.0-rc.9 => 6.2.0-rc.9
```

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200143215549071) by [Unito](https://www.unito.io/learn-more)

**Comment by shilman** [comment]
Did you try removing `node_modules` and/or lockfiles and reinstalling?

Do you have a repro repo you can share?

**Comment by kanidjar** [comment]
hi @shilman , same issue here. Tried to remove ```node_modules``` + lockfile then reinstalling, same result on 6.2.1. Did not have this issue with 6.1.

**Comment by shilman** [comment]
Do you have a repro repo you can share?

**Comment by kanidjar** [comment]
Unfortunately, private project.

Here is my env info:

````
Environment Info:

  System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 14.15.1 - /usr/local/bin/node
    Yarn: 1.16.0 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/bin/npm
  Browsers:
    Chrome: 89.0.4389.90
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-controls: ^6.2.1 => 6.2.1 
    @storybook/addon-essentials: ^6.2.1 => 6.2.1 
    @storybook/addon-knobs: ^6.2.1 => 6.2.1 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/angular: ^6.2.1 => 6.2.1 
`````

**Comment by Sqrrl** [comment]
Having the same issue after upgrading to 6.2.1. Changing my main.js file to only load stories from the src/ directory fixes the issue.

Before (constantly re-building):
`stories: ['../**/*.mdx', '../**/*.stories.tsx']`

After (no issues):
`stories: ['../src/**/*.mdx', '../src/**/*.stories.tsx']`

I have no clue, what files were triggering the watcher.

**Comment by kanidjar** [comment]
Wow, thank you @Sqrrl, it worked!

Before:

````
['../@(apps|libs)/**/*.stories.@(ts|mdx)'],
````
After:
```
['../libs/**/*.stories.@(ts|mdx)', '../apps/*/src/**/*.stories.@(ts|mdx)']
```

**Comment by LuigiClaudio** [comment]
Hi there, although marked as a `has workaround`, in my case I do need that globbing `'../**/*.stories.js'` - I do need to go one folder up, then into any folder name and right there, there's a `stories` folder and a list of `*.stories.js` files.

**Comment by RafaelMarinho96** [comment]
> Do you have a repro repo you can share?

Hi @shilman, here is an example: [repository](https://github.com/RafaelMarinho96/storybook-reloading)

**Comment by euaaaio** [comment]
@Sqrrl, @kanidjar, thanks, it works.

@shilman, it seems that rebuilding starts because of `.cache` folder.

My log with some debug info:
```
webpack building...
Files modified: 
  /Users/euaaaio/Code/@postanu/ui/node_modules/.cache/storybook/dev-server/325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7
webpack built preview b3e4bd3859a838db3f66 in 2564ms
webpack building...
Files modified: 
  /Users/euaaaio/Code/@postanu/ui/node_modules/.cache/storybook/dev-server/325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7
webpack built preview b3e4bd3859a838db3f66 in 2562ms
webpack building...
Files modified: 
  /Users/euaaaio/Code/storybook-project/node_modules/.cache/storybook/dev-server/325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7
webpack built preview b3e4bd3859a838db3f66 in 2473ms
webpack building...
Files modified: 
  /Users/euaaaio/Code/storybook-project/node_modules/.cache/storybook/dev-server/325c8f456729b912b0d2134054eb7448-41ac79ddc5290d504ad69ef1fe8200a7
```

**Comment by kayteh** [comment]
I have a repro case of the workaround not working, [repository](https://github.com/kayteh/storybook-reload-loop) set up similarly to [my live repo](https://github.com/roleypoly/roleypoly/tree/main/packages/design-system)

If the `main.js` `stories` value includes seemingly anything in the root dir, it seems to do the loop.

**Comment by sjwilczynski** [comment]
For me the workaround didn't work, looking forward to a different solution.

**Comment by shilman** [comment]
@sjwilczynski do you have a repro repo you can share?

**Comment by sjwilczynski** [comment]
Unfortunately, it's a private repository, but we are on the 6.2.3 version of storybook and are using webpack 4. I will see if I can prepare a mock repository resembling the structure of the real one.

**Comment by kpruden** [comment]
I have this problem as well, and it definitely seems related to globbing.

This works: `stories: ['../../src/components/SomeComponent/index.story.js']`

This loops: `stories: ['../../**/*.story.js']`

FWIW It appears this issue appeared in 6.2.x. If I go back to 6.1.21 the problem goes away..

**Comment by michaelaflores** [comment]
I upgraded today from `6.1.15` and began experiencing this issue as well. The workaround does not prevent the constant rebuilds for me.

**Comment by Pineapples** [comment]
I was having the same issue after upgrading Storybook from 6.1.x to 6.2.x. In the webpack config we use `CopyWebpackPlugin` with a glob of `'**/assets/**/*'` to copy any assets to the output. Somehow after the upgrade the copy plugin was triggering on the `node_modules/.cache` output of Storybook. Even though we had `node_modules` in the `globOptions.ignore` it still triggered an endless build loop.

Changing the glob to `path.posix.join(__dirname, '..', 'libs', '**/assets/**/*')` fixed the rebuilding loop issue for me.

**Comment by eric-burel** [comment]
Side question: is it possible to have an option for debugging this? `--webpack-debug` could for instance display which file triggered the reload?

**Comment by thielium** [comment]
Going to leave this here, for future sojourners into this sort of issue:

```ts
// https://github.com/storybookjs/storybook/issues/14342
// https://webpack.js.org/contribute/plugin-patterns/#monitoring-the-watch-graph

import { Compiler } from 'webpack';

export class WebpackWatchRunPlugin {
  startTime: number;
  prevTimestamps: Map<string, number>;
  constructor() {
    this.startTime = Date.now();
    this.prevTimestamps = new Map<string, number>();
  }
  apply(compiler: Compiler) {
    compiler.hooks.emit.tapAsync('MyPlugin', (compilation, callback) => {
      const changedFiles = Array.from(compilation.fileTimestamps.keys()).filter((watchfile) => {
        return (
          (this.prevTimestamps.get(watchfile) || this.startTime) <
          (compilation.fileTimestamps.get(watchfile) || Infinity)
        );
      });

      console.log(changedFiles);

      this.prevTimestamps = compilation.fileTimestamps;
      callback();
    });
  }
}
```

**Comment by ranulf10** [comment]
Tranfer acont

**Comment by Nilegfx** [comment]
using webpack5 builder solved this issue for me. 

1. install the builder as dev dependency `yarn add @storybook/builder-webpack5 -D`
2. in your `.storybook/main.js` add the following: 

```js
  core: {
    builder: 'webpack5',
  },
```

**Comment by penx** [comment]
This issue exists in v6.3.0-alpha.1 for me but is fixed in v6.3.0-alpha.2

Here's the commits:
https://github.com/storybookjs/storybook/commits/v6.3.0-alpha.2

I suspect it relates to:
https://github.com/storybookjs/storybook/pull/14461

@shilman Perhaps this can be back ported to 6.2, if 6.3 is still a way off?

**Comment by penx** [comment]
I checked out a copy of storybook locally (6.2.9) ran `yarn link` as per contributing guidelines, and could replicate the issue on my project (https://github.com/govuk-react/govuk-react)

I then patched with #14461 and the issue was resolved.

I'll raise a PR to backport #14461 in to master, which I think is the process @shilman? I see there are some other commits on master so assuming there's  6.2.10 coming?

**Comment by shilman** [comment]
Thanks so much @penx!!! 🙏 

Can somebody else here verify that 6.3.0-alpha.x fixes the issue for them? I'll also check it out on one a reproduction.

```
npx sb@next upgrade --prerelease
```

**Comment by avaneeshtripathi** [comment]
> Thanks so much @penx!!! 🙏
> 
> Can somebody else here verify that 6.3.0-alpha.x fixes the issue for them? I'll also check it out on a reproduction.
> 
> ```
> npx sb@next upgrade --prerelease
> ```
> 
> 6.3 is going into beta on Monday and is schedule for release 4 weeks after that.

For me, none of the workarounds above worked but upgrading the version to `6.3.0-alpha.x` fixed the issue.

**Comment by kushalraid** [comment]
> ```
> npx sb@next upgrade --prerelease
> ```

Indeed it helped.

**Comment by shilman** [comment]
closing this as fixed in 6.3

```
npx sb@next upgrade --prerelease
```

**Comment by gaurav5430** [comment]
I had the same issue on 6.2.4, where webpack was infinitely rebuilding when an error happened.
still do not know what was causing the infinite rebuilding, but was solved on updating to 6.3.3

**Comment by bloodf** [comment]
This issue still happens on 6.3.6 with all the configurations provided in this issue.

**Comment by shilman** [comment]
@bloodf Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce).

**Comment by kgram** [comment]
I had this issue as well (or at least a similar one). After some digging I found that the `node_modules` folder was added as a context dependency in webpack, meaning it has a full folder watch, making changes to `.cache` also trigger recompilation. After a _lot_ more digging, I finally found the culprit: `WatchMissingNodeModulesPlugin` from `react-dev-utils`. It's supposed to force a recompile whenever dependencies change, but I'm running a monorepo setup, so the only things found in the watched `node_modules` is `.cache` and `.bin`.

Since I was already using a customized webpack config, my solution was simply to remove this plugin from the list passed to the customizer:

```
plugins.filter((plugin) => plugin.constructor.name !== 'WatchMissingNodeModulesPlugin')
```

**Comment by im-mou** [comment]
I know this issue is closed but this bug is still present on 8.0.10 🫠. All of my stories are located under `<root>/stories` folder and the config points to that folder specificly but the issue still persists.

Here are the relevant Storybook packages that I have installed and their versions:
```json
"storybook": "^8.0.10",
"@storybook/addon-webpack5-compiler-swc": "^3.0.0",
"@storybook/react": "^8.0.10",
"@storybook/react-webpack5": "^8.0.10"
```

And here is my storybook config located at `<root>/.storybook/main.ts`
```ts
const config: StorybookConfig = {
  stories: ['../stories/**/*.stories.@(js|jsx|mjs|ts|tsx)'],
  addons: [
    '@storybook/addon-webpack5-compiler-swc',
    '@storybook/addon-onboarding',
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@chromatic-com/storybook',
    '@storybook/addon-interactions',
    '@storybook/addon-a11y',
  ],
  framework: {
    name: '@storybook/react-webpack5',
    options: {},
  },
  docs: {
    autodocs: true,
  },
  webpackFinal: async config => {
    config?.module?.rules?.push({
      test: /\.scss$/,
      use: ['style-loader', 'css-loader', 'resolve-url-loader', 'sass-loader'],
      include: resolve(__dirname, '../'),
    });

    return config;
  },
};
```
And this is what I see in my chrome devtools console. I haven’t found a consistent way to reproduce this behavior, but it usually happens after I refresh the browser tab following a random period of time.

<img width="1040" height="582" alt="Image" src="https://github.com/user-attachments/assets/61aee38e-ff1c-4a57-8d33-f8761b1e0111" />

I'm not using any tailwind or other fancy stuff other than sass and react.
