### ISSUE TITLE
[Vue] Source panel doesn't include render function-based component

### ISSUE THREAD

**Issue by paulgv** [storybookjs/storybook#14454]
**Describe the bug**

One of our components is written in a `.vue` file but leverages a `render` function instead of a `<template>` section to render its markup: [`GlSprintf`](https://gitlab.com/gitlab-org/gitlab-ui/-/blob/889aee6f484a31229693537f377ffe29c13450fa/src/components/utilities/sprintf/sprintf.vue).

We wrote a few [stories](https://gitlab.com/gitlab-org/gitlab-ui/-/blob/889aee6f484a31229693537f377ffe29c13450fa/src/components/utilities/sprintf/sprintf.stories.js) for this component. For instance, here's what the `SentenceWithLink` story looks like:

<img width="572" alt="Screen Shot 2021-04-02 at 9 24 03 AM" src="https://user-images.githubusercontent.com/4895885/113419302-2bd93f00-9395-11eb-85d9-b1b1db0f2fde.png">

Note how this story also uses the `GlLink` component. Interestingly, the generated source code for this story – and all other `GlSprintf` stories – does not include `GlSprintf` itself, but it does however include `GlLink`:

<img width="1022" alt="Screen Shot 2021-04-02 at 9 28 07 AM" src="https://user-images.githubusercontent.com/4895885/113419586-bd48b100-9395-11eb-8590-04ca43ef6369.png">

Here's the relevant page in our hosted Storybook: https://gitlab-org.gitlab.io/gitlab-ui/?path=/docs/utilities-sprintf--sentence-with-link

**To Reproduce**

1. Pull `https://gitlab.com/gitlab-org/gitlab-ui.git`.
2. Run `yarn && yarn start`.
3. Navigate to `GlSprintf` stories.
4. Expand any story's source code panel in the `Docs` tab.

**Expected behavior**

The source code includes all components used in the story.

**System**

```
Environment Info:

  System:
    [REDACTED]
  Binaries:
    Node: 12.18.4 - ~/.asdf/installs/nodejs/12.18.4/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.6 - ~/.asdf/installs/nodejs/12.18.4/bin/npm
  Browsers:
    Chrome: 89.0.4389.114
    Firefox: 87.0
    Safari: 13.1.3
  npmPackages:
    @storybook/addon-a11y: 6.2.2 => 6.2.2
    @storybook/addon-docs: 6.2.2 => 6.2.2
    @storybook/addon-essentials: 6.2.2 => 6.2.2
    @storybook/addon-knobs: 6.2.2 => 6.2.2
    @storybook/addon-storyshots: 6.2.2 => 6.2.2
    @storybook/addon-storyshots-puppeteer: 6.2.2 => 6.2.2
    @storybook/addon-viewport: 6.2.2 => 6.2.2
    @storybook/theming: 6.2.2 => 6.2.2
    @storybook/vue: 6.2.2 => 6.2.2
```

**Comment by alexan** [comment]
is there any update? Did you found a solution to render the source correctly?

**Comment by ndelangen** [comment]
This has been addressed recently in 7.0 beta.

Would you mind trying it, and report if it meets your needs?

**Comment by paulgv** [comment]
@ndelangen this is still happening in Storybook 7.0.7: https://gitlab-org.gitlab.io/gitlab-ui/?path=/docs/utilities-sprintf--docs

Here's the story file: https://gitlab.com/gitlab-org/gitlab-ui/-/blob/df415b9dfc204e41a9d0941a2bd3aedafe542b79/src/components/utilities/sprintf/sprintf.stories.js

**Comment by valentinpalkovic** [comment]
Thanks for the report. This was filed against Vue 2 + `@storybook/vue@6.2.2` — Vue 2 dropped in Storybook 8 and the Vue source-extraction pipeline was rewritten with `vue-component-meta` (CSF-static source). Render-function components are now documented via `parameters.docs.source.code`. Closing as stale — please open a fresh issue against Storybook 9/10 + Vue 3 if render-function components still drop from the source panel.
