### ISSUE TITLE
url params don't work for some args (protected names maybe?)

### ISSUE THREAD

**Issue by chadlavi-casebook** [storybookjs/storybook#14508]
**Describe the bug**

After reading that storybook supports controlling args through URL parameters [[1](https://github.com/storybookjs/storybook/issues/6133#issuecomment-797551716)] [[2](https://storybook.js.org/docs/react/writing-stories/args#setting-args-through-the-url)], I am trying it out, because I had a great use case for linking to a particular set of props for a component from my release notes.

However, it seems that when the prop you want to control is called `name`, or when you want to control the `children` prop, this method doesn't work. 

**To Reproduce**

I have a prop that has a type like this:

```
name: 'foo' | 'bar' | 'baz' | ...
```

I tried a URL param like this: 
```
&args=name:foo
```

but it had no effect.

There are, however, other props that _do_ work just fine, and they have similar types. For example I have props like 

```
color?: 'default' | 'primary' | 'secondary' | 'inherit'
```

and passing 

```
&args=name:foo;color:secondary
```

_does_ correctly set the color, even though the name prop gets ignored.

This leads me to suspect that it's the name `name` itself that is causing the issue here. adding a new `name` prop to other components seems to suggest this is reproducible.

I'm also experiencing this with the `children` prop.

**Comment by chadlavi-casebook** [comment]
This is reproducible in Storybook's own DS storybook: https://5ccbc373887ca40020446347-qrbicufmsd.chromatic.com/?path=/story/button--basic&args=children:hello;appearance:outline

that should show a button with appearance set to outline (which works correctly) and its children set to "hello", but the children arg here has no effect.

**Comment by ghengeveld** [comment]
I'm not quite sure the DS exhibits the same issue per se. Your problem appears to be with TS inference. I'm going to need more info to debug this. Could you run the following in your Storybook (iframe context) and post the resulting JSON?

```js
let { args, argTypes } = __STORYBOOK_STORY_STORE__._stories[__STORYBOOK_STORY_STORE__._selection.storyId]
console.log(JSON.stringify({ args, argTypes }, null, 2))
```

I suspect that the `name` field is reported as object while `color` is a string or option.

I've confirmed a bug in restoring object string values from the URL. If you set `"foo"` in a JSON (object) field it will sync that to the URL, but if you refresh the page it will not properly restore from that URL. Looks like a problem with [`mapArgsToTypes`](https://github.com/storybookjs/storybook/blob/4cbf3083c814210a00623aaafe07ed3fde40b67c/lib/client-api/src/args.ts#L39).

**Comment by chadlavi-casebook** [comment]
@ghengeveld thanks for getting back to me! 

here's what I get:

```
{
  "args": {
    "name": "casebook"
  },
  "argTypes": {
    "name": {
      "control": {
        "type": "select",
        "options": [
          "casebook",
          "drag-handle",
          "500px",
          
          ...

          "youtube-square",
          "youtube",
          "zhihu"
        ]
      },
      "type": {
        "name": "other",
        "required": true,
        "value": "\"function\" | \"search\" | \"text\" | \"image\" | \"code\" | \"h1\" | \"h2\" | \"h3\" | \"h4\" | \"link\" | \"map\" | \"table\" | \"th\" | \"video\" | \"circle\" | \"filter\" | \"line\" | \"marker\" | \"mask\" | \"stop\" | ... 2291 more ... | \"drag-handle\""
      },
      "name": "name",
      "required": true,
      "description": "The icon name",
      "sbType": {
        "name": "other",
        "value": "\"function\" | \"search\" | \"text\" | \"image\" | \"code\" | \"h1\" | \"h2\" | \"h3\" | \"h4\" | \"link\" | \"map\" | \"table\" | \"th\" | \"video\" | \"circle\" | \"filter\" | \"line\" | \"marker\" | \"mask\" | \"stop\" | ... 2291 more ... | \"drag-handle\""
      },
      "table": {
        "type": {
          "summary": "\"function\" | \"search\" | \"text\" | \"image\" | \"code\" | \"h1\" | \"h2\" | \"h3\" | \"h4\" | \"link\" | \"map\" | \"table\" | \"th\" | \"video\" | \"circle\" | \"filter\" | \"line\" | \"marker\" | \"mask\" | \"stop\" | ... 2291 more ... | \"drag-handle\""
        },
        "defaultValue": null
      }
    },
    "color": {
      "control": {
        "type": "radio"
      },
      "options": [
        "default",
        "inherit",
        "primary",
        "destructive",
        "secondary"
      ],
      "name": "color",
      "type": {
        "required": false,
        "name": "enum",
        "value": [
          "default",
          "inherit",
          "primary",
          "destructive",
          "secondary"
        ]
      },
      "required": false,
      "description": "By default an icon inherits color from its parent element. Use this prop to set the icon color independently. The DS default color for icons is #748089. 'primary' is #006EB9, and 'secondary' is #20A49A.",
      "sbType": {
        "name": "enum",
        "value": [
          "default",
          "inherit",
          "primary",
          "destructive",
          "secondary"
        ]
      },
      "table": {
        "type": {
          "summary": "\"default\" | \"inherit\" | \"primary\" | \"destructive\" | \"secondary\""
        },
        "defaultValue": null
      }
    },
    "fixedWidth": {
      "control": {
        "type": "boolean"
      },
      "name": "fixedWidth",
      "type": {
        "required": false,
        "name": "boolean"
      },
      "required": false,
      "description": "Use to set multiple icons to the same fixed width.",
      "sbType": {
        "name": "boolean"
      },
      "table": {
        "type": {
          "summary": "boolean"
        },
        "defaultValue": null
      }
    },
    "forwardClassNames": {
      "control": {
        "type": "object"
      },
      "name": "forwardClassNames",
      "type": {
        "required": false,
        "name": "other",
        "value": "string[]"
      },
      "required": false,
      "description": "classNames provided by parent component to override the styling of the icon",
      "sbType": {
        "name": "other",
        "value": "string[]"
      },
      "table": {
        "type": {
          "summary": "string[]"
        },
        "defaultValue": null,
        "disable": true
      }
    },
    "margin": {
      "control": {
        "type": "radio"
      },
      "options": [
        "default",
        "medium",
        "left",
        "right",
        "dense"
      ],
      "name": "margin",
      "type": {
        "required": false,
        "name": "enum",
        "value": [
          "default",
          "medium",
          "left",
          "right",
          "dense"
        ]
      },
      "required": false,
      "description": "Sets left and right margins on the icon. 'default' is 16px, 'dense' is 8px, and 'medium' is 24px.",
      "sbType": {
        "name": "enum",
        "value": [
          "default",
          "medium",
          "left",
          "right",
          "dense"
        ]
      },
      "table": {
        "type": {
          "summary": "\"default\" | \"medium\" | \"left\" | \"right\" | \"dense\""
        },
        "defaultValue": null
      }
    },
    "size": {
      "control": {
        "type": "select"
      },
      "options": [
        "lg",
        "sm",
        "xs",
        "2x",
        "3x",
        "4x"
      ],
      "name": "size",
      "type": {
        "required": false,
        "name": "enum",
        "value": [
          "lg",
          "sm",
          "xs",
          "2x",
          "3x",
          "4x"
        ]
      },
      "required": false,
      "description": "By default an icon inherits fontSize from its parent element. Use this prop to set the icon size independently. Sets the icons size in ems, where 'xs' is .75em, 'sm' is .875em, 'lg' is 1.33em, and '2x' through '4x' are 2em through 4em.",
      "sbType": {
        "name": "enum",
        "value": [
          "lg",
          "sm",
          "xs",
          "2x",
          "3x",
          "4x"
        ]
      },
      "table": {
        "type": {
          "summary": "\"lg\" | \"sm\" | \"xs\" | \"2x\" | \"3x\" | \"4x\""
        },
        "defaultValue": null
      }
    },
    "title": {
      "control": {
        "type": "text"
      },
      "name": "title",
      "type": {
        "required": false,
        "name": "string"
      },
      "required": false,
      "description": "Icon title",
      "sbType": {
        "name": "string"
      },
      "table": {
        "type": {
          "summary": "string"
        },
        "defaultValue": null
      }
    },
    "type": {
      "control": {
        "type": "radio"
      },
      "options": [
        "brands",
        "duotone",
        "light",
        "regular",
        "solid"
      ],
      "name": "type",
      "type": {
        "required": false,
        "name": "enum",
        "value": [
          "brands",
          "duotone",
          "light",
          "regular",
          "solid"
        ]
      },
      "required": false,
      "description": "The icon type",
      "sbType": {
        "name": "enum",
        "value": [
          "brands",
          "duotone",
          "light",
          "regular",
          "solid"
        ]
      },
      "table": {
        "type": {
          "summary": "\"brands\" | \"duotone\" | \"light\" | \"regular\" | \"solid\""
        },
        "defaultValue": {
          "summary": "light"
        }
      }
    },
    "testID": {
      "control": {
        "type": "text"
      },
      "name": "testID",
      "type": {
        "required": false,
        "name": "string"
      },
      "required": false,
      "description": "Custom data attribute for testing purposes",
      "sbType": {
        "name": "string"
      },
      "table": {
        "type": {
          "summary": "string"
        },
        "defaultValue": null
      }
    }
  }
}
```

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.2.6 containing PR #14511 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by chadlavi-casebook** [comment]
the latest version (6.2.7) does not address this. It still does not work.

**Comment by szmq** [comment]
looks like I have the same problem. For arg named `date` can't pass value via URL. It gets undefined. Before that, I had the same problem with the `select` control type but it turned out that it was enough to move options from control according to updated documentation. In the case of the `date` arg, it seems there is only a problem with the name of that argument. Changing a parameter directly from the control addon works properly. I am placing the code snippet below, but the structure seems to be correct.

```js
date: {
  control: {
    type: 'date',
  },
  defaultValue: Date.now(),
},
```

**Comment by aantonyuk** [comment]
I also see the same issue but with boolean attributes. When I switch to toggle from true to false it's work perfect but when I refresh the page I see the error message.

![3](https://user-images.githubusercontent.com/26109453/115629522-2ecbad80-a30b-11eb-9868-8db93b8c35e5.jpg)

**Comment by antoniosZ** [comment]
I think I have a similar issue since https://github.com/storybookjs/storybook/issues/6133 and https://github.com/storybookjs/storybook/pull/13803
before that, I was using the updateArgs hook to update dynamically the args:

```js
import { useArgs } from '@storybook/api';

const [args, updateArgs, resetArgs] = useArgs();

// To update one or more args:
updateArgs({ children: '<b>test</b>' });
```

through an addon I made, that was driven by my E2E testing.
With that, I could dynamically change the `children` arg during the E2E testing with any HTML value needed.

Now, because it syncs the arg values with the URL and therefore sanitizes them,
I get at the very least a warning in the console...

Can an option be added to turn off this sync args to URL feature?
I really do not need it and it creates breaking changes in my case, even though I used storybook within its "allowed" use.

As for this solution
https://storybook.js.org/docs/react/writing-stories/args#mapping-to-complex-arg-values
it will force me to have to refactor all my E2E tests, as if, this is a breaking change and it will make the whole use of dynamically updating args by E2E tests at run-time, really cumbersome.

**Comment by shilman** [comment]
@antoniosZ can you open a new issue with a repro using `npx sb@next repro`? it sounds like you're experiencing a bug to me, not a breaking change.

**Comment by aalpgiray** [comment]
I have just realised switching from `react-docgen-typescript` to `react-docgen` solves this. I don't know where to open this bug report. You can checkout this documentation if you don know how to set this parameter.

https://storybook.js.org/docs/react/configure/typescript

**Comment by TheBeerCake** [comment]
Switching to `react-docgen` not solve it for me . When I open the story in canvas it's a coin toss which URL params will work.

**Comment by dewezlopez** [comment]
> I have just realised switching from `react-docgen-typescript` to `react-docgen` solves this. I don't know where to open this bug report. You can checkout this documentation if you don know how to set this parameter.
> 
> https://storybook.js.org/docs/react/configure/typescript

Using `react-docgen` worked for me.

**Comment by shilman** [comment]
We’re cleaning house! Storybook has changed a lot since this issue was created and we don’t know if it’s still valid. Please open a new issue referencing this one if:
- this is still a problem in SB 7.x
- you can provide a consistent reproduction in 7.x (at https://storybook.new/ or per [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce)).

**Comment by alexey-kozlenkov** [comment]
@shilman it's still happening for a SB 9 🥲, here is a bug I submitted recently
https://github.com/storybookjs/storybook/issues/31735
