### ISSUE TITLE
Possible bug when a Story property contains "color" or "Color" in the name and is not a string

### ISSUE THREAD

**Issue by stfnbssl** [storybookjs/storybook#14704]
When I declare in a Story a property of name "color" (or "rgbaColor" or "bkgColor", etc..)  that is not a string; example:
```
export const Small = Template.bind({});
Small.args = {
    color: {
        red: 255, 
        green: 0, 
        blue: 0, 
        alpha: 1
     }, 
};
```
then viewing the story I see in a flash the correct widget but immediately I receive: 
```
TypeError: value.replace is not a function
    at parseValue (9.da52dd791e7234e0495a.manager.bundle.js:formatted:311)
    at 9.da52dd791e7234e0495a.manager.bundle.js:formatted:340
    at Object.yh [as useState] (vendors~main.0b7555aaeb5d052c07aa.manager.bundle.js:formatted:32888)
    at exports.useState (vendors~main.0b7555aaeb5d052c07aa.manager.bundle.js:formatted:29533)
    at useColorInput (9.da52dd791e7234e0495a.manager.bundle.js:formatted:339)
    at ColorControl (9.da52dd791e7234e0495a.manager.bundle.js:formatted:407)
    at oh (vendors~main.0b7555aaeb5d052c07aa.manager.bundle.js:formatted:32742)
    at di (vendors~main.0b7555aaeb5d052c07aa.manager.bundle.js:formatted:33329)
    at Rj (vendors~main.0b7555aaeb5d052c07aa.manager.bundle.js:formatted:35589)
    at Qj (vendors~main.0b7555aaeb5d052c07aa.manager.bundle.js:formatted:35059)
```
Renaming it, example "rgba", everything go right.

I could be wrong but it seems that trying to detect color properties for the controls panel s.t. goes wrong in the sb browser.

**Comment by yannbf** [comment]
Hey @stfnbssl, thanks for opening this issue! I assume you have configuration for [custom controls matchers](https://storybook.js.org/docs/react/essentials/controls#custom-control-type-matchers) in your `preview.js` file. 
Controls offers ways to set a regex for color and date fields so that you don't need to set them in every story. I believe controls for colors only works with strings, and that's the reason it breaks in your case. It's quite unfortunate, because the color picker is pretty awesome!

Quick solution: please check `preview.js` and change, or even remove the custom matcher for colors.

If that's not the case, please let me know!

Question to @shilman @ghengeveld: Do you think we should do something in this scenario? Like a way to detect if the argType match with the received value to protect such cases(although might be counterintuitive as argTypes can be used to override the control type).. or maybe just add a warning in the ColorPicker from controls?

**Comment by shilman** [comment]
@yannbf I think:
- the out-of-box install should not cause the user's storybook to break
- things should not fail silently if they break our assumptoins

If we take those two statements as constraints, the natural thing would be to restrict the color inference to string types only and warn if there's a conflict. WDYT?

**Comment by yannbf** [comment]
> @yannbf I think:
> 
> * the out-of-box install should not cause the user's storybook to break
> * things should not fail silently if they break our assumptoins
> 
> If we take those two statements as constraints, the natural thing would be to restrict the color inference to string types only and warn if there's a conflict. WDYT?

Sounds like a plan! I'd say it's also important to see how to better handle unforeseen events like this. I reproduced it locally and the entire Storybook breaks, leaving the user clueless with a blank page. This happened because [this piece of code](https://github.com/storybookjs/storybook/blob/f9158180b8c3ba7b2c4d56d8bd6352efe544aae5/lib/components/src/controls/Color.tsx#L245) in the color picker expected string but received an object instead. 

I thought we had an ErrorBoundary in the addons panel. Might be a good task to investigate! Would be much better if the result was actually presented in a nice looking error screen inside of the specific panel where it broke. Likely would allow users to continue using Storybook, and it would guide them to find a fix.

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.0-alpha.29 containing PR #14684 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by Kiel-H-Byrne** [comment]
i still have this issue but this thread helped work around it; 
my `color` type is either a string or an array of strings (color strings); 
the `control` for my `color` argType is colorpicker. and it doesn't like this. 
colorpicker is trying to do a replace on `#` to convert the colors to rgba and hsl; however when the color is not a string, it throws the "replace is not a function"

so i took the control type off and everything works fine.
