### ISSUE TITLE
[6.3.0rc-8] Controls not inheriting args from url.

### ISSUE THREAD

**Issue by TheComputerM** [storybookjs/storybook#15278]
**Describe the bug**
The args in the url are not obeyed.

**To Reproduce**
I toggle a control named `outlined`
![image](https://user-images.githubusercontent.com/24741538/122386938-fdc6cc80-cf8b-11eb-9f53-7d1372327a1c.png)

I copy the url and paste it into another tab.
![image](https://user-images.githubusercontent.com/24741538/122387028-0fa86f80-cf8c-11eb-9a31-83b9bd12d56a.png)

The `outlined` control is not toggled on.

**System**
  System:
    OS: Windows 10 10.0.19041
    CPU: (4) x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 81.0.4044.138
    Edge: Spartan (44.19041.1023.0), Chromium (91.0.864.48)
  npmPackages:
    @storybook/addon-a11y: ^6.3.0-rc.8 => 6.3.0-rc.8
    @storybook/addon-controls: ^6.3.0-rc.8 => 6.3.0-rc.8
    @storybook/addon-measure: ^1.2.4 => 1.2.4
    @storybook/addon-storysource: ^6.3.0-rc.8 => 6.3.0-rc.8
    @storybook/addon-svelte-csf: ^1.1.0 => 1.1.0
    @storybook/addon-viewport: ^6.3.0-rc.8 => 6.3.0-rc.8
    @storybook/addons: ^6.3.0-rc.8 => 6.3.0-rc.8
    @storybook/svelte: ^6.3.0-rc.8 => 6.3.0-rc.8
    @storybook/theming: ^6.3.0-rc.8 => 6.3.0-rc.8

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199622255231368/1200548252496343) by [Unito](https://www.unito.io)

**Comment by shilman** [comment]
Can you please create a reproduction by running `npx sb@next repro`, following the instructions, and linking it in your issue description? Or if you have an existing repro you can share, that would be much appreciated!

Also, do you happen to be using the vite-builder?

**Comment by TheComputerM** [comment]
I am not using storybook-builder-vite. Can I send you a repro using `sb init`?

**Comment by shilman** [comment]
@TheComputerM that's basically what `sb repro` does, but it adds a little extra information to standardize the repo for maintainers to consume

**Comment by TheComputerM** [comment]
Here is repro: https://github.com/TheComputerM/url-params-storybook

**Comment by ghengeveld** [comment]
The way the options are configured is [deprecated](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-controloptions) (see console), but correcting it did not help. Need to look into this.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-alpha.0 containing PR #15332 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by TheComputerM** [comment]
Thank you very much @shilman.

**Comment by TheComputerM** [comment]
@shilman , @ghengeveld Just tested this out in storybook 6.4.0 alpha, still getting the same error. Even reinstalled the node_modules folder.

**Comment by shilman** [comment]
@TheComputerM do you have a repro repo you can share?

**Comment by shilman** [comment]
@ghengeveld can you check out the repro above with 6.4 and let me know what you find?

**Comment by ghengeveld** [comment]
With that repo, after upgrading with `npx sb upgrade --prerelease` I see the problem appears resolved for `boolean` and `option` types, but the backgroundColor is still broken.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.3.1 containing PR #15332 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by cellog** [comment]
this is still present in 6.3.6. I reproduced this in an `.mdx` file using the docs plugin.

```mdx
export const Component = <div>hi</div>
export const Template = (args) => {
  console.log(args);
  return (
    <div>hi</div>
  );
};

<Meta
  title="Bug"
  component={Component}
  argTypes={{
    allowedPageSizes: {
      options: ["custom", "undefined"],
      control: { type: "radio" },
      mapping: {
        undefined: undefined,
        custom: [5, 20, 50],
      },
    },
  }}
/>

<Canvas>
  <Story name="testing">{Template.bind({})}</Story>
</Canvas>
```

With that story I don't see the bug. The component in question has several parameters. I set the args for callbacks to dummy values, and that didn't help. I don't see any error messages

This is a hard blocker for us upgrading to version 7. We use the knobs plugin to open up stories in new windows and run cypress tests against them for integration tests. We cannot migrate our system over to controls in preparation for storybook 7 unless this is isolated and fixed. I see this is part of the 6.4 milestones and help is wanted. Is there any more information on the status of this bug?

**Comment by shilman** [comment]
@tmeasday is this also an issue you looked into, or am I confusing it with another high priority URL issue?

**Comment by cellog** [comment]
How would I determine what the inferred argType looks like? allowedPageSizes is an array of numbers, but it's defined using a typescript generic. When undefined, it uses a default value of `[10, 20, 40, 60, 100]`.

**Comment by shilman** [comment]
@cellog in a story export:

```js
export const MyStory = (args, context) => {
  console.log(context.argTypes);
  // normal story ...
}
```

**Comment by tmeasday** [comment]
@cellog also what does a malfunctioning URL look like for you?

**Comment by cellog** [comment]
the URL looks correct (same params as a functioning version) `args=allowedPageSizes:custom` or something like that (I'm on a different machine atm)

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.30 containing PR #16508 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
