### ISSUE TITLE
Storybook build fails with "Cannot find module 'webpack/lib/util/makeSerializable.js" after upgrading storybook packages to 6.3.0

### ISSUE THREAD

**Issue by ismay** [storybookjs/storybook#15336]
**Describe the bug**
`start-storybook` and `build-storybook` fail with `Error: Cannot find module 'webpack/lib/util/makeSerializable.js'`

**To Reproduce**
See this commit: https://github.com/ismay/superwolff/commit/2ef03b79734af55c87d8b58f84422c1e1894a2c2. Chromatic tests here are unchanged, so on CI the build isn't failing. However a local npm install (even after clearing node_modules) of this commit, and running `npm run storybook:start` yields the following output:

```
> storybook:start
> start-storybook -p 6006 --quiet

info @storybook/react v6.3.0
info 
info => Loading presets
info => Loading 1 config file in "/Users/ismay/Projects/github/ismay/superwolff/.storybook"
info => Loading 9 other files in "/Users/ismay/Projects/github/ismay/superwolff/.storybook"
info => Adding stories defined in "/Users/ismay/Projects/github/ismay/superwolff/.storybook/main.js"
info => Using prebuilt manager
info => Using implicit CSS loaders
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module 'webpack/lib/util/makeSerializable.js'
Require stack:
- /Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/react-docgen-typescript-plugin/dist/dependency.js
- /Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/react-docgen-typescript-plugin/dist/plugin.js
- /Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/react-docgen-typescript-plugin/dist/index.js
- /Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/react/dist/cjs/server/framework-preset-react-docgen.js
- /Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/core-common/dist/cjs/presets.js
- /Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/core-common/dist/cjs/index.js
- /Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/core-server/dist/cjs/index.js
- /Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/core/dist/cjs/server.js
- /Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/core/server.js
- /Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/react/dist/cjs/server/index.js
- /Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/react/bin/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/react-docgen-typescript-plugin/dist/dependency.js:6:55)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at /Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/react-docgen-typescript-plugin/dist/plugin.js:108:42
    at _next0 (eval at create (/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/builder-webpack5/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:203:1)
    at Hook.eval [as call] (eval at create (/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/builder-webpack5/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:286:1)
    at Hook.CALL_DELEGATE [as _call] (/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/builder-webpack5/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/builder-webpack5/node_modules/webpack/lib/Compiler.js:1017:26) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/react-docgen-typescript-plugin/dist/dependency.js',
    '/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/react-docgen-typescript-plugin/dist/plugin.js',
    '/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/react-docgen-typescript-plugin/dist/index.js',
    '/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/react/dist/cjs/server/framework-preset-react-docgen.js',
    '/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/core-common/dist/cjs/presets.js',
    '/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/core-common/dist/cjs/index.js',
    '/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/core-server/dist/cjs/index.js',
    '/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/core/dist/cjs/server.js',
    '/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/core/server.js',
    '/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/react/dist/cjs/server/index.js',
    '/Users/ismay/Projects/github/ismay/superwolff/node_modules/@storybook/react/bin/index.js'
  ]
}
```

**System**

```
Environment Info:

  System:
    OS: macOS 11.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 15.14.0 - /var/folders/61/0bv_jh4j7jv0znfdbw6p5c180000gn/T/fnm_multishells/21506_1624468041471/bin/node
    npm: 7.9.0 - /var/folders/61/0bv_jh4j7jv0znfdbw6p5c180000gn/T/fnm_multishells/21506_1624468041471/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0.1
    Safari: 14.1
  npmPackages:
    @storybook/addon-actions: ^6.3.0 => 6.3.0 
    @storybook/addon-essentials: ^6.3.0 => 6.3.0 
    @storybook/addon-links: ^6.3.0 => 6.3.0 
    @storybook/builder-webpack5: ^6.3.0 => 6.3.0 
    @storybook/manager-webpack5: ^6.3.0 => 6.3.0 
    @storybook/react: ^6.3.0 => 6.3.0 
```

**Comment by shilman** [comment]
Did you try installing `webpack5` as a project dependency?

Do you have a repro you can share? You can create a reproduction by running `npx sb@next repro`, following the instructions, and linking it in your issue description. We prioritize issues with reproductions over those without. Thank you! 🙏

**Comment by dohomi** [comment]
@shilman 
I am facing the same issue. After manually adding webpack 5 I receive this errors in the install:
```
Could not resolve dependency:
npm ERR! peer webpack@"^2.0.0 || ^3.0.0 || ^4.0.0" from webpack-filter-warnings-plugin@1.2.1
npm ERR! node_modules/webpack-filter-warnings-plugin
npm ERR!   webpack-filter-warnings-plugin@"^1.2.1" from @storybook/builder-webpack4@6.3.0
npm ERR!   node_modules/@storybook/builder-webpack4
npm ERR!     @storybook/builder-webpack4@"6.3.0" from @storybook/addon-docs@6.3.0
npm ERR!     node_modules/@storybook/addon-essentials/node_modules/@storybook/addon-docs
npm ERR!       @storybook/addon-docs@"6.3.0" from @storybook/addon-essentials@6.3.0
npm ERR!       node_modules/@storybook/addon-essentials
npm ERR!     2 more (@storybook/core-server, @storybook/core-server)
```
It seems that internally some storybook features still point to webpack4?

**Comment by ismay** [comment]
> Did you try installing `webpack5` as a project dependency?

Haven't tried that yet.

> Do you have a repro you can share? You can create a reproduction by running `npx sb@next repro`, following the instructions, and linking it in your issue description. We prioritize issues with reproductions over those without. Thank you! 🙏

Sorry about that, I was a bit pressed for time when I opened this. I'll take a closer look asap and see if I can create a minimal reproduction. Should be this week. I'll try adding webpack 5 as a project dependency as well at that time and report back (weird that apparently the chromatic build doesn't need webpack 5 to be set as a dependency in my project).

**Comment by maxmezzomo** [comment]
I had the same issue from 6.29 (using  npx sb init --builder webpack5 -f to install few weeks back) to 6.3. Upgrading to latest webpack fixed

**Comment by ismay** [comment]
Ok, I've tried to reproduce it, and in messing around with it I seem to have fixed it 'accidentally'. I've narrowed it down to changes in the `package-lock.json`, those are the only (indirect) changes I made in the end that had an effect on the above bug. For some reason, after multiple rounds of adding/deleting over 20k lines to the package-lock, npm seems to have settled on a combination that works.

I've had this before with updates to storybook, where I have to kind of install and reinstall until the package-lock settles on a combination that works 🤷‍♂️. I can imagine you can't do anything with this as maintainers, so apologies if it's too vague. Feel free to close this issue if it's not actionable.

**Comment by JoshuaKGoldberg** [comment]
I can reproduce this issue with the current latest version of webpack here: https://github.com/Codecademy/client-modules/pull/1404/commits/d45f6dca52db943b653b9ddb639915ee8bd28df3. Sorry the reproduction is so complex; it's the only one I've got 😉 .

The CircleCI builds are private but you can clone the repository locally, build all packages, and `yarn start` to reproduce:

```
git clone https://github.com/Codecademy/client-modules
git checkout d45f6dca52db943b653b9ddb639915ee8bd28df3
cd client-modules
yarn
yarn lerna bootstrap
yarn build-all
yarn start
```

Adding webpack to the `devDependencies` in `packages/styleguide/package.json` indeed resolves the crash: https://github.com/Codecademy/client-modules/pull/1404/commits/1d4780d2b6f55144599da1aeddab9aebce18cb85

The offending lines of code were a chuckle:

```js
// eslint-disable-next-line
// @ts-ignore: What's the right way to refer to this one?
const makeSerializable_js_1 = tslib_1.__importDefault(require("webpack/lib/util/makeSerializable.js"));
// eslint-disable-next-line
// @ts-ignore: What's the right way to refer to this one?
const NullDependency_js_1 = tslib_1.__importDefault(require("webpack/lib/dependencies/NullDependency.js"));
```

**Comment by jgoux** [comment]
Hello, we're in the same situation.
Adding webpack@5 in our dev dependencies doesn't solve the issue for us, we still have the same error.
We're in a monorepo using yarn workspaces.

**Comment by tassoevan** [comment]
It looks like a conflict from the version used by `@storybook/react-docgen-typescript-plugin`. Here's the resolution from yarn that spawned the same error for me:

```
 @storybook/react@npm:6.3.1
└─ @storybook/react-docgen-typescript-plugin@npm:1.0.2-canary.3c70e01.0 (via npm:1.0.2-canary.3c70e01.0)
```

**Comment by tassoevan** [comment]
I can confirm @jgoux workaround for yarn-based monorepos. Only installing `webpack@5` at the root workspace did it for me.

**Comment by shobhitsharma** [comment]
@tassoevan Did adding webpack in `nohoist` in root package.json helps for you for monorepo context?

**Comment by josh-stevens** [comment]
I was only able to fix this by adding this:

`typescript: {
    reactDocgen: false
  },`

It seems that storybook was still trying to reference webpack 4 until I switched this toggle off.

**Comment by shilman** [comment]
@josh-stevens which version were you using?

**Comment by josh-stevens** [comment]
This is in 6.3.6

Turning off docgen seems to be interfering with some other handy addons so this isn't a great workaround.

**Comment by shilman** [comment]
@josh-stevens did you try adding webpack5 as a dev dependency in your project root?

**Comment by jgoux** [comment]
> I can confirm @jgoux workaround for yarn-based monorepos. Only installing `webpack@5` at the root workspace did it for me.

It isn't fully solving the issue actually, now if I install new deps, I have the error again. I need to wipe all my monorepo node_modules folders and install from scratch to make the error disappear, it's quite annoying.

**Comment by mdirshaddev** [comment]
Adding Webpack5 as dev dependencies fix the issue regardless of any version of storybook

**Comment by mdirshaddev** [comment]
this thread is really helpful @shilman Thank you.

**Comment by GuiWain** [comment]
`typescript: { reactDocgen: false },` it worked! 🚀

**Comment by luxalpa** [comment]
Can confirm the workaround. It works because for some reason this docgen thing is still using Webpack 4. Should probably get updated.

**Comment by jackhair** [comment]
> I was only able to fix this by adding this:
> 
> `typescript: { reactDocgen: false },`
> 
> It seems that storybook was still trying to reference webpack 4 until I switched this toggle off.

Came across the same issue this morning, can confirm this fixed it for me. Thank you.

**Comment by thedavidprice** [comment]
Devs are reporting this issue with Redwood's Storybook integration, specifically when trying to use `@storybook/addon-essentials`. 

We're working on documenting the workaround mentioned above (thanks all!). Would be great to have upstream resolution of the core issue.

**Comment by shilman** [comment]
@thedavidprice As far as I know this is a hoisting issue. I believe the workaround is to install `webpack@5` as a dev dependency in your project root, which forces it to be hoisted. The real fix will be to make webpack5 Storybook's default, or make no default and have users choose between webpack4/5, but we can't do that until Storybook 7.0, so the workaround is the best we can do for now. If there are better solutions that don't involve breaking changes, we are very open to incorporating them! Thanks for your patience.

**Comment by luxalpa** [comment]
No, I don't think it's a hoisting issue. The error only started appearing for me after switching to Yarn's Plug'n'Play and I've only been using Webpack 5 in the project (not just for storybook but also for the normal build process and yes it's listed as a dependency). The issue seems to be this react-docgen thing using the wrong webpack version.

**Comment by thedavidprice** [comment]
@shilman always appreciate you taking time to help! re: "Unfortunately, we can't do that until Storybook 7.0", completely understood.

Redwood (using yarn) _does_ install Webpack v5 in the root workspace. So your description of the problem nudged me to do some further digging (including a yarn resolution in package.json), which led to some Webpack polyfill errors that weren't originally displaying in build error outpout (re: missing _additional_ `resolve.fallback` settings in our Webpack config specific to Storybook). For others using Webpack v5, you might find this to be your case as well even after adding Webpack v5 as a root package (or setting as a yarn resolution via package.json).

Regardless, the issue is resolved in the upcoming Redwood v0.37 — no project workarounds are required. 🚀 This is a big release for us with a lot of moving parts, so it's hard to identify the root "fix". Looking at diffs, I believe it has more to do with upgrading to Storybook v6.3.8 and Webpack v5.53.0 (devServer v4.2.1) than any of our internal config changes.

**Comment by shilman** [comment]
@thedavidprice that's wonderful news! 🙌  if you come across any learnings that should be incorporated on the storybook side, please share. and congrats on the big upcoming release!

**Comment by luxalpa** [comment]
Isn't this line the root of the problem?: https://github.com/storybookjs/storybook/blob/main/addons/docs/src/frameworks/common/preset.ts#L9

I'm not too familiar with storybooks code base, but to me this looks like it is always using webpack4 for docs. Also it says "fixme"...

**Comment by iandd0824** [comment]
> I was only able to fix this by adding this:
> 
> `typescript: { reactDocgen: false },`
> 
> It seems that storybook was still trying to reference webpack 4 until I switched this toggle off.

This works for me. Here is the complete `module.exports` in `.storybook/main.js`

```Javascript
module.exports = {
  "stories": [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ],
  "core": {
    "builder": "webpack5"
  },
  "typescript": { "reactDocgen": false }
}
```

**Comment by raulvictorrosa** [comment]
For me nothing of this worked.

**Comment by blistok** [comment]
> For me nothing of this worked.

@raulvictorrosa Try @patrick-mcdougle [solution](https://github.com/storybookjs/storybook/issues/15336#issuecomment-954066372), but make sure to do a clean install after you've added `resolutions` field to `package.json`:
```bash
rm -rf node_modules package-lock.json && npm i
```

**Comment by thdk** [comment]
I ran into this error when using npm workspaces with a simple create-react-app with storybook initialized and configured to use webpack 5 builder.

I assume the error is caused because create-react-app still depends on webpack 4.

For what it's worth I have create a simple reproduction repo with my setup.

https://github.com/thdk/repro-storybook-15336

**Comment by shilman** [comment]
@thdk Yes, Storybook requires that you use the webpack4 builder with CRA specifically

**Comment by ndelangen** [comment]
@shilman does this require my attention, you assigned me?

**Comment by shilman** [comment]
Yes, it's been awhile I believe we discussed trying to solve this FIXME https://github.com/storybookjs/storybook/issues/15336#issuecomment-926479942

**Comment by ndelangen** [comment]
I see, so need to add a switch detecting which builder we're on.. On it!

**Comment by jlaramie** [comment]
webpack@5.64.2 for some reason has removed the "lib" directory which breaks the automatic storybook install unless overridden in resolutions. webpack@5.64.1 and below do not have this issue.

**Comment by ndelangen** [comment]
could it be this?:

![Screenshot 2021-11-24 at 10 44 22](https://user-images.githubusercontent.com/3070389/143214140-11fc8633-9431-4e61-8d4b-7559959775a1.png)

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-rc.9 containing PR #16780 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by RyanClementsHax** [comment]
I think this issue is still present. I upgraded to `6.4.0` and I'm still getting the same error. Here is a [reproduction repo](https://github.com/RyanClementsHax/ryanclements.dev/tree/upgrade-storybook-6.4.0); just run `yarn sb` to see the error.

**Comment by patrick-mcdougle** [comment]
Removing types in #16780 would not fix this. The webpack 4 dependency needs to be completely removed (or conditionally switched) from the codebase or this will keep happening.

**Comment by doomedramen** [comment]
I am also still having this with 6.4.0

```
info @storybook/react v6.4.0
info 
(node:81855) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
ERR! Error: Cannot find module '@storybook/manager-webpack5'
ERR! Require stack:
ERR! - /Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/utils/get-manager-builder.js
ERR! - /Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/build-static.js
ERR! - /Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - /Users/martinpage/workspace/chutney/node_modules/@storybook/core/dist/cjs/server.js
ERR! - /Users/martinpage/workspace/chutney/node_modules/@storybook/core/server.js
ERR! - /Users/martinpage/workspace/chutney/node_modules/@storybook/react/dist/cjs/server/index.js
ERR! - /Users/martinpage/workspace/chutney/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
ERR!     at getManagerBuilder (/Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/utils/get-manager-builder.js:38:61)
ERR!     at buildDevStandalone (/Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/build-dev.js:103:71)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async buildDev (/Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5)
ERR!  Error: Cannot find module '@storybook/manager-webpack5'
ERR! Require stack:
ERR! - /Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/utils/get-manager-builder.js
ERR! - /Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/build-static.js
ERR! - /Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/index.js
ERR! - /Users/martinpage/workspace/chutney/node_modules/@storybook/core/dist/cjs/server.js
ERR! - /Users/martinpage/workspace/chutney/node_modules/@storybook/core/server.js
ERR! - /Users/martinpage/workspace/chutney/node_modules/@storybook/react/dist/cjs/server/index.js
ERR! - /Users/martinpage/workspace/chutney/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
ERR!     at Function.resolve (node:internal/modules/cjs/helpers:108:19)
ERR!     at getManagerBuilder (/Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/utils/get-manager-builder.js:38:61)
ERR!     at buildDevStandalone (/Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/build-dev.js:103:71)
ERR!     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR!     at async buildDev (/Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/build-dev.js:161:5) {
ERR!   code: 'MODULE_NOT_FOUND',
ERR!   requireStack: [
ERR!     '/Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/utils/get-manager-builder.js',
ERR!     '/Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/build-static.js',
ERR!     '/Users/martinpage/workspace/chutney/node_modules/@storybook/core-server/dist/cjs/index.js',
ERR!     '/Users/martinpage/workspace/chutney/node_modules/@storybook/core/dist/cjs/server.js',
ERR!     '/Users/martinpage/workspace/chutney/node_modules/@storybook/core/server.js',
ERR!     '/Users/martinpage/workspace/chutney/node_modules/@storybook/react/dist/cjs/server/index.js',
ERR!     '/Users/martinpage/workspace/chutney/node_modules/@storybook/react/bin/index.js'
ERR!   ]
ERR! }

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.
```

**Comment by ThePredators** [comment]
> I was only able to fix this by adding this:
> 
> `typescript: { reactDocgen: false },`
> 
> It seems that storybook was still trying to reference webpack 4 until I switched this toggle off.

This solved the issue !

**Comment by ndelangen** [comment]
Seems you're attempting to use the webpack5 manager builder, but haven't installed it?

> ERR! Error: Cannot find module '@storybook/manager-webpack5'

please install that package. This seems like a different issue to me, WDYT @shilman ?

**Comment by doomedramen** [comment]
@ThePredators I have `typescript: { reactDocgen: false },` in my main.js and it has made no difference.

**Comment by ThePredators** [comment]
Strange it worked for me @doomedramen. Everything works as expected i just created a new project yesterday, and after adding that typescript line to module.exports, it worked ! 

this is my package.json : 
 ```
{
  "name": "...",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "storybook": "start-storybook -p 6006 ./public",
    "build-storybook": "build-storybook -s public"
  },
  "dependencies": {
    "next": "12.0.4",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.16.0",
    "@storybook/addon-actions": "^6.4.0",
    "@storybook/addon-essentials": "^6.4.0",
    "@storybook/addon-links": "^6.4.0",
    "@storybook/builder-webpack5": "^6.4.0",
    "@storybook/manager-webpack5": "^6.4.0",
    "@storybook/react": "^6.4.0",
    "@types/node": "16.11.10",
    "@types/react": "17.0.37",
    "babel-loader": "^8.2.3",
    "eslint": "7",
    "eslint-config-next": "12.0.4",
    "eslint-plugin-storybook": "^0.5.0",
    "typescript": "4.5.2"
  }
}
 ```

This is the error before i add anything to .storybook/main.js
```
❯ npm run storybook                                                                                                            ─╯

> storybook
> start-storybook -p 6006 ./public

info @storybook/react v6.4.0
info
info => Loading presets
info => Using implicit CSS loaders
info => Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
9% setup compilation DocGenPluginnode:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module 'webpack/lib/util/makeSerializable.js'
```

This is my .storybook/main.js : 
```

module.exports = {
  typescript: { reactDocgen: false },
  "stories": [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "webpack5"
  }
}
```

**Comment by doomedramen** [comment]
@ThePredators I merged my devdepends with yours:


```
MINE:
"@rollup/plugin-commonjs": "^21.0.1",
    "@rollup/plugin-node-resolve": "^13.0.6",
    "@rollup/plugin-typescript": "^8.3.0",
    "@storybook/addon-essentials": "^6.4.0",
    "@storybook/addon-postcss": "^2.0.0",
    "@storybook/builder-webpack5": "^6.4.0",
    "@storybook/react": "^6.4.0",
    "@tailwindcss/forms": "^0.3.4",
    "@types/node": "^14.14.37",
    "@types/react": "^17.0.3",
    "@types/react-dom": "^17.0.3",
    "postcss": "^8.2.10",
    "postcss-import": "^14.0.1",
    "postcss-preset-env": "^6.7.0",
    "rollup": "^2.60.1",
    "rollup-plugin-peer-deps-external": "^2.2.4",
    "rollup-plugin-terser": "^7.0.2",
    "stylelint": "^13.12.0",
    "stylelint-config-recommended": "^4.0.0",
    "stylelint-prettier": "^1.2.0",
    "tailwindcss": "^2.1.1",
    "typescript": "^4.2.3",
    "webpack": "5",

YOURS:
    "@babel/core": "^7.16.0",
    "@storybook/addon-actions": "^6.4.0",
    "@storybook/addon-essentials": "^6.4.0",
    "@storybook/addon-links": "^6.4.0",
    "@storybook/builder-webpack5": "^6.4.0",
    "@storybook/manager-webpack5": "^6.4.0",
    "@storybook/react": "^6.4.0",
    "@types/node": "16.11.10",
    "@types/react": "17.0.37",
    "babel-loader": "^8.2.3",
    "eslint": "7",
    "eslint-config-next": "12.0.4",
    "eslint-plugin-storybook": "^0.5.0",
    "typescript": "4.5.2"
    ```
    Yours had newer versions of: `@types/node`, `@types/react`, `typescript` and I removed `Webpack`.
    
    This now builds for me 👍

**Comment by 72gm** [comment]
> > I was only able to fix this by adding this:
> > `typescript: { reactDocgen: false },`
> > It seems that storybook was still trying to reference webpack 4 until I switched this toggle off.
> 
> This solved the issue !

This works for me but what is the impact of doing this? And should this not have been fixed in v6.4?

**Comment by luxalpa** [comment]
> This works for me but what is the impact of doing this? And should this not have been fixed in v6.4?

Disabling reactDocgen means that it will no longer be able to automatically infer your props from your component, so you'd have to manually tell storybook about each prop and their type.

**Comment by esharmony** [comment]
> > > I was only able to fix this by adding this:
> > > `typescript: { reactDocgen: false },`
> > > It seems that storybook was still trying to reference webpack 4 until I switched this toggle off.
> > 
> > 
> > This solved the issue !
> 
> This works for me but what is the impact of doing this? And should this not have been fixed in v6.4?

I am also wondering this, plus I am noticing now my doc does not apply my theme, wondering if this is related.

**Comment by gregorybolkenstijn** [comment]
Still having this with version 6.5.0-alpha.1, I had to apply the `typescript: { reactDocgen: false }` fix to get it working.

**Comment by remy90** [comment]
Not sure if this should be treated as a separate issue, but the react docgen 'fix' only works in yarn v2+  when ```nodeLinker: node-modules```
Setting `pnp` results in the following error:
```
Failed to compile.

./.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/page-loader.js
Error: Failed to read source code from /Users/name/repo/repo-name/.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/page-loader.js

Caused by:
    No such file or directory (os error 2)

Import trace for requested module:
./.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/index.js
./.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/next.js

./.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/request-idle-callback.js
Error: Failed to read source code from /Users/name/repo/repo-name/.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/request-idle-callback.js

Caused by:
    No such file or directory (os error 2)

Import trace for requested module:
./.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/script.js
./.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/index.js
./.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/next.js

./.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/router.js
Error: Failed to read source code from /Users/name/repo/repo-name/.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/router.js

Caused by:
    No such file or directory (os error 2)

./.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/vitals.js
Error: Failed to read source code from /Users/name/repo/repo-name/.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/vitals.js

Caused by:
    No such file or directory (os error 2)

Import trace for requested module:
./.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/index.js
./.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/client/next.js

./.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/shared/lib/amp-context.js
Error: Failed to read source code from /Users/name/repo/repo-name/.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/shared/lib/amp-context.js

Caused by:
    No such file or directory (os error 2)

Import trace for requested module:
./.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/shared/lib/head.js
./.yarn/__virtual__/next-virtual-49489493a8/0/cache/next-npm-12.0.7-4cffaa57c8-78a0ebd697.zip/node_modules/next/dist/pages/_error.js


> Build failed because of webpack errors
```

**Comment by arlyon** [comment]
Note to others, despite the linked PR above (#16831) referring to this issue, it does not fix the problem; this issue still persists on `6.5.0-alpha.1`

**Comment by simzikov** [comment]
This issue is still present in @storybook/react 6.4.9 and 6.5.0-alpha.1.

**Comment by khanakia** [comment]
I am facing the same issue with NEXT.js `npx sb init --builder webpack5` using this command as showing in the tutorial here https://storybook.js.org/blog/get-started-with-storybook-and-next-js/

**Comment by danfusaro** [comment]
@khanakia I am running into the same problem in almost real time as you and here is a solution that worked for me.

In `storybook/main.js`: 

`const path = require('path');
const fs = require('fs');

function getDirectories(path) {
  return fs.readdirSync(path).filter(function (file) {
    return fs.statSync(path + '/' + file).isDirectory();
  });
}

module.exports = {
  typescript: { reactDocgen: false },
  "stories": [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials"
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "webpack5"
  },
  webpackFinal: async (config, { configType }) => {
    // `configType` has a value of 'DEVELOPMENT' or 'PRODUCTION'
    // You can change the configuration based on that.
    // 'PRODUCTION' is used when building the static version of storybook.

    // Set alias based on folder name
    const root = path.dirname(path.resolve(__dirname));
    const dirs = getDirectories(root).filter(dir => dir.charAt(0) !== '.' && dir !== 'node_modules');
    const alias = dirs.reduce((p, next) => {
      return { ...p, [`@${next}`]: `${root}/${next}` }
    }, {});

    config.resolve.alias = alias;
    // Return the altered config
    return config;
  },
}`

I am iterating through the folder names of the root of the project and adding a '@{dirname}' to the alias object.

**Comment by khanakia** [comment]
@danfusaro thank you :)

**Comment by quantran020173** [comment]
Hi guys,
Do not turn off reactDocgen. It will not generate your whole props in the document. Instead of turning off reactDocgen, the storybook has a guide in here to fix: 
https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5-manager-build

Storybook run well after follow migration:
![Screen Shot 2021-12-22 at 16 25 06](https://user-images.githubusercontent.com/86219260/147069501-caa8ad12-d427-4ed7-aeea-b753a5dae12b.png)

**Comment by mdirshaddev** [comment]
Add webpack in your project as dev dependencies.
This will solve the issue.

**Comment by floreq** [comment]
yup, thanks @quantran020173 and @mdirshaddev. Only `yarn add webpack@5 --dev` worked like a charm.
![image](https://user-images.githubusercontent.com/25390589/147138775-7d2d36f9-c6f8-422d-a05e-8d77a1364836.png)

**Comment by Dangoo** [comment]
@mdirshaddev @floreq we already had `"webpack": "^5.61.0"` in our `package.json`.
These package versions played still fine together:
- `@storybook/react@6.3.12`
- `@storybook/builder-webpack5@6.3.12`
- `@storybook/manager-webpack5@6.3.12`

After upgrading to `6.4.x` using the script `npx sb@latest upgrade` we got the above error.
We are using Storybook inside a subpackage as part of a lerna monorepo.

@shilman any idea what could cause the issue?

**Comment by Denver44** [comment]
> `typescript: { reactDocgen: false },` it worked! 🚀

It woked for me, thank you, buddy

**Comment by uwemneku** [comment]
> > I was only able to fix this by adding this:
> > `typescript: { reactDocgen: false },`
> > It seems that storybook was still trying to reference webpack 4 until I switched this toggle off.
> 
> THIS WORKED FOR ME! 🎉
> 
> in case anyone else wants to try this: add `typescript: { reactDocgen: false },` into module.exports inside .storybook/main.js

had this issue with nextJS and this worked for me. Thanks

**Comment by markrocks** [comment]
> I was only able to fix this by adding this:
> 
> `typescript: { reactDocgen: false },`
> 
> It seems that storybook was still trying to reference webpack 4 until I switched this toggle off.

Wellllll.. this does work ( by allowing Storybook to compile and run) - but once implemented we could no longer see any content on the docs tab -- so this is not a viable solution. -- Still - its a decent stop gap that allows you to see your stories while you figure out a long term solution. ( This was happening to me on Storybook 6.4.9 )

![Screen Shot 2022-01-06 at 12 22 12 AM](https://user-images.githubusercontent.com/7376321/148332701-6a775637-6d95-4df0-bd82-c61c380e0f6d.png)

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.11 containing PR #16752 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by jeremyzilar** [comment]
Super helpful, thank you @shilman 🎉

**Comment by sivaraj-v** [comment]
Hi @shilman  / @storybookjs team,

I revalidated with 6.5.0-alpha.12 release, still users are getting following error

```
9% setup compilation DocGenPlugininternal/modules/cjs/loader.js:892
  throw err;
  ^

Error: Cannot find module 'webpack/lib/util/makeSerializable.js'
Require stack:
- /node_modules/@storybook/react-docgen-typescript-plugin/dist/dependency.js
```

Package.json 

```
    "@storybook/addon-actions": "6.5.0-alpha.12",
    "@storybook/addon-docs": "6.5.0-alpha.12",
    "@storybook/addon-jest": "6.5.0-alpha.12",
    "@storybook/addon-links": "6.5.0-alpha.12",
    "@storybook/addon-viewport": "6.5.0-alpha.12",
    "@storybook/builder-webpack5": "^6.5.0-alpha.12",
    "@storybook/manager-webpack5": "^6.5.0-alpha.12",
    "@storybook/react": "6.5.0-alpha.12",
    "@storybook/theming": "6.5.0-alpha.12",
```

**Comment by patrick-mcdougle** [comment]
This did not work for me either.

Reiterating what worked for me:
```
  "dependencies": {
    //...
    "webpack": "^5.62.1",
    //...
  },
  "resolutions": {
    "@storybook/react/webpack": "^5"
  }
```
Until webpack 4 is completely out of the storybook packages this still has a chance of being hoisted wrong. OR react-docgen-typescript-plugin needs to bump the peerDependency version to >= 5.

**Comment by patrick-mcdougle** [comment]
Since @storybook/react has a strict dependency on webpack 4, the closest webpack to @storybook/react-docgen-typescript-plugin is webpack 4 even though the running webpack is webpack 5. This means that the webpack that's resolved via @storybook/react-docgen-typescript-plugin 's peerDependency is webpack 4. We need to move webpack to a peerDependency of @storybook/react and relax the version to 4.x || 5.x if that is safe to do so.

**Comment by shilman** [comment]
@sivaraj-v did you add webpack5 as a project dependency? https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#wrong-webpack-version

**Comment by patrick-mcdougle** [comment]
I think the hard (runtime) dependency on webpack left the @storybook/react package in https://github.com/storybookjs/storybook/pull/10571/files. Now since that package only needs TYPES from webpack, it's possible that we could mark webpack as a devDependency instead of a dependency in the @stoybook/react package.json file.

**Comment by patrick-mcdougle** [comment]
^ I'm not positive that this will fix the issue, but it will move this further down the path to resolution.

**Comment by shilman** [comment]
Thanks @patrick-mcdougle !!! 🙏 Continuing the conversation on the PR

**Comment by sivaraj-v** [comment]
> @sivaraj-v did you add webpack5 as a project dependency? https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#wrong-webpack-version

Yes, Webpack5 installed properly & declaration are done in main.js as per storybook guidelines.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.14 containing PR #17192 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by patrick-mcdougle** [comment]
Provided that webpack 5 is installed at the root as either a dependency or a devDependency (as the documentation suggests), this appears to be solved for me at v6.5.0-alpha.14.

**Comment by vendramini** [comment]
> Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.14 containing PR #17192 that references this issue. Upgrade today to the `@next` NPM tag to try it out!
> 
> ```
> npx sb upgrade --prerelease
> ```
I just did it and the issue persist :(

```javascript
"dependencies": {
    "@reduxjs/toolkit": "^1.7.1",
    "axios": "^0.24.0",
    "bootstrap": "^5.1.3",
    "clsx": "^1.1.1",
    "next": "12.0.4",
    "react": "17.0.2",
    "react-bootstrap": "^2.0.2",
    "react-dom": "17.0.2",
    "react-query": "^3.34.0",
    "react-redux": "^7.2.6",
    "sass": "^1.43.5"
  },
  "devDependencies": {
    "@babel/core": "^7.16.7",
    "@storybook/addon-actions": "^6.5.0-alpha.14",
    "@storybook/addon-essentials": "^6.5.0-alpha.14",
    "@storybook/addon-links": "^6.5.0-alpha.14",
    "@storybook/builder-webpack5": "^6.5.0-alpha.14",
    "@storybook/manager-webpack5": "^6.5.0-alpha.14",
    "@storybook/react": "^6.5.0-alpha.14",
    "@types/node": "16.11.10",
    "@types/react": "^17.0.37",
    "babel-loader": "^8.2.3",
    "eslint": "7",
    "eslint-config-next": "12.0.4",
    "eslint-plugin-storybook": "^0.5.5",
    "prettier": "^2.5.1",
    "typescript": "4.5.2"
  }
```

**Comment by christian-valadez** [comment]
I ran into this issue while following the NextJS + Storybook guide - https://storybook.js.org/blog/get-started-with-storybook-and-next-js/

I was able to solve it by installing webpack 5 in my dev dependencies. 

In case this helps anyone, here's what my package.json looks like: 

```
{
  "name": "name",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "engines": {
    "node": "14.19.0"
  },
  "dependencies": {
    "next": "12.0.10",
    "react": "17.0.2",
    "react-dom": "17.0.2"
  },
  "devDependencies": {
    "@babel/core": "^7.17.2",
    "@storybook/addon-actions": "^6.4.18",
    "@storybook/addon-essentials": "^6.4.18",
    "@storybook/addon-links": "^6.4.18",
    "@storybook/builder-webpack5": "^6.4.18",
    "@storybook/manager-webpack5": "^6.4.18",
    "@storybook/react": "^6.4.18",
    "@types/node": "17.0.16",
    "@types/react": "17.0.39",
    "babel-loader": "^8.2.3",
    "eslint": "8.8.0",
    "eslint-config-next": "12.0.10",
    "eslint-plugin-storybook": "^0.5.6",
    "typescript": "4.5.5",
    "webpack": "^5.68.0"
  }
}

```

**Comment by konhi** [comment]
> If you're on a monorepo with Yarn, try this in your root package.json:
> 
> ```
> "resolutions": {
>   "webpack": "^5"
> }
> ```

This also works for a monorepo with nx and npm!

**Comment by marcusglowe** [comment]
If you're running into this, it may be because a package is in your production dependencies that also depends on webpack 4 directly. If you're on yarn, `yarn why` may help explain why webpack4 is being hoisted still. 

In our case, it was because storybook was added to production dependencies by accident.

**Comment by 16012jan** [comment]
BREAKING CHANGE:webpack < 5 used to include polyfills for node.js core modules by default. This is no longer the case. Verify if you need this module and configure a polyfill for it.

next.config.js
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  future: {
    webpack5: true,
  },
  webpack: (config) => {
    config.resolve.fallback = {
      util: require.resolve("util/")
    };
    return config;
  },
};

module.exports = nextConfig;

**Comment by jsamr** [comment]
**If you're using npm >= 8.6.0**, add the following to your top-level package.json:

```json
  "overrides": {
    "webpack": "^5"
  }
```

If using npm >= 8.3.0 < 8.6.0, that would also work, but you'd have to delete package-lock.json before it takes effect, this is a known bug.

**Comment by ugnelis** [comment]
`typescript: { reactDocgen: false },` is a **BAD FIX** because then you will loose Storybook Control feature.

As some people mentioned before, you need to have `webpack5` dependency:
```npm install --save-dev webpack```

**Comment by TomJPrice** [comment]
> Hello, we're in the same situation. Adding webpack@5 in our dev dependencies doesn't solve the issue for us, we still have the same error. We're in a monorepo using yarn workspaces.
> 
> EDIT :
> 
> It seems to work that way :
> 
> * Install webpack@5 at the root of the monorepo `yarn add -W -D webpack`
> * Add `webpack: "*"` in peerDependencies of your package.
> * ✅

This fix worked for me when adding Storybook to Turborepo. Saved me a major headache on a Friday afternoon, thanks

**Comment by thedaviddias** [comment]
@TomJPrice I'm facing the same issue, I installed `pnpm add -D -w webpack` at the root of the monorepo and added `webpack: "*"` as a `peerDependencies` in my `packages/ui` folder. I'm still getting the error:

```
Error: Cannot find module '/Users/user/dev/name-project/packages/ui/node_modules/config/webpack.config'
```

Anything you did more?

**Comment by sean256** [comment]
For anyone in a mono repo using `pnpm`, I was able to fix it with:

1. Delete all node_modules from root, `find . -name 'node_modules' -type d -prune -exec rm -rf '{}' +`
2. Reinstall all packages from root, `pnpm i`

I have a mono repo, NextJS, and Storybook.

**Comment by IvanDerlich** [comment]
> I was only able to fix this by adding this:
> 
> `typescript: { reactDocgen: false },`
> 
> It seems that storybook was still trying to reference webpack 4 until I switched this toggle off.

Add that line onto with file?

**Comment by TomJPrice** [comment]
> > I was only able to fix this by adding this:
> > `typescript: { reactDocgen: false },`
> > It seems that storybook was still trying to reference webpack 4 until I switched this toggle off.
> 
> Add that line onto with file?

It goes into `.storybook/main.js` but as mentioned by @ugnelis, you will lose some Storybook functionality. Adding webpack as a peer dependency as somebody mentioned above fixed this error for me.

**Comment by asigitjulianto** [comment]
# The solution is simply to add the following to .storybook\main.js 
reactDocgen: false

# Example
```
module.exports = {
  "stories": [
    "../stories/**/*.stories.mdx",
    "../stories/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions"
  ],
  "framework": "@storybook/react",
  "core": {
    "builder": "@storybook/builder-webpack5"
  },
  typescript: {
    reactDocgen: false
  },
}
```

**Comment by kismet-lee** [comment]
I just wanted to mention here that installing webpack5 had gotten my Storybook issue back on track. 
I used this code, we're running storybook.js with React.

`npm i -D webpack@^5.x.x`

**Comment by karolinakuzniewicz** [comment]
I'm experiencing it on a new simple Next v13 setup with Storybook with builder-webpack5. Clearing npm cache helps but the issue occurs while deploying storybook on Vercel

**Comment by ArtemFedorchuk** [comment]
> @shilman I am facing the same issue. After manually adding webpack 5 I receive this errors in the install:
> 
> ```
> Could not resolve dependency:
> npm ERR! peer webpack@"^2.0.0 || ^3.0.0 || ^4.0.0" from webpack-filter-warnings-plugin@1.2.1
> npm ERR! node_modules/webpack-filter-warnings-plugin
> npm ERR!   webpack-filter-warnings-plugin@"^1.2.1" from @storybook/builder-webpack4@6.3.0
> npm ERR!   node_modules/@storybook/builder-webpack4
> npm ERR!     @storybook/builder-webpack4@"6.3.0" from @storybook/addon-docs@6.3.0
> npm ERR!     node_modules/@storybook/addon-essentials/node_modules/@storybook/addon-docs
> npm ERR!       @storybook/addon-docs@"6.3.0" from @storybook/addon-essentials@6.3.0
> npm ERR!       node_modules/@storybook/addon-essentials
> npm ERR!     2 more (@storybook/core-server, @storybook/core-server)
> ```
> 
> It seems that internally some storybook features still point to webpack4?
> 
> Installing webpack5 with `--legacy-peer-deps` works. Do I still need to add the `@storybook/builder-webpack5` to the `addons` section of main.js? This is not mentioned in the migration docs.

You are the best!
After adding to the storybook `main.js` file this:

core: {
  builder: 'webpack5',
},
Everything compiles well

**Comment by mahdikhashan** [comment]
For me, switching from yarn to pnpm and adding webpack5 solved the issue for next.js.

**Comment by rpasechnikov** [comment]
I didn't have any luck with any solutions other than:

```
  typescript: {
    reactDocgen: false,
 },
```

This could be because we are on `yarn 1` and using `storybook 8.6.*` however 🤔
