### ISSUE TITLE
Stories are not sorted by their export (in production)

### ISSUE THREAD

**Issue by janivo** [storybookjs/storybook#15574]
**Describe the bug**
In production, stories are not sorted according to their export instead, they are sorted alphabetically.

How they should be sorted (working correctly in dev):
![image](https://user-images.githubusercontent.com/22963121/125597451-777a456f-85c1-4e79-8cc0-e0a854ada159.png)

How they are actually sorted (in production):
![image](https://user-images.githubusercontent.com/22963121/125597465-daad83b5-81ef-42c9-8bd4-0431c9b3d26b.png)

**To Reproduce**
I've tried to create an example but I could not reproduce the bug.
Here is a working example: https://github.com/inovex/elements
1. Pull repo
2. Run `yarn install`
3. Run `yarn start`
4. See that the sorting is correct
5. Run `cd packages/storybook`
6. Run `yarn build`
7. Run `cd dist`
8. Serve built content (e.g. `serve .`)
9. See wrong sorting order

Everything related to the storybook can be found under `packages/storybook`.

**System**
```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Firefox: 89.0
    Safari: 14.1.1
  npmPackages: (added manually because of monorepo)
	"@storybook/addon-actions": "^6.3.2",
    "@storybook/addon-essentials": "^6.3.2",
    "@storybook/addon-links": "^6.3.2",
    "@storybook/addon-viewport": "^6.3.2",
    "@storybook/builder-webpack5": "^6.3.2",
    "@storybook/manager-webpack5": "^6.3.2",
    "@storybook/theming": "^6.3.2",
    "@storybook/web-components": "^6.3.2",
```

**Additional context**
It seems to be related to this issue: https://github.com/storybookjs/storybook/issues/15305

I've tried to sort the stories manually within the `preview.js` but it only sorted the entries in the sidebar but not the actual content on the canvas. Meaning, I would click on the story on the top of the sidebar, leading me to the rendered story at the bottom of the page in the canvas.

**Comment by dcwarwick** [comment]
I see this too.

Here's an example:
  The storybook: https://ibm-cloud-cognitive.netlify.app/?path=/story/cloud-cognitive-canary-pageheader--demo
  The source file: https://github.com/carbon-design-system/ibm-cloud-cognitive/blob/main/packages/cloud-cognitive/src/components/PageHeader/PageHeader.stories.js
In the source file, the stories are exported (from line 451 onwards) with the three "Simple page header" stories first, but in the storybook two of those appear half-way down the list and the third at the end. In the storybook, the stories are appearing in alphabetical order of their export names, NOT in the order they were exported. This is not done by a story sort function, and didn't happen until recently.

I think this is caused by Webpack. We are using Webpack 5.45.1. Or possibly it's a babel thing. Certainly, I've looked in the bundles that Webpack is building, and I can see that the exports have been sorted into alphabetical order there. So it's not storybook's fault: it really is preserving the order it gets the stories, but in the built storybooks that order is NOT the original export order from the source files.

**Comment by CTCTIPragg** [comment]
An interesting side effect that is most likely related to this issue, our org is using DocsPage and the story presented as the 'primary' ends up getting replaced with the alphabetic first story, which for ~50% of our components is not right. I hacked around this for now by providing a custom re-implementation of the docs page that explicitly sets which story should be the primary one.

**Comment by janivo** [comment]
I stumbled over the fact that stories that import any `.scss' files are not sorted properly, while files without style imports work fine. 

I can't make sense of this at the moment, but maybe this is helpful to someone.

**Comment by davoam** [comment]
> Also seeing this under the same circumstance - only in prod with webpack 5.
> Any ideas on how to go about it?
> 
> Sorry for tagging you, @shilman. If you have any pointers, I can investigate further and try to propose a workaround.
> 
> Btw, this issue should probably be labelled as `webpack5`.

We also have the same problem. It's only in `production`, we use `angular 12` and `webpack 5`

**Comment by IanVS** [comment]
I've encountered this as well, using the vite builder, in dev.  The vite builder uses `__namedExportsOrder`, perhaps that stopped working correctly?

I've tracked down the first broken version to `6.4.0-alpha.35`.

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.30 containing PR #16626 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by IanVS** [comment]
Confirmed that this indeed fixes the story sorting for the vite builder.  🎉  Thanks!

**Comment by shilman** [comment]
Thanks for checking @IanVS !! You rock!

**Comment by sQVe** [comment]
I'm sadly still seeing this issue on `@next` with `webpack@5`.

**Comment by shilman** [comment]
@sQVe Rats!! Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). 🙏

**Comment by sQVe** [comment]
@shilman The repo I'm seeing this on is `private` and I sadly don't have time to create a reproduction repo, sorry. I solved it by downgrading to `webpack@4`.

**Comment by FBNitro** [comment]
@shilman I just grabbed 6.4.0-rc3 and I have the same issue with ordering on webpack5.

start-storybook has everything in export order.
build-storybook has a different order.

**Comment by FBNitro** [comment]
@shilman a sample has been created: https://github.com/FBNitro/webpack5-ordering

If you clone that and `yarn start-storybook`, both stories appear in the same order.  if you `yarn build-storybook` and open the index you'll see one is in order and one is not.

I was able to isolate this to an issue of having a function in the story vs the same function being imported from another file.

Let me know if you need anything else.

**Comment by IanVS** [comment]
I double-checked, and both the dev and production builds using the vite builder are correctly sorted by export order.  So it seems like maybe this is specific to the webpack5 builder, rather than storybook core.

**Comment by FBNitro** [comment]
Curious if anyone has looked at this yet, I've done all the work to move to webpack 5, but I'm holding off until this is resolved.

**Comment by shilman** [comment]
@FBNitro I just took a look at your repro and see that it's not yet resolved in 6.4.x. i know what a solution would look like tho, which is to add a webpack loader that inserts `__namedExportOrder` on each story export. if anybody is interested in pairing on this, we could probably get something working in a couple hrs.

**Comment by ViniciusResende** [comment]
I'm experiencing the exact same issue.
I recently updated my `Storybook to 6.4.9` version, and my `Webpack to 5.65.0` version. In development mode, everything works just fine. But, unfortunately, when I built it using build-storybook, the order of the stories changed.

In the Development environment, they are rendered in export orders, nevertheless, when it  is built for Production, the alphabetical order is the one that prevails.

There is at least some kind of workaround other than alphabetically sort the stories that I want to appear first?

Since now I appreciate the collaboration.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.16 containing PR #17229 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by janivo** [comment]
Seems to do the trick, thanks! 👍🏼 
Even though there is a printout `__namedExportsOrder was not supported :( !`

**Comment by shilman** [comment]
Ah thanks @janivo -- will fix in the next alpha

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.17 containing PR #17240 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.13 containing PR #17240 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by etlovett** [comment]
I was still running into this issue in both Storybook v6.4.19 and v6.5.0-alpha.39. It turned out that something we were doing in our Storybook custom Webpack config was causing the fixes above not to work. Posting it here in case anyone else runs into this.

In our `main.js`, we use `webpackFinal` to change some of the Webpack settings for our Storybook build. In particular, we add a Webpack rule for `babel-loader` with our common Babel preset (e.g. so [Emotion](https://emotion.sh/) will work). In the config for this custom `babel-loader` rule, we were setting `modules: 'commonjs',`. Removing this line causes the stories to be sorted correctly. I'm assuming that this first custom run of Babel needs to specifically export ES modules so that the `babel-plugin-named-exports-order` Babel plugin in Storybook's Babel run will see the raw ES module `export`s rather than CommonJS code.

**Comment by tmeasday** [comment]
Can confirm the issue is still there in the repro, but also that it is caused (somehow) by the webpack/babel setup:

<img width="460" alt="image" src="https://user-images.githubusercontent.com/132554/158512861-6e43dc8a-4d15-424a-b4b6-b8a3fe45a9b0.png">

Notice the exports (`__webpack_require__.d`) are in alpha order, not the order they are exported from the original file.

Seems like this is an issue with the angular configuration @shilman.

**Comment by liverant** [comment]
With the new version:

```
 "@nrwl/storybook": "^13.10.0-beta.1",
    "@storybook/addon-docs": "^6.5.0-alpha.50",
    "@storybook/addon-essentials": "^6.5.0-alpha.50",
    "@storybook/addon-viewport": "^6.5.0-alpha.50",
    "@storybook/angular": "^6.5.0-alpha.50",
    "@storybook/builder-webpack5": "^6.5.0-alpha.50",
    "@storybook/manager-webpack5": "^6.5.0-alpha.50",
```

And the default config (`preview.js`):

```
export const parameters = {
  viewMode: 'docs',
  docs: {
    inlineStories: true,
    container: DocsContainer,
    page: DocsPage,
    source: {
      state: 'open',
    },
  },
  viewport: {
    viewports: INITIAL_VIEWPORTS,
  },
};
```

**Stories in prod build are still not in their imported order** 
("Playground" should be first, instead we get alphabetical order)
![image](https://user-images.githubusercontent.com/89337403/159890121-baf906de-0c21-4b6d-a4d2-83837f4c7746.png)

@shilman can you reopen?

**Comment by fabpico** [comment]
Since I've upgraded from an older version (using Webpack 4) to version `6.4.22` using (Webpack 5), I have this phenomena already on **dev mode**.
The stories all seem to be sorted alphabetically by default now. But the [Official docs](https://storybook.js.org/docs/react/writing-stories/naming-components-and-hierarchy#sorting-stories) says `By default, stories are sorted in the order in which they were imported.`, which is not the case anymore.

**Comment by shilman** [comment]
@fabpico do you have a custom babel config?

**Comment by wuifdesign** [comment]
I have the same problem, just after running `npx create-react-app my-app --template typescript` and `npx sb init --builder webpack5` in a new folder and than starting up storybook the order will be alphabetic for the predefined stories.

<img width="461" alt="Bildschirmfoto 2022-05-17 um 12 02 41" src="https://user-images.githubusercontent.com/5678318/168786206-694338a5-0e35-4ac1-a381-fd587d2bdfad.png">

**Comment by tmeasday** [comment]
@wuifdesign can you post your reproduction somewhere please?

**Comment by wuifdesign** [comment]
@tmeasday sure i can, but it is just running the two commands in a terminal somewhere.

```
npx create-react-app my-app --template typescript 
npx sb init --builder webpack5
```

Clean repo only run the two commands: https://github.com/wuifdesign/storybook-sorting-bug

running `npm run storybook` will show wrong order.

**Comment by riccardo-forina** [comment]
It's not a clean repo, but we have the same issue on https://github.com/redhat-developer/app-services-ui-components if it can help debugging

**Comment by shilman** [comment]
Thanks @tmeasday @wuifdesign . This looks like a bug with the CRA preset for typescript specifically. When I run a new project without TS enabled, sorting works. When I run it with TS enabled, it looks like it deletes Storybook's babel config somehow. I will follow up with @mrmckeb to see if we can get to the bottom of it. Thanks for your patience!

**Comment by shilman** [comment]
I'm closing this as fixed in 6.5. If you are still encountering this issue after upgrading:
- Please try removing custom babel configs if you have them for troubleshooting
- Please file a new issue [with a reproduction](https://storybook.js.org/docs/react/contribute/how-to-reproduce)

Many thanks for your patience on this! The JS ecosystem is the gift that keeps on giving!

**Comment by fabpico** [comment]
> I'm closing this as fixed in 6.5. If you are still encountering this issue after upgrading:
> 
> * Please try removing custom babel configs if you have them for troubleshooting
> * Please file a new issue [with a reproduction](https://storybook.js.org/docs/react/contribute/how-to-reproduce)
> 
> Many thanks for your patience on this! The JS ecosystem is the gift that keeps on giving!

Don't see any upvotes, did this solve the problem for someone?  
Upgrading with `npx sb upgrade` to `6.5.4` did not fix the order, even after removing `.storybook/.babelrc` (& restart of course).

@shilman 

"[with a reproduction](https://storybook.js.org/docs/react/contribute/how-to-reproduce)" crashes on my side

```
√ 🌈 Select the repro framework » react                                  
√ 📝 Select the repro base template » cra
√ Enter the output directory ... cra
🏃 Running cra into C:\Users\fbp\Desktop\Development\zz - expermients\storybook-stories-sort\cra

🏃 Starting for cra latest

🏗 Bootstrapping cra project (this might take a few minutes)
npm_config_user_agent=npm npx -p create-react-app@latest create-react-app cra && cd cra && echo "FAST_REFRESH=true" > .env && echo "SKIP_PREFLIGHT_CHECK=true" > .env
'npm_config_user_agent' is not recognized as an internal or external command,
operable program or batch file.
An error occurred while executing: `npm_config_user_agent=npm npx -p create-react-app@latest create-react-app cra && cd cra && echo "FAST_REFRESH=true" > .env && echo "SKIP_PREFLIGHT_CHECK=true" > .env`
🚨 Bootstrapping cra failed
🚨 Failed to create repro
Error: Error: command exited with code: 1:
    at repro (C:\Users\fbp\AppData\Local\npm-cache\_npx\eebb2d3a7d26a7f1\node_modules\@storybook\cli\dist\cjs\repro.js:172:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

```

Installing a fresh storybook with `npx storybook init` also crashes.

```
info @storybook/react v6.5.4
info 
√ Port 6006 is not available. Would you like to run Storybook on port 6007 instead? ... yes
info => Loading presets
WARN   Failed to load preset: "C:\\Users\\fbp\\Desktop\\Development\\zz - expermients\\storybook-stories-sort-init\\node_modules\\@storybook\\manager-webpack4\\dist\\cjs\\presets\\manager-preset.js"
ERR! Error: Cannot find module 'react/package.json'
ERR! Require stack:
ERR! - C:\Users\fbp\Desktop\Development\zz - expermients\storybook-stories-sort-init\node_modules\@storybook\ui\noop.js
ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
```

Reopen?

**Comment by tmeasday** [comment]
@fabpico I can confirm that the posted reproduction was indeed fixed by 6.5. If you have a reproduction that fails in 6.5 we can re-open and take a look at it.

**Comment by fabpico** [comment]
@tmeasday You should be able to (at least I can) reproduce it on this [fresh storybook installation](https://github.com/fabpico/storybook-sorting-issue) (v6.5.5) since [repro creation is not working](https://github.com/storybookjs/storybook/issues/18318).

The screenshots prove that the rendered stories are still sorted alphabetically, insted of sorted by how they were defined in order.

<img width="217" alt="result" src="https://user-images.githubusercontent.com/4472725/170224135-6491947f-46e5-4632-84dc-494fd93f5a02.PNG">

<img width="429" alt="code" src="https://user-images.githubusercontent.com/4472725/170224150-16c9b957-feee-440a-8137-5761432c841a.PNG">

Node is v16.15.0 if this info helps.

**Comment by tmeasday** [comment]
Thanks @fabpico. This seems like a new issue with CRA and recent versions of either SB or the CRA preset. Opening a new issue here: https://github.com/storybookjs/storybook/issues/18322

**Comment by elenagarrone** [comment]
@tmeasday and @shilman I'm still seeing the issues using Angular 12 and Webpack 5:

```
    "@storybook/addon-a11y": "^6.5.7",
    "@storybook/addon-essentials": "^6.5.7",
    "@storybook/addons": "^6.5.7",
    "@storybook/angular": "^6.5.7",
    "@storybook/builder-webpack5": "^6.5.7",
    "@storybook/manager-webpack5": "^6.5.7",
    "@storybook/theming": "^6.5.7",
```

![Screenshot 2022-06-06 at 14 04 43](https://user-images.githubusercontent.com/8397116/172166408-abc1ac0b-8477-4cd8-a265-856421344877.png)

while it should be:
```
Buttons
  Primary dark
  Primary light
  Secondary dark
  Secondary light
  Icon only
  Icon with text
```

This is the code I'm running: https://github.com/elenagarrone/canopy/tree/fep-434-angular-upgrade

**Comment by elenagarrone** [comment]
@tmeasday and @shilman could you please reopen?

**Comment by shilman** [comment]
@elenagarrone  can you please open an angular-specific issue to track this? I believe it's fixed for the other frameworks already

**Comment by elenagarrone** [comment]
> @elenagarrone can you please open an angular-specific issue to track this? I believe it's fixed for the other frameworks already

Will do thank you!

**Comment by dkilgore-eightfold** [comment]
Repros again using webpack 5.76.0

**Comment by tmeasday** [comment]
@dkilgore-eightfold can you open a new issue with a reproduction please?
