### ISSUE TITLE
Storybook cannot handle data from extended components (Angular)

### ISSUE THREAD

**Issue by AleSergio** [storybookjs/storybook#15977]
**Describe the bug**
When we are using storybook in angular and we have a component, that extends another component with data. Data  is undefined even though we have assigned it in our stories component.

**To Reproduce**
Check the repository for more information:
https://github.com/AleSergio/storybookExtend

**System**
Error that I am having after running storybook:
![image](https://user-images.githubusercontent.com/46831993/131998735-9883d78e-8c69-41e9-a0f4-b23b54d91f87.png)

**Comment by saggypatel** [comment]
Looks like following is related.

https://github.com/storybookjs/storybook/issues/15935

**Comment by GupCa** [comment]
Having the same issue during the update of the storybook from 6.1 to 6.2-6.3 on the angular project.
Storybook assigns such properties (from extended class) only in ngAfterViewInit hook, which is too late.

**Comment by Marklb** [comment]
I think this was fixed in PR #15586. So, `v6.4.0-alpha.23` should have the fix.

I cloned the repo then upgraded to the most recent alpha and the error was gone.

**Comment by RaySheikh** [comment]
Issue still exists for [#15935](https://github.com/storybookjs/storybook/issues/15935) when extending an angular. tried `v6.4.0-alpha.34`

**Comment by GupCa** [comment]
I have tried` v6.4.0-alpha.34`, still exists. Can provide more information, whatever is needed.

**Comment by Marklb** [comment]
@RaySheikh #15935 does not look related to this issue. I added comment for how to fix it in that issue.

**Comment by Marklb** [comment]
@GupCa I cloned https://github.com/AleSergio/storybookExtend, then ran `npm i`, then started it with `npm run storybook` to see that I got the same error.

To fix it, I went into the `package.json` and updated the following.
```
"@compodoc/compodoc": "^1.1.14",
"@storybook/addon-actions": "^6.4.0-alpha.34",
"@storybook/addon-essentials": "^6.4.0-alpha.34",
"@storybook/addon-links": "^6.4.0-alpha.34",
"@storybook/angular": "^6.4.0-alpha.34",
```
Then I ran `npm i`, then started it with `npm run storybook` again and the inputs from the extended component were set without any errors.

**Comment by AleSergio** [comment]
> @GupCa I cloned https://github.com/AleSergio/storybookExtend, then ran `npm i`, then started it with `npm run storybook` to see that I got the same error.
> 
> To fix it, I went into the `package.json` and updated the following.
> 
> ```
> "@compodoc/compodoc": "^1.1.14",
> "@storybook/addon-actions": "^6.4.0-alpha.34",
> "@storybook/addon-essentials": "^6.4.0-alpha.34",
> "@storybook/addon-links": "^6.4.0-alpha.34",
> "@storybook/angular": "^6.4.0-alpha.34",
> ```
> 
> Then I ran `npm i`, then started it with `npm run storybook` again and the inputs from the extended component were set without any errors.

Thank you updating to 6.4.0-alpha.34 solved the problem! Inputs from extended components are being displayed now.
