### ISSUE TITLE
Core: Must run `--no-manager-cache` when switching to `storyStoreV7`

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#16647]
Repro: 
- [ ] fresh CRA app with `npx sb@next init`
- [ ] add `features: { storyStoreV7: true }` to `main.js`
- [ ] run storybook

If you don't run `--no-manager-cache`, the manager will hang without warning

**Comment by tmeasday** [comment]
Is this just an instance of a generic problem of not busting the cache when you change `features`?

**Comment by shilman** [comment]
Yes I think so @tmeasday

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.32 containing PR #16653 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by joshwooding** [comment]
I'm still experiencing this issue with the repo on `6.4.0-rc.1`. I'm surprised there's not check against features here: https://github.com/storybookjs/storybook/blob/next/lib/manager-webpack4/src/utils/prebuilt-manager.ts#L37

**Comment by tmeasday** [comment]
@joshwooding the features are part of the manager webpack config so should get caught up in that check.

**Comment by tmeasday** [comment]
Ok I took a closer look. It seems like a change to features will affect whether it uses the cached version of the manager build, but not the initial prebuilt manager.

**Comment by ghengeveld** [comment]
I don't recall having even considered `features` when we implemented the prebuilt manager. Did we even have feature flags back then?

**Comment by tmeasday** [comment]
@ghengeveld that was the point of the PR above (that you reviewed btw 😆 ). It works for general manager caching. 

My question is what is different about the prebuilt cache key?

**Comment by tmeasday** [comment]
> @joshwooding the features are part of the manager webpack config so should get caught up in that check.

Oh, so I see now these lines: https://github.com/storybooks/storybook/blob/b7a97e2e40345b4a72e99c8bb941696583bc5f91/lib/manager-webpack4/src/utils/prebuilt-manager.ts#L37-L41

Are a completely different check to this one: https://github.com/storybooks/storybook/blob/8dec826e3a4cfb91e51ddee002d324df77b4126d/lib/manager-webpack4/src/utils/manager-cache.ts#L26-L27

@ghengeveld is it not possible to use the same cache key for the prebuilt manager check? I guess I can just add a check on `features` in there for now.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-rc.2 containing PR #16684 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.
