### ISSUE TITLE
header links navigates to unknown page

### ISSUE THREAD

**Issue by sag1v** [storybookjs/storybook#16918]
After migrating from storybook v5 to v6 i have noticed a strange behavior regarding auto generated header links. After a quick search i found out why it is happening (but not sure how it worked until now with previous version).

Given [this check](https://github.com/storybookjs/storybook/blob/537abe1b0bf80152d8f766e875f73650db744b8f/addons/links/src/preview.ts#L56) in `addons-links` and the fact that all header anchors are actually an SVG elements, this check always evaluates to `true` (SVG element != HTML Element).

Because we `return` we are not triggering the `preventDefault` method of the event hence the link navigates to a different page (a none existing page).   

Here is a screenshot of the gist of it

![image](https://user-images.githubusercontent.com/9153149/144817971-446c80c4-7d83-4169-acb1-a09c05392339.png)

**To Reproduce**
I just created a fresh repo with `npx sb@next repro` and this bug shows up, i didn't change anything.

**System**
Environment Info:

  System:
    OS: macOS 11.6
  Binaries:
    Node: 12.16.3 - ~/.nvm/versions/node/v12.16.3/bin/node
    Yarn: 1.22.5 - ~/.y/bin/yarn
    npm: 6.14.4 - ~/.nvm/versions/node/v12.16.3/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 85.0.2
    Safari: 15.0

**Comment by cgreene-st** [comment]
I'm also seeing this in the latest version 6.4.0. Thanks for flagging the bug 👍 

You can also see it live here by clicking the headings in the docs page - https://storybookjs.netlify.app/official-storybook/?path=/story/addons-docs-markdown-docs--page

**Comment by sag1v** [comment]
I'm not sure whats the correct fix for this (should we test against SVG elements as well?) nor what could be a valid workaround until this is fixed.

Maybe @shilman can advise?

**Comment by sag1v** [comment]
Hi @shilman Do you know if this is being worked on

**Comment by shilman** [comment]
Not yet. Please feel free to take a crack at it if it's blocking you!

**Comment by sag1v** [comment]
Sure i can try. Let's discuss our options here first?
A quick fix would be to add a check for a `SVGElement` as well:

```js
if (!(target instanceof HTMLElement || target instanceof SVGElement )) {
  return;
}
```

But i'm not sure if it will impact other cases.

WDYT?

**Comment by sag1v** [comment]
@shilman Apparently my suggested fix isn't enough (or not relevant). I think that for some reason the event for the anchor element itself isn't triggered correctly. Any idea or direction?

I think this is a crucial bug for a document tool, we can't share direct links.
I may have a workaround in "user-land" but its hackie as hell and only covers DOCS pages.

Basically my workaround is to hook on EVERY click on document and check if `a` is part of the event's path, if it does then check if it has an `href` with a hash, then just prevent default and update the location.hash.

As i said, hackie but works (almost)


here is an example for reference

```js
document.addEventListener('click',e => {
    const eventPath = e.path || e.composedPath() || [];
    const linkElement = eventPath.find(tag => tag.localName === 'a');
    if (linkElement) {
      const href = linkElement.getAttribute('href');
      if (href.includes('#')) {
        e.preventDefault();
        e.stopPropagation();
        console.log(href);
        if (window.parent) {
          // in case we are inside an iframe, we need to update the global url (otherwise we can't share links)
          window.parent.location.hash = href;
        }
        // even if we are inside an iframe we must set the "local" location so we can trigger a scroll
        window.location.hash = href;
      }
    }
  },
  true
);
```

**Comment by sag1v** [comment]
OK I think i found the issue and a way to fix it. I'm not sure how good is this fix though.

It turns out that in [mdx.tsx](https://github.com/storybookjs/storybook/blob/next/addons/docs/src/blocks/mdx.tsx#L53) we call `addons.getChannel` with only the hash value instead of appending it to the entire `location.search` string.

Because we are passing `options.plain: true` (somewhere, not sure exactly where) then we just call react-router's `navigate` with the hash. see [router.tsx](https://github.com/storybookjs/storybook/blob/next/lib/router/src/router.tsx#L65).

My suggested solution is to bring back `generateHrefWithHash` (who got deleted a year ago) with some modifications:

```
function generateHrefWithHash(hash: string): string {
  const location = window.parent ? window.parent.location : window.location;
  const href = `${location.search}${hash}`;
  return href;
}

function navigate(url: string) {
  const urlWithHash = generateHrefWithHash(url);
  addons.getChannel().emit(NAVIGATE_URL, urlWithHash);
}
```

I'm not sure this is the best solution or naming but anyway it seems to work fine.

@shilman @ndelangen WDYT?

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.9 containing PR #17134 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by StanislavPonomarenko** [comment]
I've updated to prerelease.
I use tsx component for navigation via mdx file

`<NavBanner
  title="Colors"
  desc="Primary, Secondary and Support colors"
  links={[
    { path: '#identity-colors', text: 'Identity Colors' },
    { path: '#colors', text: 'Colors' },
  ]}
></NavBanner>`

and in the same file I've used anchor link `<a href="#identity-colors">Test</a>`

In result links in component do not work but test anchor link works. https://www.screencast.com/t/JStshkoy

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.10 containing PR #17134 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by StanislavPonomarenko** [comment]
Thank you for your comment but issue is still there after update to 6.4.10
here is a short video file https://www.screencast.com/t/PFo1KJ44covD

so anchor links in mdx file works, but if I use custom component with such links in mdx file those links won't work.
If you need some info from my side I would give it to you.

**Comment by shilman** [comment]
@StanislavPonomarenko we don't support links from custom components. please open a separate issue.
