### ISSUE TITLE
Certain globs not finding stories

### ISSUE THREAD

**Issue by matt-tingen** [storybookjs/storybook#16924]
**Describe the bug**
While updating from 6.3.6 to 6.4.4, we found that certain globs provided to `stories` no longer work. Specifically, we use globs like to following based on whether we want all stories from our monorepo or only those from a single packages:
- `../../../packages/*/{src,stories}/**/*.stories.{js,jsx,ts,tsx}`
- `../../../packages/foo-bar/{src,stories}/**/*.stories.{js,jsx,ts,tsx}`

(we resolve these to be absolute, but it doesn't seem to matter in the repro repo)

After updating, the former (with `*`) works as expected, but the more specific (with `foo-bar`) fails to find any stories despite there being some.

**To Reproduce**
https://github.com/matt-tingen/storybook-glob-repro

**System**
```
Environment Info:

  System:
    OS: macOS 11.6.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Binaries:
    Node: 14.17.3 - ~/.nodenv/versions/14.17.3/bin/node
    Yarn: 3.1.1 - ~/.nodenv/versions/14.17.3/bin/yarn
    npm: 6.14.13 - ~/.nodenv/versions/14.17.3/bin/npm
  Browsers:
    Chrome: 96.0.4664.55
    Firefox: 94.0.2
    Safari: 15.0
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.1 => 6.5.0-alpha.1 
    @storybook/addon-docs: ^6.5.0-alpha.1 => 6.5.0-alpha.1 
    @storybook/addon-essentials: ^6.5.0-alpha.1 => 6.5.0-alpha.1 
    @storybook/addon-links: ^6.5.0-alpha.1 => 6.5.0-alpha.1 
    @storybook/react: ^6.5.0-alpha.1 => 6.5.0-alpha.1 
```

**Additional context**
We don't use this glob, but while debugging, I found that `../../../packages/foo-bar/src/**/*.stories.{js,jsx,ts,tsx}` also works so it seems like it's the combination of `foo-bar` and `{src,stories}` that fails.

**Comment by RobHannay** [comment]
We've had a similar problem.

We used to use (<= `6.3`) this

```js
  stories: ["../@(src|docs)/**/*.stories.@(tsx|mdx)"],
```

but now, on `6.4.9`, it fails to find any matching stories. 

We get the following message in the sidebar.

> Oh no! Your Storybook is empty. Possible reasons why:
> 
>  -   The glob specified in main.js isn't correct.
>  -   No stories are defined in your story files.

The `@(src,docs)` path segment appears to be the problem because all of the following work and find some stories:

`../**/*.stories.@(tsx|mdx)`
`../src/*.stories.@(tsx|mdx)`
`../docs/*.stories.@(tsx|mdx)`


There are zero build warnings logged. The only error in the console is specifically the one saying that is can't find the matching story, either `"*"` if there has yet to be one set in a query param, or name of the story if navigating directly to one. 

For example:
![image](https://user-images.githubusercontent.com/609062/145844886-53d8facb-3ba7-4da8-923d-59a8ff08f03b.png)

Thanks for all the stuff you do

**Comment by cgatian** [comment]
This is a problem

**Comment by tmeasday** [comment]
Apologies about the delay, here is the fix: https://github.com/storybookjs/storybook/pull/17252

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.19 containing PR #17252 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Yo-ho-ho!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.14 containing PR #17252 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by andrewplummer** [comment]
Hello, thanks for the fix. However I'm still seeing issues with this:

```
  stories: [
    '../src/**/*stor(y|ies).@(js|jsx|mdx)',
    '../src/**/*page.@(js|jsx|mdx)',
  ],
```

with file structure:

```
src/intro.page.mdx
src/concepts.story.mdx
```

`concepts.story.mdx` is loading however `intro.page.mdx` is not. I am expecting the above globs to match all of:

```
src/page.mdx
src/intro.page.mdx
src/story.mdx
src/stories.mdx
src/intro.story.mdx
src/intro.stories.mdx
src/component/story.mdx
src/component/page.mdx
src/component/intro.story.mdx
src/component/intro.page.mdx
```

Am I missing something?

**Comment by tmeasday** [comment]
@andrewplummer hmm, no obvious reason why one would work but not the other. Can you create a reproduction?

**Comment by andrewplummer** [comment]
Sure, I added one here: https://github.com/andrewplummer/storybook-test

```
module.exports = {
  stories: [
    '**.*',
    '**.*.mdx',
    '**.*stor(y|ies).mdx',
    '**.*stor(y|ies).mdx',
    '../src/**/*stor(y|ies).@(js|mdx)',
    '../src/**/*.stories.@(js|mdx)',
    '../src/**/*.page.@(js|mdx)',
    '../**/*stor(y|ies).@(js|mdx)',
    '../**/*.stories.@(js|mdx)',
    '../**/*.page.@(js|mdx)',
  ],
  addons: ['@storybook/addon-links', '@storybook/addon-essentials'],
  framework: '@storybook/react',
};
```

I would expect any one of these globs to match yet none of them do.

**Comment by tmeasday** [comment]
Hey @andrewplummer I can see two things wrong here.

1. You need to use `<Meta/>` in your MDX files, even if they have no stories.
2. Also, they need to be called `.stories.mdx` (unless you mess with Webpack). This is likely the issue. See: https://storybook.js.org/docs/react/api/mdx#mdx-file-names

**Comment by andrewplummer** [comment]
I see the problem now. However it's all quite confusing isn't it?

I'm not sure I understand the point of globs named `stories` if it's only going to find files actually called `*.stories.mdx`.  I would expect anything I explicitly mark as being a story to load. Then of course it woudn't know the page title as `Meta` wasn't there so an error could be thrown, that would have made it quite obvious.

As it is you would have to have read the entire docs (down to the bottom paragraph) to know what's going on.

**Comment by tmeasday** [comment]
Yeah, we need to process the MDX file in a special way which requires Webpack to know about the location of all "mdx story" files. I agree it's an annoying and arbitrary restriction and we'll probably try to get rid of it in the future.

**Comment by andrewplummer** [comment]
I mean... fair enough if it's a hard restriction then I get it but what is the point then of having globs? Aren't the globs what is pointing at the mdx story files? I feel like I'm missing something.

**Comment by tmeasday** [comment]
I guess it is a technical limitation @andrewplummer, rather than a product decision. A couple of things that might help:

1. You can use arbitrary globs for story files, the restriction only applies for MDX files.
2. You can use glob patterns for the directory path etc, it is really just a restriction on the file extension of the MDX file.
3. It **is** possible to override the webpack config to pick up other `.mdx` file extensions as MDX story files (as opposed to other MDX files you may be using in your project). This is a bit complicated, and I think in general users have decided it is not worth it.

Technically we could probably automatically do 3, based on detecting that you've used a non-standard mdx-matching glob for your `stories` field, but that'd be very complex and I suspect error prone, and honestly I'm not sure it is worth it. 

What is probably a good idea is that we could log an error or a warning if you write a `stories` glob that matches `mdx` files without the `.stories.mdx` extension.

**Comment by andrewplummer** [comment]
Ah I see so basically the globs work with mdx files but with some restrictions.
I really feel that all of that (except #3) needs to be in the docs.

**Comment by tmeasday** [comment]
Always open for documentation improvement PRs!

**Comment by clintandrewhall** [comment]
I spent a day digging into code before I was able to find this issue.  😭
