### ISSUE TITLE
Module not found: Error: You attempted to import /node_modules/react-refresh/runtime.js which falls outside of the project src/ directory

### ISSUE THREAD

**Issue by crodriguez-plitzi** [storybookjs/storybook#17049]
**Describe the bug**
related to the new RCA 5 using @storybook/react: 6.4.9 im getting this problem https://github.com/facebook/create-react-app/issues/11810 is there a way to solve it ? if i remove this dependency works good

**To Reproduce**
create a new RCA 5 project, and add storybook and start RCA (yarn start)

 "@storybook/addon-actions": "^6.4.9",
    "@storybook/addon-essentials": "^6.4.9",
    "@storybook/addon-links": "^6.4.9",
    "@storybook/node-logger": "^6.4.9",
    "@storybook/preset-create-react-app": "^4.0.0",
    "@storybook/react": "^6.4.9",

**System**
Please paste the results of `npx sb@next info` here.

**Additional context**

**Comment by cristiadu** [comment]
Had the same issue with the alpha version  (`6.5.0-alpha.4`) that supports Webpack 5. Not sure if the problem is some sort of conflict with the latest `react-scripts` version.

**Comment by crodriguez-plitzi** [comment]
i tried with latest alpha and still same

**Comment by dbollinger** [comment]
Looks like this might be related to this issue: https://github.com/storybookjs/presets/issues/217

**Comment by crodriguez-plitzi** [comment]
@dbollinger its a bit different, in this case is saying that the dependency must be inside /src folder

Module not found: Error: You attempted to import /home/carlos/htdocs/plitzi-sdk/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
 @ ./src/services/store/reducers/sharedStore/index.js 4:0-86 11:9-26 16:9-31
 @ ./src/services/store/reducers/index.js 13:0-47 65:21-39
 @ ./src/services/store/index.js 8:0-34 38:28-36
 @ ./src/index.js 13:0-40 22:9-17

**Comment by cristiadu** [comment]
> @dbollinger its a bit different, in this case is saying that the dependency must be inside /src folder
> 
> Module not found: Error: You attempted to import .../node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported. You can either move it inside src/, or add a symlink to it from project's node_modules/. @ ./src/services/store/reducers/sharedStore/index.js 4:0-86 11:9-26 16:9-31 @ ./src/services/store/reducers/index.js 13:0-47 65:21-39 @ ./src/services/store/index.js 8:0-34 38:28-36 @ ./src/index.js 13:0-40 22:9-17
> 
> and webpack dev server complains with all files

Same problem, different outcomes. The fact that `react-refresh` is not identified as a module is creating the "src directory" problem. If it was a module we could import from node_modules with no issues.

**Comment by crodriguez-plitzi** [comment]
alright, that makes sense, the thing is who will fix it

**Comment by phnessu4** [comment]
The storybook/react need to update the dependencies version. I just check the 6.5.0-alpha.1 to 6.5.0-alpha.4, the config not update. 

[react-scripts@5.0.0](https://github.com/facebook/create-react-app/blob/main/packages/react-scripts/package.json#L65):
    "@pmmmwh/react-refresh-webpack-plugin" "^0.5.3"
    react-refresh "^0.11.0"

[storybook/react@6.4.9](https://github.com/storybookjs/storybook/blob/next/app/react/package.json#L70):
    "@pmmmwh/react-refresh-webpack-plugin": ^0.5.1
    react-refresh: ^0.10.0

Here is the [pull request](https://github.com/storybookjs/storybook/pull/17056) 

If you can't wait for the next version, you can do the hard code on node_modules.

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.5 containing PR #17056 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by robcaldecott** [comment]
I'm still seeing this issue with a large project using Storybook `6.5.0-alpha.6` and `react-scripts 5`. Removing `node_modules` has no effect.

```
ERROR in ./src/App/App.js 1:40-130
Module not found: Error: You attempted to import /Users/caldecor/Projects/digital-workshop/node_modules/react-refresh/runtime.js which falls outside of the project src/ directory. Relative imports outside of src/ are not supported.
You can either move it inside src/, or add a symlink to it from project's node_modules/.
 @ ./src/index.js 12:0-32 112:41-44
```

`npm ls react-refresh` shows this:

```
servicehub-workshop@1.0.0
├─┬ UNMET PEER DEPENDENCY @storybook/react@6.5.0-alpha.6
│ └── react-refresh@0.11.0 
└─┬ react-scripts@5.0.0
  └── react-refresh@0.11.0 

npm ERR! peer dep missing: @storybook/react@>=5.2, required by @storybook/preset-create-react-app@4.0.0
npm ERR! peer dep missing: @storybook/react@>= 3.2.16, required by storybook-addon-intl@2.4.1
```

```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.0 - ~/.nvm/versions/node/v14.17.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v14.17.0/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0
    Safari: 14.1.2
  npmPackages:
    @storybook/addon-a11y: ^6.5.0-alpha.6 => 6.5.0-alpha.6 
    @storybook/addon-essentials: ^6.5.0-alpha.6 => 6.5.0-alpha.6 
    @storybook/builder-webpack5: ^6.5.0-alpha.6 => 6.5.0-alpha.6 
    @storybook/manager-webpack5: ^6.5.0-alpha.6 => 6.5.0-alpha.6 
    @storybook/preset-create-react-app: ^4.0.0 => 4.0.0 
    @storybook/react: ^6.5.0-alpha.6 => 6.5.0-alpha.6
```

Storybook itself is working fine but I cannot start my app using `react-scripts start`.

I will roll back to `react-scripts 4` and try to put together a reproducible demo.

**Comment by robcaldecott** [comment]
OK, I can reproduce this now simply by moving all `devDependencies` into `dependencies`. So I guess `npm` is confused or the `node_modules` tree is somehow borked. Either way this is likely to catch people out as a lot of projects using `react-scripts` will not be splitting deps/devDeps.

Here's an example repo:

https://github.com/robcaldecott/storybook-react-scripts-webpack5

Clone it, `npm install` and run `npm start`. On my system I get the error.

**Comment by robcaldecott** [comment]
After much more trial and error I can only get this to work if `react-scripts` and `webpack` are in the `dependencies` list and all the Storybook packages are in `devDependencies` (and after moving things around you have to remove the lock file and `node_modules` before reinstalling.)

So it's a bit messy.

https://github.com/robcaldecott/storybook-react-scripts-webpack5/blob/fix/package.json

I'm using node 14 and npm 6.14.15. It would be interesting to see if later versions of `npm` suffer from this issue.

**Comment by phnessu4** [comment]
There's a way help you  find the conflict versions.
1. Remove  react-scripts , @storybook/react and some other error packages. 
2. Install the react-scripts, commit your package-lock.json or yarn.lock with git
3. Install the conflict packages, like @storybook/react or some others, check out the change different with react-scripts
4. solve the conflict

Most of the npm upgrade hell is packages conflict. Hope this can help you. @robcaldecott

**Comment by nelsieborja** [comment]
Recently ran into this issue and was able to fix by following [this migration guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#cra5-upgrade).

**Comment by nephydecode** [comment]
Was able to find a workaround for conflict versions for the time being

1. Ran `npm ls react-refresh` and it shows a different of `react-refresh` package versions
```
├─┬ @storybook/preset-create-react-app@4.1.2
│ └─┬ @pmmmwh/react-refresh-webpack-plugin@0.5.7
│   └── react-refresh@0.14.0
├─┬ @storybook/react@6.5.7
│ └── react-refresh@0.11.0
└─┬ react-scripts@5.0.1
```

2. Ran `npm dedupe` to de-duplicate multiple versions

3. Ran `npm ls react-refresh` to check existing versions for `react-refresh`
```
├─┬ @storybook/preset-create-react-app@4.1.2
│ └─┬ @pmmmwh/react-refresh-webpack-plugin@0.5.7
│   └── react-refresh@0.11.0 deduped
├─┬ @storybook/react@6.5.7
│ └── react-refresh@0.11.0
└─┬ react-scripts@5.0.1
  └── react-refresh@0.11.0 deduped
```

4. `npm start` compiles & runs successfully

**Comment by ilanah** [comment]
had to also do 

cd node_modules/react-scripts

npm dedupe
