### ISSUE TITLE
args values not present in url are casted to !undefined for controls of type select and radio

### ISSUE THREAD

**Issue by pixtron** [storybookjs/storybook#17063]
**Describe the bug**
If the url contains at least one arg, all arguments for controls of type `select` or `radio` that have no arg present in the url are casted to undefined.

**To Reproduce**
1.) Checkout the [repro](https://github.com/pixtron/storybook-urlargs-repro):
2.) `yarn storybook`
3.) Open the story: http://localhost:6006/?path=/story/test-args--bob
4.) Change value for `foo` from `bar` to `baz` as expected URL changes to: http://localhost:6006/?path=/story/test-args--bob&args=foo:baz
5.) Copy URL and open in another browser or refresh the tab
6.) URL changes to http://localhost:6006/?path=/story/test-args--bob&args=first:!undefined;last:!undefined;foo:baz
7.) No args for `first` and `last` are passed to the story. Default args should be passed.

**System**
```
Environment Info:

  System:
    OS: macOS 11.4
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.0/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Firefox: 95.0
    Safari: 14.1.1
  npmPackages:
    @storybook/addon-actions: ^6.5.0-alpha.4 => 6.5.0-alpha.4
    @storybook/addon-essentials: ^6.5.0-alpha.4 => 6.5.0-alpha.4
    @storybook/addon-links: ^6.5.0-alpha.4 => 6.5.0-alpha.4
    @storybook/html: ^6.5.0-alpha.4 => 6.5.0-alpha.4
```

**Comment by sysofwan** [comment]
This is also happening on page reflow (after resizing to bigger/smaller window), and when opening a story iframe for me.

**Comment by bravewick** [comment]
This is also happening on version 6.4.19 but not on version 6.3.12

**Comment by philipbushnell-valtech** [comment]
We had to downgrade to `6.3.13` (and had to remember to [put our public folder back on the package json script](https://storybook.js.org/docs/6.3/react/configure/images-and-assets)).

For us it was happening for "picker" types (e.g. radio and dropdown) when we were using string literals in TypeScript. If we defined the argType explicitly (i.e. as `radio`) but omitted the `options` property, obviously our control stopped working but the issue also didn't occur.

**Comment by WillGeller** [comment]
This is also happening to me on storybook `6.4` when using `inline-radio` argTypes.

**Comment by paulwoodland** [comment]
Also having big problems with this - the same as other people are reporting, when using dropdowns in a story, all args are going to !undefined in the URL on refresh (including when resizing the window down small enough)

**Comment by WillGeller** [comment]
@shilman @ndelangen Any update from core maintainers on whether this bug is deemed a priority or not? Is it slated to be fixed in an update? Looking at downgrading to older version of Storybook here as this is very confusing bug that is causing issues for my team when reviewing our component library. Anybody on the thread have any workarounds?

**Comment by paulwoodland** [comment]
We are in the same position, we may have to go back to a previous version as this bug is making Storybook almost unusable for development - every time you change a file that causes a reload, it looses all the select args and you have to manually edit the URL to remove the args= querystring. We can't find any workarounds other than doing that manually every time it reloads.

**Comment by WillGeller** [comment]
Yep downgrading to 6.3 is likely my next step, and commenting out the
interactive testing features I have been trying out.

I'm guessing this bug thread is being drowned in the hundreds of other open
issues on the Storybook repo.

**Comment by evont** [comment]
Still happen in the lastest release 6.5.0-alpha.63...

**Comment by peteragarclover** [comment]
We're already on `6.3.12` and getting this issue. Everything was working fine, and then at some point this bug appeared, and I don't think we had upgraded Storybook. Could it be a shared downstream dependency that we upgraded coincidentally?

This is preventing people from reloading storybook pages or sharing urls. All args are marked as `undefined` in the URL so as soon as you load any story from it's URL, if the component has any required props, we just get the error screen saying "Cannot read properties of undefined"

**Comment by evont** [comment]
I fixed it in my project by copying the `@storybook/store` in the folder root, then I alter some code in `validateOptions` in  **@storybook/store/dist/esm/args.js** 

```javascript
if (args[key] === undefined || options.includes(args[key]) || isValidArray) {
      if (key in args) acc[key] = args[key];  // origin code:  acc[key] = args[key]; 
      return acc;
}
```

I am using **pnpm** to manage my project, so I add `pnpm.overrides` to override storybook's `@storybook/store`, alternative solution is using **patch-package** in **yarn** or **npm**

```json
"pnpm": {
    "overrides": {
      "@storybook/store": "link:store"
    }
  }
```

**Comment by paulwoodland** [comment]
Thank you @evont for looking into it! I've tried applying your fix using patch/patch-commit in Yarn, and so far I haven't seen the bug happen (whereas it did happen all the time), so fingers crossed it's sorted it, but I'll keep an eye on it. Hopefully your fix #17973 gets included in the main Storybook release for everyone soon!

**Comment by hieucd04** [comment]
This is also happening to me on storybook `6.4`. Downgrade to `6.3.13` fixed it for me.

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-beta.6 containing PR #18135 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by sysofwan** [comment]
Thanks @shilman! Is this going to be ported to v6.4.x?

**Comment by CWSites** [comment]
It would be nice if there was a port to `6.4.x` as I'm unable to upgrade to `6.5` and this issue is still occurring on `6.4.13`

**Comment by jbenjoy2** [comment]
still happening in 6.4.22. Any advice on how to fix this without upgrading to 6.5?

**Comment by ndelangen** [comment]
@jbenjoy2 no that won't happen; you'll need to upgrade to get the fix.
