### ISSUE TITLE
Interactions-addon relies on polyfilled `global` (via jest-mock)

### ISSUE THREAD

**Issue by wayne-o** [storybookjs/storybook#17516]
**Describe the bug**

createed a vite / react app - added storybook:

```
npx sb@next init --builder storybook-builder-vite
```

Got an error saying I needed to add:

```
yarn add -D @mdx-js/preact
```

Finally ran:

```yarn storybook```

Got:

```
{
   "message":"Uncaught SyntaxError: The requested module '/node_modules/@storybook/addon-interactions/node_modules/jest-mock/build/index.js?v=bd021136' does not provide an export named 'fn'",
   "source":"http://localhost:6006/node_modules/@storybook/addon-interactions/dist/esm/preset/argsEnhancers.js",
   "line":28,
   "column":10,
   "error":{
      "message":"The requested module '/node_modules/@storybook/addon-interactions/node_modules/jest-mock/build/index.js?v=bd021136' does not provide an export named 'fn'",
      "name":"SyntaxError",
      "stack":"SyntaxError: The requested module '/node_modules/@storybook/addon-interactions/node_modules/jest-mock/build/index.js?v=bd021136' does not provide an export named 'fn'"
   },
   "origin":"preview"
}
```

**Comment by IanVS** [comment]
Hi, we have a report of this in the storybook-builder as well (https://github.com/eirslett/storybook-builder-vite/issues/242), although I think in the end, this is a problem either with jest, or with the way that addon-interactions is using jest-mock.

When I've needed to use jest-mock in my own project (which does not use addon-interactions), I can make it work by using:

```
import { ModuleMocker } from 'jest-mock';
const jest = new ModuleMocker(window);
```

I think the issue is that the addon-interactions imports `fn` directly from jest-mock: https://github.com/storybookjs/storybook/blob/f979a5cff227cd0e7fff495f23a198adb7eb656e/addons/interactions/src/preset/argsEnhancers.ts#L5

Which breaks in non-node or at least non-node-pollyfilled environments, because it uses `global` instead of `window`: https://github.com/facebook/jest/blob/465518a2fa17ce45f7e3280dd0f54351273432c4/packages/jest-mock/src/index.ts#L1200-L1202

CC @yannbf, would you consider a PR to change the way interactions-addon is importing jest-mock?  I've seen this come up about half a dozen times in the last few days, now.

**Comment by shilman** [comment]
Crikey!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.43 containing PR #17535 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by bstro** [comment]
I am running alpha.45: 
<img width="389" alt="image" src="https://user-images.githubusercontent.com/627290/156836546-d771bdc3-3157-46ef-a2ad-49c20342c3d9.png">
and still experiencing this error:
```
Uncaught SyntaxError: The requested module '/@fs/Users/…/hexagrams2.1/node_modules/jest-mock/build/index.js?v=898ee8c4' does not provide an export named 'ModuleMocker'
```

**Comment by IanVS** [comment]
Alphas are cut pretty regularly.  If you'd like to work around it for now, you can add a `.storybook/preview-head.html` as so:

```html
<script>
  window.global = window;
</script>
```

**Comment by bstro** [comment]
@IanVS the error persists with that workaround for me—I will comment out "addon-interactions" in `main.js` and continue until the new alpha is cut. Thanks!

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.46 containing PR #17614 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by bstro** [comment]
Hmm. Shoot. I'm still experiencing this error with v6.5.0-alpha.46. 
```
Uncaught SyntaxError: The requested module '/@fs/Users/bstro/project/node_modules/jest-mock/build/index.js?v=4151d6d7' does not provide an export named 'ModuleMocker'
```

**Comment by IanVS** [comment]
@bstro are you able to provide a reproduction?  I've seen this error reported, but I'm not sure why yet.

**Comment by IanVS** [comment]
Can you also try adding `jest-mock` to your `optimizeDeps.include`?

**Comment by bstro** [comment]
Adding `jest-mock` to `optimizeDeps.include` at least changed the error I'm seeing:
<img width="492" alt="image" src="https://user-images.githubusercontent.com/627290/156905669-e174ee41-d022-464d-a27b-bc17ed723ff0.png">

This is how I configure it in main.ts... not sure if I did it right:
```
module.exports = {
  async viteFinal(config) {
    config.optimizeDeps.include = [...config.optimizeDeps.include, "jest-mock"];
    return config;
  },
  …
```

**Comment by IanVS** [comment]
Try the latest alpha of storybook, there was a recent fix that should take care of that.

**Comment by bstro** [comment]
I am on the latest alpha (46), as well as the latest storybook-builder-vite (0.1.18) and the error is still present

**Comment by IanVS** [comment]
@bstro odd.  Have you removed the cache in your node_modules as well (`node_modules/.storybook-vite` by default)?  Are you able to send a reproduction?

**Comment by bstro** [comment]
I haven't been able to work on a reproduction yet, but I can try later this week. I did completely clear out my `node_modules` for what it's worth.

**Comment by bstro** [comment]
Here's a reproduction at https://github.com/bstro/storybook-jest-mock-bug-repro
<img width="442" alt="image" src="https://user-images.githubusercontent.com/627290/157603425-4e2cc589-ac20-4e1a-822e-5de0200f853b.png">

This is on a 100% fresh install of storybook in a brand new vite project, relatively simple to reproduce if you want to try these steps:
1. `yarn create vite` — I chose a react project with typescript
2. `npx sb@next init --builder storybook-builder-vite`
3. `yarn run storybook`

Node version 14.18.3, btw.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.53 containing PR #17830 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.20 containing PR #17830 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by izznatsir** [comment]
It still happens in `v7.0.0-beta.61`.

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.11 containing PR #21832 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
