### ISSUE TITLE
In production, stories do not appear in export order

### ISSUE THREAD

**Issue by rdebeasi** [storybookjs/storybook#17611]
**Describe the bug**
In production, stories do not appear in export order. Instead, they are sorted alphabetically.

#15574 describes similar behavior and was closed when a [fix](https://github.com/storybookjs/storybook/issues/15574#issuecomment-1012074028) was released in v6.14.13 and v6.5.0-alpha.17. I'm still experiencing this problem with Storybook 6.5.0-alpha.45, however. 

<img width="845" alt="Screenshot of dev server and production server" src="https://user-images.githubusercontent.com/1299370/156414877-41c9be26-5bd0-40bf-b8f7-2124420e2087.png">

Thank you in advance for your help!! 😄 

**To Reproduce**

1. Clone https://github.com/rdebeasi/storybook-sort-repro

2. Run `yarn storybook` to start Storybook in dev mode. Stories appear in export order (Story C, Story B, Story A). This is the expected behavior.

3. Run `yarn build-storybook && npx serve` to start Storybook in production mode. Shows appear in sorted in  alphabetical order (Story A, Story B, Story C). This behavior appears to be a bug.

**System**

```
  OS: macOS 11.6.4

  CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz

 Binaries:

  Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node

  Yarn: 3.2.0 - ~/.yarn/bin/yarn

  npm: 6.14.8 - ~/.nvm/versions/node/v14.15.1/bin/npm

 Browsers:

  Chrome: 98.0.4758.109

  Firefox: 97.0.1

  Safari: 15.3

 npmPackages:

  @storybook/addon-actions: ^6.5.0-alpha.45 => 6.5.0-alpha.45 

  @storybook/addon-docs: ^6.5.0-alpha.45 => 6.5.0-alpha.45 

  @storybook/addon-essentials: ^6.5.0-alpha.45 => 6.5.0-alpha.45 

  @storybook/addon-interactions: ^6.5.0-alpha.45 => 6.5.0-alpha.45 

  @storybook/addon-links: ^6.5.0-alpha.45 => 6.5.0-alpha.45 

  @storybook/angular: ^6.5.0-alpha.45 => 6.5.0-alpha.45 

  @storybook/builder-webpack5: ^6.5.0-alpha.45 => 6.5.0-alpha.45 

  @storybook/manager-webpack5: ^6.5.0-alpha.45 => 6.5.0-alpha.45 

  @storybook/testing-library: ^0.0.9 => 0.0.9 
```

**Comment by himerus** [comment]
I have seen this repeatedly in about 8 different Storybook environments at minimum. 

This is a major issue as on many stories, we may intentionally build the first story to handle all the controls and be a flexible demonstration of all the options. THEN we will choose to iterate out more "hard coded" stories for some of the additional ones to provide multiple varying scenarios we can run a11y tests against, etc. 

I wish I'd have had time to look into this, but we've definitely seen this for MONTHS.

**Comment by shilman** [comment]
Did you see this comment

https://github.com/storybookjs/storybook/issues/15574#issuecomment-1045103307

**Comment by rdebeasi** [comment]
Thanks for sharing that link! Unfortunately, it does not resolve this issue.

That comment refers to a problem with a custom Webpack config. In the repro above, we are using the default configuration, without any Webpack customization.

**Comment by shilman** [comment]
@rdebeasi @himerus I'm seeing an inconsistency between the babel config for angular (broken) vs. react (works). will investigate further. are all the projects you're seeing this on using Angular? If not, what framework? thanks! 🙏

**Comment by himerus** [comment]
@shilman [we](https://github.com/phase2/outline) are using web components 100%. 

![image](https://user-images.githubusercontent.com/21905/156811525-59438838-b1d5-4d11-8297-e157e0765f52.png)

**Comment by shilman** [comment]
@himerus in your case i think it's the custom babel config that's overriding the defaults. try adding `babel-plugin-named-exports-order` to process your story files and i think it should work.

**Comment by rdebeasi** [comment]
Yes, I'm seeing this problem only with Angular. I'm not able to reproduce the problem with Storybook React.

**Comment by himerus** [comment]
> @himerus in your case i think it's your custom babel config that's overriding the defaults. try adding `babel-plugin-named-exports-order` to process your story files and i think it should work. please let me know either way! 🙏

Interesting. Now I have to figure out/remember why we have that [large babel config](https://github.com/phase2/outline/blob/next/src/.storybook/babel.config.js) in place to begin with. It is a leftover remnant from long ago. Adding `babel-plugin-named-exports-order` almost solved the problem. They are listed in the correct order in the sidebar menu, but not in the story itself. 

![image](https://user-images.githubusercontent.com/21905/156823243-b92d92a7-662f-4216-bc25-9d3381f37d9b.png)

Any additional thoughts welcome, otherwise I'll dig more into that configuration.

**Comment by shilman** [comment]
> They are listed in the correct order in the sidebar menu, but not in the story itself.

To clarify, do you mean in the DocsPage for that story on the Docs tab?

**Comment by himerus** [comment]
@shilman Exactly. This is on the Docs tab.

**Comment by shilman** [comment]
@tmeasday any ideas why the DocsPage story order wouldn't match the sidebar order?

**Comment by tmeasday** [comment]
@himerus -- am I correct in saying you are **NOT** using `storyStoryV7`? 

If so, I don't really see any obvious reason why the order here (which drives the docs page): https://github.com/storybookjs/storybook/blob/fc9853ace3057ac9e98432b20b3610d1c0e22dd0/lib/store/src/StoryStore.ts#L219

would differ from the order in `extract` (which drives the sidebar).

However, I suppose technically there's definitely a bug there, as the order in the index *could* definitely be different from the raw export order (e.g. if you are using sorting, or `__namedExportsOrder`. I'll send a fix for that in any case @shilman. On the surface it doesn't seem like what's happening here though.

**Comment by tmeasday** [comment]
https://github.com/storybookjs/storybook/pull/17669

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.47 containing PR #17669 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by rdebeasi** [comment]
Thanks for making this change! I've updated [the repro](https://github.com/rdebeasi/storybook-sort-repro) to Storybook 6.5.0-alpha.48. Stories are now sorted in alphabetical order in both local and development.

My understanding is that the intended behavior is for stories to be sorted in export order, not alphabetical order. For example, in the [How to write stories](https://storybook.js.org/docs/react/writing-stories/introduction) docs, the Button stories are shown in export order:
- Primary
- Secondary
- Large
- Small

> Closing this issue. Please re-open if you think there's still more to do.

I think there's still more to do, but I don't have permission to re-open this issue because I'm not a collaborator and I didn't close the issue. Could someone please re-open this issue? Thank you!

**Comment by liverant** [comment]
With the new version:

```
 "@nrwl/storybook": "^13.10.0-beta.1",
    "@storybook/addon-docs": "^6.5.0-alpha.50",
    "@storybook/addon-essentials": "^6.5.0-alpha.50",
    "@storybook/addon-viewport": "^6.5.0-alpha.50",
    "@storybook/angular": "^6.5.0-alpha.50",
    "@storybook/builder-webpack5": "^6.5.0-alpha.50",
    "@storybook/manager-webpack5": "^6.5.0-alpha.50",
```

And the default config (`preview.js`):

```
export const parameters = {
  viewMode: 'docs',
  docs: {
    inlineStories: true,
    container: DocsContainer,
    page: DocsPage,
    source: {
      state: 'open',
    },
  },
  viewport: {
    viewports: INITIAL_VIEWPORTS,
  },
};
```

**Stories in prod build are still not in their imported order** 
("Playground" should be first, instead we get alphabetical order)
![image](https://user-images.githubusercontent.com/89337403/159890121-baf906de-0c21-4b6d-a4d2-83837f4c7746.png)

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.20 containing PR #17669 that references this issue. Upgrade today to the `@latest` NPM tag to try it out!

```
npx sb upgrade
```

**Comment by platon-rov** [comment]
Still sorted in the wrong order. Tried even `6.5-alpha.55` version. HTML framework.
