### ISSUE TITLE
6.5.0-alpha.58 - Can't resolve 'react-dom/client' 

### ISSUE THREAD

**Issue by yairEO** [storybookjs/storybook#17926]
**Describe the bug**
Apparently after upgrading to `6.5.0-alpha.60` (from `55`) I am getting this error (in the terminal)
> Can't resolve 'react-dom/client' 

`react-dom/client` is a new path exists only in `react-dom` v18, AFAIK

Traced it down to this potential line which was added recently:
https://github.com/storybookjs/storybook/pull/17215/files#diff-4ff35b6b89e790db308e2624d4187ab9a4cbc01bb54f92c0a0095f7b11a01189R10

![image](https://user-images.githubusercontent.com/845031/162638118-92b631e0-02b5-4dec-a398-d1c241d9a44a.png)

**To Reproduce**
I am using `react` & `react-dom` `17.0.2` And Webpack v5 & `Windows 10`

## Minimal reproducible demo:
https://github.com/yairEO/sb-issue--react-client

(Getting the error on Windows 10) using `npm` to install dependencies

**Comment by AmirAsghary** [comment]
We're facing the same problem.

Storybook version: "@storybook/react": "^6.5.0-alpha.60"

Previously we were on version "^6.5.0-alpha.41" and it was working fine.

**Comment by shilman** [comment]
@yairEO @AmirAsghary Do you a have a reproduction repo you can share? If not, can you create one? See [how to create a repro](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

@ndelangen @valentinpalkovic we went to some lengths to get past this. any idea what could be going on here?

**Comment by valentinpalkovic** [comment]
The `react-dom/client` path only gets ignored in React < 18 setups, when webpack/vite is properly set up. We took care of the webpack as well as the vite setup.

To start with some reproductions, it would be good to know which builder is in use. Webpack 4, Webpack 5 or Vite?

**Comment by AmirAsghary** [comment]
@valentinpalkovic We're using Webpack5 for the builder.

**Comment by yairEO** [comment]
I also use Webpack v5

**Comment by yairEO** [comment]
Hi @valentinpalkovic - I've created a repo minimal with the setup of my project, where the issue is reproducible:

https://github.com/yairEO/sb-issue--react-client

I am using `Windows 10`

**Comment by valentinpalkovic** [comment]
@yairEO I have checked your repo out and everything works fine (WSL Ubuntu environment). It seems, that it is indeed an OS related issue. On Windows 11 I am able to reproduce it the bug. I will investigate the issue further.

**Comment by valentinpalkovic** [comment]
These changes should fix the issue: https://github.com/storybookjs/storybook/pull/17946

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.63 containing PR #17946 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by BEmagical** [comment]
Thank you @shilman! Ran the command, fixed the issue right away! 
macOS Monterey, 12.3.1
HuzzahhhhH!

**Comment by valdemarrolfsen** [comment]
Still seeing this issue in 6.5.9:

```
67% building 477/500 modules 23 active node_modules/core-js/internals/define-built-in-accessor.js ERR! => Failed to build the manager
ERR! Module not found: Error: Can't resolve 'react-dom/client' in '/Users/valdemarrolfsen/Development/Ignite/main/node_modules/@storybook/react/dist/esm/client/preview'
```

I am running react & react-dom 16.14.0 with webpack v5

**Comment by thibaudcolas** [comment]
I’m running into this as well and have opened #18662 with a description of the specific issue and what I’ve done to work around it.
