### ISSUE TITLE
[Bug]: composeStories from @storybook/react does not work with components that have required props

### ISSUE THREAD

**Issue by joshwooding** [storybookjs/storybook#20026]
### Describe the bug

This is essentially a regression of https://github.com/storybookjs/testing-react/issues/4 and affects users migrating to use @storybook/react instead.

### System

```shell
npmPackages:
    @storybook/addon-a11y: ^7.0.0-alpha.54 => 7.0.0-alpha.54
    @storybook/addon-actions: ^7.0.0-alpha.54 => 7.0.0-alpha.54
    @storybook/addon-docs: ^7.0.0-alpha.54 => 7.0.0-alpha.54
    @storybook/addon-essentials: ^7.0.0-alpha.54 => 7.0.0-alpha.54
    @storybook/addon-links: ^7.0.0-alpha.54 => 7.0.0-alpha.54
    @storybook/addon-storysource: ^7.0.0-alpha.54 => 7.0.0-alpha.54
    @storybook/node-logger: ^7.0.0-alpha.54 => 7.0.0-alpha.54
    @storybook/react-vite: 7.0.0-alpha.54 => 7.0.0-alpha.54
```

### Additional context

You can workaround this the same way as https://github.com/storybookjs/testing-react/issues/4 and use `composeStory`

### Potential Fix

I haven't tested this fully, and my typescript knowledge is not great, but the issue to me is the usage of Args in the Store_CSFExports type

https://github.com/storybookjs/storybook/blob/afcd26ccd1a3ef748073b35faf96522db9964b27/code/lib/types/src/modules/composedStory.ts#L19-L23

Maybe the fix could be to allow Args as a generic here:

```ts
type Store_CSFExports<TRenderer extends Renderer = Renderer, TArgs extends Args = Args> = {
    default: ComponentAnnotations<TRenderer, TArgs>;
    __esModule?: boolean;
    __namedExportsOrder?: string[];
};
```
and update composeStories to:

```ts
function composeStories<TModule extends Store_CSFExports<ReactRenderer, ComponentProps>>(
  csfExports: TModule,
  projectAnnotations?: ProjectAnnotations<ReactRenderer>
)
```

But not sure what implications that has

**Comment by yannbf** [comment]
@kasperpeulen can we take a look at this once we have time?

**Comment by csantos1113** [comment]
hi all, shouldn't this be added to the https://github.com/orgs/storybookjs/projects/8/views/1 ?

I feel this should be a blocker for 7.0 release, otherwise all of us using `.play` with `composeStories` will have broken experience

**Comment by shilman** [comment]
@csantos1113 We'll be working on improving `composeStories` as part of 7.1.

**Comment by kasperpeulen** [comment]
@yannbf Didn't we solve this recently?

**Comment by csantos1113** [comment]
This isn't an issue for me anymore.

It might have been fixed on https://github.com/storybookjs/storybook/commit/7aa0042e306f86c08716f73ad1c348f2a089f6c0

**Comment by kasperpeulen** [comment]
Thanks for confirming @csantos1113!

**Comment by InfamousStarFox** [comment]
This issue is still present when using decorators, on version 8.0.8


Hello.tsx
```
const Hello = (props: { text: string }) => <div>{props.text}</div>;

export default Hello;
```

Hello.stories.tsx
```
import { Meta, StoryObj } from '@storybook/react';
import Hello from '../Hello';

export default {
  title: 'Hello',
  component: Hello,
  decorators: [
    (Story, { parameters }) => (
      <div style={{ color: `${parameters.color"` }}>
        <Story />
      </div>
    )
  ]
} satisfies Meta<typeof Hello>;

type Story = StoryObj<typeof Hello>;

export const HelloStory: Story = {};
HelloStory.storyName = 'Hello';
HelloStory.args = {
  text: 'Hello World'
};
HelloStory.parameters = {
  color: 'blue'
};
```

Hello.test.tsx
```
import { render, screen } from '@testing-library/react';
import { composeStories } from '@storybook/react';
import * as stories from './Hello.stories';

const { HelloStory} = composeStories(stories);

test('Hello World renders', () => {
  render(<HelloStory/>);
  expect(screen.getByText('Hello World')).toBeVisible();
});
```

This throws the error in Hello.test.tsx
```
Property 'HelloStory' does not exist on type 'Omit<StoriesWithPartialProps<ReactRenderer, Store_CSFExports<ReactRenderer, any>> keyof Store_CSFExports>'.
```

When changing prop in Hello.tsx to not be required, the error goes away.

**Comment by valentinpalkovic** [comment]
cc @kasperpeulen

**Comment by jjoselv** [comment]
Is it planned to fix this? as @InfamousStarFox with decorators it is still failing, probably because of the `StoriesWithPartialProps` in `composeStories`?
