### ISSUE TITLE
[Bug]: Multiple versions of emotion in docs leads to theme error

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#20217]
### Describe the bug

In a project without an explicit emotion dependency (in fact no version of emotion in `node_modules`), visiting docs, I see two warnings:

```
You are loading @emotion/react when it is already loaded. Running multiple instances may cause problems. This can happen if multiple versions are used, or if multiple builds of the same version are used.
```

Then many errors:
```
Uncaught TypeError: Cannot read properties of undefined (reading 'secondary')
....

The above error occurred in the <IconButton> component:
....
```

etc

### To Reproduce

1. Clone https://github.com/tmeasday/inkline/tree/upgrade
2. `npm i`
3. `yarn storybook`
4. Visit a docs page.

#### Explanation

The issue is due to a dependency on `@storybook/theming@6.5.9` being hoisted and so multiple versions of `@storybook/theming@7` being created inside each dependent package.

**Comment by tmeasday** [comment]
@ndelangen I think the reason is that the project has a dependency on `@storybook/theming@6.5.9` due to `@storybook/testing-library@^0.0.14-next.0` and that is the version being hoisted.

**Comment by tmeasday** [comment]
I resolved via adding a direct dependency on `@storybook/theming@next`.

**Comment by tmeasday** [comment]
This was fixed by https://github.com/storybookjs/testing-library/pull/30, thanks @yannbf !

**Comment by ndelangen** [comment]
This could still happen in the real world, not super likely, but possible..

**Comment by yannbf** [comment]
> We can reopen if you like @ndelangen but I'd say let's wait to see if it comes from users before doing anything about it.
> 
> In the above case, it was a totally standard installation that led to two different versions of `@storybook/theming`, and when the wrong one was hoisted, we had problems. Now the testing-lib package is updated that won't happen any more.

Is it also possible this could happen from community addons which are not updated to support SB 7.0 yet?

**Comment by ndelangen** [comment]
Yes, it could happen that way indeed @yannbf

**Comment by sljuka** [comment]
After upgrading to v7 I am seeing this error:
<img width="1591" alt="Screenshot 2023-04-14 at 22 42 21" src="https://user-images.githubusercontent.com/5074688/232151161-0d6b9957-16ee-4240-b5a4-c84d4c3e3d26.png">
It only shows up when going to the `docs` (autodocs) story. The design system lib is not using emotion, but it's in a monorepo with other libs that are using emotion that might be clashing with storybook's internals.
Relevant `npm ls` from lib's root:
```
 ├── @storybook/addon-a11y@7.0.4
  ├── @storybook/addon-essentials@7.0.4
  ├── @storybook/addon-interactions@7.0.4
  ├── @storybook/addon-links@7.0.4
  ├── @storybook/blocks@7.0.4
  ├── @storybook/react-vite@7.0.4
  ├── @storybook/react@7.0.4
  ├── @storybook/theming@7.0.4
  ├── @vanilla-extract/vite-plugin@3.8.0
  ├── @vitejs/plugin-react@3.1.0
  ├── chromatic@6.17.3
```
`npm ls` from monorepo root:
```
│ ├── @storybook/addon-a11y@7.0.4
│ ├── @storybook/addon-essentials@7.0.4
│ ├── @storybook/addon-interactions@7.0.4
│ ├── @storybook/addon-links@7.0.4
│ ├── @storybook/blocks@7.0.4
│ ├── @storybook/react-vite@7.0.4
│ ├── @storybook/react@7.0.4
│ ├── @storybook/theming@7.0.4
...
│ ├── @emotion/react@11.10.6 deduped
│ ├── @emotion/styled@11.10.6 deduped
```
Both Adding `@storybook/theming` package explicitly and removing `@storybook/testing-library` did not fix the issue.

**Comment by sljuka** [comment]
> You are loading @emotion/react when it is already loaded. Running multiple instances...
Right, I'm also seeing this warning before the first error

**Comment by sljuka** [comment]
Fixing all `@storybook` related packages to `7.0.4` (without carrot `^`) fixed the package clash. This is not best practice since I'm missing out on minor version changes. There is probably no need to fix versions on all @storybook packages but I would need to experiment here to find out.
With Tailwind, Vanilla-extract and other "0-runtime" css-in-js libs becoming popular, perhaps it would be good if SB migrated away from runtime styling libs like emotion.
