### ISSUE TITLE
[Bug]: unexpected configure() call

### ISSUE THREAD

**Issue by mantismamita** [storybookjs/storybook#20547]
### Describe the bug

Using Vite 4.0.0

When running npm run storybook I get the following message in red:

```
info => Starting manager..
info => Serving static files from ././static at /
The following Vite config options will be overridden by SvelteKit:
  - base
```
  
  Storybook starts correctly but there remains a loader with the console message: 
  
  ```
Uncaught Error: unexpected configure() call
    at configure (chunk-M72LMS77.mjs:2:2420)
    at configure (index.mjs:1:461)
    at configStories (storybook-stories.js:17:7)
    at null:92:1
```
    
    when I click on the last element of the stack trace I get 
    `Could not load content for http://localhost:6006/virtual:/@storybook/builder-vite/null (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)`

### To Reproduce

```shell
https://github.com/mantismamita/storybook-svelte-bugreproduction
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.1
    CPU: (10) arm64 Apple M1 Max
  Binaries:
    Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
    npm: 8.19.2 - ~/.nvm/versions/node/v16.16.0/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Safari: 16.2
  npmPackages:
    @storybook/addon-a11y: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/addon-actions: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/addon-essentials: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/addon-interactions: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/addon-links: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/addon-postcss: ^2.0.0 => 2.0.0 
    @storybook/addon-svelte-csf: ^3.0.0-next.3 => 3.0.0-next.3 
    @storybook/builder-vite: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/client-logger: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/svelte: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/sveltekit: ^7.0.0-beta.21 => 7.0.0-beta.21 
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

### Additional context

discussion via discord with @IanVS 
Thanks for your help and your hard work 🙂

**Comment by IanVS** [comment]
@mantismamita could you try upgrading `@storybook/addon-postcss` to [3.0.0-alpha.1](https://www.npmjs.com/package/@storybook/addon-postcss/v/3.0.0-alpha.1)?

**Comment by mantismamita** [comment]
I actually  tried to remove it altogether already and no luck .I'll try upgrading it

**Comment by IanVS** [comment]
I tried to check out your reproduction, but I wasn't able to install because of `https://nexus-production` in the package-lock.json. I removed the lockfile, but then I couldn't start storybook because I couldn't generate css because I got `Error: [postcss-custom-media] "importFrom" is no longer supported`

I'm going to close this out since you got it working, but it seems like you might have been using an older addon that still uses a deprecated `configure()` call.  Using StoryStoreV7 is what you should be doing now anyway, so kind of a moot point perhaps.

**Comment by mantismamita** [comment]
ok I updated the package-lock in case it wants looking at again.

**Comment by IanVS** [comment]
Thanks. I still get an error:

```
▶ npm run generate:css-json

> storybook-svelte-bugreproduction@0.0.1 generate:css-json
> postcss src/assets/styles/global.css > /dev/null

Error: [postcss-custom-media] "importFrom" is no longer supported
```

Should I be running something else to generate `customProperties.json`?

**Comment by mantismamita** [comment]
I think that's from `postcss-custom-media` which has to be at 8 or below.
