### ISSUE TITLE
[Bug]: [v7] vite.config.js is required in root for @storybook/vue3-vite + @storybook/builder-vite

### ISSUE THREAD

**Issue by samturrell** [storybookjs/storybook#20576]
### Describe the bug

When using Storybook 7.0.0-beta.24 and the vue3 vite combo, the following error is thrown unless a `vite.config.js` is present in the root directory with the vue plugin setup.

<details>
<summary>Details</summary>

```
@storybook/cli v7.0.0-beta.24

info => Starting manager..
info => Serving static files from ././assets at /
WARN Force closed manager build
ERR! TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
ERR!     at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
ERR!     at new NodeError (node:internal/errors:371:5)
ERR!     at createRequire (node:internal/modules/cjs/loader:1222:11)
ERR!     at null.../../node_modules/@vitejs/plugin-vue/dist/index.mjs (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/vue3-vite/dist/preset.js:20:5389)
ERR!     at null.<anonymous> (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/vue3-vite/dist/preset.js:1:327)
ERR!     at null.<anonymous> (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/vue3-vite/dist/preset.js:28:1066)
ERR!     at Object.viteFinal (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/vue3-vite/dist/preset.js:28:1032)
ERR!     at null.createViteServer (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/builder-vite/dist/index.js:162:7535)
ERR!     at Module.start (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/builder-vite/dist/index.js:162:9428)
ERR!     at async storybookDevServer (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/core-server/dist/index.js:20:4323)
ERR!     at async buildDevStandalone (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/core-server/dist/index.js:33:2841)
ERR!     at async withTelemetry (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/core-server/dist/index.js:33:5533)
ERR!     at async dev (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/cli/dist/generate.js:427:3177)
ERR!  TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
ERR!     at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
ERR!     at new NodeError (node:internal/errors:371:5)
ERR!     at createRequire (node:internal/modules/cjs/loader:1222:11)
ERR!     at null.../../node_modules/@vitejs/plugin-vue/dist/index.mjs (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/vue3-vite/dist/preset.js:20:5389)
ERR!     at null.<anonymous> (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/vue3-vite/dist/preset.js:1:327)
ERR!     at null.<anonymous> (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/vue3-vite/dist/preset.js:28:1066)
ERR!     at Object.viteFinal (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/vue3-vite/dist/preset.js:28:1032)
ERR!     at null.createViteServer (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/builder-vite/dist/index.js:162:7535)
ERR!     at Module.start (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/builder-vite/dist/index.js:162:9428)
ERR!     at async storybookDevServer (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/core-server/dist/index.js:20:4323)
ERR!     at async buildDevStandalone (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/core-server/dist/index.js:33:2841)
ERR!     at async withTelemetry (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/core-server/dist/index.js:33:5533)
ERR!     at async dev (/Users/samturrell/www/web/nuxt-template-2/node_modules/@storybook/cli/dist/generate.js:427:3177) {
ERR!   code: 'ERR_INVALID_ARG_VALUE'
ERR! }
```

</details>

`viteFinal` is never ran unless a valid `vite.config.js` exists, and this is where i'm creating the actual vite config as we are pulling in the vite config from nuxt so that we can pass it to storybook and have the same vite config with no extra configuration, e.g.

```
    async viteFinal(config) {
        const nuxt = await loadNuxt();

        const mergedNuxtConfig = mergeConfig(config, nuxt.options.vite);

        return mergeConfig(mergedNuxtConfig, {
            resolve: {
                alias: tsconfig.compilerOptions.paths,
            },
        });
    },
```

The `@storybook/vue3-vite` preset seems to be setting up the vue plugin itself, so i'm not sure why i would need to set this up in the root `vite.config.js` manually https://github.com/storybookjs/storybook/blob/f7826d538200f16b6a470c1dcd45dca1aa68e9f7/code/frameworks/vue3-vite/src/preset.ts

### To Reproduce

```shell
Reproduction repository here: https://github.com/samturrell/storybook-7-vue-vite

To reproduce: run `yarn storybook`

Observe: Error is called and the `viteFinal` `console.log` is not fired.

To successfully run: rename `vite-disabled.config.js` to `vite.config.js` and run `yarn storybook` again.

Observe: Storybook runs successfully without errors and the `viteFinal` `console.log` is logged to the terminal.
```

### System

```shell
Environment Info:

  System:
    OS: macOS 13.0
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
    Yarn: 1.22.17 - /opt/homebrew/bin/yarn
    npm: 8.5.0 - ~/.nvm/versions/node/v16.14.2/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 100.0
    Safari: 16.1
  npmPackages:
    @storybook/addon-a11y: ^7.0.0-beta.24 => 7.0.0-beta.24
    @storybook/addon-essentials: ^7.0.0-beta.24 => 7.0.0-beta.24
    @storybook/addon-jest: ^7.0.0-beta.24 => 7.0.0-beta.24
    @storybook/addon-links: ^7.0.0-beta.24 => 7.0.0-beta.24
    @storybook/builder-vite: ^7.0.0-beta.24 => 7.0.0-beta.24
    @storybook/cli: ^7.0.0-beta.24 => 7.0.0-beta.24
    @storybook/theming: ^7.0.0-beta.24 => 7.0.0-beta.24
    @storybook/vue3-vite: ^7.0.0-beta.24 => 7.0.0-beta.24
```

### Additional context

Adding a `vite.config.js` to the root breaks nuxt as i assume it's overriding the default config provided by nuxt, so this isn't a fix for my use case.

**Comment by tobiasdiez** [comment]
I've encountered the same error. Did you find a workaround?

**Comment by iamandrewluca** [comment]
Fixed in https://github.com/storybookjs/storybook/pull/20681 by @IanVS

**Comment by tobiasdiez** [comment]
Thanks for the pointer! This doesn't completely fixes the issue (directing to an empty vite config still fails with the same error), but once you add the vue plugin it works:
```
import vue from '@vitejs/plugin-vue'

export default {
  plugins: [vue()],
}
```

**Comment by IanVS** [comment]
Yeah there's still something strange going on here that I don't quite understand. But I'll try to look into it when I can.

**Comment by IanVS** [comment]
This is the same issue as https://github.com/storybookjs/storybook/issues/20583, so I'm going to close this and track the bug in the other one just to keep things organized.  Please subscribe to it for updates.
