### ISSUE TITLE
[Bug]: `remarkGfm` does not work under the `@storybook/react-vite` framework

### ISSUE THREAD

**Issue by htmlin** [storybookjs/storybook#20570]
### Describe the bug

I used the command to create a new storybook

```
npx storybook@next init --package-manager=pnpm
```

I follow [Guides](https://storybook.js.org/docs/7.0/react/writing-docs/mdx#lack-of-github-flavored-markdown-gfm) to add MDX options to the main configuration file:

```js
const remarkGfm = require('remark-gfm')

module.exports = {
  stories: ['../stories'],
  addons: [
    '@storybook/addon-links',
    '@storybook/addon-essentials',
    '@storybook/addon-interactions',
    {
      name: '@storybook/addon-docs',
      options: {
        mdxCompileOptions: {
          remarkPlugins: [remarkGfm],
        },
      },
    },
  ],
  framework: {
    name: '@storybook/react-vite',
    options: {},
  },
  docs: {
    autodocs: 'tag',
  },
}
```

But table is still not rendered.

❌ Actual:

![image](https://user-images.githubusercontent.com/18374110/211784657-d7ad2944-c9ed-4a19-a0e1-5c247cd89fc1.png)

✅ Expected:

![image](https://user-images.githubusercontent.com/18374110/211785036-00f3a688-96f1-49bc-9e20-553f886d60ee.png)

### System

```shell
Environment Info:

  System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
  Binaries:
    Node: 16.14.0 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 8.3.1 - /usr/local/bin/npm
  Browsers:
    Firefox: 70.0.1
    Safari: 16.2
  npmPackages:
    @storybook/addon-essentials: ~7.0.0-beta.24 => 7.0.0-beta.24 
    @storybook/addon-interactions: ~7.0.0-beta.24 => 7.0.0-beta.24 
    @storybook/addon-links: ~7.0.0-beta.24 => 7.0.0-beta.24 
    @storybook/blocks: ~7.0.0-beta.24 => 7.0.0-beta.24 
    @storybook/react: ~7.0.0-beta.24 => 7.0.0-beta.24 
    @storybook/react-vite: ~7.0.0-beta.24 => 7.0.0-beta.24 
    @storybook/testing-library: 0.0.13 => 0.0.13 
    @storybook/theming: ~7.0.0-beta.24 => 7.0.0-beta.24
```

**Comment by htmlin** [comment]
I think it's fixed by #20116

**Comment by markpalfreeman** [comment]
@htmlin was this fixed officially? I'm using `@storybook/web-components-vite` and it's still broken for me even after updating to the new `beta.41` :/

(I imagine Vite is the common denominator?)
