### ISSUE TITLE
[Bug]: unattached (docs only) stories from *.stories.mdx are failing in Storybook 7

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#20587]
### Describe the bug

Storybook loads with the following error:
```
VM1459 runtime.mjs:11320 Uncaught (in promise) Error: Unexpected missing story example-introduction--page from referenced CSF file.
    at VM1459 runtime.mjs:11320:15
    at Array.forEach (<anonymous>)
    at DocsContext.referenceCSFFile (VM1459 runtime.mjs:11316:36)
    at VM1459 runtime.mjs:11306:12
    at Array.forEach (<anonymous>)
    at new DocsContext (VM1459 runtime.mjs:11305:14)
    at CsfDocsRender.docsContext (VM1459 runtime.mjs:11416:25)
    at CsfDocsRender.renderToElement (VM1459 runtime.mjs:11428:30)
    at PreviewWeb.renderSelection (VM1459 runtime.mjs:11774:26)
    at async PreviewWeb.selectSpecifiedStory (VM1459 runtime.mjs:11609:5)
```

### To Reproduce

```shell
1. Create a sandbox for `internal-ssv6-vite`
2. Change Introduction.mdx to Introduction.stories.mdx

You should see the failure
```

**Comment by jorgeguberte** [comment]
I'm also getting this error. Currently using Storybook v7.0.0-beta.28 with Vue 3

```
runtime.mjs:71 Uncaught (in promise) Error: Unexpected missing story example-introduction--page from referenced CSF file.
    at runtime.mjs:71:2046
    at Array.forEach (<anonymous>)
    at DocsContext.referenceCSFFile (runtime.mjs:71:1912)
    at runtime.mjs:71:1643
    at Array.forEach (<anonymous>)
    at new DocsContext (runtime.mjs:71:1612)
    at CsfDocsRender.docsContext (runtime.mjs:71:4924)
    at CsfDocsRender.renderToElement (runtime.mjs:71:5251)
    at PreviewWeb.renderSelection (runtime.mjs:80:4432)
```

**Comment by t0byman** [comment]
I'm also getting this error. Currently using Storybook v7.0.0-beta.**29** with Vue v3.2.45 trying to load the ColorPalette starter-example code from https://storybook.js.org/docs/react/writing-docs/doc-block-colorpalette. Same error as above:
<img width="864" alt="Screenshot 2023-01-17 at 16 20 18" src="https://user-images.githubusercontent.com/5767100/212938428-9a046ba7-d745-43e9-8c9a-d2295c07f773.png">

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.30 containing PR #20661 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by Alxandr** [comment]
I'm still having problems on `beta.30` - though the error changed:

```
Uncaught Error: No primary story defined for docs entry. Did you forget to use `<Meta>`?
```

And yes, I do have a `<Meta title="Typography" />`.

**Comment by tmeasday** [comment]
@Alxandr -- maybe you are running into this one? https://github.com/storybookjs/storybook/issues/19964 -- hoping to have it fixed very soon!

**Comment by Alxandr** [comment]
Ah - probably. Not using Description though, but `Typeset` and `Canva` - one of them probably has the same issue.
