### ISSUE TITLE
[Bug]: TypeError: Cannot read properties of undefined (reading 'indexOf')

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#20652]
### Describe the bug

Users have anonymously reported the following error in the Webpack builder:

```
node_modules/html-webpack-plugin/index.js:1027
    if (template.indexOf('!') === -1) {
                 ^

TypeError: Cannot read properties of undefined (reading 'indexOf')
    at getFullTemplatePath (node_modules/html-webpack-plugin/index.js:1027:18)
    at hookIntoCompiler (node_modules/html-webpack-plugin/index.js:174:22)
    at <anonymous> (node_modules/html-webpack-plugin/index.js:104:9)
    at Array.forEach (<anonymous>)
```

If you're seeing this in your project and have a reproduction you can share, please share here to help us stabilize Storybook for release.

**Comment by shilman** [comment]
@ndelangen you suggested that we could do better error-checking on the results of `previewMainTemplate` when it's evaluated and that could help us narrow down the problem.

**Comment by shilman** [comment]
Jiminy cricket!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.30 containing PR #20669 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by gabrielsch** [comment]
@shilman I still have this issue on beta.30, no additional information about the error is printed:

```
ERR! /Users/$projectFolder/node_modules/html-webpack-plugin/index.js:1027
ERR!     if (template.indexOf('!') === -1) {
ERR!                  ^
ERR!
ERR! TypeError: Cannot read properties of undefined (reading 'indexOf')
ERR!     at null.getFullTemplatePath (/Users/$projectFolder/node_modules/html-webpack-plugin/index.js:1027:18)
ERR!     at null.hookIntoCompiler (/Users/$projectFolder/node_modules/html-webpack-plugin/index.js:174:22)
ERR!     at null.<anonymous> (/Users/$projectFolder/node_modules/html-webpack-plugin/index.js:104:9)
ERR!     at Array.forEach (<anonymous>)
ERR!     at null.<anonymous> (/Users/$projectFolder/node_modules/html-webpack-plugin/index.js:103:20)
ERR!     at Hook.eval [as call] (eval at create (/Users/$projectFolder/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:7:1)
ERR!     at Hook.CALL_DELEGATE (/Users/$projectFolder/node_modules/tapable/lib/Hook.js:14:14)
ERR!     at null.createCompiler (/Users/$projectFolder/node_modules/webpack/lib/webpack.js:81:28)
ERR!     at null.create (/Users/$projectFolder/node_modules/webpack/lib/webpack.js:134:16)
ERR!     at null.webpack (/Users/$projectFolder/node_modules/webpack/lib/webpack.js:158:32)
ERR!  /Users/$projectFolder/node_modules/html-webpack-plugin/index.js:1027
ERR!     if (template.indexOf('!') === -1) {
ERR!                  ^
ERR!
ERR! TypeError: Cannot read properties of undefined (reading 'indexOf')
ERR!     at null.getFullTemplatePath (/Users/$projectFolder/node_modules/html-webpack-plugin/index.js:1027:18)
ERR!     at null.hookIntoCompiler (/Users/$projectFolder/node_modules/html-webpack-plugin/index.js:174:22)
ERR!     at null.<anonymous> (/Users/$projectFolder/node_modules/html-webpack-plugin/index.js:104:9)
ERR!     at Array.forEach (<anonymous>)
ERR!     at null.<anonymous> (/Users/$projectFolder/node_modules/html-webpack-plugin/index.js:103:20)
ERR!     at Hook.eval [as call] (eval at create (/Users/$projectFolder/node_modules/tapable/lib/HookCodeFactory.js:14:14), <anonymous>:7:1)
ERR!     at Hook.CALL_DELEGATE (/Users/$projectFolder/node_modules/tapable/lib/Hook.js:14:14)
ERR!     at null.createCompiler (/Users/$projectFolder/node_modules/webpack/lib/webpack.js:81:28)
ERR!     at null.create (/Users/$projectFolder/node_modules/webpack/lib/webpack.js:134:16)
ERR!     at null.webpack (/Users/$projectFolder/node_modules/webpack/lib/webpack.js:158:32)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

error Command failed with exit code 1.
```

**Comment by ndelangen** [comment]
@gabrielsch please supply a full reproduction, so we can analyse what's going on..

**Comment by mandarini** [comment]
I am experiencing the same issue as well! :D Will provide repro soon!

**Comment by ndelangen** [comment]
Thank for for the reproduction @mandarini 🙏 
I'll take a look tomorrow!

**Comment by mandarini** [comment]
Thank you @ndelangen ! I updated the code, same error happens when running through `storybook dev` directly!

**Comment by ndelangen** [comment]
@mandarini I looked at the repo, and it seems to be using `storybook/builder-webpack5@7.0.0-alpha.0`

Could you ensure this is using the latest beta version?

**Comment by mandarini** [comment]
Oops @ndelangen !

I updated (and pushed again), and getting a slightly different error now:

```
TypeError: (0 , import_core_common2.getBuilderOptions) is not a function
    at iframe_webpack_config_default (/Users/katerina/Projects/nrwl/my_nx/nx/node_modules/@storybook/builder-webpack5/dist/presets/preview-preset.js:1:3514)
    at starter (/Users/katerina/Projects/nrwl/my_nx/nx/node_modules/@storybook/builder-webpack5/dist/index.js:1:4550)
    at Module.start (/Users/katerina/Projects/nrwl/my_nx/nx/node_modules/@storybook/builder-webpack5/dist/index.js:1:8492)
    at async storybookDevServer (/Users/katerina/Projects/nrwl/my_nx/nx/node_modules/@storybook/core-server/dist/index.js:20:4562)
    at async buildDevStandalone (/Users/katerina/Projects/nrwl/my_nx/nx/node_modules/@storybook/core-server/dist/index.js:33:2845)
```

**Comment by ndelangen** [comment]
@mandarini That would suggest that somehow `core-common` is outdated?

**Comment by ndelangen** [comment]
yea confirmed, another outdated package:
![Screenshot 2023-02-16 at 11 39 26](https://user-images.githubusercontent.com/3070389/219342287-ea13f099-e917-481a-8de9-9c4b43777fb1.png)

**Comment by mandarini** [comment]
Hmm that's strange. How could I fix these bad dependencies?

**Comment by mandarini** [comment]
OK yes!!! When I delete `yarn.lock` and `node_modules` and install again it works!!!! It was some bad cache I guess! THANK YOUUUUU

**Comment by mandarini** [comment]
So I am closing this, since it's fixed if one makes sure all `@storybook/*` packages use latest beta.

**Comment by ndelangen** [comment]
🎉
