### ISSUE TITLE
[Bug]: Show code displays `<[object Object]...` instead of component name

### ISSUE THREAD

**Issue by konsalex** [storybookjs/storybook#20920]
### Describe the bug

Components that are wrapped with `forwardRef` in react are not displaying the proper name in built Storybook, whole working as expected in development mode. Example of what I mean in the image below.

![image](https://user-images.githubusercontent.com/12672541/216639123-21c6d84a-7c02-4404-9bf7-96267f6721a3.png)

Tried to debug by modifying and logging what is passed here: https://github.com/storybookjs/storybook/blob/next/code/renderers/react/src/docs/jsxDecorator.tsx#L108

![image](https://user-images.githubusercontent.com/12672541/216639188-a2c9dadb-a574-49eb-add9-f37c07c4e4b6.png)

and indeed the element is different in dev vs prod.

After digging with the help of @IanVS and @JReinhold found out that this might be an issue with `react-docgen-typescript` and `tsconfig.json` of the project.

### To Reproduce

```shell
Visit this link: https://github.com/konsalex/design-system-newline-course/tree/storybook-v7-issue
Clone then:


// Install packages
yarn
yarn workspace @newline-ds/foundation build
yarn workspace @newline-ds/react build

// Build and run
yarn workspace @newline-ds/storybook build-storybook && live-server packages/storybook/storybook-public
```
```


### System

```shell
Environment Info:

  System:
    OS: macOS 13.0
    CPU: (10) x64 Apple M1 Max
  Binaries:
    Node: 16.19.0 - ~/Library/Caches/fnm_multishells/44085_1675428690209/bin/node
    Yarn: 3.2.1 - /usr/local/bin/yarn
    npm: 8.19.3 - ~/Library/Caches/fnm_multishells/44085_1675428690209/bin/npm
  Browsers:
    Chrome: 109.0.5414.119
    Firefox: 109.0
    Safari: 16.1
```

**Comment by konsalex** [comment]
I think that the `preserveSymlinks` is the root cause in tsconfig.json

**Comment by JReinhold** [comment]
I'm having issues trying to get the reproduction up and running, when building the Storybook I get

```
ERR! Error: Failed to resolve entry for package "@newline-ds/foundation". The package may have incorrect main/module/exports specified in its package.json.
```

I also don't consider this a _minimal_ reproduction. I think you should be able to further reduce the complexity of this reproduction by removing anything regarding the monorepo/multi-package setup to make it laser-focused on the Storybook part. I would be surprised if any of that cross-package importing and linking was related to the actual issue.

**Comment by konsalex** [comment]
Sorry for the bad reproduction.

The repo had problems indeed and the start scripts I pasted were wrong. Updated the issue description with the new scripts, and the repo to fix some initialisation issues.

Also if it helps here is a Gitpod snapshot where the issue is reproduced properly:
https://gitpod.io#snapshot/e705b55d-3d0f-4996-93e3-89b03fa30b7e

<img width="1904" alt="image" src="https://user-images.githubusercontent.com/12672541/217102892-047e9b73-57d3-4e08-841b-13db3ebc39a1.png">

> I also don't consider this a minimal reproduction. I think you should be able to further reduce the complexity of this reproduction by removing anything regarding the monorepo/multi-package setup to make it laser-focused on the Storybook part.

This is the whole point though @JReinhold , as it's a common practise to host a component library inside a monorepo as a single package and consume it inside another Storybook package or it is not so common? 🤔

**Comment by JReinhold** [comment]
> The repo had problems indeed and the start scripts I pasted were wrong. Updated the issue description with the new scripts, and the repo to fix some initialisation issues.

Thanks, this helped and I got it working.

> This is the whole point though @JReinhold , as it's a common practise to host a component library inside a monorepo as a single package and consume it inside another Storybook package or it is not so common? 🤔

I think it's fairly common, but my point was that I'm not sure if it is related to this issue. If you remove ESLint, Prettier, Tailwind, importing from other packages and just have a plain story file with a component next to it, does it still break?

I've tried to debug this and comparing it to our "base" React-Vite example, but I still haven't figured out where things go wrong. It certainly works in some cases.

I think if you can keep removing more stuff from the reproduction until you've gotten so close to the base example that it starts working, then we can figure out what is causing this.

This is the "base" I'm referring to: https://github.com/storybookjs/sandboxes/tree/next/react-vite/default-ts/after-storybook

**Comment by konsalex** [comment]
@JReinhold a component next to it could not be the case, as we need a cross package import (monorepo). 

But I tried to remove everything that is unnecessary as you mentioned, now it's much thinner monorepo with only the necessary packages to work with. This is updated in the GitHub branch here: https://github.com/konsalex/design-system-newline-course/tree/storybook-v7-issue

or if you prefer a sandbox:
https://gitpod.io#snapshot/42ca6b6f-722f-47c5-a907-fcf913c35597



Also tested again if I change the `"preserveSymlinks": true` to `false` inside the Storybook's `tsconfig.json` what would happen, the issue goes away again.

**Comment by JReinhold** [comment]
Did some more trial and error and I can confirm that `"preserveSymlinks": false` makes it work. I've also tried to minimize it, by removing the `viteFinal`, not importing the component from the other package but just defining the component directly in the `stories` file, but that still had the error.

Interestingly, if you change the component import from `import { Button } from '@newline-ds/react/src/Button';` to `import { Button } from '../../react/src/Button';` it actually starts working again.

Maybe this is the combination of the tsconfig and yarn workspaces hoisting dependencies that causes this.

I can't look further into this at the moment, so I recommend that you use one of the workarounds for now.

**Comment by IanVS** [comment]
Vite treats source files differently from dependencies, which I'd guess is where this issue is coming from.  @joshwooding this might also be something to look into in https://github.com/joshwooding/vite-plugin-react-docgen-typescript

**Comment by sriramrudraraju** [comment]
Adding `displayName` to the component showed me the correct thing in the storybook for me

```jsx
Button.displayName = "Button"
```

**Comment by mnrendra** [comment]
I also got the same error when I wrapped the component using `forwardRef`.
When I remove the `forwardRef` and export the component, then the result is fine (no error like above), ex:
```tsx
export default ComponentName
```
but when I use `forwardRef` to wrap the component, then the result has an error like the above, ex:
```tsx
export default forwardRef(ComponentName)
```

**Comment by mnrendra** [comment]
> Adding `displayName` to the component showed me the correct thing in the storybook for me
> 
> ```js
> Button.displayName = "Button"
> ```

Hi @sriramrudraraju how did you implement it? Can you show more by an example? Thank you

**Comment by konsalex** [comment]
As simple as this @mnrendra: https://stackoverflow.com/a/43356103/3247715

```jsx
const MyComponent = forwardRef(function MyInput(props, ref) {
  return (
    <p>Hello World</p>
  )
})

MyComponent.displayName = "MyComponent"
```

**Comment by hailwood** [comment]
Seems like `.displayName` is now becoming the *cause* of `<[object Object...` in v8.

**Comment by shilman** [comment]
@hailwood Please try configuring your Storybook to use the legacy docgen to analyze your components. Does that fix it?

```ts
// .storybook/main.js

export default {
  // stories, addons, etc.
  typescript: {
    reactDocgen: 'react-docgen-typescript'
  }
}
```

**Comment by hailwood** [comment]
Hey @shilman 

So things get a little weird... I setup three identical buttons components.
The only differences are

**NoForwardRefButton**
```tsx
export const NoForwardRefButton = function (
  { className, variant, size, asChild = false, ...props }: ButtonProps
) {/*...*/};
```

**ForwardRefNoDisplayNameButton**
```tsx
export const ForwardRefNoDisplayNameButton = forwardRef(function (
  { className, variant, size, asChild = false, ...props }: ButtonProps,
  ref: ForwardedRef<HTMLButtonElement>,
) {/*...*/});
```

**ForwardRefWithDisplayNameButton**
```tsx
export const ForwardRefWithDisplayNameButton = forwardRef(function (
  { className, variant, size, asChild = false, ...props }: ButtonProps,
  ref: ForwardedRef<HTMLButtonElement>,
) {/*...*/});

ForwardRefWithDisplayNameButton.displayName = 'MyForwardRefWithDisplayNameButton';
```

I then ran the build with the default options and then with react-docgen-typescript

# react-docgen
**NoForwardRefButton**
![image](https://github.com/storybookjs/storybook/assets/709773/466a4801-3fad-4a4d-88ea-d7fbe022236f)
**ForwardRefNoDisplayNameButton**
![image](https://github.com/storybookjs/storybook/assets/709773/747f1418-1a4e-438f-8147-4be59a64b314)
**ForwardRefWithDisplayNameButton**
![image](https://github.com/storybookjs/storybook/assets/709773/0528a65f-3141-46d3-9cb4-2e4231742c98)

# react-docgen-typescript
**NoForwardRefButton**
![image](https://github.com/storybookjs/storybook/assets/709773/da27e7c1-c13a-49b7-b60a-ac35dd7e2ebb)
**ForwardRefNoDisplayNameButton**
![image](https://github.com/storybookjs/storybook/assets/709773/1143a819-faea-40f4-aa46-ea071a01633a)
**ForwardRefWithDisplayNameButton**
![image](https://github.com/storybookjs/storybook/assets/709773/7df448dc-02ba-4ead-9d1b-3f04cf32c16b)

**Comment by andrewvo89** [comment]
> Hey @shilman
> 
> So things get a little weird... I setup three identical buttons components. The only differences are
> 
> **NoForwardRefButton**
> 
> ```tsx
> export const NoForwardRefButton = function (
>   { className, variant, size, asChild = false, ...props }: ButtonProps
> ) {/*...*/};
> ```
> 
> **ForwardRefNoDisplayNameButton**
> 
> ```tsx
> export const ForwardRefNoDisplayNameButton = forwardRef(function (
>   { className, variant, size, asChild = false, ...props }: ButtonProps,
>   ref: ForwardedRef<HTMLButtonElement>,
> ) {/*...*/});
> ```
> 
> **ForwardRefWithDisplayNameButton**
> 
> ```tsx
> export const ForwardRefWithDisplayNameButton = forwardRef(function (
>   { className, variant, size, asChild = false, ...props }: ButtonProps,
>   ref: ForwardedRef<HTMLButtonElement>,
> ) {/*...*/});
> 
> ForwardRefWithDisplayNameButton.displayName = 'MyForwardRefWithDisplayNameButton';
> ```
> 
> I then ran the build with the default options and then with react-docgen-typescript
> 
> # react-docgen
> **NoForwardRefButton** ![image](https://private-user-images.githubusercontent.com/709773/312033673-466a4801-3fad-4a4d-88ea-d7fbe022236f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTUxMjcsIm5iZiI6MTcxMDI5NDgyNywicGF0aCI6Ii83MDk3NzMvMzEyMDMzNjczLTQ2NmE0ODAxLTNmYWQtNGE0ZC04OGVhLWQ3ZmJlMDIyMjM2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwMTUzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYmQ0NDNmNDgwM2U5ZDZiYzA0YmE1YTU5MTliMDNjN2QzMjE3N2E4MGZjOTBmYzc1YzA3ZTk5NjFmMTU4ODkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oDknKok_wI6OmOrRPxnQACl3fxYhOul2TUZDEjGW480) **ForwardRefNoDisplayNameButton** ![image](https://private-user-images.githubusercontent.com/709773/312033790-747f1418-1a4e-438f-8147-4be59a64b314.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTUxMjcsIm5iZiI6MTcxMDI5NDgyNywicGF0aCI6Ii83MDk3NzMvMzEyMDMzNzkwLTc0N2YxNDE4LTFhNGUtNDM4Zi04MTQ3LTRiZTU5YTY0YjMxNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwMTUzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjM0MGUzZTY2YjRlODg4ZGUxNDViYzc3NGViODY2NjM0OGUzZmRiZWI4OTBiNGU0YzYxYjhkYjRjZmNkZDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.L9x0JeEu36nrQ07OuHWpHNeAO0jDl2Grog1LrpQ-ONE) **ForwardRefWithDisplayNameButton** ![image](https://private-user-images.githubusercontent.com/709773/312033864-0528a65f-3141-46d3-9cb4-2e4231742c98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTUxMjcsIm5iZiI6MTcxMDI5NDgyNywicGF0aCI6Ii83MDk3NzMvMzEyMDMzODY0LTA1MjhhNjVmLTMxNDEtNDZkMy05Y2I0LTJlNDIzMTc0MmM5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwMTUzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzVkMWQ5MGM1NmZhZjVjNzZhM2E5Yzk4MDc0NTBmOTk1OThjMDEyYzFhZGJhOThmZDcwZWM3Nzg2OTFhMjNlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.8uj_r3o6KXvOyS98n6sK2UGwB7MRE3W5goamgKD9hAI)
> 
> # react-docgen-typescript
> **NoForwardRefButton** ![image](https://private-user-images.githubusercontent.com/709773/312034260-da27e7c1-c13a-49b7-b60a-ac35dd7e2ebb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTUxMjcsIm5iZiI6MTcxMDI5NDgyNywicGF0aCI6Ii83MDk3NzMvMzEyMDM0MjYwLWRhMjdlN2MxLWMxM2EtNDliNy1iNjBhLWFjMzVkZDdlMmViYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwMTUzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjRiMDY0MTE1MjBlYjkwZjAxYTNmZmIxYTllMjM2NDRmNmM0NjdiN2ZmOTZjZDc1NGQ4ZjExMGQ1YTZhNzBiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.byBezYm9R9OZN5XL79jCizdzPvHAF1VoVEvz4Ns8wug) **ForwardRefNoDisplayNameButton** ![image](https://private-user-images.githubusercontent.com/709773/312034398-1143a819-faea-40f4-aa46-ea071a01633a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTUxMjcsIm5iZiI6MTcxMDI5NDgyNywicGF0aCI6Ii83MDk3NzMvMzEyMDM0Mzk4LTExNDNhODE5LWZhZWEtNDBmNC1hYTQ2LWVhMDcxYTAxNjMzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwMTUzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMDBmNDNkZmQ4OWU4NWRjZmI0NzhjNGNlMzc3NzcxNWJlM2MyZTZkZDA5NzU1MGU1ZWIzYWI5ZjhhZDAxMmEyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.os2WH__6xegX9MzG1-tkwhq57F4jsP0pthyJQrMl-Eg) **ForwardRefWithDisplayNameButton** ![image](https://private-user-images.githubusercontent.com/709773/312034514-7df448dc-02ba-4ead-9d1b-3f04cf32c16b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyOTUxMjcsIm5iZiI6MTcxMDI5NDgyNywicGF0aCI6Ii83MDk3NzMvMzEyMDM0NTE0LTdkZjQ0OGRjLTAyYmEtNGVhZC05ZDFiLTNmMDRjZjMyYzE2Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxM1QwMTUzNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMDk2ZjEwNWUxMTQ3YjIzYzAzMGMxY2YzYzExYTc3YThiOTM1NjYyYTE4MTJmZmYyYWRmOWU2MTIxMjdmNDY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wfMJjVxKcuvyFy1Bwoi4wzo7Fi6GmjcVxXilMSj8txM)
> 
> I just did a stackblitz to check if it's still the case in 8.1 alpha, and it is - https://stackblitz.com/edit/github-umceda?file=src%2Fstories%2FButton.tsx,.storybook%2Fmain.ts&preset=node

Can confirm this is happening on forwarded refs with `.displayName` set after upgrading to Storybook 8.

**Comment by tobeyboe** [comment]
Indeed, having the same issue after upgrading to Storybook 8 from rc.3

**Comment by janith-bl** [comment]
I have the same problem after migrating to 8.
Here is a simple example from storybook.
```
const meta: Meta<typeof Button> = {
  component: Button,
  //👇 Enables auto-generated documentation for the component story
  tags: ['autodocs'],
};

export default meta;
type Story = StoryObj<typeof Button>;

export const Primary: Story = {
  args: {
    variant: "default",
  },
};
```

Here it is the auto docs output inside the code section.
`
<[object Object] variant="default" />`

**Comment by tobeyboe** [comment]
It also fails using basic Next.js components, like <Image>

Modified Button with children prop:


```jsx
// More on writing stories with args: https://storybook.js.org/docs/writing-stories/args
export const Primary: Story = {
  args: {
    primary: true,
    label: "Button",
    children: (
      <Image
        src="https://via.placeholder.com/100x100"
        alt="Button Image"
        width={100}
        height={100}
      />
    ),
  },
};
```
Output
```jsx
<Button
  label="Button"
  onClick={() => {}}
  primary
>
  <[object Object]
    alt="Button Image"
    height={100}
    src="https://via.placeholder.com/100x100"
    width={100}
  />
</Button>
```

**Comment by Astarosa** [comment]
It's indeed the displayName that is causing the issue. Removing it works fine but there is obviously a bug or does the V8 implement it with custom Storybook logic based on the imported component name ? I've seen no motion of that in the migration guide.

It should not be the case because we must keep the posibility to add the displayName for devtools DOM support for example in some cases.

**Comment by yannbf** [comment]
Hey everyone! This issue is solved in #26566 and will be released soon. Thanks for your patience 🙏

**Comment by Nic-S** [comment]
> Hey everyone! This issue is solved in #26566 and will be released soon. Thanks for your patience 🙏

In all stories with arguments for controls, as in the example, we still have the problem after the update.

<img width="1047" alt="Screenshot 2024-03-19 alle 16 50 53" src="https://github.com/storybookjs/storybook/assets/18029425/57b70659-9994-4040-ab74-43c47b9f6a8d">

<img width="609" alt="Screenshot 2024-03-19 alle 16 53 03" src="https://github.com/storybookjs/storybook/assets/18029425/76a78ff1-b55d-4fbe-941e-dece597772a1">

**Comment by Astarosa** [comment]
> > Hey everyone! This issue is solved in #26566 and will be released soon. Thanks for your patience 🙏
> 
> In all stories with arguments for controls, as in the example, we still have the problem after the update.
> 
> <img alt="Screenshot 2024-03-19 alle 16 50 53" width="1047" src="https://private-user-images.githubusercontent.com/18029425/314133709-57b70659-9994-4040-ab74-43c47b9f6a8d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzc4OTEsIm5iZiI6MTcxMTM3NzU5MSwicGF0aCI6Ii8xODAyOTQyNS8zMTQxMzM3MDktNTdiNzA2NTktOTk5NC00MDQwLWFiNzQtNDNjNDdiOWY2YThkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0Mzk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI0YmJmM2RmYTQyYmU3NWFiNTQ5YTFkMTc0MjhlZTFlMjZmMzRjYzk1NTJjOGFjZDdmN2FmODhiOWU2OTNlZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.xJARJQUdJEOkeGZxWt-Ciq4eeYRewXjIU0gFgtISr_o"> <img alt="Screenshot 2024-03-19 alle 16 53 03" width="609" src="https://private-user-images.githubusercontent.com/18029425/314133759-76a78ff1-b55d-4fbe-941e-dece597772a1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNzc4OTEsIm5iZiI6MTcxMTM3NzU5MSwicGF0aCI6Ii8xODAyOTQyNS8zMTQxMzM3NTktNzZhNzhmZjEtYjU1ZC00ZmJlLTk0MWUtZGVjZTU5Nzc3MmExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDE0Mzk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmZGEwZjJlZjg5MDM0YWQzNTQ1YzFlY2M4MjhmYzIyZjRlMjgxZDE1NWZhMDJlYjBhY2E5MzQ3MjUxNzJkYzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iogiKgtCrM_9Oopn0xlQRlmu2cEySbL8p0OC-NOsPhM">

I confirm that we have the same issue using react-docgen-typescript now instead of `object object` we have the `React.FordwardRef`

**Comment by drwaky** [comment]
Hey It was happening to me also at v8.0.0, but I can confirm it is fixed now after updating to v.8.0.5.
Thanks! <3

**Comment by JReinhold** [comment]
@nandhiniG can you open a new issue with a minimal reproduction on the latest Storybook version? https://storybook.js.org/docs/contribute/how-to-reproduce
