### ISSUE TITLE
[Bug]: Default fonts are not found using v7 beta

### ISSUE THREAD

**Issue by adaliszk** [storybookjs/storybook#20938]
### Describe the bug

When using the beta branch with Vite, the fonts are not loaded:

![image](https://user-images.githubusercontent.com/5189131/216816861-e97af614-e69e-4e18-8cdf-b5f80004e428.png)

### To Reproduce

```shell
https://stackblitz.com/github/storybookjs/sandboxes/tree/next/lit-vite/default-ts/after-storybook
```

### System

```shell
Environment Info:
- System (WSL):
  - OS: Linux 5.15 Alpine Linux
  - CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
- Binaries:
  - Node: 18.12.1 - /usr/bin/node
  - Yarn: 3.3.1 - /usr/bin/yarn
  - npm: 9.1.2 - /usr/bin/npm
```

### Additional context

The error happens with the default template; no extra steps are needed to run the generated storybook files unchanged.

### Edits
- The issue seems to be happening on non-vite frameworks, so removed the Vite from the title.

**Comment by valentinpalkovic** [comment]
@ndelangen that`s interesting. I thought our implementation is completely framework independent. I personally don’t think it is related to the framework. I will investigate on Monday.

**Comment by adaliszk** [comment]
I have not debugged it all that deeply as it technically does not break the app, but interestingly the resources are trying to be loaded from `/sb-common-assets` while the fonts and the stylesheet in question are found under `/sb-manager-assets`. The log says that it gets mounted from `@storybook/manager/static` within the node_modules.

**Comment by sgammon** [comment]
i'm hitting this on a pure React app, so it probably doesn't have to do with Vite. i'm on `7.0.0-beta.42`.

**Comment by adaliszk** [comment]
Ah nice, I'll remove that from the title to make it less confusing 😉

**Comment by ndelangen** [comment]
I'll fix this today!

**Comment by alpual** [comment]
I'm getting a similar error on `7.0.0-beta.43`, as well as some other `404` errors that are totally breaking storybook (white screen of death). This all works for me on `7.0.0-beta.36`

I am using the @storybook/nextjs framework, so it is webpack5 under the hood, with `yarn@3.4.1` using pnp. So I'd agree with @sgammon, it's not Vite specific.

Because it's nextjs, I have `staticDirs: ["../public"]` set in my `main.ts`. My logs say:
```
Serving static files from ././.yarn/cache/@storybook-manager-npm-7.0.0-beta.43-1194501e04-809870274b.zip/node_modules/@storybook/manager/static at /sb-manager-assets
info => Serving static files from ././public at /
```
Interesting that it logs it as `././.yarn...` with the two `./`. I don't think that should break anything, but it's strange.

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.44 containing PR #20957 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by Pikachews** [comment]
I just upgraded my project from SB 6 to SB 7 `v7.0.0-beta.47` using the migration tool and am still seeing these errors.
![image](https://user-images.githubusercontent.com/5668416/218627388-d1812423-00b1-4726-af51-2e53d40c2f12.png)

**Comment by alpual** [comment]
I had some weird 404 errors loading webpack chunks that seemed to go away
when I set my dev tools to ignore the cache. Try clearing/ignoring your
cache and see if that helps.

**Comment by Pikachews** [comment]
> I had some weird 404 errors loading webpack chunks that seemed to go away when I set my dev tools to ignore the cache. Try clearing/ignoring your cache and see if that helps.

Tried it in incognito, cache disabled, still occurs.

**Comment by ndelangen** [comment]
Can you please supply a reproduction? then I can take a look today!

**Comment by Pikachews** [comment]
> Can you please supply a reproduction? then I can take a look today!

Huh, okay, that's interesting, it doesn't occur on the CRA template, but I can reproduce it on the Next.js (TS) template. No changes, just `npx sb@next sandbox`.

**Comment by ndelangen** [comment]
I'll investigate this today with @valentinpalkovic

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.49 containing PR #21119 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by adaliszk** [comment]
"Serving static files from" line is back to being executed before the "Starting manager..." :)

**Comment by ndelangen** [comment]
I'll remove those messages entirely, I think they aren't useful.

**Comment by adaliszk** [comment]
I prefer having them, but under debug so that it is possible to enable them when needed.

**Comment by shilman** [comment]
Olé!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-rc.0 containing PR #21137 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```
