### ISSUE TITLE
[Bug]:  7.0.0-beta.55 Module "@storybook/addon-actions/decorator" has no exported member 'withActions'

### ISSUE THREAD

**Issue by TarinAComer** [storybookjs/storybook#21308]
### Describe the bug

I am getting a typescript error when I try to `import { withActions } from "@storybook/addon-actions/decorator";` I'm trying to import it so that I can use it in my story as `decorators: [withActions],`.

### Additional context

While this technically runs properly locally there is highlighting for the error. Unfortunately when I go to deploy it the TS errors are being picked up during the build process causing it to error out.

**Comment by shilman** [comment]
I believe this has been fixed in 7.0. Please try upgrading to the latest prerelease.

Migration guide: https://storybook.js.org/migration-guides/7.0

**Comment by jattasNI** [comment]
I am still seeing this TypeScript error with version `7.0.0-rc.8`. I believe the problem is that `withActions` is [exported from `addons/actions/src/decorator.ts`](https://github.com/storybookjs/storybook/blob/d9d2fbb31406c0783f412a43e6e37b7bd0e6684d/code/addons/actions/src/decorator.ts#L54) but [is not exported from `addons/actions/src/index.ts`](https://github.com/storybookjs/storybook/blob/d9d2fbb31406c0783f412a43e6e37b7bd0e6684d/code/addons/actions/src/index.ts). Other decorators like `withLinks` [are exported from their `index.ts`](https://github.com/storybookjs/storybook/blob/d9d2fbb31406c0783f412a43e6e37b7bd0e6684d/code/addons/links/src/index.ts#L20).

**Comment by jattasNI** [comment]
I re-reported this in https://github.com/storybookjs/storybook/issues/21887 so that it would get more visibility than just a comment on a closed issue (I don't have permission to re-open this one).
