### ISSUE TITLE
[Bug]: Docs Rendering does not recover from errors thrown in React

### ISSUE THREAD

**Issue by tmeasday** [storybookjs/storybook#21440]
### Describe the bug

If you get an error in your MDX that comes from React (e.g. invalid value passed to `useOf`), and you fix it on HMR, all you get is a white screen.

### To Reproduce

1. `yarn start`
2. Add to `Introduction.mdx`:
```
import * as ButtonStories from './Button.stories';

<Meta of={ButtonStories} />
<Story of={ButtonStories} />
```
3. You see an error: 
![image](https://user-images.githubusercontent.com/132554/223317431-1081a0bb-aade-406f-8826-bd343f63ac67.png)

4. Change to `<Story of={ButtonStories.Primary} />`
5. You see a white screen, no error in console:

![image](https://user-images.githubusercontent.com/132554/223317479-e8f7e89b-de79-4025-a9d1-2fb2cb280c97.png)

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.0.0-beta.63 containing PR #21454 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by wintercounter** [comment]
Unfortunately, I'm still experiencing this issue using 7.0.6. Ever since I upgraded to v7 I constantly need to restart Storybook as it's not recovering after I make slight modifications to my components.

I'm using it with React+Webpack, CSF 3.

MDX:

```
import * as Stories from './button.stories';

<Meta title="Elements/Button" />
<Canvas of={Stories.Showcase} />
```

**Comment by tmeasday** [comment]
@wintercounter are the errors in the `.mdx` files or the components? I think you might want to open another issue for this with a reproduction.

**Comment by yannbf** [comment]
@tmeasday I found out how to reproduce it, it's quite simple actually, just add a `throw new Error('bla')` to a component


https://user-images.githubusercontent.com/1671563/233017345-63c314cb-f951-49a6-8990-95bc3286f794.mov

**Comment by wintercounter** [comment]
@tmeasday It's happening in docs. It's not consistent to reproduce it for me. Sometimes it doesn't do it for a longer period, sometimes on the first change. The error I get is exactly the same as OP (different from @yannbf's repro). It's an even bigger issue that many times it does this on error-free changes, like duplicating a simple `<div />`.

Error with stack:
```
Error
Invalid value passed to the 'of' prop. The value was resolved to a 'component or unknown' type but the only types for this block are: story.
- Did you pass a component to the 'of' prop when the block only supports a story or a meta?
- ... or vice versa?
- Did you pass a story, CSF file or meta to the 'of' prop that is not indexed, ie. is not targeted by the 'stories' globs in the main configuration?
Call Stack
 DocsContext.resolveOf
  runtime.mjs:82:4027
 useSourceProps
  vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:468:534
 useDeprecatedPreviewProps
  vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:488:1271
 Canvas
  vendors-node_modules_storybook_addon-docs_dist_chunk-PCJTTTQV_mjs.iframe.bundle.js:488:2202
 renderWithHooks
  vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ErrorOverlayEntry_js-node_mod-7ceeba.iframe.bundle.js:180051:18
 mountIndeterminateComponent
  vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ErrorOverlayEntry_js-node_mod-7ceeba.iframe.bundle.js:183815:13
 beginWork
  vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ErrorOverlayEntry_js-node_mod-7ceeba.iframe.bundle.js:185328:16
 HTMLUnknownElement.callCallback
  vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ErrorOverlayEntry_js-node_mod-7ceeba.iframe.bundle.js:167910:14
 Object.invokeGuardedCallbackDev
  vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ErrorOverlayEntry_js-node_mod-7ceeba.iframe.bundle.js:167959:16
 invokeGuardedCallback
  vendors-node_modules_pmmmwh_react-refresh-webpack-plugin_client_ErrorOverlayEntry_js-node_mod-7ceeba.iframe.bundle.js:168023:31
```

**Comment by wintercounter** [comment]
I've put a breakpoint where the error is. Here are the values around there when throwing the exception.

![image](https://user-images.githubusercontent.com/963776/233034627-3a903bb2-9576-427c-a03a-c310840d969a.png)
![image](https://user-images.githubusercontent.com/963776/233034804-64563fa8-d23f-4c62-a273-33baa72973e6.png)
![image](https://user-images.githubusercontent.com/963776/233035133-8a127858-5f5b-4e99-b68a-c26d38e8b34f.png)

**Comment by tmeasday** [comment]
@yannbf I guess that's a new issue that was never actually addressed by this PR or https://github.com/storybookjs/storybook/issues/22127#issuecomment-1513960902 -- shall we open a new issue? Probably easy to fix by changing the `showMain` here to unset the error?

https://github.com/storybookjs/storybook/blob/cded4cd4c6043564e6a79fad982260482c9889e9/code/ui/blocks/src/components/Story.tsx#L52-L55

**Comment by tmeasday** [comment]
@wintercounter Can you log what's actually in `moduleExportToType` when the error occurs? Is it empty or does it contain "old" story references?

It seems very odd though, IIRC the code path is that the HMR triggers a recreation of the `DocsContext` and a re-rendering of the `DocsContainer` (containing your MDX, and ultimately the `Story` block) with that new context. So I am not sure how the the `Story` block could end up talking to the old context.

It's not when you make >1 change at the same time?

> The error I get is exactly the same as OP 

To be clear the error in the OP is a legitimate error, this issue was about SB not *recovering* from that error, if you made a mistake and passed the wrong thing to `<Story of={}>`. But we can debug further here if you can't get a repro.

**Comment by tmeasday** [comment]
Maybe it is an interaction with React Refresh somehow. I wonder what component it is trying to re-render?

**Comment by tmeasday** [comment]
> It's there above (3rd picture): https://github.com/storybookjs/storybook/issues/21440#issuecomment-1514435396

Sorry, I was hoping to see the value of `this.exportToStory` at that breakpoint.

>  The issue I believe is that it was always expected that upon editing, Storybook gets the same module reference. I guess that's not the case and that's not handled.

But it doesn't always happen, right? I mean it's never happened to me before :)

**Comment by tmeasday** [comment]
Hmm, so `csfFiles` is set in the `prepare` function via `store.loadEntry`:

https://github.com/storybookjs/storybook/blob/07145b62ced5dc8539c83f9635185648c32f44df/code/lib/preview-api/src/modules/preview-web/render/MdxDocsRender.ts#L68

@wintercounter I wonder if you can put a logpoint in this function to see what the `entry` looks like on HMR: 

https://github.com/storybookjs/storybook/blob/07145b62ced5dc8539c83f9635185648c32f44df/code/lib/preview-api/src/modules/store/StoryStore.ts#L269-L270

We've had a user report an issue before where a docs entry somehow got turned into a story entry on HMR. I've no idea how that could happen but if that's happening here, I guess that'd lead to `storyImports` being `[]`?
