### ISSUE TITLE
[Bug]: Typescript argType inference is not working

### ISSUE THREAD

**Issue by AdisonCavani** [storybookjs/storybook#21801]
### Describe the bug

Bug: Storybook does not infer typescript types.

I'm using class-variance-authority in a similar way as shown in [this Next.js showcase](https://www.youtube.com/watch?v=T-Zv73yZ_QI).

![ss-1](https://user-images.githubusercontent.com/76855180/228331503-ab3ba74b-ec15-42c5-baab-5534e3477989.png)
![ss-2](https://user-images.githubusercontent.com/76855180/228331510-dea93fb8-4387-46b0-9d33-50ede5826e94.png)

### To Reproduce

Github: https://github.com/AdisonCavani/storybook-arg-types-bug
Published: https://stackblitz.com/github/AdisonCavani/storybook-arg-types-bug

### System

```shell
Environment Info:
  System:
    OS: Windows 10 10.0.22000
    CPU: (12) x64 AMD Ryzen 5 3600 6-Core Processor
  Binaries:
    Node: 18.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 9.5.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.22000.120.0), Chromium (111.0.1661.54)
  npmPackages:
    @storybook/addon-essentials: ^7.0.0-rc.8 => 7.0.0-rc.8
    @storybook/addon-interactions: ^7.0.0-rc.8 => 7.0.0-rc.8
    @storybook/addon-links: ^7.0.0-rc.8 => 7.0.0-rc.8
    @storybook/blocks: ^7.0.0-rc.8 => 7.0.0-rc.8
    @storybook/nextjs: ^7.0.0-rc.8 => 7.0.0-rc.8
    @storybook/react: ^7.0.0-rc.8 => 7.0.0-rc.8
    @storybook/testing-library: ^0.0.14-next.1 => 0.0.14-next.1
```

**Comment by shilman** [comment]
@kasperpeulen any idea what's going on here?

**Comment by kasperpeulen** [comment]
@shilman This is docgen issue right? The TS type is correct, but the controls don't show the variants.

My guess is that it is similar to the problems @ethriel3695 had with MUI. I would need to heavily debug react-docgen-typescript to get a clue what is going on in those cases.

**Comment by nuxcodes** [comment]
Same issue here. Works well in Storybook 6, but broken after migrating to version 7.

**Comment by kasperpeulen** [comment]
Might be a regression in react-docgen-typescript or something @shilman ?

**Comment by Xiphe** [comment]
I also don't get any automatic argType inference with `v7.0.2` was trying to replicate the [example of the docs](https://storybook.js.org/docs/react/writing-docs/autodocs#setup-automated-documentation) assuming that i could add JSDoc to the props but nothing I document at the `Button` component is showing up in the docs.

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.1 containing PR #22024 that references this issue. Upgrade today to the `@future` NPM tag to try it out!

```
npx sb@next upgrade --prerelease
```

**Comment by kiastorm** [comment]
I'm still getting this issue. I have a `variant` prop defined by cva, and it is being inferred incorrectly as a `string`, when it should be a string literal union, `primary | secondary | tertiary`.

Better year, even if I try to overrides this, it isn't applying. It is string no matter what I do - even if I explicitly defined `options`

**Comment by larevalos** [comment]
I'm also experiencing this issue. Default values defined in `args `within a story are appearing in the "Controls" section, rather than being set as defaults. Additionally, attempting to explicitly define these control types using `argTypes `doesn't resolve the problem.

Example:
```
const meta = {
  component: Avatar,
  argTypes: {
    src: { control: "text", description: "URL of the avatar image" },
    gravatarEmail: { control: "text", description: "Email to fetch the Gravatar image" },
    displayName: { control: "text", description: "Display name for the avatar" },
  },
} satisfies Meta<typeof Avatar>;
```
```

export const Missing = {
  args: {
    src: "https://gravatar.com/avatar/8b96a0522ab8ba375b18f37f70ea0a22?d=404",
    gravatarEmail: "missing.person@laingorourke.com.au",
    displayName: "Missing Person",
  },
  argTypes: {
    src: { control: "text", description: "URL of the avatar image" },
    gravatarEmail: { control: "text", description: "Email to fetch the Gravatar image" },
    displayName: { control: "text", description: "Display name for the avatar" },
  },
} satisfies Story;

```
![image](https://github.com/user-attachments/assets/df282fb1-f7d6-4e55-901e-8f3e187554c8)

My main.ts (see that I tried to use `babel-plugin-react-docgen`  and `react-docgen-typescript`  but same problem):

```

import type { StorybookConfig } from "@storybook/react-vite";
import path from "path";
import { mergeConfig } from "vite";
import svgrPlugin from "vite-plugin-svgr";

const nodeModules = path.resolve(__dirname, "../node_modules");

const config: StorybookConfig = {
  stories: ["../src/**/*.stories.@(js|jsx|mjs|ts|tsx)"],
  addons: [
    "@storybook/addon-toolbars", // Necessary for global types (e.g. core components theme)
    "@storybook/addon-essentials",
    "@storybook/addon-controls",
    "@storybook/addon-docs",
  ],
  framework: {
    name: "@storybook/react-vite",
    options: {},
  },
  async viteFinal(config) {
    return mergeConfig(config, {
      plugins: [svgrPlugin()],
      resolve: {
        alias: {
          react: `${nodeModules}/react`,
          "react-router-dom": `${nodeModules}/react-router-dom`,
        },
      },
    });
  },
  // babel: async (options) => ({
  //   ...options,
  //   presets: [...options.presets, "@babel/preset-env", "@babel/preset-react", "@babel/preset-typescript"],
  //   plugins: [
  //     ...options.plugins,
  //     [
  //       "babel-plugin-react-docgen",
  //       {
  //         exclude: ["**/index.ts", "**/*.d.ts", "**/*.test.ts", "**/*.test.tsx"],
  //       },
  //     ],
  //   ],
  // }),
  typescript: {
    reactDocgen: "react-docgen-typescript",
    reactDocgenTypescriptOptions: {
      shouldExtractLiteralValuesFromEnum: true,
      propFilter: (prop) => {
        if (prop.parent) {
          return !prop.parent.fileName.includes("node_modules");
        }
        return true;
      },
    },
  },
};

export default config;

```

**Comment by signor-pedro** [comment]
Same here and the bug still makes argType inference unusable. Is there any way we could get this working please?

**Comment by mkal1375** [comment]
In my case, I just needed to set the correct reactDocgen value for it:

```js 
const config = {
	stories: ['../app/**/*.stories.@(js|jsx|mjs|ts|tsx)', '../app/**/stories.ts', '../app/**/*.mdx'],
	addons: [
		'@storybook/addon-onboarding',
		'@storybook/addon-essentials',
		'@chromatic-com/storybook',
		'@storybook/addon-interactions',
	],
	typescript: {
		reactDocgen: 'react-docgen-typescript',
	},
	framework: {
		name: '@storybook/nextjs',
		options: {},
	},
	staticDirs: ['../public'],
};
```
