### ISSUE TITLE
[Bug]: Newly created svelte projects depending on svelte@3.58.0 have type errors

### ISSUE THREAD

**Issue by kasperpeulen** [storybookjs/storybook#21884]
### Describe the bug

Newly created svelte projects have type errors:

```
Type 'typeof Button__SvelteComponent_' is not assignable to type 'ComponentType<{ primary?: boolean | undefined; backgroundColor?: string | undefined; size?: "small" | "medium" | "large" | undefined; label?: string | undefined; }, any>'.
  Types of parameters 'options' and 'options' are incompatible.
    Type 'ComponentConstructorOptions<{ primary?: boolean | undefined; backgroundColor?: string | undefined; size?: "small" | "medium" | "large" | undefined; label?: string | undefined; }>' is not assignable to type 'Svelte2TsxComponentConstructorParameters<{ primary?: boolean | undefined; backgroundColor?: string | undefined; size?: "small" | "medium" | "large" | undefined; label?: string | undefined; }>'.
      Types of property 'target' are incompatible.
        Type 'Element | ShadowRoot | Document' is not assignable to type 'Element | ShadowRoot'.
          Type 'Document' is not assignable to type 'Element | ShadowRoot'.
            Type 'Document' is missing the following properties from type 'ShadowRoot': delegatesFocus, host, mode, slotAssignment, innerHTML
```

The problem occurs because svelte changed the component type in v3.58.0:
https://github.com/sveltejs/svelte/commit/d49b568019fbd6578ceba72de68d0790db909bee

But the autogenerated types from svelte files are not (yet) matching that.

**Comment by shilman** [comment]
Do we need to open an issue on Svelte @kasperpeulen ? Or is there anything we can do on our side?

**Comment by kasperpeulen** [comment]
The issue is solved upstream, but not yet released:
https://github.com/sveltejs/language-tools/pull/1968

**Comment by CarlAmbroselli** [comment]
@kasperpeulen This has merged, but the issue still persists unfortunately.

**Comment by CarlAmbroselli** [comment]
@kasperpeulen This has merged, but the issue still persists unfortunately.

**Comment by kasperpeulen** [comment]
Colsing, because I can not reproduce this anymore.
