### ISSUE TITLE
[Bug]: BigInt cannot be serialized as property

### ISSUE THREAD

**Issue by fdc-viktor-luft** [storybookjs/storybook#22452]
### Describe the bug

When using the addons panel components are not working using BigInt as property values. Below is the stack.

```
TypeError: Do not know how to serialize a BigInt
    at JSON.stringify (<anonymous>)
    at generateAttributeSource (config.mjs:36:12621)
    at config.mjs:36:12296
    at Array.map (<anonymous>)
    at generateAttributesSource (config.mjs:36:12287)
    at generateComponentSource (config.mjs:37:754)
    at config.mjs:41:143
    at Array.map (<anonymous>)
    at generateSource (config.mjs:41:131)
    at sourceDecorator (config.mjs:43:1050)
e
```

**Comment by fdc-viktor-luft** [comment]
Workaround:

```js
BigInt.prototype.toJSON = function () {
    return this.toString();
};
```

But this causes the action to serialize wrongly the BigInt which was working without that above workaround.

**Comment by shilman** [comment]
Do you a have a reproduction repo you can share? If not, can you create one? Go to https://storybook.new or see [repro docs](https://storybook.js.org/docs/react/contribute/how-to-reproduce). Thank you! 🙏

**Comment by fdc-viktor-luft** [comment]
Here you go: https://stackblitz.com/edit/github-v5vcsq?file=src/stories/Button.vue

**Comment by fdc-viktor-luft** [comment]
@shilman Any updates on this?

**Comment by gagarin55** [comment]
Hi, any updates ?

**Comment by bgentry** [comment]
Ran into this while setting up Storybook for the first time on a brand new project. It would be great to get #25309 over the finish line to remove this hurdle for newcomers like me. @valentinpalkovic is there anything that can be done to help do so? I  am happy to help test a fix if needed, although it looks like that PR is mainly missing unit tests.

**Comment by valentinpalkovic** [comment]
I will try to get this over the finish line during our 8.0 RC phase :)

**Comment by fdc-viktor-luft** [comment]
@valentinpalkovic Was it fixed in v8 now? Should I check myself?

**Comment by valentinpalkovic** [comment]
It isn't fixed yet. I have a PR open but it doesn't have a high priority currently to finish it.

**Comment by fdc-viktor-luft** [comment]
Thank you for the update :+1:

**Comment by marcinretecki** [comment]
How about just using the same solution that wagmi.sh is using? It should be drop-in
https://wagmi.sh/core/guides/faq#bigint-serialization

Whole crypto front end dev community is waiting for this update.

**Comment by tuler** [comment]
Any hope for this to be fixed?
