### ISSUE TITLE
[Bug]: Error: Storybook 7.0+ doesn't support react-scripts@<5.0.0.

### ISSUE THREAD

**Issue by rohanarihant** [storybookjs/storybook#22794]
### Describe the bug

I am trying to intialize storybook to my React Project, which was created with create-react-app
I updated the react-scripts version to 5.0.1 and my React version is 18.2.0, node 16.20.1.
but still I am facing this issue.
**Error: Storybook 7.0+ doesn't support react-scripts@<5.0.0.**

can anyone please let me know how to fix this and intall storybook?
 

### System

```shell
mac os
```

**Comment by Sidnioulz** [comment]
The code that checks this is very explicit and simple, it checks the `react-script` package's version.

I would suggest you run `yarn why react-scripts` to make double sure this package is resolved to version 5 and not 4. I would also make sure you don't have a mix of `npm` and `yarn` dependencies.

**Comment by felixmokross** [comment]
I encounter the same issue. We are on react-scripts@5.0.1. 
I also ran `npm-why react-scripts`, but there is no other version of that package listed.

**Comment by felixmokross** [comment]
OK, I found a workaround. I noticed that this code only checks `dependencies`, but not he `devDependencies`: https://github.com/storybookjs/storybook/blob/v7.0.17/code/lib/cli/src/generators/REACT_SCRIPTS/index.ts

In our project, we had `react-scripts` in `devDependencies` (I think this was the default in the past, might no be this way for newer CRA projects). I temporarily moved `react-scripts` it into `dependencies` and the storybook init worked fine.

I still think storybook should check `devDependencies` too though.

**Comment by valentinpalkovic** [comment]
@felixmokross Would you like to open a PR to fix this. It sounds like being a simple fix.

**Comment by felixmokross** [comment]
Thanks, @Sidnioulz! For me, it would take some lead time as I am not familiar with the repo.

**Comment by WenLonG12345** [comment]
I have the same issue here. Looking forward for a fix! :)

**Comment by valentinpalkovic** [comment]
Fixed by https://github.com/storybookjs/storybook/pull/22642 and released in [v7.1.0-alpha.36](https://github.com/storybookjs/storybook/releases/tag/v7.1.0-alpha.36)

**Comment by chadhiremysub** [comment]
I am still having issues with this! I have react-scripts version 5.0.1, react version 18.2.0, and node version 16.20.1.

I have react-scripts in my dev-dependencies. Is this an issue?

<img width="1512" alt="image" src="https://github.com/storybookjs/storybook/assets/117949150/850ecc4c-71b6-4c2d-99b9-c100e43db125">
