### ISSUE TITLE
[Bug]: @types/jest is updated to 29.6.1 even if version in package.json is lower

### ISSUE THREAD

**Issue by valentinbourqui** [storybookjs/storybook#23636]
### Describe the bug

The package @types/jest is updated inside node_module file to 29.6.1 even if version in package.json is lower like 27.*. 

This problem breaks the compatibility of storybook with Stencil which is not compatible with version 29.X and more globally breaks probably the compatibility with Jest if you don't have version 29.x installed. 

### To Reproduce

Just run : npm install  @types/jest@27.5.1 jest@27.5.1 jest-cli@27.5.1  @storybook/addon-essentials

### System

```shell
Environment Info:

  System:
    OS: macOS 13.2
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 18.16.1 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.5.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Edge: 113.0.1774.57
    Safari: 16.3
  npmPackages:
    @storybook/addon-docs: ^7.1.1 => 7.1.1
    @storybook/addon-links: ^7.1.1 => 7.1.1
    @storybook/addon-viewport: ^7.1.1 => 7.1.1
    @storybook/html: ^7.1.1 => 7.1.1
    @storybook/html-webpack5: ^7.1.1 => 7.1.1
```

### Additional context

This problem happen just with some addons like @storybook/addon-essentials.

**Comment by valentinpalkovic** [comment]
Hi @valentinbourqui!

Could you please try out v7.2.0-rc.0 of Storybook? It should be fixed in the latest prerelease. We will provide a proper fix as a minor release next week.

**Comment by valentinbourqui** [comment]
Problem is still present even with "@storybook/addon-essentials": "^7.2.0-rc.0"
