### ISSUE TITLE
[Bug]:  TypeError: Cannot read properties of undefined (reading 'count') with onClick action

### ISSUE THREAD

**Issue by magic-m-johnson** [storybookjs/storybook#23787]
### Describe the bug

<img width="710" alt="image" src="https://github.com/storybookjs/storybook/assets/27994580/f4a6ae77-277a-4ae4-b763-47768372c5da">

<img width="431" alt="image" src="https://github.com/storybookjs/storybook/assets/27994580/5a6db055-4489-4733-aaeb-d477e2cccc60">

### To Reproduce

just setup a react app with webpack or vite, then install storybook and create a story for a single button component

### System

```shell
Environment Info:

  System:
    OS: macOS 13.5
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 18.13.0 - ~/.nodenv/versions/18.13.0/bin/node
    Yarn: 1.22.19 - ~/.nodenv/versions/18.13.0/bin/yarn
    npm: 9.6.7 - ~/.nodenv/versions/18.13.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.170
    Safari: 16.6
  npmPackages:
    @storybook/addon-essentials: ^7.2.1 => 7.2.1
    @storybook/addon-interactions: ^7.2.1 => 7.2.1
    @storybook/addon-links: ^7.2.1 => 7.2.1
    @storybook/addon-onboarding: ^1.0.8 => 1.0.8
    @storybook/blocks: ^7.2.1 => 7.2.1
    @storybook/react: ^7.2.1 => 7.2.1
    @storybook/react-webpack5: ^7.2.1 => 7.2.1
    @storybook/testing-library: ^0.2.0 => 0.2.0
```

**Comment by sthiepaan** [comment]
I have the same error, here are my remarks:
- When I reload page at _Story1_, the error occur and _Actions_ are not collected
- When I change from _Story1_ to _Story2_, the error is gone and _Actions_ are collected
- When I change back from _Story2_ to _Story1_, the error is not appearing anymore and _Actions_ are collected

So - from my understanding - it means, the error happens on _page load_ and not when we re-render 🤔

**Comment by magic-m-johnson** [comment]
> I have the same error, here are my remarks:
> 
> * When I reload page at _Story1_, the error occur and _Actions_ are not collected
> * When I change from _Story1_ to _Story2_, the error is gone and _Actions_ are collected
> * When I change back from _Story2_ to _Story1_, the error is not appearing anymore and _Actions_ are collected
> 
> So - from my understanding - it means, the error happens on _page load_ and not when we re-render 🤔

for it happens whenever I trigger the assigned action, e.g. click the button.

**Comment by austinm911** [comment]
I get this error as well

```ts
import type { Meta, StoryObj } from '@storybook/react'
import { Loader2, Mail } from 'lucide-react'

import { Button } from './button'

const meta: Meta<typeof Button> = {
    component: Button,
    tags: ['autodocs'],
    parameters: {
        layout: 'centered',
    },
    argTypes: { onClick: { action: 'clicked' } },
}
export default meta

type Story = StoryObj<typeof Button>

export const Base: Story = {
	render: args => <Button {...args}>Button</Button>,
	args: {},
}
```

This is the component: https://github.com/shadcn-ui/ui/blob/3c9f7ca0e20638bf75833ef920f9b23f5d97bc71/apps/www/registry/default/ui/button.tsx

Error
<img width="1299" alt="image" src="https://github.com/storybookjs/storybook/assets/31991302/eb3afc64-664e-4219-8087-5aabfcb95609">


Doesn't help using `argTypes: { onClick: { control: false } },`

**Comment by chloe-spendesk** [comment]
We're facing the same issue : `Cannot read properties of undefined (reading 'count')` when we click on a checkbox before clicking in any other field on the page.

**Comment by laverdet** [comment]
Same, downgrading `@storybook/addon-essentials` to 7.1.1 fixes it.

**Comment by Spielboerg** [comment]
Related/duplicate: https://github.com/storybookjs/storybook/issues/23741

**Comment by jasosims** [comment]
> Same, downgrading `@storybook/addon-essentials` to 7.1.1 fixes it.

Yeah, that works for now. Unfortunately it's necessary to downgrade all of Storybook to 7.1.1 and not just this addon. Using Storybook 7.2.0 or newer with `@storybook/addon-essentials` 7.1.1 causes a different error instead (the one described in #23782).

**Comment by kasperpeulen** [comment]
Fixed in latest alpha release by https://github.com/storybookjs/storybook/pull/23804

**Comment by jasosims** [comment]
Just updated to Storybook 7.4.0 and I'm still seeing this error. After a manual reload of Storybook, any action that's tracked by the Actions addon starts throwing this error again, until I switch to a different story. Exact same problem as before.

**Comment by herzaso** [comment]
This is still happening in 7.4.1 as well

**Comment by bennylame** [comment]
Can confirm that it is still happening in 7.4.1

**Comment by IanVS** [comment]
@kasperpeulen looks like this is still broken, I'm observing it in my project as well.

**Comment by ndelangen** [comment]
Is there a reproduction repo anyone could share?

**Comment by IanVS** [comment]
@ndelangen here's what I learned when trying to reproduce:

- Still occurs in 7.5.0-alpha.2
- Only happens when the interactions tab is focused, and the page is reloaded

Here's a repro: https://stackblitz.com/edit/github-iz1qiv?file=src%2Fstories%2FButton.stories.ts

Because you can't reload the page in stackblitz, you'll need to download the project and run locally.

**Comment by ndelangen** [comment]
@IanVS 
- I downloaded the template
- I unzipped it
- I deleted the npm lockfile
- I used yarn to install
- I used yarn to start storybook in dev mode
- I navigated to the second page story (logged-in).
- I observed the play function working
- I observed the interaction tab updating, showing 1 step
- I opened the browser console
- I refresh the page
- I'm not seeing the error anywhere.
- I refresh again, still no error.

When I look at the lockfile I removed it does have multiple versions of storybook for some reason!:
![Screenshot 2023-09-19 at 17 37 41](https://github.com/storybookjs/storybook/assets/3070389/1959e7f4-09f2-4e2e-9aab-d890294e2ff2)

**Comment by IanVS** [comment]
I think the package-lock.json was created by storybook.new / stackblitz, which runs `npm install && yarn storybook` when it starts up.  I'm not sure how to configure that...

So, I tried this again as well on a fresh laptop after re-downloading the zip file.

- I deleted the package-lock.json
- `yarn install`
- `yarn storybook`
- visit the button primary story
- there are no errors in console, and there is one logged action
- <img width="1406" alt="image" src="https://github.com/storybookjs/storybook/assets/4616705/e42d70e9-6eeb-434d-ad03-dc62368d90f8"/>
- view the interactions tab
- refresh the page
- no actions are logged, and there's an error in the console
- <img width="1063" alt="image" src="https://github.com/storybookjs/storybook/assets/4616705/0925b916-ca93-4241-9c61-ff8c0d39f1b8">

**Comment by ndelangen** [comment]
> I navigated to the second page story (logged-in).

I guess i should navigate to the button story instead.. I didn't know it had a play function.

**Comment by IanVS** [comment]
I added one for this reproduction.
