### ISSUE TITLE
Storybook fails to index .story files in 7.3.0

### ISSUE THREAD

**Issue by yannbf** [storybookjs/storybook#23850]
Upgraded to Storybook 7.3.0, and all my component stories now fail to indexed, crashing the storybook build. Related to this PR? 

```
WARN 🚨 Unable to index files:
WARN - ./src/components/Anchor/Anchor.story.tsx: Invariant failed: No matching indexer found for /Project/Frontend/src/components/Anchor/Anchor.story.tsx
...
```

My `main.ts`:

```ts
import { StorybookConfig } from '@storybook/react-vite';
import { projectConfig } from '../src/project-config';

// Set an env variable, so we can detect Storybook inside other tools (Mainly Tailwind)
process.env.STORYBOOK = 'true';

const config: StorybookConfig = {
  framework: '@storybook/react-vite',
  staticDirs: [
    '../public',
    {
      // Move the favicon.svg to the root, so it can be found by the browser
      from: '../public/assets/favicon.svg',
      to: '/favicon.svg',
    },
  ],
  stories: [
    {
      directory: '../docs',
      titlePrefix: 'Docs',
      files: '**/*.mdx',
    },
    '../src/**/*.@(story|stories).@(js|jsx|ts|tsx)',
  ],
  addons: [
    '@storybook/addon-links',
    {
      name: '@storybook/addon-essentials',
      options: {
        backgrounds: false,
      },
    },
    '@storybook/addon-a11y',
    '@storybook/addon-interactions',
    '@storybook/addon-designs',
  ],
  core: {
    builder: '@storybook/builder-vite',
  },

};

export default config;

```

_Originally posted by @thebuilder in https://github.com/storybookjs/storybook/issues/23691#issuecomment-1679079454_

**Comment by shilman** [comment]
Fixed in https://github.com/storybookjs/storybook/releases/tag/v7.3.1

**Comment by ro-ka** [comment]
Trying to upgrade to v7.3.2 and I get the same error. It worked fine with <= v7.2.

This is my `.storybook/main.js`:

```js
module.exports = {
  stories: [
    '../src/**/story.tsx',
    '../src/**/*.story.tsx',
    '../src/**/*/*.mdx',
  ],
  addons: [
    '@storybook/addon-essentials',
    '@storybook/addon-a11y',
    '@storybook/addon-interactions',
  ],
  framework: {
    name: '@storybook/react-vite',
    options: {
      fastRefresh: true,
      strictMode: true,
    },
  },
  docs: {
    autodocs: true,
  },
};
```

**Comment by ro-ka** [comment]
@yannbf @shilman Not sure if I shall open a new issue or if this is actually not fully resolved. Thanks for your work on this!

**Comment by ro-ka** [comment]
It’s fixed for me with v7.4. Thanks a lot!
