### ISSUE TITLE
[Bug]: After upgrade to Storybook `7.4.4` has bug, browser blocked

### ISSUE THREAD

**Issue by eneaaliko0** [storybookjs/storybook#24275]
### Describe the bug

<img width="744" alt="Screenshot 2023-09-22 at 3 48 35 PM" src="https://github.com/storybookjs/storybook/assets/37410892/740a0053-634d-4935-b531-7c9046c46ce8">

### System

```bash
System:
    OS: macOS 13.5.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 16.15.0 - ~/node_modules/.bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 8.5.5 - ~/.nvm/versions/node/v16.15.0/bin/npm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.6
```

### Additional context

    "@vitejs/plugin-react": "^3.1.0",
    "@storybook/builder-vite": "^7.4.4",
    "@rollup/plugin-commonjs": "^22.0.0",
    "@storybook/client-api": "^7.4.4",
    "@storybook/addon-actions": "^7.4.4",
    "@storybook/addon-essentials": "^7.4.2",
    "@storybook/addon-links": "^7.4.4",
    "@storybook/addon-styling": "^1.3.7",
    "@storybook/addons": "^7.4.4",
    "@storybook/mdx1-csf": "^1.0.0",
    "@storybook/react": "^7.4.4",
    "@storybook/cli": "^7.4.4",
    "@storybook/react-vite": "^7.4.4",

**Comment by eneaaliko0** [comment]
maybe, this is the problem [in last merge](https://github.com/storybookjs/storybook/pull/24237/files#diff-8e32cce628af3c63ddc47847b2c89d91619bd9ea0ef43b5e2045fbbc70bf4fb8L408)

**Comment by DanielPower** [comment]
I'm experiencing a likely related issue where the first component load works, but switching to another component results in the browser hanging indefinitely. This started after upgrading to 7.4.4

**Comment by mnicholstamu** [comment]
I am running into the same issues. We moved back to Storybook 4.4.3 for the time being.

**Comment by ritterb82** [comment]
+1, Seeing same issues.

**Comment by mnicholstamu** [comment]
> +1, Seeing same issues.
> 
> For me, would work fine with:
> 
> `addons: ['@storybook/preset-create-react-app', '@storybook/addon-essentials'],`
> 
> But as soon as I added `@storybook/addon-a11y`, it would break.
> 
> `addons: ['@storybook/preset-create-react-app', '@storybook/addon-essentials', '@storybook/addon-a11y']`

I wonder if we are all using the a11y addon... I just removed it from our `7.4.4` branch and it's working fine now.

**Comment by joelpierre** [comment]
Happening to me as well. Having to revert back to previous version 😢

**Comment by BorisZubchenko** [comment]
Same, removing `@storybook/addon-themes` helps.

**Comment by liuxian496** [comment]
+1, Seeing same issues. This is “main.ts” in my project.
`
import type { StorybookConfig } from "@storybook/react-webpack5";
const config: StorybookConfig = {
  stories: ["../src/**/*.mdx", "../src/**/*.stories.@(js|jsx|ts|tsx)"],
  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-interactions",
    {
      name: '@storybook/preset-create-react-app',
      options: {
        craOverrides: {
          fileLoaderExcludes: ['less']
        }
      }
    },
    {
      name: '@storybook/addon-coverage',
      options: {
        istanbul: {
          include: ['**'],
          exclude: ['**/src/test/**'],
          excludeNodeModules: true,
        },
      },
    },
    {
      name: '@storybook/addon-styling',
      options: {
        less: {
          // Require your Less preprocessor here
          implementation: require('less')
        }
      }
    }, "@storybook/addon-mdx-gfm"],
  framework: {
    name: "@storybook/react-webpack5",
    options: {}
  },
  docs: {
    autodocs: 'tag'
  },
  staticDirs: ["../public"]
};
export default config;
`

**Comment by mfc-admin** [comment]
> +1, Seeing same issues.
> 
> For me, would work fine with:
> 
> `addons: ['@storybook/preset-create-react-app', '@storybook/addon-essentials'],`
> 
> But as soon as I added `@storybook/addon-a11y`, it would break.
> 
> `addons: ['@storybook/preset-create-react-app', '@storybook/addon-essentials', '@storybook/addon-a11y']`

Yes, got the same error when adding addon-a11y.

**Comment by yannbf** [comment]
Hey everyone! Thank you so much for reporting this issue, and especially @eneaaliko0 for spotting where bug got introduced. We will be releasing a fix as soon as we can.

**Comment by eneaaliko0** [comment]
> Hey everyone! Thank you so much for reporting this issue, and especially @eneaaliko0 for spotting where bug got introduced. We will be releasing a fix as soon as we can.

Thank you so much for your support @yannbf ! 🙏

**Comment by shilman** [comment]
We're having some problems getting a release out, so until we do please pin your dependency to `7.4.3`. Thank you for your patience!

**Comment by shilman** [comment]
Ok hopefully fixed in https://github.com/storybookjs/storybook/releases/tag/v7.4.5. Thanks @yannbf !

**Comment by Kosai106** [comment]
@shilman I just spun up a new Storybook and I'm still having this issue on `7.4.5` as soon as I add `addon-a11y` 😢
