### ISSUE TITLE
[Bug]: sveltekit $app/environment is missing

### ISSUE THREAD

**Issue by tomfrit** [storybookjs/storybook#25133]
### Describe the bug

Even though the readme says that $app/enviroment mock is now supported, the build fails with the message `Failed to load url /node_modules/@storybook/sveltekit/src/mocks/app/environment` since the file does not exist

### To Reproduce

Create a stock Storyboard/sveltekit project and use `import { browser } from "$app/environment";` in a module used in a story

### System

```bash
Storybook Environment Info:

  System:
    OS: Linux 6.6 openSUSE Tumbleweed 20231128
    CPU: (8) x64 AMD Ryzen 7 4700U with Radeon Graphics
    Shell: 5.2.21 - /bin/bash
  Binaries:
    Node: 18.15.0 - ~/.nvm/versions/node/v18.15.0/bin/node
    Yarn: 4.0.2 - /usr/bin/yarn <----- active
    npm: 9.5.0 - ~/.nvm/versions/node/v18.15.0/bin/npm
  Browsers:
    Chrome: 119.0.6045.199
  npmPackages:
    @storybook/addon-essentials: ^7.6.3 => 7.6.3 
    @storybook/addon-interactions: ^7.6.3 => 7.6.3 
    @storybook/addon-links: ^7.6.3 => 7.6.3 
    @storybook/blocks: ^7.6.3 => 7.6.3 
    @storybook/svelte: ^7.6.3 => 7.6.3 
    @storybook/sveltekit: ^7.6.3 => 7.6.3 
    @storybook/test: ^7.6.3 => 7.6.3 
    eslint-plugin-storybook: ^0.6.15 => 0.6.15 
    storybook: ^7.6.3 => 7.6.3
```

### Additional context

I tried adding my own app/environment and resolving it as an alias but couldn't get it to work:

**.storybook/main.ts**
```
async viteFinal(config) {    
    return mergeConfig(config, {    
            resolve: {       
                alias: [{       
                    find: "@app",    
                    replacement: "../.storybook/app"    
                }]    
           }     
    });    
}

**Comment by HaydenBruin** [comment]
I'm also having this same issue.

If I create a file called node_modules/@storybook/sveltekit/src/mocks/app/environment.ts with the following exports it works fine.

`export const browser = true;
export const dev = false;
export const version = 'storybook';
`

**Comment by jamesscottbrown** [comment]
I'm experiencing what I think is the same issue, after upgrading `@storybook/svelte`/`@storybook/sveltekit`/`@storybook/svelte-vite` etc. from `7.4.6` to `7.6.4`.

I have some Svelete components that import ` $app/paths` or `$app/environment`; I have stories that import these components to show how they are used.

Importing them into a story now results in errors like:

```
[vite:load-fallback] Could not load /home/runner/work/ldn-viz-tools/ldn-viz-tools/node_modules/@storybook/sveltekit/src/mocks/app/paths (imported by ../../packages/ui/src/lib/header/NavLink.svelte): ENOENT: no such file or directory, open '/home/runner/work/ldn-viz-tools/ldn-viz-tools/node_modules/@storybook/sveltekit/src/mocks/app/paths'
```

**Comment by shilman** [comment]
Should be fixed in 7.6.5! Please let me know if not

**Comment by fhaertig** [comment]
Hi,

i still experience this bug, I'm using version 7.6.13:

`13:59:33 [vite] Internal server error: Failed to resolve import "$app/environment" from "../src/components/modules/product/Price.svelte". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/.../src/components/modules/product/Price.svelte:2:26
  21 |
  22 |  import "svelte/internal/disclose-version";
  23 |  import { browser } from "$app/environment";
     |                           ^
  24 |  const file = "Users/.../codebase/closed/closed-storefront/apps/web/src/components/modules/product/Price.svelte";
  25 |
      at formatError (file:///Users/.../codebase/closed/closed-storefront/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:63765:46)
      at TransformContext.error (file:///Users/.../codebase/closed/closed-storefront/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:63759:19)
      at normalizeUrl (file:///Users/.../codebase/closed/closed-storefront/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:62034:33)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async file:///Users/.../codebase/closed/closed-storefront/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:62188:47
      at async Promise.all (index 2)
      at async TransformContext.transform (file:///Users/.../codebase/closed/closed-storefront/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:62109:13)
      at async Object.transform (file:///Users/.../codebase/closed/closed-storefront/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:64060:30)
      at async loadAndTransform (file:///Users/.../codebase/closed/closed-storefront/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:49741:29)
13:59:33 [vite] Pre-transform error: Failed to resolve import "$app/environment" from "../web/src/components/modules/product/Price.svelte". Does the file exist?`


This is my package.json:

`{
  "name": "workshop",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "storybook dev -p 6006",
    "build": "storybook build"
  },
  "dependencies": {
    "@closed/storefront": "*"
  },
  "devDependencies": {
    "@storybook/addon-essentials": "^7.6.13",
    "@storybook/addon-interactions": "^7.6.13",
    "@storybook/addon-links": "^7.6.13",
    "@storybook/addon-svelte-csf": "^4.1.0",
    "@storybook/blocks": "^7.6.13",
    "@storybook/sveltekit": "^7.6.13",
    "@storybook/test": "^7.6.13",
    "@sveltejs/kit": "^1.20.5",
    "@sveltejs/vite-plugin-svelte": "^3.0.1",
    "autoprefixer": "^10.4.16",
    "postcss": "^8.4.32",
    "postcss-load-config": "^5.0.2",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "storybook": "^7.6.13",
    "storybook-addon-sass-postcss": "^0.1.3",
    "svelte": "^4.0.5",
    "svelte-check": "^3.6.2",
    "tailwindcss": "^3.3.6",
    "tslib": "^2.6.2",
    "typescript": "^5.2.2",
    "vite": "^4.4.2"
  }
}`
