### ISSUE TITLE
[Bug]: Build fails with "@vitest/mocker" resolution error in Docker when Vitest is not used

### ISSUE THREAD

**Issue by serenaqchen** [storybookjs/storybook#33306]
### Describe the bug

When building a Next.js application with Storybook 10.1.4 in a Docker environment, the build process fails with module resolution errors for @vitest/mocker and @vitest/mocker/browser. This occurs even though:
- Vitest is not installed or used in the project
- No test-related Storybook addons are configured
- The mocker runtime functionality is not needed

This is how my `main.ts` looks like:
```
// .storybook/main.ts
import type { StorybookConfig } from 'storybook/internal/types';

const config: StorybookConfig = {
  stories: ['../src/__stories__/**/*.stories.tsx'],
  addons: ['@storybook/addon-a11y', '@storybook/addon-docs'],
  framework: '@storybook/nextjs',
};

module.exports = config;
```
This is the error I am encountering when I try to build storybook in docker: 
```
✘ [ERROR] Could not resolve "@vitest/mocker"

    node_modules/storybook/assets/server/mocker-runtime.template.js:1:31:
      1 │ import { MockerRegistry } from '@vitest/mocker';
        ╵                                ~~~~~~~~~~~~~~~~

  You can mark the path "@vitest/mocker" as external to exclude it from the bundle, 
  which will remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@vitest/mocker/browser"

    node_modules/storybook/assets/server/mocker-runtime.template.js:2:50:
      2 │ ... ModuleMocker, createCompilerHints } from '@vitest/mocker/browser';
        ╵                                              ~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@vitest/mocker/browser" as external to exclude it from the bundle, 
  which will remove this error and leave the unresolved path in the bundle.
```
The build error shows that node_modules/storybook/assets/server/mocker-runtime.template.js is being processed during the build, causing it to attempt to resolve Vitest dependencies that don't exist.

My current workaround is to install `@vitest/mocker` and `vite`, but ideally I would not need to install these since I'm not testing my storybook components. 

### Reproduction link

No link for this.

### Reproduction steps

1. Create a Next.js project with Storybook 10.1.4
2. Configure Storybook with basic addons (no test addons)
3. Build the application in a Docker container
4. Observe the build failure

### System

```bash
│  Storybook Environment Info:
│

│  System:
│  OS: macOS 26.1
│  CPU: (12) arm64 Apple M2 Pro
│  Shell: 5.9 - /bin/zsh
│  Binaries:
│  Node: 22.18.0 
│  Yarn: 1.22.22
│  npm: 10.9.3 
│  pnpm: 8.15.2 - /opt/homebrew/bin/pnpm
│  Browsers:
│  Chrome: 143.0.7499.41
│  Safari: 26.1
│  npmPackages:
│  @storybook/addon-a11y: 10.1.4 => 10.1.4
│  @storybook/addon-docs: 10.1.4 => 10.1.4
│  @storybook/nextjs: 10.1.4 => 10.1.4
│  storybook: 10.1.4 => 10.1.4
```

**Comment by valentinpalkovic** [comment]
Hi @serenaqchen 

Could you please try out the following canary release and report back whether it fixes the issue, and you can safely remove `@vitest/mocker` and `vite` from the list of dependencies?:
`0.0.0-pr-33315-sha-68608956`

`npx storybook@0.0.0-pr-33315-sha-68608956 upgrade`

**Comment by serenaqchen** [comment]
Hi @valentinpalkovic, I tried out the canary release and still ran into the same issue. 

```
┌  Building storybook v0.0.0-pr-33315-sha-68608956
│
◇  Cleaning outputDir: storybook-static
│
◇  Loading presets
│
◇  Building manager..
│
▲  unable to find package.json for @mui/icons-material
│
●  Building preview..
│
●  Addon-docs: using MDX3
│
●  Using implicit CSS loaders
[baseline-browser-mapping] The data in this module is over two months old.  To ensure accurate Baseline data, please update: `npm i baseline-browser-mapping@latest -D`
│
●  Using SWC as compiler
│
●  Using default Webpack5 setup
<i> [storybook-mock-plugin] Mock map updated with 0 mocks.
92% sealing asset processing HtmlWebpackPlugin✘ [ERROR] Could not resolve "@vitest/mocker"

    ../../storybook/assets/server/mocker-runtime.template.js:1:31:
      1 │ import { MockerRegistry } from '@vitest/mocker';
        ╵                                ~~~~~~~~~~~~~~~~

  You can mark the path "@vitest/mocker" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@vitest/mocker/browser"

    ../../storybook/assets/server/mocker-runtime.template.js:2:50:
      2 │ import { ModuleMocker, createCompilerHints } from '@vitest/mocker/browser';
        ╵                                                   ~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@vitest/mocker/browser" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle.

│
■  Error: Build failed with 2 errors:
│  ../../storybook/assets/server/mocker-runtime.template.js:1:31: ERROR: Could not
│  resolve "@vitest/mocker"
│  ../../storybook/assets/server/mocker-runtime.template.js:2:50: ERROR: Could not
│  resolve "@vitest/mocker/browser"

```

**Comment by serenaqchen** [comment]
@valentinpalkovic Using version `0.0.0-pr-33315-sha-a17762c8` worked for me

**Comment by valentinpalkovic** [comment]
Oh wow! You were faster than me :D I just wanted to ask you to try out the new Canary!

**Comment by anomiex** [comment]
I ran into a similar issue using `pnpm` with hoisting disabled (yarn's P'n'P would likely have the same issue). Even though `@storybook/builder-webpack5` depends on `@vitest/mocker`, `storybook` can't access it because it doesn't have the dependency itself. It only works on npm due to hoisting.

`0.0.0-pr-33315-sha-a17762c8` seems to work to fix this too.

**Comment by heath-freenome** [comment]
@valentinpalkovic Any update on when the fix in canary will be released for general consumption?

**Comment by MarcusUMN** [comment]
@valentinpalkovic thanks for that solution! Would be great to get the canary fix released for general consumption

**Comment by valentinpalkovic** [comment]
I have refined the PR after internal feedback. We will ship it as a hotfix after we release Storybook 10.2 (likely today).

**Comment by WillsB3** [comment]
I think I'm still seeing this error with 10.2.0.

We're using `msw-storybook-addon` in `preview.jsx`


```jsx
import React from 'react'
import { BrowserRouter } from 'react-router-dom'
import { initialize, mswLoader } from 'msw-storybook-addon'

import { Auth0ProviderWithNavigate } from '../src/auth0-provider-with-navigate'
import { Toast } from '../src/components/Toast'
import { GlobalStylesWrapper } from './GlobalStylesWrapper'

initialize({
  onUnhandledRequest: ({ url }, print) => {
    const URLS_TO_IGNORE = [
      /https:\/\/fonts.googleapis.com/,
      /https:\/\/res.cloudinary.com/,
    ]

    if (URLS_TO_IGNORE.some((pattern) => pattern.test(url))) {
      return
    }
    print.warning()
  },
})

export const decorators = [
  (storyFn) => (
    <BrowserRouter>
      <Auth0ProviderWithNavigate>
        <Toast.Provider>
          <GlobalStylesWrapper>{storyFn()}</GlobalStylesWrapper>
        </Toast.Provider>
      </Auth0ProviderWithNavigate>
    </BrowserRouter>
  ),
]

export const loaders = [mswLoader]

export const parameters = {
  msw: {
    handlers: {},
  },
}
export const tags = ['autodocs']

```

```
> NODE_PATH=$NODE_PATH:./src storybook dev -p 5602


┌  storybook v10.2.0
│
●  Storybook collects completely anonymous usage telemetry. We use it to shape
│  Storybook's roadmap and prioritize features. You can learn more, including how
│  to opt out, at https://storybook.js.org/telemetry
│
●  Starting...
│
●  Addon-docs: using MDX3
│
●  Using implicit CSS loaders
│
●  Using default Webpack5 setup
<i> [webpack-dev-middleware] wait until bundle finished
<i> [storybook-mock-plugin] Mock map updated with 0 mocks.
92% sealing asset processing HtmlWebpackPlugin✘ [ERROR] Could not resolve "@vitest/mocker"

    node_modules/storybook/assets/server/mocker-runtime.template.js:1:31:
      1 │ import { MockerRegistry } from '@vitest/mocker';
        ╵                                ~~~~~~~~~~~~~~~~

  You can mark the path "@vitest/mocker" as external to exclude it from the bundle, which will
  remove this error and leave the unresolved path in the bundle.

✘ [ERROR] Could not resolve "@vitest/mocker/browser"

    node_modules/storybook/assets/server/mocker-runtime.template.js:2:50:
      2 │ import { ModuleMocker, createCompilerHints } from '@vitest/mocker/browser';
        ╵                                                   ~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@vitest/mocker/browser" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle.

ERROR in   Error: Build failed with 2 errors:
  node_modules/storybook/assets/server/mocker-runtime.template.js:1:31: ERROR: Could not resolve "@vitest/mocker"
  node_modules/storybook/assets/server/mocker-runtime.template.js:2:50: ERROR: Could not resolve "@vitest/mocker/browser"
  
  - main.js:1467 failureErrorWithLog
    [spotlight]/[esbuild]/lib/main.js:1467:15
  
  - main.js:926 
    [spotlight]/[esbuild]/lib/main.js:926:25
  
  - main.js:878 
    [spotlight]/[esbuild]/lib/main.js:878:52
  
  - main.js:924 buildResponseToResult
    [spotlight]/[esbuild]/lib/main.js:924:7
  
  - main.js:951 
    [spotlight]/[esbuild]/lib/main.js:951:16
  
  - main.js:603 responseCallbacks.<computed>
    [spotlight]/[esbuild]/lib/main.js:603:9
  
  - main.js:658 handleIncomingPacket
    [spotlight]/[esbuild]/lib/main.js:658:12
  
  - main.js:581 Socket.readFromStdout
    [spotlight]/[esbuild]/lib/main.js:581:7
  
  - node:events:519 Socket.emit
    node:events:519:28
  
  - readable:561 addChunk
    node:internal/streams/readable:561:12
  


preview compiled with 1 error
│
▲  DefinePlugin
│  Conflicting values for 'process.env'
│
■  Failed to build the preview
99% end closing watch compilation│
▲  Force closed preview build
│
■  SB_BUILDER-WEBPACK5_0003 (WebpackCompilationError): There were problems when
│  compiling your code with Webpack.
│  Run Storybook with --debug-webpack for more information.
│  at starter
│  (file://./node_modules/@storybook/builder-webpack5/dist/index.js:799:11)
│  at starter.next (<anonymous>)
│  at Module.start
│  (file://./node_modules/@storybook/builder-webpack5/dist/index.js:857:34)
│  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
│  at async storybookDevServer
│  (file://./node_modules/storybook/dist/core-server/index.js:7207:83)
│  at async buildOrThrow
│  (file://./node_modules/storybook/dist/core-server/index.js:4504:12)
│  at async buildDevStandalone
│  (file://./node_modules/storybook/dist/core-server/index.js:7577:66)
│  at async withTelemetry
│  (file://./node_modules/storybook/dist/_node-chunks/chunk-5T2PCIM6.js:218:12)
│  at async dev (file://./node_modules/storybook/dist/bin/core.js:2734:3)
│  at async _Command.<anonymous>
│  (file://./node_modules/storybook/dist/bin/core.js:2801:92)
│
▲  Broken build, fix the error above.
│  You may need to refresh the browser.
│
◇  Would you like to send anonymous crash reports to improve Storybook and
│  fix bugs faster?
│  Yes
│
│  Debug logs are written to:
│  /Users/wills/Development/Farewill/spotlight/debug-storybook.log
│
└  Storybook exited with an error
```

**Comment by valentinpalkovic** [comment]
The fix is not patched back yet. You have to wait for 10.2.1.
