### ISSUE TITLE
create-react-app babel-loader clash

### ISSUE THREAD

**Issue by mohamedmansour** [storybookjs/storybook#4764]
<details><summary>Original Post Hidden As It Relates to CRAv2</summary>
<p>

When installing create-react-app 2, it already has `babel-loader` and `@babel/core` . We need to add those two as a `peerDependency`?

My `packages.json`:

```json
{
  "version": "0.1.0",
  "private": true,
  "license": "ISC",
  "dependencies": {
    "react": "^16.6.1",
    "react-dom": "^16.6.1",
  },
  "devDependencies": {
    "@storybook/react": "^4.0.4",
    "@types/node": "^10.12.5",
    "@types/react": "^16.7.1",
    "@types/react-dom": "^16.0.9",
    "@types/storybook__react": "^4.0.0",
    "react-scripts": "^2.1.1",
    "typescript": "3.1.6"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "storybook": "start-storybook -p 9001 -c .storybook"
  },
  "browserslist": [
    ">0.2%",
    "not dead",
    "not ie <= 11",
    "not op_mini all"
  ]
}

```

The errors warnings are:

```bash
PS D:\> yarn install
yarn install v1.12.1
info No lockfile found.
[1/4] Resolving packages...
warning react-scripts > eslint > file-entry-cache > flat-cache > circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "win32" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @storybook/react@4.0.4" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning "@storybook/react > @babel/preset-flow@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @babel/preset-react@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @babel/preset-flow > @babel/plugin-transform-flow-strip-types@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @babel/preset-react > @babel/plugin-transform-react-display-name@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @babel/preset-react > @babel/plugin-transform-react-jsx@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core@4.0.4" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning "@storybook/react > @babel/preset-react > @babel/plugin-transform-react-jsx-self@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @babel/preset-react > @babel/plugin-transform-react-jsx-source@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @babel/preset-flow > @babel/plugin-transform-flow-strip-types > @babel/plugin-syntax-flow@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".warning "@storybook/react > @babel/preset-react > @babel/plugin-transform-react-jsx > @babel/plugin-syntax-jsx@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/plugin-proposal-class-properties@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/plugin-transform-runtime@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/plugin-transform-regenerator@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env@7.1.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @emotion/styled > @emotion/styled-base@0.10.6" has unmet peer dependency "@emotion/core@0.x.x".
warning "@storybook/react > @storybook/core > @babel/plugin-proposal-class-properties > @babel/plugin-syntax-class-properties@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-proposal-async-generator-functions@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-proposal-json-strings@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-syntax-object-rest-spread@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-proposal-optional-catch-binding@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-syntax-async-generators@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-arrow-functions@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-block-scoping@7.1.5" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-function-name@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-for-of@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-literals@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-modules-amd@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-modules-commonjs@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-object-super@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-new-target@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-modules-umd@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-parameters@7.1.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-shorthand-properties@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-spread@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-modules-systemjs@7.1.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-sticky-regex@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-template-literals@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-unicode-regex@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-transform-typeof-symbol@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".warning "@storybook/react > @storybook/core > @babel/preset-env > @babel/plugin-proposal-json-strings > @babel/plugin-syntax-json-strings@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".[4/4] Building fresh packages...

success Saved lockfile.
Done in 10.14s.
```

</p>
</details>

**Comment by igor-dv** [comment]
Yes, you need. These are direct deps for CRA, but peer for the Storybook, which means you need to install them.

**Comment by mohamedmansour** [comment]
This is a problem, when installing `babel-loader`, it requires `webpack` but these two dependencies are already the required dependencies of `react-scripts` for CRA2.

```
> react-scripts start

There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "webpack": "4.19.1"

Don't try to install it manually: your package manager does it automatically.
However, a different version of webpack was detected higher up in the tree:
```

I don't believe it is good to make users install `babel-loader` or `@babel-core` when CRA is there, it will conflict and devs will have a trouble upgrading in the future.

Is there a better way to support this? For example, once #4587 is supported, can we infer these packages like how CRA2 does it?

**Comment by igor-dv** [comment]
`@storybook/react` is supposed to match different versions of different tools. 

For example:
1. Your application may use babel 6. In that case, you will install babel-loader@7 that has a peer for babel-core (babel v6). that is why we have babel-loader as a peer dependency
2. Another user may use babe 7. And will install babel-loader@8 with `@babel/core` (v7)
3. The third user may have a usage of CRA1
4. The fourth is using CRA2
5. One is using TS with babel
6. The last is using TS without babel

Unfortunately, node deps can't be transitive and we can't assume that some third party tool will bring some dep for us. Also, we can't make sure how npm/yarn will install these deps.

How can we now make everyone happy?  Maybe we need to start deprecating older tooling in favor of newer... In that case, we will be able to move some of the `peerDeps` just to `deps` but it will just minimize the problem 🤷‍♂️ 

PS.. @storybooks/team this is something we should talk about on the next roadmap meeting.

**Comment by kylemh** [comment]
Maybe a preset for CRA 1 and 2?

**Comment by igor-dv** [comment]
In my vision, we need to extract presets out of the supported frameworks and make CLI install them when it recognizes one or another tool.

**Comment by tmeasday** [comment]
It sounds like maybe the problem you describe can be solved by optional [react] presets that depend on these various things directly @igor-dv? Then the CLI can install the preset for you and as a user maybe you don't actually need to understand what's happening

**Comment by ndelangen** [comment]
Perhaps before you build or start storybook our CLI does a quick check on node_nodules.

We know what storybook needs...

So if we detect missing things, we add then before running. (and then run).

This way we don't have to bother users at all, and we can re-use whatever version people have though whatever means..

**Comment by sylvhama** [comment]
I am facing the same error as @mohamedmansour 
When I dod `npm start` with CRA v2 it says:

```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "webpack": "4.19.1"
```

I've removed my package-lock.json and my node_modules, the issue is still there.
Wjen i run `npm ls webpack` it lists:
```
console-lite@4.2.0 f:\www\console-lite
+-- @storybook/react@4.1.6
| +-- @storybook/core@4.1.6
| | `-- webpack@4.28.1  deduped
| `-- webpack@4.28.1
`-- react-scripts@2.1.3
  `-- webpack@4.19.1
```

My depedencies:
```
"dependencies": {
    "intl": "^1.2.5",
    "lodash": "^4.17.11",
    "promise.prototype.finally": "^3.1.0",
    "react": "^16.6.3",
    "react-app-polyfill": "^0.2.0",
    "react-dom": "^16.6.3",
    "react-intl": "^2.7.2",
    "react-loadable": "^5.4.0",
    "react-redux": "^6.0.0",
    "react-router-dom": "^4.3.1",
    "redux": "^4.0.1",
    "redux-thunk": "^2.3.0",
    "styled-components": "^4.1.3"
  },
"devDependencies": {
    "@club/ci-tools": "^0.11.4",
    "@storybook/addon-info": "^4.1.6",
    "@storybook/addon-knobs": "^4.1.6",
    "@storybook/react": "^4.1.6",
    "cross-env": "^5.1.4",
    "ftp": "^0.3.10",
    "husky": "^1.1.2",
    "jest-image-snapshot": "^2.7.0",
    "jest-puppeteer": "^3.7.0",
    "jest-styled-components": "^6.3.1",
    "klaw-sync": "^4.0.0",
    "lint-staged": "^7.0.0",
    "mkdirp": "^0.5.1",
    "ncp": "^2.0.0",
    "prettier": "^1.15.3",
    "puppeteer": "^1.11.0",
    "react-intl-cra": "^0.3.3",
    "react-scripts": "^2.1.1",
    "react-test-renderer": "^16.6.3",
    "redux-mock-store": "^1.5.3",
    "source-map-explorer": "^1.5.0"
  },
```

**Comment by sylvhama** [comment]
Weird fix:
```
npm uninstall @storybook/react
npm install react-scripts
npm install @storybook/react
```
After doing that you should not remove *`package-lock.json`* otherwise you will face the same issue again.

**Comment by sylvhama** [comment]
I've updated react-scripts (2.1.5) and storybook react and its addons (4.1.11). The issue is still there but it's about `babel-loader` now:

```
The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.0.5"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  f:\www\console-lite\node_modules\babel-loader (version: 8.0.4)
```

**Comment by tmeasday** [comment]
@sylvhama now you are running into this one 😢 : https://github.com/storybooks/storybook/issues/5183

Most people have managed to fix it by fixing the version of `babel-loader` to `8.04` in `package.json`.

**Comment by ndelangen** [comment]
😭 There's a PR to fix the babel-loader version, and make it match cra's one. I haven't been able to check it out and verify it's good.

If someone here can help us review the PR, we may be able to get it merged faster.

**Comment by sylvhama** [comment]
@tmeasday thanks for your feedback!
Their solution is not recommended by CRA Team tho. Plus Storybook v4 promise was to be compatible with CRA2 😞

**Comment by tmeasday** [comment]
> Their solution is not recommended by CRA Team tho. Plus Storybook v4 promise was to be compatible with CRA2

It's hard because CRA is a moving target :/

**Comment by mrmckeb** [comment]
I'm sorry guys, this is on me too - as I got caught up and haven't gotten back to refactoring that POC/PR.

We need a more reliable system here. Right now we have an issue that's kind of related to this, so once we get through that, I think we can talk more about a long-term solution here. https://github.com/facebook/create-react-app/issues/6398

I'll talk to the CRA team on this and see what ideas we can come up with to make this a more robust experience for all.

**Comment by sylvhama** [comment]
No more issue since v5.

**Comment by shilman** [comment]
That's great to hear. Closing this now, but feel free to re-open if the issue hasn't gone away.

**Comment by sparanoid** [comment]
@shilman I can still reproduce this issue in a fresh project created with CRA 3.0.1:

```bash
npx create-react-app my-app-sb
cd my-app-sb
npx -p @storybook/cli sb init

...

yarn add v1.16.0
[1/4] 🔍  Resolving packages...
warning @storybook/react > @storybook/core > @storybook/ui > recompose > fbjs > core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "react-scripts > @typescript-eslint/eslint-plugin@1.6.0" has unmet peer dependency "typescript@*".
warning "react-scripts > @typescript-eslint/parser@1.6.0" has unmet peer dependency "typescript@*".
warning "@storybook/react > @babel/plugin-transform-react-constant-elements@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @babel/preset-react@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "react-scripts > @typescript-eslint/eslint-plugin > @typescript-eslint/typescript-estree@1.6.0" has unmet peer dependency "typescript@*".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.10.0" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev".
warning "@storybook/react > @storybook/core > @babel/plugin-proposal-object-rest-spread@7.4.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @storybook/react@5.1.3" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning "@storybook/react > @babel/preset-flow@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @babel/preset-flow > @babel/plugin-transform-flow-strip-types@7.4.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core@5.1.3" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning "@storybook/react > @storybook/core > @babel/plugin-proposal-class-properties@7.4.4" has unmet peer dependency "@babel/core@^7.0.0-0".

...
```

**Comment by shilman** [comment]
@mrmckeb Any chance you can help @sparanoid on this?

**Comment by mikecousins** [comment]
Yeah I still get the same errors with CRA 3.0.1 and Storybook 5.1.3 as well.

`yarn install v1.16.0
[1/4] �🔍  Resolving packages...
[2/4] �🚚  Fetching packages...
info fsevents@2.0.6: The platform "win32" is incompatible with this module.
info "fsevents@2.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.9: The platform "win32" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] �🔗  Linking dependencies...
warning " > connected-react-router@6.4.0" has incorrect peer dependency "react-redux@^6.0.0".
warning " > react-ga@2.5.7" has unmet peer dependency "prop-types@^15.6.0".
warning "@storybook/react > @babel/plugin-transform-react-constant-elements@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @babel/preset-react@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core > @babel/plugin-proposal-object-rest-spread@7.4.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @storybook/react@5.1.3" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning "@storybook/react > @babel/preset-flow@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @babel/preset-flow > @babel/plugin-transform-flow-strip-types@7.4.4" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "@storybook/react > @storybook/core@5.1.3" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".
warning "@storybook/react > @storybook/core > @babel/plugin-proposal-class-properties@7.4.4" has unmet peer dependency "@babel/core@^7.0.0-0".
[4/4] �🚚  Building fresh packages...
success Saved lockfile.
✨  Done in 14.21s.`

**Comment by cyrus-za** [comment]
@shilman please open this issue again as it's happening in CRA 3

**Comment by kylemh** [comment]
No need to tag any one maintainer ❤️

**Comment by shilman** [comment]
We've got some movement here with the recent beta release of `@storybook/preset-create-react-app` by @mrmckeb 🎉

https://github.com/storybookjs/presets/tree/master/packages/preset-create-react-app

Please give it a try and see whether it helps address the issue

**Comment by cyrus-za** [comment]
I'll check it out and let you know, thanks!

**Comment by mikecousins** [comment]
I get the following warnings with the new preset:

warning "@storybook/react > @babel/preset-react@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".                warning "@storybook/react > @babel/plugin-transform-react-constant-elements@7.5.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning " > @storybook/preset-create-react-app@1.0.0-beta.2" has incorrect peer dependency "@storybook/react@>=5.3".    warning " > @storybook/preset-create-react-app@1.0.0-beta.2" has unmet peer dependency "@types/webpack@*".              warning " > @storybook/react@5.1.11" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".                         warning "@storybook/react > @babel/preset-flow@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".                 warning "@storybook/react > @storybook/core@5.1.11" has unmet peer dependency "babel-loader@^7.0.0 || ^8.0.0".

**Comment by techieshark** [comment]
With the preset (and not using Typescript) I'm seeing:
```
"@storybook/preset-create-react-app > react-docgen-typescript-loader@3.6.0" has unmet peer dependency "typescript@*".
```

**Comment by mrmckeb** [comment]
@shilman @mikecousins This is hard to fix. Peer dependencies expect that you have listed the dependency, it doesn't recognise that the dependency is included as a _dependency of a dependency_ (if that makes sense). We could remove it, but that would cause chaos too...

We could remove it, make it an optional dependency instead - and then throw an error if it doesn't exist..?

**Comment by mrmckeb** [comment]
@techieshark, unfortunately this is hard to avoid... if you are using a CRA project with TypeScript, you would have to have this installed or things would break. We could force users to install `react-docgen-typescript-loader` if they use TS, but that will also cause confusion for some people.

There's no _easy_ solution, but I'm interested in hearing thoughts on these.

**Comment by Hypnosphi** [comment]
> We could force users to install react-docgen-typescript-loader if they use TS

@mrmckeb we can make `sb init` install it if typescript is detected

**Comment by mrmckeb** [comment]
We could @Hypnosphi, but it would need to be in the user's dependencies then - which may (for some people) be more annoying than this error message.

**Comment by Hypnosphi** [comment]
@shilman what do you think?

**Comment by Hypnosphi** [comment]
BTW it's also a direct dependency in `@storybook/react`: https://github.com/storybookjs/storybook/blob/next/app/react/package.json#L55

**Comment by shilman** [comment]
Fixed in https://github.com/storybookjs/storybook/pull/13220 and released in `v6.1.3`.

**Comment by gynekolog** [comment]
Still not fixed. Tested with CRA 4.0.1.
One of the possible fixes is to run `yarn add react-scripts`.

**Comment by shilman** [comment]
@gynekolog can you tell me more about your setup? `npx sb info`

**Comment by gynekolog** [comment]
@shilman 
I tried clean install now:
```
npx create-react-app cra-storybook --template typescript && cd cra-storybook && npx sb init 
```
`yarn start`
error:
```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.1.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  /Users/honza/Sites/cra-storybook/node_modules/babel-loader (version: 8.2.2)
```

`yarn storybook` is run fine.

After run `yarn add react-scripts` is app fixed (`yarn start`) but storybook (`yarn storybook`) broken.
Error: ` Error: Cannot find module 'babel-loader'`

```
Environment Info:

  System:
    OS: macOS 11.0.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
  Binaries:
    Node: 14.15.0 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.8 - /usr/local/opt/node@14/bin/npm
  Browsers:
    Chrome: 87.0.4280.67
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-actions: ^6.1.9 => 6.1.9 
    @storybook/addon-essentials: ^6.1.9 => 6.1.9 
    @storybook/addon-links: ^6.1.9 => 6.1.9 
    @storybook/node-logger: ^6.1.9 => 6.1.9 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.9 => 6.1.9 
```

**Comment by hharnisc** [comment]
Experiencing the same issue as @gynekolog. 

A workaround is to disable the check for all NPM scripts that call `react-scripts` with `SKIP_PREFLIGHT_CHECK=true`. Commands still seem to run, but there's a risk in things breaking without warning.

**Comment by shilman** [comment]
I have a pretty similar setup but an older OS version and a few older dependencies, but am not seeing this error. Any ideas what could be different? Is it something that changed in yarn over the past few versions? cc @gaetanmaisse @arcanis @merceyz 

```
  System:
    OS: macOS Mojave 10.14.6
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Binaries:
    Node: 12.19.0 - /usr/local/opt/node@12/bin/node
    Yarn: 1.22.5 - ~/.yarn/bin/yarn
    npm: 6.14.8 - /usr/local/opt/node@12/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Firefox: 83.0
    Safari: 14.0
```

**Comment by hharnisc** [comment]
```
Environment Info:

  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
    Yarn: 1.19.2 - ~/.yarn/bin/yarn
    npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
  Browsers:
    Chrome: 86.0.4240.198
    Safari: 14.0
  npmPackages:
    @storybook/addon-actions: ^6.1.9 => 6.1.9
    @storybook/addon-docs: ^6.1.9 => 6.1.9
    @storybook/addon-essentials: ^6.1.9 => 6.1.9
    @storybook/addon-links: ^6.1.9 => 6.1.9
    @storybook/addons: ^6.1.9 => 6.1.9
    @storybook/node-logger: ^6.1.9 => 6.1.9
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5
    @storybook/react: ^6.1.9 => 6.1.9
```

**Comment by hharnisc** [comment]
Also `react-scripts` is locked at `4.0.1`

Looks like I've got a _slightly_ older version of `yarn`

**Comment by owen-calico** [comment]
Seeing same problem as @hharnisc and @gynekolog with a new c-r-a typescript project.

Fix that's working for me:
1) Manually remove `node_modules/babel-loader`
2) Add to package.json
```
    "resolutions": {
       "@storybook/react/babel-loader": "8.1.0"
    }
```
3) `yarn add -D babel-loader@8.1.0`

Jest and storybook appear to be working fine after this.  
The fix survived deleting `npm-modules` and a clean `yarn install`.

Environment Info:
```
  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  Binaries:
    Node: 15.3.0 - ~/.nodenv/versions/15.3.0/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.0.14 - ~/.nodenv/versions/15.3.0/bin/npm
  Browsers:
    Chrome: 87.0.4280.67
    Firefox: 83.0
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-actions: ^6.1.9 => 6.1.9 
    @storybook/addon-essentials: ^6.1.9 => 6.1.9 
    @storybook/addon-links: ^6.1.9 => 6.1.9 
    @storybook/node-logger: ^6.1.9 => 6.1.9 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.9 => 6.1.9 
```

**Comment by AskAlice** [comment]
Anyone have a solution for NPM?

**Comment by L-U-C-K-Y** [comment]
@AskAlice have you tried @owen-calico approach?

I have added 

```json
"resolutions": {
       "@storybook/react/babel-loader": "8.1.0"
    }
```

To my package.json and ran `rm -rf node_modules && yarn`.

**Comment by AskAlice** [comment]
@L-U-C-K-Y NPM actually doesn't support dependency resolution like yarn does

**Comment by merceyz** [comment]
This should be raised with the `create-react-app` team, they shouldn't care what other versions exists in `node_modules` and what is hoisted to the top, the package manager will give them the version they declare either way.

cc @iansu

**Comment by ccaspanello** [comment]
The post by @owen-calico worked great!  This at least gets me running; but like others I would really like a no-hack way to get up and running.

**Comment by IngenieroLata** [comment]
I'm having this exact issue. Here is my sb info

```
Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.3/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
  Browsers:
    Chrome: 87.0.4280.88
    Firefox: 80.0.1
    Safari: 14.0.1
  npmPackages:
    @storybook/addon-actions: ^6.1.11 => 6.1.11 
    @storybook/addon-essentials: ^6.1.11 => 6.1.11 
    @storybook/addon-links: ^6.1.11 => 6.1.11 
    @storybook/node-logger: ^6.1.11 => 6.1.11 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.11 => 6.1.11 
```
and here is the versioning problem:
```
app
├─┬ @storybook/react@6.1.11
│ └─┬ @storybook/core@6.1.11
│   └── babel-loader@8.2.2 
└─┬ react-scripts@3.4.4
  └── babel-loader@8.1.0 
```
When I try to build my App got this message: 
```
There might be a problem with the project dependency tree.
It is likely not a bug in Create React App, but something you need to fix locally.

The react-scripts package provided by Create React App requires a dependency:

  "babel-loader": "8.1.0"

Don't try to install it manually: your package manager does it automatically.
However, a different version of babel-loader was detected higher up in the tree:

  /Users/diegotoro/code/web-er/node_modules/babel-loader (version: 8.2.2) 

Manually installing incompatible versions is known to cause hard-to-debug issues.

If you would prefer to ignore this check, add SKIP_PREFLIGHT_CHECK=true to an .env file in your project.
That will permanently disable this message but you might encounter other issues.

To fix the dependency tree, try following the steps below in the exact order:

  1. Delete package-lock.json (not package.json!) and/or yarn.lock in your project folder.
  2. Delete node_modules in your project folder.
  3. Remove "babel-loader" from dependencies and/or devDependencies in the package.json file in your project folder.
  4. Run npm install or yarn, depending on the package manager you use.

In most cases, this should be enough to fix the problem.
If this has not helped, there are a few other things you can try:

  5. If you used npm, install yarn (http://yarnpkg.com/) and repeat the above steps with it instead.
     This may help because npm has known issues with package hoisting which may get resolved in future versions.

  6. Check if /Users/diegotoro/code/web-er/node_modules/babel-loader is outside your project directory.
     For example, you might have accidentally installed something in your home folder.

  7. Try running npm ls babel-loader in your project folder.
     This will tell you which other package (apart from the expected react-scripts) installed babel-loader.
...
```

The only solution that worked for me was manually install `babel-loader` and `webpack` to match react-script versions. But seems pretty weird as I see https://github.com/storybookjs/storybook/pull/13220 skips babel installation for CRA case. But it's fully skipped. And doesn't seems to have a flag to force that behavior.

**Comment by shilman** [comment]
Fixed in https://github.com/storybookjs/storybook/pull/13607 and released in `6.2.0-alpha.12` and `6.1.12`.

**Comment by AskAlice** [comment]
@shilman could you explain how that works?
 I updated my package.json to use storybook `^6.1.14`, deleted my package.lock.json and node_modules, then ran npm i and got
 ```
 +-- @storybook/react@6.1.14
| `-- @storybook/core@6.1.14
|   `-- babel-loader@8.2.2  deduped
+-- babel-loader@8.2.2 
`-- react-scripts@4.0.1
  `-- babel-loader@8.1.0
```

**Comment by AskAlice** [comment]
it turns out it needs to be in the dev dependencies not the dependencies. We had it this way because of eslint expecting a storybook plugin to exist, and the fact that we deploy storybook on production.

**Comment by FutureKode** [comment]
I am still seeing this issue. How can I fix it? npm is my package manager. Here is my sb info:

```
  System:
    OS: macOS 11.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 14.15.4 - /usr/local/opt/node@14/bin/node
    Yarn: 1.22.5 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/opt/node@14/bin/npm
  Browsers:
    Chrome: 87.0.4280.141
    Safari: 14.0.2
  npmPackages:
    @storybook/addon-essentials: ^6.1.15 => 6.1.15 
    @storybook/addons: ^6.1.15 => 6.1.15 
    @storybook/preset-create-react-app: ^3.1.5 => 3.1.5 
    @storybook/react: ^6.1.15 => 6.1.15 
```

This is the problem after updating react-scripts to 4.0.1:

├─┬ @storybook/react@6.1.15
│ └─┬ @storybook/core@6.1.15
│   └── babel-loader@8.2.2 
└─┬ react-scripts@4.0.1
  └── babel-loader@8.1.0

**Comment by AskAlice** [comment]
@FutureKode is storybook in your _devDependencies_? also have you tried deleting your package.lock.json and node_modules then running `npm i`?

**Comment by FutureKode** [comment]
> @FutureKode is storybook in your _devDependencies_?
> Also have you tried deleting your `package.lock.json` & `node_modules` then running `npm i`?

Hi @AskAlice , this is what is in my devDependencies:

```
    "@storybook/addon-essentials": "^6.1.15",
    "@storybook/addons": "^6.1.15",
    "@storybook/preset-create-react-app": "^3.1.6-alpha.0",
    "@storybook/react": "^6.1.15",
```

Yes I have tried deleting `package-lock.json` & `node_module`s then running `npm i` but I still see the same error when running `npm run start`

**Comment by edwardbrowncross** [comment]
I found [this medium article](https://medium.com/learnwithrahul/understanding-npm-dependency-resolution-84a24180901b) helpful in understanding what it means by 'higher up the tree'. As I understand it, it is insisting (pointlessly) that its version is the first one to be installed into node_modules. However npm installs dependencies in alphabetical order, so there's really no way to actually enforce this (without yarn).

The hacky solution I found was this:
1. Delete `node_modules` and `package-lock.json`
2. Add the desired version to a new package lock first with `npm i --package-lock-only babel-loader@8.1.0`
3. This also adds the dependency to `package.json`, so now delete that added line
4. `npm i` to add the rest of the packages to the lock file and install everything to node_modules.
5. Validate the tree is correct with `npm test`
6. Commit the now correct `package-lock.json`

**Comment by JavascriptDeNoobAPro** [comment]
The issue went away after adding  "resolutions" : { "babel-loader": "8.1.0"} to my package.json, delete yarn.lock, yarn install and then it worked !

**Comment by JuanGidoni** [comment]
> The issue went away after adding "resolutions" : { "babel-loader": "8.1.0"} to my package.json, delete yarn.lock, yarn install and then it worked !

This force the entire team to use `yarn` and maybe others wants to use `npm`.  I don't think this is the best solution.

However I found this [npm force resolutions](https://github.com/rogeriochaves/npm-force-resolutions) and maybe it's a way to all in the team have the problem resolved.

**Comment by merceyz** [comment]
> This force the entire team to use yarn and maybe others wants to use npm. I don't think this is the best solution.

They should be forced to use either or, shouldn't mix package managers in the same project. Besides you can disable the check that CRA does.
