### ISSUE TITLE
Knobs are not clearing when switching between stories

### ISSUE THREAD

**Issue by LinaBell** [storybookjs/storybook#5141]
### In React Native, when navigating between stories on a device (simulator), the knobs persist and stack rather than clearing/resetting.

If the same knob exists on multiple components, the value of the first knob caries over to the next.
_Potentially related to closed issue https://github.com/storybooks/storybook/issues/794_?

If the knob does not exist, it remains anyway and new knobs are added underneath.

![screen recording 2019-01-03 at 4 45 08 pm](https://user-images.githubusercontent.com/10732112/50669151-64043400-0f78-11e9-964d-9ddf9264b3c9.gif)

**Comment by shilman** [comment]
Yee-haw!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.12 that addresses this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
We’ve released a brand new `@storybook/react-native` with a bunch of core improvements. It’s available in the latest `5.1-alpha` on `next` and has been verified by several RN users on their existing apps. It should fix a bunch of compatibility issues, especially if you’re using the web server feature. Please give it a try and comment here if it fixes your problem. Migration instructions available here: https://github.com/storybooks/storybook/blob/next/MIGRATION.md#react-native-server

@LinaBell @davi0015

**Comment by SEAPUNK** [comment]
We're using `5.1.0-rc.3` with `addon-knobs` on `@storybook/react-native-server`, but we're still experiencing the same problem, particularly when switching between stories with knobs to stories w/o knobs: The knobs don't clear out, and you have to press the "reset" button for it to actually say that there are no knobs on the story.

**Comment by kenny-inthirath-pear** [comment]
Had the same issue in `5.1.9` and did **not** attempt using with`@storybook/react-native-server`

It seems fixed using the `@next`, guessing [5.20-beta.12](https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.12) may have resolved it.

**Comment by Gongreg** [comment]
Can confirm it is working in 5.3.0-alpha.37 :)
