### ISSUE TITLE
5.0.0-rc.9: Option sortStoriesByKind is not working

### ISSUE THREAD

**Issue by danielg2002** [storybookjs/storybook#5827]
```js
addParameters(
  {
    options: {
      theme: create({
        base: "light",
        brandTitle: "Test",
      }),
      sortStoriesByKind: true,
    },
  },
);
```

sortStoriesByKind is not working, true/false it's the same.

5.0.0-rc.9

**Comment by SamKirkland** [comment]
Also an issue with the other options in the ui object: enableShortcuts and sidebarAnimations

**Comment by randak** [comment]
This is still happening in 5.0.1 for us.

**Comment by sunlanterns** [comment]
Uncertain if it's related but I've also found since updating to 5.0.1 (from a 4.* ver) that my welcome story that used to show up as the first thing is now showing up as the last, no matter how I play around with naming conventions or import order.

**Comment by simonhoss** [comment]
I have the same with this options

`{
    sortStoriesByKind: true,
    hierarchySeparator: null,
    hierarchyRootSeparator: null
}`

**Comment by jjspace** [comment]
It does not seem like `sortStoriesByKind` is implemented at all in v5+ based on this [search](https://github.com/storybooks/storybook/search?q=sortstoriesbykind&type=Code) which shows the only places it's referenced are in documentation about the feature but it's not actually used anywhere.

**Comment by nemoDreamer** [comment]
My hope is that there's some kind of API in the works that'll allow us to provide our own sorting function! ❤️ 

In v4, we had hacked something into `.storybook/config.js` which accessed `window.__STORYBOOK_CLIENT_API__._storyStore.getStoryKinds()` and sorted `window.__STORYBOOK_CLIENT_API__._storyStore._data` based on that, but that's obviously now broken w/ our update to v5.

Would be soooo sweet to be able to supply `sortStories` func in config that returns `-1|0|1`...

**Comment by dizlexik** [comment]
Still not working in v5.0.5

**Comment by rwieruch** [comment]
Not working in 5.0.6.

![Screen Shot 2019-04-04 at 11 42 26](https://user-images.githubusercontent.com/2479967/55546053-c92e0980-56ce-11e9-8da2-094c5bc6a83a.png)

**Comment by simonhoss** [comment]
I found out that the order of the stories is now sorted by the folder name where there story is inside.

To make a correct ordering you can rename the folder to the same structure you want to see. I will rename my folders to 01_feature/... 02_feature/... and so on

**Comment by rwieruch** [comment]
Hm, I have the stories co-located to the actual implementation of the component. I wouldn't want to order my UI components based on Storybook, but rather how it fits best for my UI libraries project folder structure. So that's no option for me unfortunately

**Comment by antitoxic** [comment]
> It does not seem like `sortStoriesByKind` is implemented at all in v5+ based on this [search](https://github.com/storybooks/storybook/search?q=sortstoriesbykind&type=Code) which shows the only places it's referenced are in documentation about the feature but it's not actually used anywhere.

Pure WTF. @leoyli @shilman @ndelangen Please remove from documentation, or show a giant warning next to each option which is "todo"

**Comment by absgjames** [comment]
is there another way to sort these stories?

**Comment by tmeasday** [comment]
Looks like we'll have a way soon: https://github.com/storybooks/storybook/pull/6472

**Comment by ndelangen** [comment]
We're in the final phase of the 5.1 release. I just had a short discussion with @shilman & @tmeasday about this, and although https://github.com/storybooks/storybook/pull/6472 is very promising, we feel it's a bit too late into the process to merge this into 5.1.

This will be a 5.2 feature.

Reason being:
The visual sorting & sorting of the keyboard shortcuts are kinda independent and haven't been thoroughly tested.

**Comment by danielg2002** [comment]
apparently was resolved in 5.1.0-rc.5 ?

**Comment by shilman** [comment]
@danielg2002 We removed from the docs, but didn't actually solve the issue AFAIK. Is it working for you now?

**Comment by danielg2002** [comment]
@shilman  well, I did a test on 5.1.1 and conclusions are:
- sortStoriesByKind is not working
- now the stories are sorted alphabetically (“byKind”) by default
- this solve my needs

**Comment by rwieruch** [comment]
If sortStoriesByKind is not working, the issue isn't resolved, is it?

**Comment by danielg2002** [comment]
correct!, not resolved

**Comment by tmeasday** [comment]
This is in the pipeline for 5.2 however!

**Comment by shilman** [comment]
We released #6472 and I'll update `MIGRATION.md` accordingly

**Comment by rwieruch** [comment]
Thank you @shilman 🎉 Tried it in 5.2.0-alpha.35 and it worked.

**Just in case:** sortStoriesByKind  changed to storySort and expects a function now.

```
addParameters({
  options: {
    storySort: (a, b) => a[1].id.localeCompare(b[1].id),
  },
});
```

**Comment by mlegait** [comment]
Hello,

I'm sorry if it's a silly question 😅 But I'm not used to `sortStoriesByKind` and I don't find any documentation on `storySort`. 

Where do these `id` come from? I would like to sort the stories manually. How can I do that?

Thank you for your help 😊

**Comment by rwieruch** [comment]
@mlegait I think `id` is the name of the story, without looking into it so I am not a 100% sure, but you can do the following to get clarity:

```
addParameters({
  options: {
    storySort: (a, b) => {
      console.log(a);
      console.log(b);

     // check whether the information from a or b helps you to [sort](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) the values 

      return true; // return false;
    },
  },
});
```

**Comment by mlegait** [comment]
@rwieruch Thank you for your response :)

When I log a and b, I get something like that:
```
{
    id: "guidelines-content--empty-story",
    kind: "Guidelines|Content",
    name: "Empty story",
    story: "Empty story",
    [...]
}
```
So it's perfect if I want to sort stories alphabetically but I'd like to sort them manually. Is it possible to add a custom field `order` (or something like that) or should I do it in a completely different way?

**Comment by shilman** [comment]
@mlegait You could add a story parameter and sort by that?

```
storiesOf(...).add('foo', () => <Foo />, { order: 1 });
```

Pretty sure it will show up in `a.parameters.order`, but I didn't verify.

**Comment by mlegait** [comment]
Thank you very much for your quick answer :) 

 I tried with `storiesOf` and I managed to have something like this:
```
{
    id: "components-dropdown--default",
    kind: "Components|Dropdown",
    name: "default",
    parameters:
    {
        order: 2,
        [...]
    },
    story: "default",
    [...]
}
```
It's perfect! It'll allow me to order stories manually.

I'm currently testing the new plugin **addon-docs**, which is so promising, and I was wondering if it's possible to do something similar in a **mdx file** in the `Meta` tag for example.

**Comment by shilman** [comment]
@mlegait `Meta` and `Story` in MDX can both provide parameters in the same way 👍

**Comment by rwieruch** [comment]
Perhaps the custom order is a a good addition for the docs :)

**Comment by shilman** [comment]
@rwieruch @mlegait Yeah, tho I think this is more of a workaround and probably not the "final" way to do it. Will noodle on that!

**Comment by mlegait** [comment]
```
<Meta title="Components|Button" component={Button} parameters={{ order: 3 }} />
```
works perfectly!

I'll use this workaround while waiting for the final version.

Thank you very much for your help 😄

**Comment by shilman** [comment]
@mlegait 💯💪🎉

**Comment by shilman** [comment]
FIXME: Need to deprecate this

**Comment by shilman** [comment]
This has been documented, closing: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#storysort-option

**Comment by thefolake** [comment]
You can fix this with `storySort`, I had this issue but I figured it out.

To choose a file or component as your landing file, you can specify in your `.storybook/preview.js` file.
Just like this:

```
    export const parameters = {
      .........,
      options: {
        storySort: {
          order: ['Components', ['Forms', ['Select']]],
        },
      },
    };

 ```

![Screenshot 2022-05-20 at 18 55 49](https://user-images.githubusercontent.com/34154242/169586916-13385a31-4eb1-48d0-82b8-e8935008ff6d.png)


To sort stories alphabetically, you can do this

```
    export const parameters = {
      .........,
      options: {
        storySort: (a, b) => a[1].id.localeCompare(b[1].id),
      },
    };

```
