### ISSUE TITLE
addon-storysource: not working without chaining

### ISSUE THREAD

**Issue by sebastian-nowak** [storybookjs/storybook#6136]
Storysource addon does not detect stories when they are created without chaining:

```js
const stories = storiesOf('MyCoolButton', module);

stories.add('first story', () => (
  ...
));

stories.add('second story', () => (
  ...
));

stories.add('third story', () => (
  ...
));
```

Tested on @storybook/react@5.0.1, @storybook/addon-storysource@5.0.1

**Comment by Armanio** [comment]
Hmm, indeed. I'll study it.

**Comment by shilman** [comment]
Hmm @igor-dv I think you're the only one who really understands the code ... 😉

**Comment by libetl** [comment]
I do if needed

**Comment by shilman** [comment]
@libetl I think you just volunteered yourself 😘

**Comment by libetl** [comment]
quite busy these days, ideally already fixed in storysource v2, I will take a look when I can

**Comment by shilman** [comment]
Fair answer! Keep it in mind for storysource v2. In the meantime if anybody else wants to pick this up, go for it!

**Comment by sebastian-nowak** [comment]
For those of us mortals, what is storysource v2? Is that some new 5.x.x release?

**Comment by shilman** [comment]
@sebastian-nowak Probably 6.0 :trollface:

**Comment by libetl** [comment]
I was sick this weekend and therefore no access to any computer

**Comment by libetl** [comment]
I think this will be available only in v6

**Comment by shilman** [comment]
@libetl would love to discuss this with you for 10m on discord when you have time. i'm making some changes to the story format as part of SB docs. the changes are backwards compatible (i.e. old stories will keep working), but i'm wondering whether the new format will break storysource. so i want to understand the impact & whether there's anything i need to consider.

**Comment by libetl** [comment]
sure we can chat

**Comment by shilman** [comment]
In 5.2 we're moving to `@storybook/source-loader` which was overhauled by @libetl. This might have been fixed in there.

**Comment by ndelangen** [comment]
@libetl has done amazing work on this stuff, v5.2 will include his work to bring the loader much needed upgrade 🎉

**Comment by shilman** [comment]
I believe this is fixed by #7117

**Comment by shilman** [comment]
Closing this. Please give a shout if this is not working in 5.2-beta and above!

**Comment by datasoysa** [comment]
I am still not able to make it work. Even with the latest beta version tab stays at "loading source" state

**Comment by shilman** [comment]
@datasoysa does it work if you used chained `storiesOf().add().add()` style?

**Comment by datasoysa** [comment]
yes i've also tried like that but couldn't make it running. I am using addon-info instead but it not the same thing.

**Comment by datasoysa** [comment]
> @datasoysa does it work if you used chained `storiesOf().add().add()` style?

Yes i've also tried like that but couldn't make it running @shilman . I am using addon-info instead but it is not the same thing.

**Comment by shilman** [comment]
@datasoysa do you see any errors in the console? Are you using JS or Typescript? Which version of Storybook? What does your `webpack.config.js` look like?

**Comment by datasoysa** [comment]
> @datasoysa do you see any errors in the console? Are you using JS or Typescript? Which version of Storybook? What does your `webpack.config.js` look like?

Actually no errors on console. I am not using webpack. Using a CRA project with .storybook/config.js adding the storysource addon as import '@storybook/addon-storysource/register'; to the addons.js and tried both addDecoration withStorySource and without that one. It creates the tab but only shows "loading source..."

**Comment by shilman** [comment]
@datasoysa If you're using Storybook then you're using webpack. And you need to add the appropriate webpack loader in order to view the source, otherwise you'll see "loading source...". See https://github.com/storybookjs/storybook/blob/next/addons/storysource/README.md#getting-started

**Comment by datasoysa** [comment]
@shilman  Thank you :) I've made a mistake on test regex. Now it is fine 👍
