### ISSUE TITLE
Addon Actions is not handling React events properly

### ISSUE THREAD

**Issue by vdh** [storybookjs/storybook#6471]
**Describe the bug**
Attempting to use `action` from `@storybook/addon-actions` causes console errors and the output doesn't match the docs, possibly due to how the React Synthetic Events are being serialized.

**To Reproduce**

```
create-react-app sbtemp
cd sbtemp
npx -p @storybook/cli sb init
yarn storybook
```

Then the demo button in the "Button" "with Text" story is clicked. Google Chrome gives a deprecation warning:

```
[Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.
```

The output in the Storybook Actions addon panel doesn't match the output shown in the docs, reading as `clicked: [Class]` instead of the `clicked: ["[SyntheticEvent]", null, "[SyntheticEvent]"]` shown on https://storybook.js.org/docs/addons/introduction/

```
clicked: [Class]
0: Class
_dispatchInstances: Object
_dispatchListeners: function action()
_targetInst: Object
altKey: false
bubbles: true
button: 0
buttons: 0
cancelable: true
clientX: 82
clientY: 32
ctrlKey: false
currentTarget: HTMLButtonElement
defaultPrevented: false
detail: 1
dispatchConfig: Object
eventPhase: 3
getModifierState: function modifierStateGetter()
isDefaultPrevented: function functionThatReturnsFalse()
isPropagationStopped: function functionThatReturnsFalse()
isTrusted: true
metaKey: false
movementX: 0
movementY: 0
nativeEvent: MouseEvent
pageX: 82
pageY: 32
relatedTarget: null
screenX: 292
screenY: 185
shiftKey: false
target: HTMLButtonElement
timeStamp: 266833.9550000001
type: "click"
view: Window
```

Additionally, if `react` and `react-dom` is downgraded to `16.3.2` (the version I was using when I encountered the issue), there is also another console error:

```
Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're adding a new property in the synthetic event object. The property is never released. See https://fb.me/react-event-pooling for more information.
```

**Expected behavior**
No console errors or warnings, and for the Action panel to match the docs.

**System:**

* OS: macOS Mojave Version 10.14.4
* Device: MacBook Pro
* Browser: Google Chrome Version 73.0.3683.103 (Official Build) (64-bit)
* Framework: react
* Addons: addon-actions
* Version:
        react@^16.8.6
        react-dom@^16.8.6
        react-scripts@2.1.8
        @storybook/react@^5.0.6
        @storybook/addon-actions@^5.0.6
        @storybook/addon-links@^5.0.6
        @storybook/addons@^5.0.6
        @babel/core@^7.4.3
        babel-loader@^8.0.5

**Additional context**
I was unable to recreate this additional error, but in my own setup I also saw `telejson` / `JSON.stringify` choke on something (`Date`-related?) with an error of `Uncaught TypeError: toISOString is not a function`

**Comment by wonskarol** [comment]
Im facing similar issue. Right after 
`[Deprecation] 'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.` 
I'm getting 
`tslib.es6.js:17 Uncaught TypeError: toISOString is not a function` error.

**Comment by shilman** [comment]
Sounds like something weird is going on. Any chance you can provide a repro?

**Comment by vdh** [comment]
@shilman I gave some example CLI commands to reproduce it, is there a better repro format or service to use?

I tested it again just now and got the same issue (Chrome 73.0.3683.103, Storybook 5.0.10, Node v11.14.0)

**Comment by shilman** [comment]
@vdh Sorry I missed that. I'll check it out!

**Comment by shilman** [comment]
Ok, I can reproduce. Marking this as a bug & will gratefully accept any PRs to fix! 🙇

**Comment by kohakukun** [comment]
Aside from the warning, what would be the desired behavior?

**Comment by vdh** [comment]
@kohakukun Not causing warnings/errors, and consistent behaviour with what is described by the docs. So either update the behaviour to match the docs or vice versa. Compatibility with React 16.3.2 would be nice but I would understand if that's not possible.

I assume the `Uncaught TypeError: toISOString is not a function` error I was encountering was either fallout from the event handling issue or a problem in my own code, which should hopefully be fixed once the main issue is addressed.

**Comment by mousemke** [comment]
i'm actually hitting the `Uncaught TypeError: toISOString is not a function` after update, and cannot find an issue aside from this issue, so i'm hoping it is not your code and is instead part of this issue.

**Comment by alechp** [comment]
I'm using `@storybook/react-native` and `@storybook/react-native-server` and having the same issue as described above. 

I'm also getting the synthetic event is used for performance reasons error described above. I haven't updated react-dom. 

## Error
The error recurses
### Screenshot
![Screen Shot 2019-05-17 at 11 01 05 AM](https://user-images.githubusercontent.com/3058939/57947515-f48e4180-7893-11e9-84ef-156c4d2bbfdf.png)

### Text
```
Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're %s `%s` on a released/nullified synthetic event. %s. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information., accessing the property, target, This is set to null
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:619:8 in warningWithoutStack
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:1577:10 in warn
- node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:1569:9 in get$$1
* [native code]:null in stringify
- node_modules/@storybook/react-native/node_modules/@storybook/channel-websocket/dist/index.js:67:46 in sendNow
- node_modules/@storybook/react-native/node_modules/@storybook/channel-websocket/dist/index.js:56:21 in send
- node_modules/@storybook/channels/dist/index.js:126:32 in handler
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:152:14 in _callTimer
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:200:17 in _callImmediatesPass
- node_modules/react-native/Libraries/Core/Timers/JSTimers.js:464:30 in callImmediates
* [native code]:null in callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:320:6 in __callImmediates
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:6 in <unknown>
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:297:10 in __guard
- node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:17 in flushedQueue
* [native code]:null in flushedQueue
* [native code]:null in callFunctionReturnFlushedQueue
```

## Screenshots
### Chrome (`@storybook/react-native-server`)
![Screen Shot 2019-05-17 at 11 00 44 AM](https://user-images.githubusercontent.com/3058939/57947572-1982b480-7894-11e9-9341-7cb320633d87.png)

### iOS Simulator (`@storybook/react-native`)
<img width="545" alt="Screen Shot 2019-05-17 at 11 06 06 AM" src="https://user-images.githubusercontent.com/3058939/57947530-fd7f1300-7893-11e9-8849-3b0a07acea9b.png">
<img width="545" alt="Screen Shot 2019-05-17 at 11 04 03 AM" src="https://user-images.githubusercontent.com/3058939/57947531-fd7f1300-7893-11e9-8530-e04c1d8b982d.png">


## Config
### package.json
```json
  "scripts": {
    "android": "expo start --android",
    "build": "yarn run build:components",
    "build:components": "webpack --config ./webpack.components.js",
    "eject": "expo eject",
    "expo": "expo start",
    "ios": "expo start --ios",
    "start": "npm-run-all --parallel expo storybook",
    "storybook": "start-storybook -p 7007"
  },
  "dependencies": {
    "@emotion/native": "^10.0.11",
    "expo": "^32.0.0",
    "native-base": "^2.12.1",
    "react": "16.5.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-32.0.0.tar.gz",
    "react-router": "^5.0.0"
  },
  "devDependencies": {
    "@babel/preset-react": "^7.0.0",
    "@emotion/core": "^10.0.10",
    "@storybook/addon-actions": "^5.0.11",
    "@storybook/addon-links": "^5.0.11",
    "@storybook/addon-storysource": "^5.0.11",
    "@storybook/addons": "^5.0.11",
    "@storybook/react-native": "^5.0.11",
    "@storybook/react-native-server": "5.1.0-alpha.7",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.5",
    "babel-preset-expo": "^5.0.0",
    "babel-runtime": "^6.26.0",
    "duplicate-package-checker-webpack-plugin": "^3.0.0",
    "emotion-theming": "^10.0.10",
    "npm-run-all": "^4.1.5",
    "prop-types": "^15.7.2",
    "react-dom": "16.5.0",
    "size-plugin": "^1.2.0",
    "storybook-react-router": "^1.0.5",
    "webpack-cli": "^3.3.2",
    "webpack-node-externals": "^1.7.2"
  },
```

### Addon files

#### addons.js
```js
import "@storybook/addon-actions/register";
import "@storybook/addon-links/register";
import "@storybook/addon-storysource/register";
```

#### rn-addons.js
```js
import "@storybook/addon-ondevice-actions/register";
import "@storybook/addon-ondevice-links/register";
import "@storybook/addon-ondevice-storysource/register";
```

**Comment by shilman** [comment]
@alechp Can you open a separate issue? `ondevice-actions` is a RN addon, and I'd like the RN guys to look at it, but I'm not sure it's the same issue.

**Comment by alechp** [comment]
@shilman Roger. New issue created here: https://github.com/storybooks/storybook/issues/6827

**Comment by umakantp** [comment]
I'm getting the following error when I listen to click even on a button and pass it to actions:-

```
_ctx.js:18 Uncaught TypeError: toISOString is not a function
    at String.toJSON (<anonymous>)
    at Object.<anonymous> (_ctx.js:18)
    at JSON.stringify (<anonymous>)
    at Object.stringify (index.js:353)
    at PostmsgTransport.push../node_modules/@storybook/channel-postmessage/dist/index.js.PostmsgTransport.send (index.js:43)
    at handler (index.js:46)
    at Channel.push../node_modules/@storybook/channels/dist/index.js.Channel.emit (index.js:55)
    at action (action.js:32)
    at HTMLUnknownElement.callCallback (react-dom.development.js:149)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:199)
(anonymous) @ _ctx.js:18
stringify @ index.js:353
push../node_modules/@storybook/channel-postmessage/dist/index.js.PostmsgTransport.send @ index.js:43
handler @ index.js:46
push../node_modules/@storybook/channels/dist/index.js.Channel.emit @ index.js:55
action @ action.js:32
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
invokeGuardedCallbackAndCatchFirstError @ react-dom.development.js:270
executeDispatch @ react-dom.development.js:561
executeDispatchesInOrder @ react-dom.development.js:583
executeDispatchesAndRelease @ react-dom.development.js:680
executeDispatchesAndReleaseTopLevel @ react-dom.development.js:688
forEachAccumulated @ react-dom.development.js:662
runEventsInBatch @ react-dom.development.js:816
runExtractedEventsInBatch @ react-dom.development.js:824
handleTopLevel @ react-dom.development.js:4826
batchedUpdates$1 @ react-dom.development.js:20439
batchedUpdates @ react-dom.development.js:2151
dispatchEvent @ react-dom.development.js:4905
(anonymous) @ react-dom.development.js:20490
unstable_runWithPriority @ scheduler.development.js:255
interactiveUpdates$1 @ react-dom.development.js:20489
interactiveUpdates @ react-dom.development.js:2170
dispatchInteractiveEvent @ react-dom.development.js:4882
```

My code is as simple as
`<Button onClick={actions('clicked')}Default</Button>`

Button component accepts the onClick and prop and sets on `<input type="button" onClick={props.onClick} />`.

**Comment by mousemke** [comment]
i just wanted to pass this on. we have been having this issue for a while now (in JS, storybook-react)

we fixed it with a small tweak to how we called actions.  it seemed to be an issue of how the addon was serializing the date.  maybe this just applies to us, but also maybe it'll help some folk

fixed.

<img width="1241" alt="Screenshot 2019-06-12 at 17 44 00" src="https://user-images.githubusercontent.com/1480168/59365934-b6bcf580-8d39-11e9-970a-eae1308ae207.png">

**Comment by montezume** [comment]
I'm also having this issue with the errors / warnings about reusing synthetic events. Any ideas to do a quick fix? There must be a way to wrap `action` so that we call event.persist() before it runs?

**Comment by mallik-svmx** [comment]
I'm having the same issue. Any workaround will be greatly appreciated.

**Comment by mallik-svmx** [comment]
@montezume It worked for me after removing import babel-polyfill.

**Comment by njdancer** [comment]
@montezume Thats what this code does.

```typescript
import { action as brokenAction } from "@storybook/addon-actions"

const action: typeof brokenAction = (name, options) => {
  const constructedAction = brokenAction(name, options)
  return event => constructedAction(event.persist())
}

<Button onPress={action("Button pressed")} />
```

Not sure if there are any serious implications to calling persist on all of these events.

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.39 containing PR #8690 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by tay1orjones** [comment]
This shouldn't be closed. The PR explicitly states 

> "The issue #6471 still persists, but at least we can avoid it by not passing react events to it directy by doing."

You might consider modifying your release script to require the use of specific keywords to auto-close issues, like [GitHub's native functionality](https://help.github.com/en/github/managing-your-work-on-github/closing-issues-using-keywords).

**Comment by petermikitsh** [comment]
This is my solution to action logging concerning React synthetic events.

The key is to set `view` to undefined, because it's a reference to `window`, and logging window substantially slows down the performance of storybook (because window is giant-- that's by no means Storybook's fault or anything).

Use this facade for Storybook's `action` function throughout your project:

```ts
import { action } from '@storybook/addon-actions';

/* Partial event logging, as full logging can be expensive/slow
 * Invocation: partialLog('actionName')(eventObj, ...args)
 */
export const partialAction = (actionName) => {
  const beacon = action(actionName);
  return (eventObj, ...args) => {
    beacon({ ...eventObj, view: undefined }, ...args);
  };
};
```

Literal example in a story:

```tsx
const Template: Story<AccordionProps> = (args) => <Accordion {...args} />;

export const Simple = Template.bind({});
Simple.args = {
  header: 'Hello World',
  body: 'This is my example accordion.',
  onChange: partialAction('dsOnChange'), // fires whenever my accordion expands or collapses
};

```

This fix gets rid of React error message:

```
Warning: This synthetic event is reused for performance reasons. If you're seeing this, you're accessing the method `isDefaultPrevented` on a released/nullified synthetic event. This is a no-op function. If you must keep the original synthetic event around, use event.persist(). See https://fb.me/react-event-pooling for more information.
```

It's a good compromise of logging nearly all the data (except the 'view' property), and keeping Storybook fast.

**Comment by luissmg** [comment]
Hey @shilman, how are you? Do you know by any chance if this is being taken care of in the next release (6.2.0)? Since it is kinda related with performance

**Comment by shilman** [comment]
@luissmg nope! PRs welcome tho and I can try to squeeze it in

**Comment by luissmg** [comment]
Alright! Does the workaround on the top look "ok"? It might be something to be considered adding. I can try to handle that in the next couple days

**Comment by shilman** [comment]
We want to address this in 6.3. If you want to contribute to Storybook, we'll prioritize PR review for any fixes here. And if you'd like any help getting started, please jump into the #support channel on our Discord: https://discord.gg/storybook

**Comment by vdh** [comment]
So far, I've been using the workaround of manually bypassing events for every use of `action` (so, never inlining `action` calls), but it tends to create a lot of boilerplate:
```ts
import { action } from '@storybook/addon-actions';
import MyComponent, { MyComponentProps } from './MyComponent';

type OnChange = MyComponentProps['onChange'];
const changeAction = action('Change');
const mockOnChange: OnChange = event => {
  const newValue = event.target.value;
  changeAction(newValue);
};
```

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-beta.33 containing PR #16514 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
¡Ay Caramba!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.4.0-rc.0 containing PR #16514 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

**Comment by michal-kurz** [comment]
The RC didn't help me with  the synthetic event error, I'm still getting it in my project for actions auto-generated via `react-docgen-typescript` after upgrading (I checked I have `6.4.0-rc.6` in my package lock). This seems to be clogging the execution thread for multiple seconds with MuI Tooltip, as it autogenerates (and throws an error in) about 40 callbacks on hover. Unfortunately I wasn't able to reproduce this in a clean repo :/ Could someone please point me at a helpful direction to go from here?

**Comment by forivall** [comment]
@michal-kurz do you have any reproduction case that i can take a look at? (even if it's not clean). I'm not sure what exactly you mean by "clean repo", and i don't know which exact library you're talking about (material-ui? which one? etc).

Basically, i wrote this fix in a way to detect that the event is a synthetic event in a best-effort approach, which means that we can only detect that it's a synthetic event when using the development build of react and when function names arent mangled.

**Comment by michal-kurz** [comment]
@forivall I did manage to make a reproduction scenario today! In my previous attempt I was on React version 17, but synthetic event pooling was removed in 17.0.0. I just remembered that today, went to my previous attempt, bumped down React version to 16 and sure enough the error is there, on `6.4.0-rc.6`.  

I made the scenario as a separate branch on a different repo I made earlier to demonstrate a different issue. [Here it is](https://github.com/michal-kurz/storybook-controls-bug-reporuction-repo/tree/synthetic-event-error). The reproduction scenario is described in the branches README. I think the example will answer all of your questions better than I could :). But if there's something I can add, let me know!

Also, if you do find the time to look at it, would you mind answering the following question, please? Do you think the errors could be the reason for the extremely long delay before hovering the element and the tooltip actually showing up? Or is there something else you suspect? Finding out an answer to that would help me greatly :) Thank you very much!

**Comment by forivall** [comment]
Sorry, i haven't had a chance to take a look yet.
