### ISSUE TITLE
SB5 Theming breaks React 15 compat

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#6474]
## The problem
Currently theming operates in `config.js` which is "preview" code (user code). It requires Emotion, which in turn requires React 16.3+.

In `5.0.x` the workaround is to not theme Storybook.

This breaks in `5.1.x`, probably due to https://github.com/storybooks/storybook/pull/6435

I've created an example and added it to the repo so we can discuss around it, and also to make sure we don't inadvertently break back-compat in the future. Coming in a PR shortly.

## The solution
Allow users to configure the manager separately from the preview, as relates to https://github.com/storybooks/storybook/issues/4796 https://github.com/storybooks/storybook/issues/4995

- [ ] split out `create` into its own file
- [ ] update documentation

**Comment by tmeasday** [comment]
There is another solution which I suggested somewhere else and which seems to have dropped off the map: rearrange `@storybook/theming` so the bit that you import from `config.js` doesn't import from emotion.

This doesn't seem at all hard to do, I had just asked @ndelangen some question about the animation stuff but he hadn't responded. I can take a look at it if we clear that up (that's the file that imports emotion)

**Comment by ndelangen** [comment]
Should be fixed in this PR:
https://github.com/storybooks/storybook/pull/6475

**Comment by ndelangen** [comment]
Thanks for the repro branch @shilman !

**Comment by shilman** [comment]
Yowza!! I just released https://github.com/storybooks/storybook/releases/tag/v5.1.0-alpha.40 containing PR #6475 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by natocTo** [comment]
I have tried it and still get same error.
```js
TypeError: Object(...) is not a function
```
problem is here: (core.browser.esm.js)
```js
var EmotionCacheContext = createContext(createCache());
```
There is problem with two versions of React. I use React 15 and Emotion use React 16. Import `createContext` from React 15 is resolved as undefined so it can not be call as function.

**Comment by mundosk8** [comment]
Im facing the same problem also. Even using the next tag

**Comment by ndelangen** [comment]
@shilman do you know how to reproduce this?

**Comment by shilman** [comment]
This issue seems like it hasn't gotten much action lately. Closing, please shout if you're still stuck on this!
