### ISSUE TITLE
Angular Storyshots 5.0.6: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by rfreydi** [storybookjs/storybook#6490]
**Describe the bug**
I was trying to follow the tutorial from https://www.learnstorybook.com/angular/en/simple-component/ but got a lot of trouble (the doc for jest-preset-angular is not up to date and hard to find the right way).

I'm stuck with last step, I think I configured everything up but when I run the jest test angularshots.test.ts fail. it look like it's the import 'global' which doesn't work properly from addon-storyshots/dist/api/index.js.

**To Reproduce**
1. Clone repository at https://github.com/chromaui/learnstorybook-code/tree/angular
2. Apply the patch from attached file (remove .txt in the extension)
3. Run "npm i"
4. Run "npm run jest"
5. See error

I personally use Intellij IDEA built-in Jest runner which is more visual (screenshot come from it)

[migrate_to_v5.patch.txt](https://github.com/storybooks/storybook/files/3069146/migrate_to_v5.patch.txt)

**Expected behavior**
The test should run like for the v3 version of the repo

**Screenshots**
v5
![image](https://user-images.githubusercontent.com/21192766/55965177-5694cf00-5c76-11e9-8852-bd02fa15164d.png)

v3
![image](https://user-images.githubusercontent.com/21192766/55965395-cd31cc80-5c76-11e9-9cd9-2647145d0c0b.png)

**System:**
 - OS: MacOS
 - Device: MacBook Pro (15-inch, 2018)
 - NodeJS: v11.12.0
 - Framework: Angular 7.3.8
 - Addons: storyshots
 - Version: 5.0.6

**Comment by markusdresch** [comment]
I got the same problem with
* Storyshots ^5.0.11
* OS: Windows 10
* Node v11.12.0
* Angular 8.0.0-rc.4

```
TypeError: Cannot read property 'get' of undefined

    > 1 | import initStoryshots, { multiSnapshotWithOptions } from '@storybook/addon-storyshots';
        | ^
      2 | 
      3 | initStoryshots({
      4 |     test: multiSnapshotWithOptions({}),

      at _interopRequireWildcard (node_modules/@storybook/addon-storyshots/dist/api/index.js:22:331)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/api/index.js:8:15)
      at Object.<anonymous> (node_modules/@storybook/addon-storyshots/dist/index.js:52:35)
      at Object.<anonymous> (src/storyshots.test.ts:1:1)
```

**Comment by rfreydi** [comment]
Up (to not get closed again for nothing...)

**Comment by AkshayRana92** [comment]
Hi, I'm also having the same issue. Did anyone find a solution yet?

**Comment by bjufre** [comment]
@AkshayRana92 @rfreydi any luck setting it up? Getting the same exact error and can't figure out why :|

**Comment by costalvaro** [comment]
Hi, same issue on my side (Angular 8.2.12 & Storybook 5.2.5).
+1 about the fact that the tutorial would require a refresh to fit with current jest-preset-angular version.

**Comment by Hypnosphi** [comment]
I can reproduce in in `master` but not in `next`. Still have to find out what fixed it

**Comment by cloakedninjas** [comment]
I seem to be getting this in `5.2.6` 😟

**Comment by Hypnosphi** [comment]
@shilman https://github.com/storybookjs/storybook/pull/8776 is yet unreleased, right?

**Comment by cloakedninjas** [comment]
Hmm, running this on Node 10 (matching our build server) this issue goes away, but on my new laptop (with Node `13.2.0`) it fails 🤷‍♂

**Comment by Hypnosphi** [comment]
Yes, it's an issue specific to newer Node versions

**Comment by cloakedninjas** [comment]
This is now resolved as of `5.3.3`

**Comment by shilman** [comment]
awesome! closing!

**Comment by arun678** [comment]
> This is now resolved as of `5.3.3`

No i installed a fresh copy from create react app and then storybook with npx -p @storybook/cli sb init --type react_scripts
. But still getting the same error

**Comment by shilman** [comment]
@arun678 this is an angular issue?

**Comment by arun678** [comment]
> @arun678 this is an angular issue?

No, it's react. But have encountered same error.
