### ISSUE TITLE
The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. 

### ISSUE THREAD

**Issue by ringodotnl** [storybookjs/storybook#6998]
**Describe the bug**
At the console: The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".

**To Reproduce**
Run the angular demo in this repo and check the console.

**Expected behavior**
No error log

**System:**
 - OS: [Windows10,]
 - Device: [Desktop]
 - Browser: [Chrome]
 - Framework: [angular]
 - Addons: [all]
 - Version: [5.1.1 and 5.2.0-alpha.21]

**Comment by NickSofology** [comment]
I have also got this error since upgrading.

**Comment by magicspon** [comment]
I'm also seeing this... except with React.

**Comment by javidhsueh** [comment]
same here with React
Version: SB@v5.1.3

**Comment by B3Kay** [comment]
Im also seeing this error with React:

```javascript
"react": "^16.4.0",
"react-dom": "^16.4.0"
```

```javascript
 "@storybook/addon-links": "^5.0.11",
 "@storybook/addon-notes": "^5.0.11",
 "@storybook/addon-storyshots": "^5.0.11",
 "@storybook/addon-storyshots-puppeteer": "^5.0.11",
 "@storybook/addon-storysource": "^5.0.11",
 "@storybook/addons": "^5.0.11",
```

**Comment by nmorris2** [comment]
Also seeing the same error with Storybook and Vue after upgrading to 5.1.3.

**Comment by lPaths** [comment]
```
"@storybook/react" "^5.1.7"
```
The error still there

**Comment by HiHiPoBang** [comment]
```
"vue": "^2.6.10"
```
```
"@storybook/addon-actions": "^5.1.7",
"@storybook/addon-links": "^5.1.7",
"@storybook/addons": "^5.1.7",
"@storybook/vue": "^5.1.7"
```
The error is still there after upgrading (v5.1.3 -> v5.1.7)
repo: [https://github.com/HiHiPoBang/storybook-demo](url)

**Comment by shilman** [comment]
@HiHiPoBang we'll comment here when the issue is fixed. Or feel free to issue a PR to fix it if you're in a rush! 👍

**Comment by gms1** [comment]
the upstream bug:
https://github.com/emotion-js/emotion/issues/1105

**Comment by kon-rad** [comment]
same here - react 16.6.3

**Comment by gabrielmoncea** [comment]
Same here!
```
 "@storybook/addon-actions": "^5.1.9",
 "@storybook/react": "^5.1.9",
```

**Comment by VladimirHumeniuk** [comment]
Any updates about this? 🤔

**Comment by ashnamuh** [comment]
I have a same issue on

```
    "@storybook/addon-actions": "^5.1.9",
    "@storybook/vue": "^5.1.9",
```

**Comment by rajkeshwar** [comment]
I have same issue on 

```js 
    "@storybook/addon-actions": "^5.1.9",
    "@storybook/addon-links": "^5.1.9",
    "@storybook/addons": "^5.1.9",
    "@storybook/react": "^5.1.9",
```

**Comment by Travilioni** [comment]
Only deactivating these addons, resolves issue. 
unfortunately we need them.
"@storybook/addon-a11y": "5.1.9",
"@storybook/addon-actions": "5.1.9",
"@storybook/addon-knobs": "5.1.9",

**Comment by Travilioni** [comment]
Only deactivating these addons, resolves issue.
unfortunately we need them.
`"@storybook/addon-a11y": "5.1.9",
"@storybook/addon-actions": "5.1.9",
"@storybook/addon-knobs": "5.1.9",`

**Comment by omrilotan** [comment]
The reason for this error has to do with `<style>` elements being added inline in the DOM when doing SSR.
It seems to me that the recommendation is a good one. Using `:first-of-type` will resolve this.

Other, more generic alternatives may be:
- `:first-child:not(style)`
- `style:first-child + *`

**Comment by leetercola** [comment]
> 
> ```css-scss
> & > :first-child:not(style), & > style:first-child + * {
> ```
@omrilotan 
Can you explain how this is any better and would stop the warning as it still uses first-child?

**Comment by omrilotan** [comment]
> > ```
> > & > :first-child:not(style), & > style:first-child + * {
> > ```
> 
> @omrilotan
> Can you explain how this is any better and would stop the warning as it still uses first-child?

Of course. This selector is made up of two parts:
1. `& > :first-child:not(style)` The first child *unless it is a style tag*
2. `& > style:first-child + *` The adjacent sibling immediate following a first element which *is a style tag*

Thus covering both options.
```html
<parent>
	<style/>
	<child/> <!-- this one -->
	<other-child/>
</parent>

<parent>
	<child/> <!-- this one -->
	<other-child/>
</parent>
```

**Comment by Haroenv** [comment]
IIRC the css to change is here: https://github.com/storybookjs/storybook/blob/81e399648ba65006130768bac6890517ca5b3091/lib/components/src/tabs/tabs.tsx#L76

**Comment by gmotzespina** [comment]
I got the same error while doing the following,

```
npx -p @angular/cli ng new my-app --style css
cd my-app

# Add Storybook:
npx -p @storybook/cli sb init

# Run the test runner (Karma) in a terminal (we will add Jest along the way):
yarn test

# Start the component explorer on port 6006:
yarn run storybook

# Run the frontend app proper on port 4200:
yarn start
```

### Error
```sh
Can't resolve all parameters for AppComponent: (?, ?, [object Object]).
Error: Can't resolve all parameters for AppComponent: (?, ?, [object Object]).
    at syntaxError (http://localhost:6006/vendors~main.3bd8b3ded11253e53459.bundle.js:9483:17)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata (http://localhost:6006/vendors~main.3bd8b3ded11253e53459.bundle.js:28502:35)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata (http://localhost:6006/vendors~main.3bd8b3ded11253e53459.bundle.js:28394:26)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://localhost:6006/vendors~main.3bd8b3ded11253e53459.bundle.js:28013:24)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getEntryComponentMetadata (http://localhost:6006/vendors~main.3bd8b3ded11253e53459.bundle.js:28598:28)
    at http://localhost:6006/vendors~main.3bd8b3ded11253e53459.bundle.js:28257:163
    at Array.map (<anonymous>)
    at CompileMetadataResolver.push../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata (http://localhost:6006/vendors~main.3bd8b3ded11253e53459.bundle.js:28257:128)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules (http://localhost:6006/vendors~main.3bd8b3ded11253e53459.bundle.js:34297:51)
    at JitCompiler.push../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents (http://localhost:6006/vendors~main.3bd8b3ded11253e53459.bundle.js:34278:36)
```

**Comment by BerQin** [comment]
> 在执行以下操作时，我遇到了同样的错误，
> 
> ```
> npx -p @angular/cli ng new my-app --style css
> cd my-app
> 
> # Add Storybook:
> npx -p @storybook/cli sb init
> 
> # Run the test runner (Karma) in a terminal (we will add Jest along the way):
> yarn test
> 
> # Start the component explorer on port 6006:
> yarn run storybook
> 
> # Run the frontend app proper on port 4200:
> yarn start
> ```
> 
> ### 错误
> ```shell
> 可以'牛逼解析AppComponent所有参数：（？，[目标对象]）。
> 错误：“牛逼解决所有的参数为 AppComponent：（ ？ ，？ ，[目标对象]）。
>     at syntaxError（http：// localhost：6006 / vendors~main.3bd8b3ded11253e53459.bundle.js：9483：17）
>     at CompileMetadataResolver.push ../ node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getDependenciesMetadata（http） ：// localhost：6006 / vendors~main.3bd8b3ded11253e53459.bundle.js：28502：35）
>     at CompileMetadataResolver.push ../ node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getTypeMetadata（http：// localhost） ：6006 /厂商〜main.3bd8b3ded11253e53459.bundle.js：28394：26）
>     在CompileMetadataResolver.push ../ node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNonNormalizedDirectiveMetadata（HTTP：//本地主机：6006 /厂商〜main.3bd8b3ded11253e53459.bundle.js：28013：24）
>     在CompileMetadataResolver.push ../node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver._getEntryComponentMetadata（http：// localhost：6006 / vendors~main.3bd8b3ded11253e53459.bundle.js：28598：28）
>     位于http：// localhost：6006 /vendors~main.3bd8b3ded11253e53459.bundle.js:28257:163 
>     在Array.map（< anonymous >）
>     在CompileMetadataResolver.push ../ node_modules/@angular/compiler/fesm5/compiler.js.CompileMetadataResolver.getNgModuleMetadata（HTTP：//本地主机：6006 /厂商〜main.3bd8b3ded11253e53459.bundle.js：28257：128）
>     在JitCompiler.push ../node_modules/@angular/compiler/fesm5/compiler.js.JitCompiler._loadModules（http：// localhost：6006 / vendors~main.3bd8b3ded11253e53459.bundle.js：34297：51）
>     at JitCompiler.push ../ node_modules /@angular/compiler/fesm5/compiler.js.JitCompiler._compileModuleAndComponents(http://hosthost：6006 / vendors~main.3bd8b3ded11253e53459.bundle.js：34278：36）
> ```

I met the same mistake,How to solve

**Comment by RDUBPhoto** [comment]
Getting the exact same errors as mentioned:

`    "@angular-devkit/build-angular": "~0.802.0",
    "@angular/cli": "~8.2.0",
    "@angular/compiler-cli": "~8.2.0",
    "@angular/language-service": "~8.2.0",
    "@babel/core": "^7.5.5",
    "@storybook/addon-actions": "^5.1.10",
    "@storybook/addon-info": "^5.1.10",
    "@storybook/addon-links": "^5.1.10",
    "@storybook/addon-notes": "^5.1.10",
    "@storybook/addons": "^5.1.10",
    "@storybook/angular": "^5.1.10",`

`vendors~main.5d83abd61dceb2c27289.bundle.js:617 The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type".
(anonymous) @ vendors~main.5d83abd61dceb2c27289.bundle.js:617`

**Comment by brandonkal** [comment]
For those who want a quick fix, save this snippet as preview-head.html and manager-head.html in your storybook directory.
```html
<script>
  // Clean console hack for Storybook by @brandonkal
  // emotion leaves some pesky console warnings in Storybook.
  // Let's hide those as we are not using emotion.
  // define a new console
  let change = (function(oldCons) {
    function shouldIgnore(text) {
      let all = text.join(' ')
      return (
        all.includes('":first-child" is potentially unsafe') ||
        all.includes('Please update the following components: Draggable')
      )
    }
    window.console.log = (...text) => {
      if (shouldIgnore) return
      return oldCons.log(...text)
    }
    window.console.info = (...text) => {
      if (shouldIgnore) return
      return oldCons.info(...text)
    }
    window.console.warn = (...text) => {
      if (shouldIgnore) return
      return oldCons.warn(...text)
    }
    window.console.error = (...text) => {
      if (shouldIgnore) return
      return oldCons.error(...text)
    }
  })(window.console)
</script>
```

**Comment by vladreed** [comment]
In **"5.1.11"** still reproducible

**Comment by pelotom** [comment]
> For those who want a quick and dirty fix, save this snippet as preview-head.html and manager-head.html in your storybook directory.

Buyer beware, this code has at least 3 problems:
1. `if (shouldIgnore)` will always succeed, so you're effectively silencing all logs. Should be `if (shouldIgnore(...text))`
1. If you fix the previous bug you'll now have a stack overflow when logging happens because `oldCons` is just a reference to `window.console`
1. This will not work in older browsers because it uses `String.includes`.

**Comment by brandonkal** [comment]
Oh yes. Good catch on point 1. Thank you.
Interestingly, logs were still getting through. You'd have to go pretty far back to find a browser that doesn't support String.includes or ES6.

**Comment by brandonkal** [comment]
> IE11 support is still a requirement for many of us.

I pity the developer that develops his components with a 6 year old browser. 😃  

IE likely won't die for another 8 years which is a shame. But I understand it is the current lowest denominator target.

**Comment by shilman** [comment]
Shiver me timbers!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.41 containing PR #7861 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by Yaowenjie** [comment]
@shilman the version including the fix is still pre-release, and is still not included in the latest release version (v5.3.13). Do you know when it will come into the new formal release?

**Comment by shilman** [comment]
@Yaowenjie 5.2 was released months ago. Did #7861 not fix the problem? Or did it regress at some point between 5.2.0-beta.41 and 5.3.13?

**Comment by Yaowenjie** [comment]
@shilman Thanks for reply! I didn't check 5.2, but with 5.3.13, the warning is still there.

**Comment by dgellow** [comment]
Using `"@storybook/react": "^5.3.17"`, I can confirm I still get the error.

**Comment by datdotatprotocol** [comment]
The error still exists when using `"@storybook/react"`.
The error is shown when using [CSF Stories with MDX Docs](https://github.com/storybookjs/storybook/blob/next/addons/docs/docs/recipes.md#csf-stories-with-mdx-docs).

Detailed steps:

- Import `Props` from `addon-docs`.

- Put `<Props of={Component} />` into the code.

- Hovering on Component item and the error is shown.

**_Notice:_** Without `<Props of={Component} />`, the error will not appear.

**Comment by charleshimmer** [comment]
I get this error on "@storybook/react": "^5.3.18" as well.

**Comment by vnues** [comment]
Any updates about this? 🤔

**Comment by jmadelaine** [comment]
The problem is that Emotion's SSR sometimes injects a `style` element as the first child, therefore the `:first-child` selector refers to the `style` element instead of the element we intend.

You can get around this by applying style to all children, and then unsetting that style by applying style to all children _except_ the first child that isn't a `style` element:

```css
.parent > * {
  /* 1. Styling all children with the style we want for the first element */
}

.parent > *:not(style) + * {
  /* 2. Unset style applied to all children. */
  /* This effects all children except the first child (that isn't a style element) */
}
```

This will leave only the first (non-style element) child with the style from step 1.

In my case, I wanted to add `margin-top` to all children except the first child, so I only had to do step 2:

```css
/* All children except the first child (not including style elements) get a margin-top */
.parent > *:not(style) + * {
  margin-top: 16px
}
```

Obviously this doesn't work if there are `style` elements found part way through the child array, but that's something I've never seen before.

**Comment by hendriklammers** [comment]
Currently facing the exact same issue after updating Storybook with `npx sb@latest upgrade` to 6.5.0

```
    "@storybook/addon-actions": "^6.5.0",
    "@storybook/addon-essentials": "^6.5.0",
    "@storybook/addon-links": "^6.5.0",
    "@storybook/react": "^6.5.0",
```

**Comment by robbishop** [comment]
Same here, just upgraded to 6.5.0 and "pseudo class ":first-child" is potentially unsafe..."

**Comment by fullsnackdeveloper** [comment]
Same here, using 6.5.3 and "pseudo class ":first-child" is potentially unsafe..."

**Comment by NicolasReibnitz** [comment]
Dito! Update to 6.5.3 brought that up here too.

```
"@storybook/addon-actions": "^6.5.3",
"@storybook/addon-essentials": "^6.5.3",
"@storybook/addon-interactions": "^6.5.3",
"@storybook/addon-links": "^6.5.3",
"@storybook/builder-vite": "^0.1.35",
"@storybook/testing-library": "^0.0.11",
"@storybook/vue3": "^6.5.3",
"storybook-dark-mode": "^1.1.0",
```

**Comment by Muranaka-Kosuke** [comment]
Same here, using 6.5.3 and "pseudo class ":first-child" is potentially unsafe..."

**Comment by asso1985** [comment]
Same here seems to be back

**Comment by rafahell** [comment]
Same here, just upgraded to 6.5.0 and "pseudo class ":first-child" is potentially unsafe..."

**Comment by gregorybolkenstijn** [comment]
Upgraded to 6.5.0 and starting getting these errors. Upgraded to 6.5.3 and still got the same errors "The pseudo class ":first-child" is potentially unsafe when doing server-side rendering. Try changing it to ":first-of-type"."

<img width="844" alt="image" src="https://user-images.githubusercontent.com/683497/169531360-7918fc6c-3998-4577-a18a-eea491a602ac.png">

**Comment by jonsoku2** [comment]
6.5.3 is same...
<img width="807" alt="image" src="https://user-images.githubusercontent.com/51524954/169634299-26e5ef83-c754-4672-8afb-0182cf4e63f9.png">

**Comment by slowselfip** [comment]
Seem to be some css that still does not have the `ignoreSsrWarning` https://github.com/storybookjs/storybook/blob/68a73b8087f22324636d135519a230e9185c3774/lib/core-common/templates/base-preview-head.html#L266-L275

Here's a search for reference : https://github.com/storybookjs/storybook/search?q=%2A%3Afirst-child&type=code.

**Comment by lsebastiankellner** [comment]
Same here after upgrading to 6.5.4 :(

**Comment by jeripeierSBB** [comment]
See #18103

**Comment by vdh** [comment]
For anyone else wanting to hack this annoyance away with a `yarn patch`, I found it hiding away inside `@storybook/theming`.

**Comment by shilman** [comment]
follow at https://github.com/storybookjs/storybook/issues/18103

**Comment by AnnabellFlem** [comment]
Same here at `6.5.6` as well

**Comment by rv7918** [comment]
6.5.6 also.

**Comment by fivaz** [comment]
the same with storybook/react 6.5.5

**Comment by lukePeavey** [comment]
@vdh could you explain what you mean by this?

> For anyone else wanting to hack this annoyance away with a yarn patch, I found it hiding away inside @storybook/theming

**Comment by euaaaio** [comment]
Same

**Comment by xxxKOTxxx** [comment]
6.5.7 - same problem
Anybody cares?

**Comment by vdh** [comment]
> @vdh could you explain what you mean by this?
> 
> > For anyone else wanting to hack this annoyance away with a yarn patch, I found it hiding away inside @storybook/theming

`createUnsafeSelectorsAlarm` inside `@storybook/theming` is what is generating this log spam. It can be patched away via Yarn (`yarn patch @storybook/theming`) and this patch:
```diff
diff --git a/dist/cjs/index.js b/dist/cjs/index.js
index 1b8b61eac2d191f1a8e1421a57d2738b37d06937..9137b52c3b624ccc3ac980799785da12f1c93ff9 100644
--- a/dist/cjs/index.js
+++ b/dist/cjs/index.js
@@ -1396,15 +1396,6 @@ var createCache = function createCache(options) {
 
   var omnipresentPlugins = [compat, removeLabel];
 
-  if (process.env.NODE_ENV !== 'production') {
-    omnipresentPlugins.push(createUnsafeSelectorsAlarm({
-      get compat() {
-        return cache.compat;
-      }
-
-    }), incorrectImportAlarm);
-  }
-
   if (isBrowser$6) {
     var currentSheet;
     var finalizingPlugins = [stringify, process.env.NODE_ENV !== 'production' ? function (element) {
diff --git a/dist/esm/index.js b/dist/esm/index.js
index e7b796a97d657ea711285724a54b40d4c4e06ccf..f65669abd258db602d3d9e32e9b70d7f9002ebda 100644
--- a/dist/esm/index.js
+++ b/dist/esm/index.js
@@ -1445,15 +1445,6 @@ var createCache = function createCache(options) {
 
   var omnipresentPlugins = [compat, removeLabel];
 
-  if (process.env.NODE_ENV !== 'production') {
-    omnipresentPlugins.push(createUnsafeSelectorsAlarm({
-      get compat() {
-        return cache.compat;
-      }
-
-    }), incorrectImportAlarm);
-  }
-
   if (isBrowser$6) {
     var currentSheet;
     var finalizingPlugins = [stringify, process.env.NODE_ENV !== 'production' ? function (element) {
diff --git a/dist/modern/index.js b/dist/modern/index.js
index 4006f0846b2711d82fef0cad026814307192ba98..f6b2b560e3a708a18830bd2c9139b7f4a622cf33 100644
--- a/dist/modern/index.js
+++ b/dist/modern/index.js
@@ -1366,15 +1366,6 @@ var createCache = function createCache(options) {
 
   var omnipresentPlugins = [compat, removeLabel];
 
-  if (process.env.NODE_ENV !== 'production') {
-    omnipresentPlugins.push(createUnsafeSelectorsAlarm({
-      get compat() {
-        return cache.compat;
-      }
-
-    }), incorrectImportAlarm);
-  }
-
   if (isBrowser$6) {
     var currentSheet;
     var finalizingPlugins = [stringify, process.env.NODE_ENV !== 'production' ? function (element) {
```

**Comment by shilman** [comment]
Please try upgrading to the latest release https://github.com/storybookjs/storybook/releases/tag/v6.5.8

```
npx storybook upgrade
```

Does that fix it?

**Comment by xxxKOTxxx** [comment]
> Does that fix it?
For me - yes!
Thank You!

**Comment by rv7918** [comment]
The console error has gone after upgrading to 6.5.8 for me. also.

**Comment by BiancaArtola** [comment]
That's do the trick for me! Thanks

**Comment by shilman** [comment]
Huge props to @Andarist 🙌

**Comment by lukePeavey** [comment]
@vdh thank you for the explanation!

Upgrading to `v6.5.8` resolved the issue for me.

**Comment by katsenkatorz** [comment]
Upgrading to `v6.5.9` it's work for me thanks @shilman

**Comment by charleshimmer** [comment]
Upgrading to v6.5.9 does not work for me as well.

**Comment by AnnabellFlem** [comment]
Upgrading to v6.5.10 doesn't work for me

**Comment by scrptd95** [comment]
Also comes up in v6.5.14. Any solutions for the issue ?

**Comment by ScorpAL** [comment]
Also comes up in v6.5.14

**Comment by RobineSavert** [comment]
Any updates on this? We have the same error...

**Comment by krakadet** [comment]
The same error at storybook 7

**Comment by idMolotov** [comment]
Also appears in v6.5.16
