### ISSUE TITLE
Warning: Received `true` for a non-boolean attribute `loading`.

### ISSUE THREAD

**Issue by HiHiPoBang** [storybookjs/storybook#7049]
**Describe the bug**
At the console: Warning: Received `true` for a non-boolean attribute `loading`.

**To Reproduce**
1.  vue create my-project
2. npx -p @storybook/cli sb init --type vue
3. Then follow the doc from [https://storybook.js.org/docs/guides/guide-vue/](url)

repo: https://github.com/HiHiPoBang/storybook-demo

**Expected behavior**
No error log

**Screenshots**
<img width="1263" alt="螢幕快照 2019-06-11 下午8 04 13" src="https://user-images.githubusercontent.com/51361109/59270956-5bc9c680-8c85-11e9-8063-75e8d80f0d83.png">

**System:**
 - OS: [MacOS]
 - Device: [iMac 2017]
 - Browser: [chrome]
 - Framework: [vue]
 - Addons: [all]
 - Version: [5.1.3]

**Comment by gorilazish** [comment]
I get this one as well on React project (Storybook 5.1.3)

**Comment by Nightbr** [comment]
I get it also on HTML (stenciljs)
```
    "@storybook/addon-actions": "^5.1.3",
    "@storybook/addon-backgrounds": "^5.1.3",
    "@storybook/addon-knobs": "^5.1.3",
    "@storybook/addon-notes": "^5.1.3",
    "@storybook/html": "^5.1.3",
    "@storybook/theming": "^5.1.3",
```

**Comment by neil-morrison44** [comment]
Seeing this as well with a react storybook with the following deps:

```
    "@storybook/addon-actions": "^5.1.3",
    "@storybook/addon-backgrounds": "^5.1.3",
    "@storybook/addon-knobs": "^5.1.3",
    "@storybook/addon-storyshots": "^5.1.3",
    "@storybook/addon-storysource": "^5.1.3",
    "@storybook/addon-viewport": "^5.1.3",
    "@storybook/react": "^5.1.3",
```

Interestingly `storyshots` runs the storybook fine -  it'd have been caught in our tests if they were both affected

**Comment by vlaraort** [comment]
getting this too

**Comment by fantun3s** [comment]
getting this as well :/

**Comment by joselcvarela** [comment]
I am also experiencing this using Angular.
```
    "@storybook/addon-actions": "^5.1.3",
    "@storybook/addon-links": "^5.1.3",
    "@storybook/addon-notes": "^5.1.3",
    "@storybook/addons": "^5.1.3",
    "@storybook/angular": "^5.1.3",

```

**Comment by Turkyden** [comment]
@HiHiPoBang Yeah, i get it error in react project too. Could you help me ?

**Comment by HiHiPoBang** [comment]
@Turkyden 
Sorry, I use Vue.js and search the similar problems are also with react, so I guess it' s a bug of storybook.

**Comment by drichar** [comment]
Getting this as well with React
```
"@storybook/addon-actions": "^5.0.11",
"@storybook/addon-knobs": "^5.1.3",
"@storybook/addon-links": "^5.0.11",
"@storybook/addons": "^5.0.11",
"@storybook/react": "^5.0.11",
```

**Comment by B3Kay** [comment]
I get this problem aswell with React

`"react": "^16.4.0",
    "react-dom": "^16.4.0"`

`"@storybook/addon-links": "^5.0.11",
    "@storybook/addon-notes": "^5.0.11",
    "@storybook/addon-storyshots": "^5.0.11",
    "@storybook/addon-storyshots-puppeteer": "^5.0.11",
    "@storybook/addon-storysource": "^5.0.11",
    "@storybook/addons": "^5.0.11",`

**Comment by magnusottosson** [comment]
I downgraded from 5.1.3 to 5.0.11 (which worked perfect before) today but I still get the error message. Could it be a dependancy package that has changed maybe?

**Comment by ndelangen** [comment]
I'm on it

**Comment by Turkyden** [comment]
> @Turkyden
> Sorry, I use Vue.js and search the similar problems are also with react, so I guess it' s a bug of storybook.

哈哈，原来是台湾同胞，你好噢！可惜我现在用的是 react 版的，但是和你遇到的是同样的问题，这个 bug 后来你找到解决方案了吗？

**Comment by HiHiPoBang** [comment]
@Turkyden Not yet, 但上面看來已修正準備merge了

**Comment by ndelangen** [comment]
Is anyone able to give me a repo, that they are experiencing this on? I'm having a hard time tracking/reproducing this in our own repo. I did issue a PR already which I THINK MAY fix it, but I'd like to be sure tbh.

**Comment by HiHiPoBang** [comment]
> Is anyone able to give me a repo, that they are experiencing this on? I'm having a hard time tracking/reproducing this in our own repo. I did issue a PR already which I THINK MAY fix it, but I'd like to be sure tbh.

Hi, you can try this [https://github.com/HiHiPoBang/storybook-demo](url)

**Comment by ndelangen** [comment]
My hero

**Comment by ndelangen** [comment]
YES, I found the issue!

React StrictMode + passing a prop down to a dom-element which it kinda understand, but not really.

**Comment by ndelangen** [comment]
@shilman This requires a patch release from our part to fix for users, I'm opening a PR now

**Comment by ndelangen** [comment]
@HiHiPoBang send me your address in a private convo on discord and I'll send you a batch of swag 
🤜🤛

**Comment by ndelangen** [comment]
PR is open, anyone feel like reviewing it?

**Comment by lPaths** [comment]
does the bug fixed anyone? i still getting this warning!

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.5 containing PR #7073 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by chrisdrackett** [comment]
I'm still getting the issue on 5.1.5 myself

**Comment by mkochendorfer** [comment]
I am also still seeing this issue in 5.1.5.  Looks like https://github.com/storybookjs/storybook/pull/7080 which is the PR that solves this was not actually in the 5.1.5 release.  Perhaps @shilman or @ndelangen  can clarify this.

**Comment by shilman** [comment]
Ack. The PR was not marked with `patch` cc @ndelangen 

Re-releasing now

**Comment by shilman** [comment]
Son of a gun!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.7 containing PR #7080 that references this issue. Upgrade today to try it out!

Closing this issue. Please re-open if you think there's still more to do.

**Comment by mkochendorfer** [comment]
That did the trick.  5.1.7 is working well.

**Comment by joselcvarela** [comment]
> I am also experiencing this using Angular.
> 
> ```
>     "@storybook/addon-actions": "^5.1.3",
>     "@storybook/addon-links": "^5.1.3",
>     "@storybook/addon-notes": "^5.1.3",
>     "@storybook/addons": "^5.1.3",
>     "@storybook/angular": "^5.1.3",
> ```

Version 5.1.7 worked for me

**Comment by numericgraphics** [comment]
Version 5.1.8 storybook/html, opening viewport addons displayed the error --> Warning: Received `false` for a non-boolean attribute `loading`.

**Comment by ndelangen** [comment]
@numericgraphics are you able to reproduce here:
https://monorepo.storybook.now.sh/examples/html-kitchen-sink/?path=/story/welcome--welcome

I'm not, so what am I doing wrong?
Can you give me a bit more detail on how to reproduce the problem?

**Comment by Yankovsky** [comment]
I have same issue as well. You've fixed the issue for lib/ui/src/components/sidebar/SidebarItem.js but I get it for ListItem ![http://s.csssr.ru/U02D248T6/2019-06-21-13-50-11-q96kn_.jpg](http://s.csssr.ru/U02D248T6/2019-06-21-13-50-11-q96kn_.jpg)

**Comment by JosephHalter** [comment]
This issue is already closed. Please refer to https://github.com/storybookjs/storybook/issues/7219 to follow progress on the similar issue in newer versions of Storybook rather than add to this already very long ticket.

**Comment by Silverium** [comment]
In my case, it was the cookies. Removed all cookies and all cached storage, and automagically Addons tab shows again!
