### ISSUE TITLE
Ability to hide Canvas Tab

### ISSUE THREAD

**Issue by B3Kay** [storybookjs/storybook#7066]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that **Canvas** is the main tab. My team use Storybook as a component library but also as a styleguide. We put the styleguide text as Markdown with Notes.

**Describe the solution you'd like**
I would be able to hide the Canvas tab. So the user doesn't need an extra click to read the Notes.

Maybe something like this?
```javascript
storiesOf('Addons|Hide Canvas options', module)
    .addParameters({
        options: {
            panelPosition: 'bottom',
            // To hide canvas tab:
            showCanvas: false,
        },
    })
    .add(
        'Story for MyComponent',
        () => <MyComponent />,
        // If you want to set the options for a specific story
        { options: { showCanvas: false } },
    );
```
**Describe alternatives you've considered**
An alternative would be that you can config each story which tab should be opened upon clicking the specific story.

**Are you able to assist bring the feature to reality?**
I can contribute by reading pull-requests and test.

**Additional context**
![storybook](https://user-images.githubusercontent.com/23380102/59363899-4496e180-8d36-11e9-8ce8-a26f5ccc35c4.png)

**Comment by shilman** [comment]
We do this in a fairly hardcoded way as part of `addon-docs`. @ndelangen I wonder if we should make this more configurable.

**Comment by ndelangen** [comment]
We could 'hide' it, but it must be present in order for storybook to function right now, at least until #4169.

Hiding it via some option would be a possibility.

**Comment by eduina** [comment]
I am currently facing the same problem. Ideally, we could have the option to reorder the tabs as we wish so that for example in my case Notes could come first and Canvas later.

**Comment by shilman** [comment]
You can currently hide all of the non-docs tabs with `--docs`, e.g. `yarn storybook --docs` or `yarn build-storybook --docs`

**Comment by bmayen** [comment]
Is there an option to change the order and/or default selection? We would like to use Storybook primarily for Docs functionality but still have the ability to view the canvas. However, with Canvas in the first position and selected by default, newer users sometimes miss the actual documentation included in the MDX files.

**Comment by shilman** [comment]
@bmayen I'd say that goes into the same feature bucket as hiding canvas tab.

**Comment by sanchez** [comment]
I would love to see the ability to hide the canvas tab for particular stories as well as being able to hide stories so you have the high-level docs tab for a component and that's it

**Comment by sanchez** [comment]
My current fix for this is to just not have any "Story" tags in the documentation, however I then loose the ability for the "Show Code" button. Is there any way to have a preview+code without a Story? Thanks

**Comment by shilman** [comment]
@sanchez see https://github.com/storybookjs/storybook/pull/7966

**Comment by cgatian** [comment]
No I want this!

**Comment by bennypowers** [comment]
At my company, we have two major uses for storybook
1. Documenting our *design system* - this use case is oriented towards the design and product departments
1. Documenting our *web components* - this use case is oriented towards the engineering department

In the former case, we'd prefer to only showcase 'real-world examples' with typical content and properties for our componentss
However in the latter case, we'd prefer to exhaustively document all component properties, with defaults preserved, using minimal placeholder content.

The design-oriented case is perfect for docs mode, while we would still like to retain the canvas for engineers to play with as needed.

However, we all agree that to put our 'best foot forward', the pretty docs mode should be displayed more prominently.

To that end, we'd like to be able to configure storybook to show the "Docs" tab at the far left, with "Canvas" to the right.

**Comment by shilman** [comment]
Lots of requests for this, both here and in chat. It's probably a general SB UI issue and not a docs-specific thing, but we'll figure out a solution one way or another. cc @ndelangen

**Comment by matiasmenker** [comment]
> @eduina @B3Kay FYI You can currently hide all of the non-docs tabs with the `--docs` flags, e.g. `yarn storybook --docs` or `yarn build-storybook --docs`

If we do that the addons disappear there is some way to show the addons?

**Comment by shilman** [comment]
@matiasmenker https://github.com/storybookjs/storybook/issues/6700

**Comment by LarsDenBakker** [comment]
Running into this myself as well. Any pointers where one could start to work on a PR?

**Comment by ndelangen** [comment]
Lars it's not super easy. the way `preview.js` works: https://github.com/storybookjs/storybook/blob/a007de8dfd3ea7db08f88970b410a62615c5546f/lib/ui/src/components/preview/preview.js#L267-L300

The tab is injected there.

We'd have to detach adding the tab from the rendering of the iframe.

We can't NOT inject the iframe, because the iframe also renders docs & actually tells the manager which stories to display in the explorer.

**Comment by atanasster** [comment]
@LarsDenBakker - its actually implemented and waiting #9095 , give it a thumbs up to speed up the review and merge process :)

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.2 containing PR #9095 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by JanST123** [comment]
PR #9005 is nice but I am still missing the feature to set a default tab: Even if - for example - the Docs tab is placed to the first position, the canvas tab is active when opening a story.

**Comment by kushalmahajan** [comment]
> @eduina @B3Kay FYI You can currently hide all of the non-docs tabs with the `--docs` flags, e.g. `yarn storybook --docs` or `yarn build-storybook --docs`

Verified on 5.3.7 and 5.3.14 to be not working. Canvas tab is still visible

**Comment by eduina** [comment]
Then I am not sure what was even achieved in this PR

**Comment by kushalmahajan** [comment]
Waiting for this release desperately now. I'm almost done with the upgrade after holding this update for long. @shilman migt know my history of bugs raised with `addon-info`.  Off it goes from my project. 
Successfully updated. Beautiful usage of `CSF` and `docspage`. Loved it! 

Please speed this release if possible. Dependent on it.

**Comment by shilman** [comment]
You can track the release status here https://github.com/storybookjs/storybook/issues/9311

**Comment by dcts** [comment]
@B3Kay I have the same issue. You can replace in the storybook url `/?path=/story/` with `/?path=/docs/` to have the docs selected whenever the storybook is opened. 

To hide the button (not ideal fix at all) I am just adding the following CSS to a browser extension that injects CSS (of course this only works for you, your other company members will still see it):
```css
#root > div > div.css-sqdry3 > div > div.css-sqdry3 > div:nth-child(1) > div > div.simplebar-wrapper > div.simplebar-mask > div > div > div > div > div.css-11sh1n2 > div.css-1tgscux > a:nth-child(1) > button {
    display: none;   
}
```

Not ideal but maybe thats usefull to someone.

**Comment by hv-pul** [comment]
If anyone is interested, I have a solution that is working well for me.

1)
I created a super simple plugin with this. It's `register.js` is this:

```javascript
import { addons } from '@storybook/addons';
import { STORY_RENDERED, DOCS_RENDERED } from '@storybook/core-events';

const ADDON_ID = 'YOUR_PLUGIN_ID';

addons.register(ADDON_ID, api => {
	// Check whether we are on a docsOnly page and add a corresponding body class for styling
	const setBodyClass = () => {
		// Needs animation frame to make sure story component has been mounted
		window.requestAnimationFrame(() => {
			const isDocsOnly = api.getCurrentStoryData().parameters.docsOnly === true;

			if (isDocsOnly) {
				document.body.classList.add('is-docs-only');
			} else {
				document.body.classList.remove('is-docs-only');
			}
		});
	};

	api.on(STORY_RENDERED, setBodyClass);
	api.on(DOCS_RENDERED, setBodyClass);
});
```

In my `manager-head.html`
```css
.is-docs-only .os-content a:not([id])[href*="?path=/story"] {
	display: none !important;
}
```

On my `docsOnly` pages, I set `viewMode: 'docs'` to make sure navigation works nicely.


You can change the logic of when to hide the canvas button of course, you have full access to the storybook API, so you can also configure it per-story etc.

**Comment by corysimmons** [comment]
I'm sure there is a way to inject global CSS to Storybook via the webpack config or something. So you can do this to hide the Canvas tab:

```css
div[role="main"] .os-content a[href*="/?path=/story"] {
  display: none;
}
```

Then add `viewMode: 'docs'` to auto-focus the Docs tab:

```js
// preview.js
export const parameters = {
  actions: { argTypesRegex: "^on[A-Z].*" },
  controls: {
    matchers: {
      color: /(background|color)$/i,
      date: /Date$/,
    },
  },
  viewMode: 'docs' // Add this
}
```

If someone wants to update this with the correct way to add global CSS to a Storybook, it'd solve this problem for everyone. I'm happy with just the default tab being Docs though.

**Comment by DominicTobias** [comment]
> ```css
> /* this should get the first link with that path in the URL (which happens to be the Canvas tab) */
> [role="main"] [href*="/?path=/story"] {
>   display: none;
> }
> ```

Thanks I could have lived with Canvas but found the UX poor with `viewMode: 'docs'` since if you switch to Canvas it will switch right back to Docs when you click on another story so it might as well not be there! Also being able to change the order would be great.

So I didn't manage to modify webpack to load the .css (tried adding another entry point for it), but I did manage by

- adding `global.css` to my public dir with

```css
/* Hide the Canvas tab */
[role='main'] .os-content [href*='/?path=/story'] {
  display: none;
}
```

- `.storybook/manager-head.html` with `<link rel="stylesheet" href="/global.css" />`

Also note I didn't see any changes until starting storybook with manager cache disabled and thereafter it worked.

**Comment by ndelangen** [comment]
@DominicTobias @shilman I think we should -at some point- revisit this part of customization.

I think adding a Addon Type "ToolbarManager" which would be able to receive, then sort,filter,add,substract children would be an option.

We can wrap this here with a user supplied component:
https://github.com/storybookjs/storybook/blob/ff25d7f2f44e16c6a36f07694f9bbde4aeca072c/lib/ui/src/components/panel/panel.tsx#L88-L92

To allow them to do whatever with the children?
