### ISSUE TITLE
@storybook/theming causes type errors during tsc

### ISSUE THREAD

**Issue by backbone87** [storybookjs/storybook#7379]
**Describe the bug**
Ok this is a fun one. Basically tsc complains about missing react typings, when trying to use `create` of `@storybook/theming`.
This is because:
- `@storybook/theming` imports `@emotion/*`
- which in turn imports `react`
- which in turn requires `@types/react`
- which would have to be installed manually
- which would then declare global [`JSX` namespace](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2807)
- which would then conflict with the `JSX` namespace of Vue

**To Reproduce**
- create Vue project with TS support via Vue CLI 3
- Storybook via vue-cli-plugin-storybook (TS conversion and config must be done by hand)
- Vue JSX/TSX typings -> https://github.com/vuejs/vue-cli/blob/dev/packages/%40vue/cli-plugin-typescript/generator/template/src/shims-tsx.d.ts
- Create theme:
```ts
import { create } from '@storybook/theming';

export default create({
  base: 'light',
  brandTitle: 'My Storybook',
});
```
- `npx tsc`

**Expected behavior**
Use `create` from `@storybook/theming` without requiring react typings and therefore no JSX namespace conflicts.

**System:**
 - OS: any
 - Device: any
 - Browser: any
 - Framework: vue
 - Version: 5

**Additional context**
Workaround:
- dont use storybook theming
- or dont use vue jsx/tsx
- or run tsc with `--skipLibCheck`

Solution:
- provide a `create` theme function/module that does not use `@emotion/*`
- the only stuff that `create` requires from `@emotion/*` is `import { css, keyframes } from '@emotion/core';` in `animation.ts`)
- where `css` type doesnt require `react` typings (so no problem here), but is imported from `@emotion/core` types, which imports `react` typings for other stuff (this is a problem) -> import `css` from `@emotion/css`
- where `keyframes` type doesnt require `react` typings (so no problem here), but its type is declared in `@emotion/core` type declaration file that imports `react` typings, but actually dont use react typings for `keyframes` itself (but for other stuff) -> ask for upstream change in emotion (which would maybe require some reorganisation of types/exports on their part) **or** reimplement/c&p `keyframes` into `@storybook/theming` **or** dont use `keyframes` during `create`

**Comment by ndelangen** [comment]
@backbone87 try:
```
import { create } from '@storybook/theming/create';
```

Does that solve the issue?

**Comment by backbone87** [comment]
@ndelangen no, see section "solution" in the opening post

**Comment by backbone87** [comment]
still relevant

**Comment by selcet** [comment]
Still, very need full custom styling for Storybook.

**Comment by vertic4l** [comment]
I'm having the same issue with @storybook/vue... which installs some babel dependency which also changes the typings

**Comment by backbone87** [comment]
Can confirm, this isnt limited to theming anymore. (It has nothing to do with installs, just about what is imported, which means some import during storybook config/bootstrap imports something which imports something etc, until finally react TSX typings get imported, which results in conflict)

the only 2 workarounds left are:
- `--skipLibCheck` (not recommended)
- not use vue jsx/tsx

**Comment by ndelangen** [comment]
@backbone87 isn't there some way to make folder specific tsconfig?

**Comment by backbone87** [comment]
not as far as i know. the TSX declarations target the global namespace, so you can never have vue and react TSX shims imported (directly or indirectly) within the same compliation. just importing `@storybook/vue` will import react TSX d.ts from somewhere. you can prevent TS from checking stuff in node_modules (skipLibCheck), but that may result in incomplete typings.

removing the vue TSX declarations (and not using TSX) is a good workaround, since TSX traction in the vue ecosystem is low, but that may change with vue 3.

**Comment by ndelangen** [comment]
@backbone87 I sympathise.

> the TSX declarations target the global namespace

That seems like the root of the problem.

I'm guessing that's not configurable either?

**Comment by backbone87** [comment]
At least currently it is not configurable. but i dont think that it is feasible either. it would definitely require changes within typescript itself and maybe even the babel plugin to transpile 2 TSX files differently based on its path. vue tsx gets compiled into vues createElement calls, while react tsx gets compiled to reacts renderComponent (or whatever its called in react).

but i think it is bad for frameworks/libs/packages to (indirectly) import tsx shims in their public typings since the code is compiled already most of the time and therefore the shims arent needed.

when i opened this issue, these conflicts come from emotion packages, which was only imported when using storybook theming, but now the shims get even imported when importing `@storybook/vue`, but i havent tracked down the import chains, so i cant tell if its still just emotion or other chains as well

**Comment by backbone87** [comment]
fwiw: the real problem seems to be `@types/react` which should not expose their TSX shims without explicitly importing them -> https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L2939

which means as soon as you want to use react in any way (and even it its just exposing some APIs which have nothing to do with rendering react at all) you get the react shims

**Comment by viljark** [comment]
I'm facing the same issue.

Had to add  `"paths": {
			"react": [".sink.d.ts"]
		}` and `"skipLibCheck": true,` to tsconfig.json. 

The .sink.d.ts is just an empty file and enables me to use my own `namespace JSX` for vue, since the react module import eventually will not introduce it's own JSX namespace.

**Comment by vertic4l** [comment]
Thank you for deleting my comment.
Very transparent censorship.

**Comment by shilman** [comment]
We've just released zero-config typescript support in 6.0-beta. Please upgrade and test it!

- [Release 6.0.0-beta.12+](https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.12)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#zero-config-typescript)
- [Updated docs](https://github.com/storybookjs/storybook/blob/next/docs/src/pages/configurations/typescript-config/index.md)

Thanks for your help and support getting this stable for release!

**Comment by blake-newman** [comment]
@shilman it looks like the `@storybook/theming` package doesn't cause TS + JSX conflicts.

However it seems the `@storybook/knobs` package causes this issue still as it ships [`@types/react-color`](https://github.com/storybookjs/storybook/blob/next/addons/knobs/package.json#L39). I'm unsure if this is intentional. 

The above causes the `@types/react` package to be installed when using the `@storybook/knobs` package. If the `knobs` addon can ship without this types dependency then this should resolve the Vue + TSX issues.

**Comment by shilman** [comment]
@blake-newman We’ve just released addon-controls in 6.0-beta!

Controls are portable, auto-generated knobs that are intended to replace addon-knobs long term.

- [Controls README](https://github.com/storybookjs/storybook/tree/next/addons/controls)
- [Migration instructions](https://github.com/storybookjs/storybook/blob/next/addons/controls/README.md#how-do-i-migrate-from-addon-knobs)

Can also try to fix the knobs issue but if you’re able to upgrade i recommend it!

**Comment by yandongxu** [comment]
Still have problem with JSX type conflicts, when i write stories like this:

```
import { Story } from '@storybook/vue';

const Template: Story = (args, { argTypes }) => ({
  components: { Card },
  props: Object.keys(argTypes),
  template: '<Card v-bind="$props" />',
});

export const Default = Template.bind({});
Default.args = {
  title: 'MyTitle',
};
```

**`@storybook/vue` imported react JSX types**

**Comment by akay64** [comment]
Currently facing the same issue, one solution I found is to not use TypeScript at all for writing stories. Story files will all be ".js" files.

**Comment by ndelangen** [comment]
This is resolved in storybook 7.0 beta because we bundle in emotion.
