### ISSUE TITLE
Theming and addon-notes code block

### ISSUE THREAD

**Issue by nbrylev** [storybookjs/storybook#7619]
Greetings!

**Describe the bug**
I use a custom theme for Storybook. `barBg` property changes background of blocks with code.

**To Reproduce**
1. Create a .md file with code example inside.
2. Import it in any story.
3. Go to "Notes" section.
4. See error.

**Expected behavior**
So, I expect `barBg` to change background of top bar only.

**Screenshots**
![Снимок экрана 2019-07-30 в 11 27 12](https://user-images.githubusercontent.com/12825240/62113588-8b787080-b2bd-11e9-996a-e877f07a05a0.png)

**Code snippets**
```javascript
// file with custom theme settings
import { create } from '@storybook/theming';

export const theme = create({
  base: 'light', // base theme

  appBg: '#f4f5f9',
  barBg: '#3f4557',
  barTextColor: '#ffffff',
  barSelectedColor: '#ebb242',
});
```
**System:**
```bash
  System:
    OS: macOS 10.14.5
  Binaries:
    Node: 10.16.0 - /usr/local/bin/node
    Yarn: 1.5.1 - /usr/local/bin/yarn
    npm: 6.9.0 - /usr/local/bin/npm
```

**Comment by shilman** [comment]
Related:

https://github.com/storybookjs/storybook/pull/5922

https://github.com/storybookjs/storybook/issues/7434

**Comment by nbrylev** [comment]
By the way, version I use are
```json
"@storybook/addon-notes": "^5.1.9",
"@storybook/addons": "^5.1.9",
"@storybook/theming": "^5.1.9",
"@storybook/vue": "^5.1.9",
```

**Comment by ndelangen** [comment]
Fixing this now.

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.1.10 containing PR #7623 that references this issue. Upgrade today to try it out!

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.2.0-beta.19 containing PR #7623 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by shiftgeist** [comment]
I'm sorry, but I still have an issue with the theming (https://github.com/storybookjs/storybook/issues/7434):

Running on Storybook `5.2.0-rc.4` (angular).

My theme:
```
base: 'dark'
```

How the `notes` tab looks:

![image](https://user-images.githubusercontent.com/30648730/64170042-62fd0c80-ce4f-11e9-8a0c-efc8136a8d3e.png)

**Comment by shilman** [comment]
FYI `addon-notes` is being superceded by `addon-docs`. It’s reached release candidate (RC) status and will be properly released soon. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf
