### ISSUE TITLE
dotenv-webpack missing

### ISSUE THREAD

**Issue by revmischa** [storybookjs/storybook#7641]
I upgraded to the latest @storybook/core and @storybook/react
and now get:
```
info @storybook/react v5.2.0-beta.19
info 
info => Loading static files from: /Users/cyber/dev/jb/qc/qc-frontend/public .
info => Loading presets
WARN   Failed to load preset: "/Users/cyber/dev/jb/qc/qc-frontend/node_modules/@storybook/react/node_modules/@storybook/core/dist/server/manager/manager-preset.js"
ERR! Error: Cannot find module 'dotenv-webpack'
ERR! Require stack:
ERR! - /Users/cyber/dev/jb/qc/qc-frontend/node_modules/@storybook/react/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js
ERR! - /Users/cyber/dev/jb/qc/qc-frontend/node_modules/@storybook/react/node_modules/@storybook/core/dist/server/manager/manager-preset.js
ERR! - /Users/cyber/dev/jb/qc/qc-frontend/node_modules/@storybook/react/node_modules/@storybook/core/dist/server/presets.js
ERR! - /Users/cyber/dev/jb/qc/qc-frontend/node_modules/@storybook/react/node_modules/@storybook/core/dist/server/config.js
ERR! - /Users/cyber/dev/jb/qc/qc-frontend/node_modules/@storybook/react/node_modules/@storybook/core/dist/server/build-static.js
ERR! - /Users/cyber/dev/jb/qc/qc-frontend/node_modules/@storybook/react/node_modules/@storybook/core/server.js
ERR! - /Users/cyber/dev/jb/qc/qc-frontend/node_modules/@storybook/react/dist/server/index.js
ERR! - /Users/cyber/dev/jb/qc/qc-frontend/node_modules/@storybook/react/bin/index.js
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:527:27)
ERR!     at Module.require (internal/modules/cjs/loader.js:683:19)
ERR!     at require (internal/modules/cjs/helpers.js:16:16)
ERR!     at Object.<anonymous> (/Users/cyber/dev/jb/qc/qc-frontend/node_modules/@storybook/react/node_modules/@storybook/core/dist/server/manager/manager-webpack.config.js:14:45)
ERR!     at Module._compile (internal/modules/cjs/loader.js:776:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:643:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
ERR!     at Module.require (internal/modules/cjs/loader.js:683:19)
ERR!     at require (internal/modules/cjs/helpers.js:16:16)
ERR!     at Object.<anonymous> (/Users/cyber/dev/jb/qc/qc-frontend/node_modules/@storybook/react/node_modules/@storybook/core/dist/server/manager/manager-preset.js:21:46)
ERR!     at Module._compile (internal/modules/cjs/loader.js:776:30)
ERR!     at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
ERR!     at Module.load (internal/modules/cjs/loader.js:643:32)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
ERR!  Error: Cannot find module 'dotenv-webpack'
```

**Comment by revmischa** [comment]
and if install it, it yells at me i don't have raw-loader
if i install that too, it runs like before except for the error
    TS2305: Module '"../../../../../../../../Users/cyber/dev/jb/qc/qc-frontend/node_modules/@storybook/react/dist/client"' has no exported member 'RenderFunction'.

**Comment by revmischa** [comment]
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-resize-detector' in '/Users/cyber/dev/jb/qc/qc-frontend/node_modules/@storybook/react/node_modules/@storybook/ui/dist'

**Comment by revmischa** [comment]
And after getting it to start up I get the error
`  return api.configure.apply(api, args.concat([framework]));`
```

(anonymous) @ vendors~main.12b2a6f84f7c5f7e11bc.bundle.js:585
index.js:37 Uncaught TypeError: Cannot read property 'apply' of undefined
    at configure (index.js:37)
    at Module.<anonymous> (config.js:8)
    at Module../.storybook/config.js (config.js:8)
    at __webpack_require__ (bootstrap:785)
    at fn (bootstrap:150)
    at Object.0 (storybookThemeDecorator.tsx:28)
    at __webpack_require__ (bootstrap:785)
    at checkDeferredModules (bootstrap:45)
    at Array.webpackJsonpCallback [as push] (bootstrap:32)
    at main.45c52f6220ccb7b0328b.bundle.js:1
```

**Comment by shilman** [comment]
Sorry I missed this the first time around. Are you still seeing this in the latest beta?

**Comment by wKich** [comment]
@shilman, hello. I updated on latest stable 5.2.0 and receive type checking error
```
node_modules/@storybook/react/dist/client/preview/index.d.ts:2:23 - error TS2688: Cannot find type definition file for 'webpack-env'.

2 /// <reference types="webpack-env" />
```

**Comment by Uyarn** [comment]
> Sorry I missed this the first time around. Are you still seeing this in the latest beta?
@shilman Hi, I upgrade @storybook/react from 5.1.x to 5.2.0 and I use typescript.I got this error "has no exported member 'RenderFunction' "；May I ask you did you fix this problem and which version can I use now?

**Comment by revmischa** [comment]
I experienced this unpleasantness as well @Uyarn  - I tried `import { StoryFn } from '@storybook/addons'` and it seemed to work

**Comment by Uyarn** [comment]
> I experienced this unpleasantness as well @Uyarn - I tried `import { StoryFn } from '@storybook/addons'` and it seemed to work

@revmischa Hi revmischa, did you just add this line of code into your project? and which file do you add?

**Comment by revmischa** [comment]
yes in my custom wrapper addon

**Comment by Uyarn** [comment]
> yes in my custom wrapper addon

Thank you @revmischa , I'll try it and hope it can be fixed throughly :), Cheers.

**Comment by ndelangen** [comment]
@kroeder I'm looking at:

```
node_modules/@storybook/react/dist/client/preview/index.d.ts:2:23 - error TS2688: Cannot find type definition file for 'webpack-env'.

2 /// <reference types="webpack-env" />
```

And the output does reference `webpack-env`, but the package does not depend on it at all. Should it?

This is true for a LOT of packages actually.

**Comment by kroeder** [comment]
In app/angular it was due to tsconfig "types=[webpack-env]"

I assume it was added because in one server file `module.hot` or something like that is accessed. It shows a TSLint error because it uses node instead of webpack.env module. I fixed it by casting module to any in this file and removed webpack-env from the tsconfig

**Comment by futbolsalas15** [comment]
Hi!

It seems the error persists even with version 6.0.22

```txt
$ C:\project\node_modules\.bin\start-storybook --loglevel info
info @storybook/angular v6.0.22
info
info => Loading presets
WARN   Failed to load preset: "C:\\project\\node_modules\\@storybook\\angular\\node_modules\\@storybook\\core\\dist\\server\\manager\\manager-preset.js"
ERR! Error: Cannot find module 'dotenv-webpack'
ERR!     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
ERR!     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
ERR!     at Module.require (internal/modules/cjs/loader.js:692:17)
ERR!     at require (internal/modules/cjs/helpers.js:25:18)
ERR!     at Object.<anonymous> (C:\project\node_modules\@storybook\angular\node_modules\@storybook\core\dist\server\manager\manager-webpack.config.js:20:45)
```

I've tried to install the required package, but it seems to continue requiring more packages. 

Analyzing the content of `@storybook/core` folder inside node_modules, it seems that it has its own version of node_modules, where the package is available. Maybe it is an error where the local `node_modules` inside  `@storybook/core` isn't being included in the build process?

**Comment by ndelangen** [comment]
@futbolsalas15 if you can provide a clean reproduction repo, I can take a look.

I suspect it's a lockfile issue, try removing all lockfiles, node_modules and re-installing.
See if it works then.
