### ISSUE TITLE
[addon-docs] Component with position:fixed leaks out from Preview

### ISSUE THREAD

**Issue by chrsep** [storybookjs/storybook#8011]
**Describe the bug**
When a component with css `position:fixed` is displayed on the Docs page, it's fixed to the viewport, leaks out of the preview box, and does not scroll with the page. I've noticed that adding `transform: scale(1)` to the parent of the `position:fixed` component (tried it by pressing the the zoom button) clips and bound the `position:fixed` element correctly.

**To Reproduce**
1. Create a div with `position: fixed`
2. Display it on the docs-page

**Expected behavior**
All element of the component that is rendered inside the Docs preview should be contained  inside the preview.

**Screenshots**
***The Bug***
![image](https://user-images.githubusercontent.com/8491552/64420610-dd38c580-d0c9-11e9-9bc9-de873f2158a8.png)
***Expected (this is with `transform:scale(1)`)***
![image](https://user-images.githubusercontent.com/8491552/64420913-91d2e700-d0ca-11e9-897d-946d7899fbe6.png)

**System:**
```
Environment Info:

  System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  Binaries:
    Node: 12.4.0 - ~/.nvm/versions/node/v12.4.0/bin/node
    Yarn: 1.17.3 - /usr/bin/yarn
    npm: 6.9.0 - ~/.nvm/versions/node/v12.4.0/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
  npmPackages:
    @storybook/addon-a11y: ^5.2.0-rc.6 => 5.2.0-rc.6 
    @storybook/addon-actions: ^5.2.0-rc.6 => 5.2.0-rc.6 
    @storybook/addon-backgrounds: ^5.2.0-rc.6 => 5.2.0-rc.6 
    @storybook/addon-console: ^1.2.1 => 1.2.1 
    @storybook/addon-docs: ^5.2.0-rc.6 => 5.2.0-rc.6 
    @storybook/addon-knobs: ^5.2.0-rc.6 => 5.2.0-rc.6 
    @storybook/addon-links: ^5.2.0-rc.6 => 5.2.0-rc.6 
    @storybook/addon-viewport: ^5.2.0-rc.6 => 5.2.0-rc.6 
    @storybook/addons: ^5.2.0-rc.6 => 5.2.0-rc.6 
    @storybook/react: ^5.2.0-rc.6 => 5.2.0-rc.6 
    @storybook/theming: ^5.2.0-rc.6 => 5.2.0-rc.6 
```

**Additional context**
[Source Code](https://gitlab.com/decapos/termlink/blob/develop/silverhand/src/components/Layout/Layout.stories.tsx)
[Live Storybook](https://silverhand.decapos.io/?path=/docs/components-layout--basic)

**Comment by atanasster** [comment]
@chrsep not sure, but can you wrap your component in a container with styling as needed instead of storybooks adding styles that can interfere with other types of components?

**Comment by chrsep** [comment]
@atanasster Yes, i can do that. I can see why adding styles directly to storybook can be problematic.  

But I feel that this might be something that would be better solved directly on storybook, other people might get confused when their components jumps out of the preview block. It kinda surprises me when that happen, i didn't expect my component to be able to affect or be affected by stuffs outside the preview block. I guess i sort of expected it to work like a miniaturized canvas page that have iframe that fully contained my code.

**Comment by shilman** [comment]
@chrsep i'm open to styling the container differently. i'll play around with your solution!

**Comment by dcods22** [comment]
Id want to add to this.  We have a component that is a navigation which has a fixed position and top: 0; left: 0.  We want this component to be fixed to the top of the screen at all times.  This looks great when we have the component in the canvas, but when trying to leverage docs it looks very weird.  

Screenshot:
![image](https://user-images.githubusercontent.com/3107251/67812157-cc2a8600-fa74-11e9-93f5-ae7164df479d.png)


Ideally this would somehow be contained in the preview window.  This causes issues because of navigation component has 3 different examples of the options as stories and they all overlay ontop of each other.

**Comment by morganfeeney** [comment]
I found decorators useful here as a temp fix:

```jsx

import React from 'react';
import { action } from '@storybook/addon-actions';
import bagItems from '../../../lib/bagItems';
import MiniBag from './Header__minibag';

const styles = {
  transform: 'scale(1)',
  height: '100vh',
};

export default {
  title: 'Components|Header/Minibag',
  component: MiniBag,
  decorators: [storyFn => <div style={styles}>{storyFn()}</div>],
};

export const basic = () => (
  <MiniBag
    minibagItems={bagItems[0]}
    active
    toggleMinibag={action('toggleMinibag')}
  />
);

basic.story = {
  name: 'Default',
};

```

**Comment by pixelass** [comment]
@morganfeeney Thank you for your suggestion. Sadly this also breaks the CSS logic of fixed elements since they will now be fixed to that container and not the viewport.

I think the only valid solution would be to render each preview in an iframe otherwise there is no way to support fixed elements (this is just how CSS works)

**Comment by shilman** [comment]
@pixelass you can force Storybook to render your Docs story in an iframe

https://storybook.js.org/docs/react/writing-docs/doc-blocks#inline-rendering

**Comment by morganfeeney** [comment]
@pixelass you are welcome, but it is only a suggestion, a mere workaround to help people out if they get here and are in a hurry to get things working quickly.

You got me thinking about CSS, what I found is that adding a transform is a valid way to change the _containing block_ from the _viewport_: https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed

**Comment by pixelass** [comment]
@morganfeeney Thank you. I did not know that one can force iframe rendering. I did hit another issue though and I have the feeling this is not documented anywhere: https://storybook.js.org/docs/react/writing-docs/docs-page#inline-stories-vs-iframe-stories

>  [...] But using an iframe has disadvantages. You have to explicitly set the height of iframe stories or you’ll see a scroll bar.  [...] 

It neither states how to set the height nor does it link to a section of the docs where it is documented. Searching for "height"  within the docs also returned no results.

 **I would be willing to fix the missing parts in the documentation once I find a solution.**

I tried this without success:

```jsx
function withWrapper(style: React.CSSProperties) {
	return f => <div style={style}>{f()}</div>;
}

const story = {
	component: MyComponent,
	title: "Foo/Bar/My Component",
	decorators: [ withWrapper({
		height: 500,
	})]
};
```

I ended up disabling "docs" for the components with this issue for now. Since we have a separation of docs and examples this doesn't bother us too much right now.

```
const story = {
	component: MyComponent,
	title: "Foo/Bar/My Component",
	parameters: {
		docs: {
			page: null
		}
	}
};

```

Also to answer your statement:

> You got me thinking about CSS, what I found is that adding a transform is a valid way to change the containing block from the viewport: https://developer.mozilla.org/en-US/docs/Web/CSS/position#fixed

That is in fact true but changing the containing block causes other features to not work as expected. Fixing the element to the top would be the biggest impact. Obviously there are ways to rewrite the components to fix this issue but I strongly suggest against adjusting styles "only to support" that the Components can be rendered inline.

Features that will not work or experience issues could be:

* position: fixed works as expected
* scroll listeners will return the result as expected
* animations/performance

**Comment by shilman** [comment]
@pixelass you can force the iframe height using the `docs.story.iframeHeight` parameter.

**Comment by frassinier** [comment]
👋 Could please tell me if it works for y'all?
https://github.com/storybookjs/storybook/pull/11350

Demo is here
https://5a375b97f4b14f0020b0cda3-qwtnrhmjkl.chromatic.com/?path=/docs/addons-docs-mdx-id--fixed-layout-example

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.1.0-alpha.8 containing PR #11350 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by pixelass** [comment]
@shilman I updated `@storybook/docs` to `` but the issue persists.

I also tried this code: m(but the height does not apply.

```js

const story: Meta = {
	component: Grid,
	title: "Design System/Layout/Grid",
	parameters: {
		docs: {
			inlineStories: false,
			story: {
				iFrameHeight: 500,
			},
		},
	},
};
```

**Comment by shilman** [comment]
@pixelass `iFrameHeight` => `iframeHeight`

**Comment by shilman** [comment]
@frassinier can you help @pixelass with the original issue?

**Comment by pixelass** [comment]
> @pixelass `iFrameHeight` => `iframeHeight`

My bad. I tried `iframeHeight ` too but neither works.

**Comment by frassinier** [comment]
Actually, it's not designed to be used with CSF but with MDX:

```jsx
<Story name="custom-height" height="500px">
  <YourComponentUsingFixingPosition />
</story>
```

I can try to add it to [this interface](https://github.com/storybookjs/storybook/blob/master/addons/docs/src/frameworks/common/config.ts#L4L11) @shilman, in addition?

**Comment by pixelass** [comment]
@frassinier you just found the issue... 💯 
@shilman 

The issue was 

```js
{docs: {story: { iframeHeight: 500}}}
```

should be 

```js
{docs: { iframeHeight: 500}}
```

(not nested under the `story` property)

**Comment by shilman** [comment]
Looks like we're good @frassinier. Thanks!

**Comment by RenanRossiDias** [comment]
> @frassinier you just found the issue... 💯
> @shilman
> 
> The issue was
> 
> ```js
> {docs: {story: { iframeHeight: 500}}}
> ```
> 
> should be
> 
> ```js
> {docs: { iframeHeight: 500}}
> ```
> 
> (not nested under the `story` property)

Thank you dude! This worked nicely for me!

**Comment by vatsalRai** [comment]
I tried setting the iframeHeight and inlineStories property but it didnt work for me. I also tried with declarations as suggested but still no success.

<Meta
  title="ng-form-helpers/combo-box/API Reference"
  decorators={[
    storyFn => <div style={
  transform: 'scale(1)',
  height: '100vh',
}>{storyFn()}</div>,
      ]
    })
  ]}
  parameters={{
    docs: {
      inlineStories: false,
      iframeHeight: 500,
    }
  }}
/>

**Comment by bjankord** [comment]
You might try wrapping a div around your story with the following CSS:
```
<div style="height: 500px; transform: translateZ(0);">
  Your story template code
</div>
```

**Comment by EarthlingDavey** [comment]
If your file extension is  `.stories.jsx` or `.stories.tsx` then you can inline a wrapper div like: 


```js
onst meta = {
  title: "UI/SideBar",
  component: () => (
    <div style={{ minHeight: "200px" }}>
      <SideBar />
    </div>
  ),
...
```
