### ISSUE TITLE
Broken build, fix the error below.

### ISSUE THREAD

**Issue by Alfr3d** [storybookjs/storybook#8016]
**Describe the bug**
The storybook server doesn't startup.

> WARN Broken build, fix the error below.
> WARN You may need to refresh the browser.

**To Reproduce**

1. npm install ionic@3.0.0
2. ionic start myApp tabs --type=ionic-angular
3. cd myApp
4. npx -p @storybook/cli sb init
5. npm i html-webpack-plugin
6. //edit .storybook/tsconfig.json with manual version
7. npm i -D @angular-devkit/core

**Code snippets**
```
> myApp@0.0.1 storybook ./myApp
> start-storybook -p 6006

info @storybook/angular v5.1.11
info 
info => Loading presets
info => Loading presets
info => Loading custom addons config.
info => Found custom tsconfig.json
info => Using default webpack setup.
Starting type checking service...
Using 1 worker with 2048MB memory limit
10% building 1/1 modules 0 active(node:53538) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
webpack built 7a6d8c38cbd2eaa2a9fc in 5235ms
✖ ｢wdm｣: Hash: 7a6d8c38cbd2eaa2a9fc
Version: webpack 4.39.3
Time: 5235ms
Built at: 09/06/2019 4:24:10 PM
                                          Asset      Size        Chunks                    Chunk Names
                                    iframe.html  2.52 KiB                [emitted]         
            main.7a6d8c38cbd2eaa2a9fc.bundle.js  10.5 KiB          main  [emitted]         main
        main.7a6d8c38cbd2eaa2a9fc.bundle.js.map  3.52 KiB          main  [emitted]         main
    runtime~main.7a6d8c38cbd2eaa2a9fc.bundle.js  31.2 KiB  runtime~main  [emitted]         runtime~main
runtime~main.7a6d8c38cbd2eaa2a9fc.bundle.js.map  32.3 KiB  runtime~main  [emitted]         runtime~main
    vendors~main.7a6d8c38cbd2eaa2a9fc.bundle.js  5.62 MiB  vendors~main  [emitted]  [big]  vendors~main
vendors~main.7a6d8c38cbd2eaa2a9fc.bundle.js.map  5.91 MiB  vendors~main  [emitted]         vendors~main
Entrypoint main [big] = runtime~main.7a6d8c38cbd2eaa2a9fc.bundle.js runtime~main.7a6d8c38cbd2eaa2a9fc.bundle.js.map vendors~main.7a6d8c38cbd2eaa2a9fc.bundle.js vendors~main.7a6d8c38cbd2eaa2a9fc.bundle.js.map main.7a6d8c38cbd2eaa2a9fc.bundle.js main.7a6d8c38cbd2eaa2a9fc.bundle.js.map
[0] multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true 64 bytes {main} [built]
[./.storybook/config.js] 554 bytes {main} [built]
[./node_modules/@storybook/angular/dist/client/index.js] 1.46 KiB {vendors~main} [built]
[./node_modules/@storybook/core/dist/server/common/polyfills.js] 120 bytes {vendors~main} [built]
[./node_modules/@storybook/core/dist/server/preview/globals.js] 93 bytes {vendors~main} [built]
[./node_modules/@storybook/core/node_modules/regenerator-runtime/runtime.js] 23 KiB {vendors~main} [built]
[./node_modules/@storybook/core/node_modules/webpack/buildin/harmony-module.js] (webpack)/buildin/harmony-module.js 573 bytes {vendors~main} [built]
[./node_modules/@storybook/core/node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {vendors~main} [built]
[./node_modules/airbnb-js-shims/index.js] 40 bytes {vendors~main} [built]
[./node_modules/core-js/features/symbol/index.js] 305 bytes {vendors~main} [built]
[./node_modules/core-js/modules/es.array.for-each.js] 300 bytes {vendors~main} [built]
[./node_modules/core-js/modules/es.array.iterator.js] 2.16 KiB {vendors~main} [built]
[./node_modules/core-js/modules/es.object.to-string.js] 367 bytes {vendors~main} [built]
[./node_modules/core-js/modules/web.dom-collections.for-each.js] 619 bytes {vendors~main} [built]
[./node_modules/webpack-hot-middleware/client.js?reload=true] 7.68 KiB {vendors~main} [built]
    + 1059 hidden modules

WARNING in ./node_modules/@angular/core/esm5/core.js 6570:15-36
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@storybook/angular/dist/demo/welcome.component.ts
 @ ./node_modules/@storybook/angular/demo.js
 @ ./src/stories/index.stories.ts
 @ ./src/stories sync \.stories\.ts$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true

WARNING in ./node_modules/@angular/core/esm5/core.js 6590:15-102
Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@storybook/angular/dist/demo/welcome.component.ts
 @ ./node_modules/@storybook/angular/demo.js
 @ ./src/stories/index.stories.ts
 @ ./src/stories sync \.stories\.ts$
 @ ./.storybook/config.js
 @ multi ./node_modules/@storybook/core/dist/server/common/polyfills.js ./node_modules/@storybook/core/dist/server/preview/globals.js ./.storybook/config.js ./node_modules/webpack-hot-middleware/client.js?reload=true

ERROR in ./myApp/node_modules/@storybook/angular/index.d.ts
ERROR in ./myApp/node_modules/@storybook/angular/index.d.ts(61,51):
TS2304: Cannot find name 'NodeModule'.

ERROR in ./myApp/node_modules/@storybook/angular/index.d.ts
ERROR in ./myApp/node_modules/@storybook/angular/index.d.ts(69,58):
TS2304: Cannot find name 'NodeModule'.

ERROR in ./myApp/src/stories/index.stories.ts
ERROR in ./myApp/src/stories/index.stories.ts(7,22):
TS2304: Cannot find name 'module'.

ERROR in ./myApp/src/stories/index.stories.ts
ERROR in ./myApp/src/stories/index.stories.ts(12,21):
TS2304: Cannot find name 'module'.

ERROR in ./myApp/src/stories/index.stories.ts
ERROR in ./myApp/src/stories/index.stories.ts(41,29):
TS2304: Cannot find name 'module'.
Child HtmlWebpackCompiler:
                          Asset      Size               Chunks  Chunk Names
    __child-HtmlWebpackPlugin_0  29.5 KiB  HtmlWebpackPlugin_0  HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    [./node_modules/@storybook/core/node_modules/html-webpack-plugin/lib/loader.js!./node_modules/@storybook/core/dist/server/templates/index.ejs] 1.76 KiB {HtmlWebpackPlugin_0} [built]
```

**System:**
```
Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.9.1 - ~/.nvm/versions/node/v12.9.1/bin/node
    npm: 6.11.3 - ~/.nvm/versions/node/v12.9.1/bin/npm
  Browsers:
    Chrome: 76.0.3809.132
    Firefox: 69.0
    Safari: 12.1.2
  npmPackages:
    @storybook/addon-actions: ^5.1.11 => 5.1.11 
    @storybook/addon-links: ^5.1.11 => 5.1.11 
    @storybook/addon-notes: ^5.1.11 => 5.1.11 
    @storybook/addons: ^5.1.11 => 5.1.11 
    @storybook/angular: ^5.1.11 => 5.1.11 

```

**Comment by Alfr3d** [comment]
fixed:

`npm install @types/node``

**Comment by hosseinghs** [comment]
I get this
```
WARN Broken build, fix the error below.
WARN You may need to refresh the browser.
```
with no error or warnings in the console
and installing @types/node **didn't fix the issue.**

**Comment by Ross-Angus** [comment]
I get the same issue as @Tisamu

**Comment by mamadshni** [comment]
I get also the same issue @Tisamu

**Comment by Xmerr** [comment]
Same issue as @Tisamu

**Comment by Xmerr** [comment]
I'm using yarn. I tried uninstalling Storybook + addons and starting from scratch and still got the same issue.

**Comment by kuyaNgora** [comment]
same issue as @Tisamu

**Comment by eksno** [comment]
same issue

**Comment by mamadshni** [comment]
the issue is with missing module esbuild

run npm i esbuild

**Comment by chrisvander** [comment]
No, @mamadshni, not necessarily. I think Storybook 7.2 isn't bubbling up errors properly. My issue had to do with Vite and Vite-Plugin-SSR not working properly with the Storybook Vite builder. When I downgraded to 7.1 I saw the error and was able to fix it, and now it works like a charm on 7.2.

**Comment by Ross-Angus** [comment]
I no longer see this issue. My steps were to roll back my code to before the upgrade, delete `node_modules` and run the update again. The only step I did differently was to decline adding the `eslint-plugin`. I doubt this was the cause and from what everyone else has said, it appears that there is an ongoing issue with Storybook failing to add errors to the console.
