### ISSUE TITLE
No Prop Types detected when using forwardRef (React +TypeScript)

### ISSUE THREAD

**Issue by LiamMartens** [storybookjs/storybook#8336]
**Describe the bug**
When using `React.forwardRef` the prop types table is not correctly generated. From the moment I remove the forward ref stuff everything works as expected. Another thing to note, which might be related, is the fact that the story source loader also corrupts and is unable to show the component name when using forwardRef.

**To Reproduce**
Use reproduction repository [repository](https://github.com/LiamMartens/storybook-docgen-ts-react-forwardref). Run and check examples

**Expected behavior**
* Prop types should be detected correctly
* Story source should show component name

**Screenshots**
![image](https://user-images.githubusercontent.com/5265324/66384441-0c8b6c80-e9bf-11e9-8897-8a234b139fdb.png)

**System:**
Environment Info:
  System:
    OS: Linux 5.0 Pop!_OS 19.04
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
  Binaries:
    Node: 11.15.0 - /usr/bin/node
    Yarn: 1.19.0 - /usr/bin/yarn
    npm: 6.7.0 - /usr/bin/npm
  Browsers:
    Firefox: 69.0.1
  npmPackages:
    @storybook/addon-info: ^5.2.3 => 5.2.3 
    @storybook/addon-notes: ^5.2.3 => 5.2.3 
    @storybook/addon-storysource: ^5.2.3 => 5.2.3 
    @storybook/cli: ^5.2.3 => 5.2.3 
    @storybook/react: ^5.2.3 => 5.2.3 
    @storybook/source-loader: ^5.2.3 => 5.2.3

**Additional context**
For typescript I am using
* `babel-loader` with `preset-react`, `preset-typescript` and `preset-env`
* `react-docgen-typescript-loader`

**Comment by shilman** [comment]
`Addon-info` is being superceded by `addon-docs`, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Comment by bostondv** [comment]
> Addon-info is being superceded by addon-docs, which fixes a bunch of bugs and is easier to maintain. Please give it a try! https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

`addon-docs@5.2.3` appears to suffer from the same bug with `forwardRef`.

## With forwardRef

The prop type descriptions as well as the component description is missing.

```jsx
/**
 * Use the `Alert` component to display inline notices.
 */
export const Alert = forwardRef((props, ref) => {
  const { children, variant, ...restProps } = props

  return (
    <div ref={ref} role="alert" {...restProps}>
      {children}
    </div>
  )
})

Alert.defaultProps = {
  variant: 'info',
}

Alert.propTypes = {
  /**
   * The content of the component.
   */
  children: PropTypes.node.isRequired,
  /**
   * The variant style of the component.
   */
  variant: PropTypes.oneOf(['success', 'warning', 'info', 'error']),
}
```

![Screen Shot 2019-10-09 at 1 41 47 PM](https://user-images.githubusercontent.com/133814/66506044-92c8b100-ea9a-11e9-9c64-7dad5e137b36.png)

## Without forwardRef

Prop type and component descriptions work.

```jsx
/**
 * Use the `Alert` component to display inline notices.
 */
export const Alert = props => {
  const { children, variant, ...restProps } = props

  return (
    <div role="alert" {...restProps}>
      {children}
    </div>
  )
}

Alert.defaultProps = {
  variant: 'info',
}

Alert.propTypes = {
  /**
   * The content of the component.
   */
  children: PropTypes.node.isRequired,
  /**
   * The variant style of the component.
   */
  variant: PropTypes.oneOf(['success', 'warning', 'info', 'error']),
}
```

![Screen Shot 2019-10-09 at 1 41 36 PM](https://user-images.githubusercontent.com/133814/66506082-a411bd80-ea9a-11e9-830c-3be8cb5da5b1.png)

## Packages

"@storybook/addon-a11y": "^5.2.3",
    "@storybook/addon-actions": "^5.2.3",
    "@storybook/addon-docs": "^5.2.3",
    "@storybook/addon-knobs": "^5.2.3",
    "@storybook/addon-links": "^5.2.3",
    "@storybook/addon-viewport": "^5.2.3",
    "@storybook/addons": "^5.2.3",
    "@storybook/cli": "^5.2.3",
    "@storybook/components": "^5.2.3",
    "@storybook/core-events": "^5.2.3",
    "@storybook/react": "^5.2.3",
    "@storybook/theming": "^5.2.3",

**Comment by apdrsn** [comment]
Will this be fixed in addon-info?

**Comment by shilman** [comment]
This was fixed in `addon-docs`, the successor to `addon-info`. If anybody wants to back-port it to `addon-info`, I'd merge that: https://github.com/storybookjs/storybook/pull/8445

**Comment by LiamMartens** [comment]
@shilman according to @bostondv the bug still appears in `addon-docs` as well

**Comment by shilman** [comment]
@LiamMartens that was 14 days ago and it has been fixed in #8445

**Comment by raunofreiberg** [comment]
Unfortunately, this still doesn't work for me :/

When using a `forwardRef` component in `addParameters({ component: Component })` I get the following in props table:

![image](https://user-images.githubusercontent.com/23662329/67568078-da566a80-f733-11e9-864d-4f5211561185.png)

I tried implementing the #8445 fix in `addon-info` and the same error popped up.

Anyone else?

**Comment by raunofreiberg** [comment]
I think ☝️ might have something to do with this line:

https://github.com/storybookjs/storybook/blob/12bd73864969bc119e21862466a57d56eee55e01/addons/docs/src/frameworks/react/extractProps.ts#L66

The function tries to render the component via `render()` but there are no props passed in, so destructuring or accessing any of the props in the component will throw.

**Comment by felipeleusin** [comment]
Just wanted to say that I was testing addon-docs with a simple setup with TypeScript + styled-components and this same line is causing the issue for me when using a component like:

```export interface ButtonProps {
  /**
   * ID of the component
   */
  scale: 'small' | 'big';
}

/**
 * This is our main button component!
 */
export const Button = styled.button<ButtonProps>`
  padding: ${({ scale }) => scale === 'small' ? '2px' : '4px};
`;
```

And it was showing that no props were found because the processed type was being resolved as StyledComponent instead of the correct one. If I comment the following lines lines in getPropDefs it starts to work

```
  if (type.render) {
    processedType = type.render().type;
  }

  if (typeof type.type === 'function') {
    processedType = type.type().type;
  }
```

**Comment by shilman** [comment]
Argh, good catch guys. Does anybody have a solution?

**Comment by felipeleusin** [comment]
I'm going to spend some time debugging this. I've worked with this kind of issue before in Docz and it's really hard to make it work consistent. My initial suggestion would be to just allow this behavior to be overriden in userland if that's the case.

From looking at the code there's already some change in the last few days. Will see how it behaves and test with our codebase here

**Comment by datasoysa** [comment]
Any updates on this?

**Comment by felipeleusin** [comment]
Hi, sorry for the delay on this. I ended up switching jobs after that and I'm on PTO. If you want to pick this issue up feel free otherwise I'll take a look next week when I'm back.

From my latest tests in 5.3 things were working but I was trying to find out how to add tests to this feature

**Comment by datasoysa** [comment]
Thanks for your quick reply, i'll also lots of works to do because of it i'll wait for the next release. If i can find a quick solution i'll take it.

> Hi, sorry for the delay on this. I ended up switching jobs after that and I'm on PTO. If you want to pick this issue up feel free otherwise I'll take a look next week when I'm back.
> 
> From my latest tests in 5.3 things were working but I was trying to find out how to add tests to this feature

**Comment by SirMoustache** [comment]
Still having this issue with `v.5.3.0-rc.3`

**Comment by raunofreiberg** [comment]
This solved the problem for me: https://github.com/strothj/react-docgen-typescript-loader/issues/76#issuecomment-570368448 🎉

**Comment by jeffcstock** [comment]
Still having issues, the above solution @raunofreiberg suggested isn't working even with destructuring `forwardRef`.

https://github.com/strothj/react-docgen-typescript-loader/issues/76#issuecomment-573163382
