### ISSUE TITLE
Addons panel not showing - but knobs are still working(?)

### ISSUE THREAD

**Issue by goralight** [storybookjs/storybook#8383]
**Describe the bug**
I am using the knobs addon for my StencilJs project and it is technically working (if i set the component prob within the story it is changing it, for example: look at the story file and then the component, you will see that it is setting it - and it does). but I cannot see the addons panel. I think have done all the set up correctly (addons.js, package.json, etc).

I have tried selecting the show addons option inside of the running storybook but nothing is displayed. 

How i am running it is with `npm run storybook`

**To Reproduce**
1. Launch storybook
2. No addons panel is visible on the side or bottom

**Expected behavior**
I expect to see the addons panel if I have an addon installed to be used 

**Screenshots**
![storybook](https://user-images.githubusercontent.com/5850319/66636552-549dcf80-ec09-11e9-9b53-0617b02c85bf.png)

**Code snippets**
Below is my .storybook/addons.js
```
import '@storybook/addon-a11y/register';
import '@storybook/addon-actions/register';
import '@storybook/addon-knobs/register';
```

Below is my package.json
```
"scripts": {
    "build": "stencil build",
    "start": "stencil build --dev --watch --serve",
    "stencil.dev": "stencil build --dev --watch --docs",
    "storybook.dev": "./node_modules/.bin/start-storybook -p 8008 -c .storybook -s ./dist",
    "storybook": "npm run build && ./node_modules/.bin/concurrently  \"npm run stencil.dev\" \"npm run storybook.dev\"",
    "test": "stencil test --spec --e2e",
    "test.watch": "stencil test --spec --e2e --watch",
    "generate": "stencil generate"
  },
  "dependencies": {
    "@ionic/core": "^4.9.1"
  },
  "devDependencies": {
    "@stencil/core": "^1.7.0",
    "@stencil/less": "^1.0.0",
    "@stencil/utils": "0.0.5",
    "@stencil/webpack": "0.0.6",
    "@storybook/addon-a11y": "5.2.3",
    "@storybook/addon-actions": "5.2.3",
    "@storybook/addon-knobs": "5.2.3",
    "@storybook/addon-storysource": "5.2.3",
    "@storybook/addon-viewport": "5.2.3",
    "@storybook/addons": "5.2.3",
    "@storybook/cli": "5.2.3",
    "@storybook/html": "5.2.3",
    "@storybook/polymer": "5.2.3",
    "babel-core": "6.26.3",
    "babel-loader": "7.1.5",
    "babel-preset-env": "1.7.0",
    "lit-html": "1.1.1",
    "polymer-webpack-loader": "2.0.3",
    "ts-loader": "^5.4.5",
    "concurrently": "^4.1.0"
  }
```

Below is my .storybook/config.js
```
import { addDecorator, addParameters, configure } from '@storybook/polymer';
import { withA11y } from '@storybook/addon-a11y';
import { withKnobs } from '@storybook/addon-knobs';
import 'sumai-frontend';

addParameters({
  options: {
    /**
     * name to display in the top left corner
     * @type {String}
     */
    name: 'Sumai Components',
    /**
     * URL for name in top left corner to link to
     * @type {String}
     */
    url: '#',
    /**
     * show story component as full screen
     * @type {Boolean}
     */
    isFullscreen: false,
    /**
     * display panel that shows a list of stories
     * @type {Boolean}
     */
    showNav: true,
    /**
     * display panel that shows addon configurations
     * @type {Boolean}
     */
    showPanel: true,
    /**
     * display floating search box to search through stories
     * @type {Boolean}
     */
    showSearchBox: false,
    /**
     * show addon panel as a vertical panel on the right
     * @type {string}
     */
    addonPanelInRight: true,
    /**
     * sorts stories
     * @type {Boolean}
     */
    sortStoriesByKind: false,
    /**
     * regex for finding the hierarchy separator
     * @example:
     *   null - turn off hierarchy
     *   /\// - split by `/`
     *   /\./ - split by `.`
     *   /\/|\./ - split by `/` or `.`
     * @type {Regex}
     */
    hierarchySeparator: null,
    /**
     * regex for finding the hierarchy root separator
     * @example:
     *   null - turn off multiple hierarchy roots
     *   /\|/ - split by `|`
     * @type {Regex}
     */
    hierarchyRootSeparator: null,
    /**
     * sidebar tree animations
     * @type {Boolean}
     */
    sidebarAnimations: true,
    /**
     * id to select an addon panel
     * @type {String}
     */
    selectedAddonPanel: undefined, // The order of addons in the "Addon panel" is the same as you import them in 'addons.js'. The first panel will be opened by default as you run Storybook
    /**
     * enable/disable shortcuts
     * @type {Boolean}
     */
    enableShortcuts: true // true by default
  }
});

const req = require.context('../src/components', true, /story.tsx$/);
function loadStories() {
  req.keys().forEach(filename => req(filename));
}
configure(loadStories, module);
addDecorator(withA11y);
addDecorator(withKnobs);

// HMR interface
if (module.hot) {
  // Capture hot update
  module.hot.accept('sumai-frontend', () => {
    document.location.reload();
  });
}
```

below is my story.tsx
```
import { storiesOf } from "@storybook/polymer";
import { text } from "@storybook/addon-knobs";

storiesOf("Basic Components", module)
  .add("Modal", () => {
    const el = document.createElement("sumai-full-width-image");
    el.name = text('Name', 'Namey');
    return el;
  });
```

**System:**
```
System:
    OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
    CPU: (4) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: 1.16.0 - /bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.80
    Firefox: 69.0.2
  npmPackages:
    @storybook/addon-a11y: 5.2.3 => 5.2.3 
    @storybook/addon-actions: 5.2.3 => 5.2.3 
    @storybook/addon-knobs: 5.2.3 => 5.2.3 
    @storybook/addon-storysource: 5.2.3 => 5.2.3 
    @storybook/addon-viewport: 5.2.3 => 5.2.3 
    @storybook/addons: 5.2.3 => 5.2.3 
    @storybook/cli: 5.2.3 => 5.2.3 
    @storybook/html: 5.2.3 => 5.2.3 
    @storybook/polymer: 5.2.3 => 5.2.3
```

**Additional context**

**Comment by shilman** [comment]
Sometimes the UI gets into a funny state where the addon panel is hidden based on local storage. In that case, running `localStorage.clear()` in the browser console and hard-reloading the page should fix it.

**Comment by goralight** [comment]
Yeah I did that and it worked, sorry for the redundant issue, thank you for your help!

**Comment by shilman** [comment]
Sorry for the bug! Glad you got it working!

**Comment by josephdicdican** [comment]
> Sometimes the UI gets into a funny state where the addon panel is hidden based on local storage. In that case, running `localStorage.clear()` in the browser console and hard-reloading the page should fix it.

this saved my day, tvm @shilman

**Comment by bradennapier** [comment]
Not sure this should be closed - is this not fixable ?  This happens quite often

**Comment by shilman** [comment]
Re-opening

**Comment by Mazuh** [comment]
thanks for for the hint on fixing it. Looking forward to a permanent fix

**Comment by ekilah** [comment]
If it helps, I just ran into this bug immediately after adding the knobs package. All I did to get the panel to be visible was to go to the `...` menu and change the orientation of the (invisible) panel. It magically appeared in the vertical orientation, and I was able to rotate it back afterwards.

Maybe that'll help, maybe not!

**Comment by jessicarobins** [comment]
I am also running into this issue, except that clearing local storage/opening an incognito window doesn't work. I can find the panel in the Elements console and force it to be visible, and the knobs work just fine.

**Comment by tomasztunik** [comment]
Had the same issue, changing orientation helped but it keeps disappearing whenever I select another story. I believe it might be related to the 3:2 ratio screen (Surface Book) and maybe it's not treating it as a desktop because of that?

**Comment by ruicarest** [comment]
Had the same issue on a desktop, chrome. Again, changing orientation helped but it keeps disappearing whenever I select another story.

**Comment by nhunt3** [comment]
Glad I came across this page. I encountered this frustrating bug today and `localStorage.clear()` fixes it. Looking forward to a permanent fix as well.

**Comment by milenaNeumann** [comment]
Hey, I just ran into this bug on Storybook 6.0.10, but I found a fix for it by changing the config:
I had the `showPanel` and `panelPosition` configured in my `preview.js` like this:
```js
// preview.js
addParameters({
  options: {
    showPanel: true,
    panelPosition: "bottom",
  },
});
```
Moving these into the `manager.js` solved the issue for me:
```js
// manager.js
addons.setConfig({
  showPanel: true,
  panelPosition: "bottom",
});
```

Maybe this helps you find the underlying issue or other people looking for a workaround ;)

**Comment by MrSunshyne** [comment]
Came across this in Storybook 6.x, the localStorage.clear() solution fixed it.

**Comment by valgaze** [comment]
+1 on localStorage.clear() as a quick fix

And also @milenaNeumann 🙌 🙌

When in this state the following will **not** resolve:

- Pressing "a" (keyboard shortcut)
- Refresh, reload, kill all browser instances, etc

Quick and dirty fixes:

- Localstorage.clear()
- Jump into a different browser like Firefox

Long-term fix (this seems to resolve in all cases, props to @milenaNeumann):

```sh
npm i @storybook/addons
```

**.storybook/manager.js**:

```js
import { addons } from "@storybook/addons";

addons.setConfig({
  showPanel: true,
  panelPosition: "bottom",
});

```

**Comment by cybervaldez** [comment]
Same. Been following through the guide and i'm having the same issue, nothing here fixes it for me. I can go to the Docs tab and set my args there however.

**Comment by surdu** [comment]
Just to be sure: this should happen only for users that saw the Storybook _before_ it had Knobs, right? Completely new visitors should not be affected.

**Comment by CiprianaM** [comment]
For me none of the above worked, but I managed to fix it by adding the controls addon in the main.js: 

```
module.exports = {
  addons: ['@storybook/addon-knobs', '@storybook/addon-controls'],
  stories: ['./src/stories/*.stories.js'],
};
```

**Comment by ahuggins** [comment]
> If it helps, I just ran into this bug immediately after adding the knobs package. All I did to get the panel to be visible was to go to the `...` menu and change the orientation of the (invisible) panel. It magically appeared in the vertical orientation, and I was able to rotate it back afterwards.
> 
> Maybe that'll help, maybe not!

This did the trick for me!!!

**Comment by surdu** [comment]
In version 6.3.0 none of the above options seems to work anymore ... 😞

**Comment by R-Bower** [comment]
> In version 6.3.0 none of the above options seems to work anymore ... 😞

I'm seeing the same on my end.  Tried all of the above steps including clearing the localStorage and trying other browsers.  Could it be because I'm only using MDX docs?  Are addons even available in those cases?

**Comment by shilman** [comment]
@surdu do you have a repro?

**Comment by surdu** [comment]
> Could it be because I'm only using MDX docs?

Not using them, still have the issue

> @surdu do you have a repro?

Unfortunately, no, it's a private repo :(

**Comment by PeteJStewart** [comment]
I'm still getting this issue on the latest version of storybook.
localStorage.clear() worked a treat, but I had spent quite a while trying to figure it out before coming across this bug issue!
I feel it would be good to have something about this on the documentation until the bug is resolved.
Many thanks for the solution!! ;-)

**Comment by softdays** [comment]
Reproduced using SB 6.4.19. 
Using `localStorage.clear()` fix the issue.

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.50 containing PR #17714 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by Wouter125** [comment]
FYI, this issue is still present in 7.0.0-beta.19 when running firefox. Will try beta.34 later.

**Comment by nuxcodes** [comment]
@shilman Issue still present in `7.0.2`. Thanks!

**Comment by rosskevin** [comment]
@shilman this issue is still present in 7.0.12.  I had to workaround with `localStorage.clear()` because the addons panel unexpectedly disappeared.  Perhaps it is a hot key sequence putting it in a bad state?

**Comment by charlestbell** [comment]
Two years old and bug is still present

**Comment by itsmebasti** [comment]
I am using the [a] [s] [d] keys to make it visible if missing, they are configured as layout shortcuts by default...

**Comment by musjj** [comment]
Just had this issue too. On Firefox, `localStorage.clear()` doesn't work and I had to go to `Web Developer Tools` -> `Storage` -> `Session Storage` and clear it.

**Comment by Sydney-o9** [comment]
FYI there is a bug with the addons pannel, you need to complete the onboarding, once you do, it will show at the bottom of the screen. Tested on both firefox and chrome.
