### ISSUE TITLE
Addon-Docs: Props Loading Issues

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#8435]
There are a variety of issues piling up regarding inconsistencies in Storybook Docs Props handling. Creating an umbrella issue to track a systematic investigation:

- [ ] Static builds https://github.com/storybookjs/storybook/issues/8140
- [ ] Class components https://github.com/storybookjs/storybook/issues/8428
- [ ] Component description https://github.com/storybookjs/storybook/issues/8162
- [ ] Typescript issues https://github.com/storybookjs/storybook/issues/8143 https://github.com/storybookjs/storybook/issues/8114
- [ ] Default props https://github.com/storybookjs/storybook/issues/8191 https://github.com/storybookjs/storybook/issues/8728 https://github.com/storybookjs/storybook/issues/8740
- [ ] Forward refs / memo wrappers https://github.com/storybookjs/storybook/issues/7933
- [ ] Styled components https://github.com/storybookjs/storybook/issues/8279
- [ ] Emotion https://github.com/storybookjs/storybook/issues/8496
- [ ] Gatsby props? https://github.com/storybookjs/storybook/issues/8425
- [ ] Externally defined props https://github.com/storybookjs/storybook/issues/3493 https://github.com/storybookjs/storybook/issues/8482
- [ ] External libraries https://github.com/storybookjs/storybook/issues/8481
- [ ] Flow types https://github.com/storybookjs/storybook/issues/8115

**Comment by patricklafrance** [comment]
Here's another one:

If the component import the props types object from another file, they will not be available in the props table of the component.

```
// shared-prop-types.js

import { string } from "prop-types";

export const MY_PROP_TYPES = {
     foo: string.isRequired
};
```

```
// my-component.jsx

import { MY_PROP_TYPES  } from "./shared-prop-types";

export class MyComponent extends PureComponent {
    static propTypes = MY_PROP_TYPES;

   ....
};
```

Thank you,

Patrick

**Comment by shilman** [comment]
Zoinks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.31 containing PR #8581 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by shilman** [comment]
5.3.0-alpha.31 contains a new version of `react-docgen` that may address some of these issues. I'll be running tests tomorrow, but if anybody wants to kick the tires, please report back!

**Comment by patricklafrance** [comment]
@shilman 

I tried with `alpha.31` and the issue I mentioned earlier in this issue and it still doesn't work.  Props defined in an object imported from an external file are still not rendered.

**Comment by patricklafrance** [comment]
@shilman 

The fix you made for the forwardRef kind of work for you. Now the props are listed but the description are missing.

![image](https://user-images.githubusercontent.com/794579/67704287-2ea75780-f98b-11e9-9d30-8b6aeba91cba.png)

**Comment by patricklafrance** [comment]
As discussed, exporting an additional component without the `forwardRef` fix it for me.

```jsx
export { DateRangePickerInputInner as PureDateRangePickerInput };

export const DateRangePickerInput = forwardRef((props, ref) => (
    <DateRangePickerInputInner { ...props } inputRef={ref} />
));
```

Then in my MDX file

```jsx
<Props of={PureDateRangePickerInput } />
```

**Comment by jebadirad** [comment]
5.3.0-alpha.35 does not fix my issue. 

When building storybook I still cannot see prop descriptions. I tried the work around that @patricklafrance  used above and prop descriptions still are not showing.

I don't use mdx though, I am using 

```
export default {
  title: 'Inputs|Button',
  decorators: [withKnobs],
  parameters: {
    component: PureButton,
    componentSubtitle: 'subtitle',
    notes: {
      markdown: ButtonMD
    }
  }
};
```

On the bright side everything still works perfectly when running `start-storybook`

**Comment by patricklafrance** [comment]
@jebadirad try 5.3.0-alpha.36 should works.

**Comment by patricklafrance** [comment]
The following use case still doesn't work:

```
export const ForwardRefButton = React.forwardRef((props, ref) => (
  <DocgenButton ref={ref} {...props} />
));

export const DocgenButton = ({ disabled, label, onClick }) => (
  <button type="button" disabled={disabled} onClick={onClick}>
    {label}
  </button>
);

DocgenButton.propTypes = {
   ....
};
```

![image](https://user-images.githubusercontent.com/794579/68054026-c080ce80-fcc3-11e9-9593-dc7b8da611a8.png)

**Comment by apdrsn** [comment]
I'm still having issues getting props tables to show using `5.3.0-alpha.38`
I'm having a button component wrapped in `forwardRef`:
```
import React, { forwardRef } from 'react';
import PropTypes from 'prop-types';

export const Button = forwardRef(({ type, ...props }, ref) => (
  <button type={type} ref={ref} {...props} />
));

Button.propTypes = {
  children: PropTypes.node.isRequired,
  type: PropTypes.oneOf(['button', 'submit'])
};

Button.defaultPropTypes = {
  type: 'button'
};
```

This is my story:
```
import React from 'react';
import { Button } from '../components/button/button';

export default {
  title: 'Button',
  component: Button
};

export const text = () => (
  <Button>Hello Button</Button>
);
```

In docs-tab I'm getting the following:
![image](https://user-images.githubusercontent.com/6361772/68203669-96325800-ffc6-11e9-8509-b607bd8af4bc.png)

When I do `console.log(Button)` I'm getting:
![image](https://user-images.githubusercontent.com/6361772/68203728-c0841580-ffc6-11e9-90fb-5d4f2167107b.png)

Am I doing something wrong?

**Comment by PSJgit** [comment]
On `5.3.0-alpha.39` I'm having a similar issue with a component that uses `ReactDOM.createPortal`. Props aren't generated unfortunately.

**Comment by donysukardi** [comment]
I'm currently on `5.3.0-alpha.41` and the prop definitions have suddenly gone missing for all components now.

![image](https://user-images.githubusercontent.com/410792/68372084-244f3f80-017b-11ea-85f8-5531a90aed9c.png)

**Comment by shilman** [comment]
sorry about that! `alpha.41` contains a bunch of work in progress from @patricklafrance and it's possible that something broke for some cases (tho i'm not seeing it on my examples). can you file an issue with your setup, ideally with a repro? we'll be sure to get it fixed in `alpha.42`!

**Comment by donysukardi** [comment]
oops.. false alarm. i have custom `babel.config.js` file. that explains why the docgen info that i got was always empty! since the DocsPage is dependent on docgen via `babel-plugin-react-docgen`, it might be good to make this indication more prominent

**Comment by shilman** [comment]
I've created a github label to track this more easily. Here's the current set of props bugs: https://github.com/storybookjs/storybook/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22block%3A+props%22+label%3Abug

Closing this umbrella issue

**Comment by SuzanneMcWeb** [comment]
Hi, using Storybook with Angular and was wanting to use CSF for creating stories but include the props details like the MDX supports. Was wondering if there's any progress with this?
