### ISSUE TITLE
Set the current story name in the title

### ISSUE THREAD

**Issue by shilman** [storybookjs/storybook#866]
<a href="https://github.com/arunoda"><img src="https://avatars2.githubusercontent.com/u/50838?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [arunoda](https://github.com/arunoda)**
_Monday Aug 15, 2016 at 06:19 GMT_
_Originally opened as https://github.com/storybooks/storybook-ui/issues/28_

----

It's great if we can set the title as the current story name(with the kind name) as shown below:

```
Kindname.storyname || Storybook
```

**Comment by shilman** [comment]
<a href="https://github.com/TheSisb"><img src="https://avatars0.githubusercontent.com/u/1592327?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [TheSisb](https://github.com/TheSisb)**
_Wednesday Jan 18, 2017 at 21:47 GMT_

----

+1 or custom title

**Comment by ndelangen** [comment]
Related: #952 

If we could expose an API for setting the header, an addon could be created to set it `onStory()`

#1209

**Comment by Hypnosphi** [comment]
Doesn‘t addon-options solve the issue?

**Comment by ndelangen** [comment]
Yes it can, but that's super verbose.

We should make it the default behavior that a selected kind + name would appear in the page title.

**Comment by victorteodoro** [comment]
Hi guys! I'd like to help on this one. I'm not very familiar with the code base though. Could you help me get started?

**Comment by skybrandevs** [comment]
please how do i add this to my exisiting react project . how do i use this to create a component a draggable component

**Comment by skybrandevs** [comment]
i dont understand this any video example on this

**Comment by danielduan** [comment]
While this feature is nice to have, I'm gonna close this ticket since this has been open for a while.

Please open a new issue or PR and reference this one if you're interested in working on this.

**Comment by adamchenwei** [comment]
@danielduan don't understand... seems, @janmichek answer in `https://github.com/storybooks/storybook/issues/812`  works pretty well... why not just use that?

**Comment by janmichek** [comment]
@adamchenwei This should be the proper way to set Storybook header name in config.js
https://github.com/storybooks/storybook/tree/master/addons/options

```
import { setOptions } from '@storybook/addon-options';

setOptions({
  name: 'My Styleguide',
  url: 'https://site.com',
});
```

**Comment by brunoreis** [comment]
I have two configs. One I'm using for global components. The other one, for specific functionalities. Both show as "Storybook" in the page title, and so in the browser tab. 

I see that sometimes people are talking about the title on the upper left corner of the page and in other times, about html title. So, I just want to add to this saying it would be nice to be able to set the html title.

**Comment by martinmacko47** [comment]
@adamchenwei The method you describe is an ugly hack, not a solution.

Please add title too `setOptions` arguments or use `name` from `setOptions` as the title as well.

**Comment by Hypnosphi** [comment]
@martinmacko47 Both make sense to me. Would you like to open a PR?

**Comment by sdailly** [comment]
any PR ? - about this

**Comment by ndelangen** [comment]
Should be implemented in this:
https://github.com/storybooks/storybook/pull/4086

**Comment by ndelangen** [comment]
Working on this

**Comment by shilman** [comment]
Yay!! I just released https://github.com/storybooks/storybook/releases/tag/v5.0.0-alpha.7 containing PR #5277 that references this issue. Upgrade today to try it out!

Because it's a pre-release you can find it on the `@next` NPM tag.

**Comment by flxwu** [comment]
The document title still doesn't update for me, although I'm on the latest version :(

**Comment by visionpoint** [comment]
I've tried different variations of this to set the title. From adding a `title` tag in the `manager-head.html` file, to injecting it with JavaScript (this shows up for a second but get overridden immediately by the default "Storybook"). 

So with the latest stable version of Storybook, how can I set the `document.title` property?

**Comment by herman-rogers** [comment]
This also doesn't update for me on v5.2.1 - there's about 5 tickets on it all closed and chained to the next ticket. Not sure why it keeps getting closed when it hasn't been addressed.

**Comment by shilman** [comment]
@herman-rogers This issue is open and marked as high priority. We have 391 issues open, and are working through them as quickly as we can. If you'd like it fixed more quickly, I would be more than happy to review a PR if you provided one.

**Comment by rtkaaho** [comment]
FWIW it seems this feature is partially working in version `5.3.0-alpha.45`. However, out of curiosity, is there any way to manually set the page title via configuration? For now the default is `Storybook` as per the `managers` `index.ejs` but I can seem to find anywhere in the code where we are able to modify the options that are passed to `HTMLWebpackPlugin` and I dont really want to have to override it in a custom webpack config. 

If this isn't a thing, i'd be more than happy to implement it. Any help would be appreciated!

**Comment by jayarjo** [comment]
Is this fixed or not? I'm not sure.

**Comment by jayarjo** [comment]
Setting Storybook title to the current story name is one problem. But there's another one - title of the preview iframe should be updated as well. Otherwise this happens: 
![Screen Shot 2020-07-11 at 10 59 20 AM](https://user-images.githubusercontent.com/150075/87219872-fbb5c000-c36f-11ea-85fe-dd63c6d9b9d9.png)


Related: https://github.com/storybookjs/storybook/issues/522#issue-180174479

As a solution adapted the following from: https://github.com/storybookjs/storybook/issues/812#issuecomment-610154066
```javascript
import addons from '@storybook/addons';
import { STORY_RENDERED } from '@storybook/core-events';

// set a title of the preview iframe to that of current story
addons.register('addon-title', (api) => {
  const customTitle = 'Cartographer Story'; // Define your customTitle title
  const setTitle = () => {
    let storyData;
    try {
      storyData = api.getCurrentStoryData();
    } catch {
      console.info(`addon-title: wasn't able to change the title of Story iframe`);
    }
    const title = storyData ? `${storyData.kind} - ${storyData.name} ⋅ ${customTitle}` : customTitle;
    const iframe = document.getElementById('storybook-preview-iframe');
    if (iframe && iframe.contentDocument.title !== title) {
      // As few dom operations as possible
      iframe.contentDocument.title = title;
    }
  };
  setTitle();
  api.on(STORY_RENDERED, (story) => {
    setTimeout(setTitle, 100);
  });
});
```

**Comment by shilman** [comment]
@jayarjo any interest in fixing this inside storybook?

**Comment by jayarjo** [comment]
@shilman I'd gladly participate, but don't think  I will be able to find time. Maybe later.

**Comment by spaceninja** [comment]
Now that v6 is out, is there a way to do this? I'd really like to be able to change the title in the browser tab from "Storybook" to whatever the name of my pattern library is.

**Comment by dutscher** [comment]
@spaceninja use a manager-head.html add `<title>TITLE</title>` and it overrides the `<title>Storybook</title>`

cheers

**Comment by rwieruch** [comment]
> @spaceninja use a manager-head.html add `<title>TITLE</title>` and it overrides the `<title>Storybook</title>`
> 
> cheers

This does not work for me. It doesn't override it, instead you have two title tags now. Anyone knows how to solve this?

**Comment by YozhEzhi** [comment]
I've tried to dig it. As we see in `lib/ui/src/components/preview/preview.tsx` `title` has overriding by `Helmet`:

```
<Helmet key="description">
    <title>{description}</title>
</Helmet>
```

But `iframe` doesn't using `Helmet` or `Preview`.
So I didn't understand how to upgrade `title` in `iframe` rendering :(

**Comment by ndelangen** [comment]
We set the title of the manager here:
https://github.com/storybookjs/storybook/blob/2d393aa072e987fe44f65090268162439d465608/lib/ui/src/components/preview/preview.tsx#L178-L182

We don't set the title of the iframe, because for storybook the title of the iframe is never shown anywhere.
But a global decorator could definitely do this (set the document's title to whatever it wants)

**Comment by ndelangen** [comment]
Right.. 

Setting the `document.title= story.id` shouldn't be too difficult..

In fact, looking at this, we might be able to make a simple change here:
https://github.com/storybookjs/storybook/blob/b823bd936f9c0ed0d0f5f974ec3da631919152b0/lib/preview-web/src/UrlStore.ts#L45

Seems like a "good first issue"? would anyone want to take this on? 

@dutscher @spaceninja @rwieruch @YozhEzhi

**Comment by YozhEzhi** [comment]
Hi everyone!

### Simple change as @ndelangen told.

https://github.com/whatwg/html/issues/2174 

### Title generation variants

#### Overhead variant

Storybook generates formatted title here:
https://github.com/storybookjs/storybook/blob/b823bd936f9c0ed0d0f5f974ec3da631919152b0/lib/ui/src/containers/preview.tsx#L16

So, for generating title in iframe we should reuse that function. But here:
https://github.com/storybookjs/storybook/blob/b823bd936f9c0ed0d0f5f974ec3da631919152b0/lib/preview-web/src/UrlStore.ts#L41
we have only `selection.storyId` (e.g. `button--text` and not `{kind: 'Text', name: 'Button'}`)

We could use here:
https://github.com/storybookjs/storybook/blob/b823bd936f9c0ed0d0f5f974ec3da631919152b0/lib/preview-web/src/PreviewWeb.tsx#L236
something like:

```
const { kind, name } = await this.storyStore.loadStory({ storyId });
this.urlStore.setSelection({ storyId, viewMode, kind, name });
```

But I think this is overhead.

#### Easy workaround variant

As @ndelangen advised we could do this:
````
document.title = selection.storyId;
```

And title in iframe should be like this:
![image](https://user-images.githubusercontent.com/2706062/147061036-49b8531e-8986-42b4-a838-cd9ccf21a439.png)

**Comment by franklinjavier** [comment]
The problem with client-side document.title is that when you are trying to share the link, it shows "Webpack app" instead of document.title = 'xxxx'
![image](https://user-images.githubusercontent.com/440220/148096267-eeefaebb-4404-4e65-8d85-b57f89a47ce6.png)

I tried to add <title> to manager-head.html, but it only duplicated the title tag, as you can see here https://hflorabook.gb.tech/483/index.html?path=/story/disclosure-accordion--accordion

Is there an option to remove the default title?

**Comment by shilman** [comment]
w00t!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.5.0-alpha.13 containing PR #17177 that references this issue. Upgrade today to the `@next` NPM tag to try it out!

```
npx sb upgrade --prerelease
```

Closing this issue. Please re-open if you think there's still more to do.

**Comment by sag1v** [comment]
@shilman / @ndelangen What is the API here to control the `title`? By inspecting the changes it seems to take the story id as the title, but i dont see a way to manipulate it, like appending text or replace it all together.

**Comment by parkerault** [comment]
There seems to be two separate issues being conflated here. One is people wanting a client-side method for setting the document title. The other is customizing the document title in the generated HTML. As @franklinjavier pointed out previously:

> The problem with client-side document.title is that when you are trying to share the link, it shows "Webpack app" instead of document.title = 'xxxx' ![image](https://github.com/assets/440220/eeefaebb-4404-4e65-8d85-b57f89a47ce6)

I've written a script that rewrites the title tag after the storybook build process finishes as a workaround, but I haven't been able to find any documentation or type definitions that hint at how to set the default generated document title. Currently, every time I paste a link into any service that does link previews, it says "Webpack App", which is vague and confusing.

**Comment by muratcorlu** [comment]
For the people who came here by searching: [Current document says](https://storybook.js.org/docs/web-components/sharing/publish-storybook#title) it's as easy as exporting title from `main.js`. But that doesn't work for me and I created a bug report for it: https://github.com/storybookjs/storybook/issues/22211
