### ISSUE TITLE
Storybook interface not loading on IE11

### ISSUE THREAD

**Issue by bpeab** [storybookjs/storybook#8884]
**Describe the bug**
The interface/stories are not loading on Internet Explorer 11.

**To Reproduce**
1. `start-storybook -p 3000` with `storybook-html`
2. Open Internet Explorer 11
3. See that Storybook is stuck in the loading state. 

**Expected behavior**
Storybook should be working correctly on Internet Explorer 11.

**System:**
System:
    OS: macOS Mojave 10.14.5
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 13.1.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.97
    Firefox: 70.0.1
    Safari: 12.1.1
  npmPackages:
    @storybook/addon-a11y: ^v5.3.0-beta.2 => 5.3.0-beta.2 
    @storybook/addon-actions: ^v5.3.0-beta.2 => 5.3.0-beta.2 
    @storybook/addon-docs: ^v5.3.0-beta.2 => 5.3.0-beta.2 
    @storybook/addon-knobs: ^v5.3.0-beta.2 => 5.3.0-beta.2 
    @storybook/html: ^v5.3.0-beta.2 => 5.3.0-beta.2

**Additional context**
The console of Internet Explorer outputs `Syntax Error` on `vendors~main.js` which redirect to the following code:

```js
return class extends Parser {
  static get acornJsx() {
    return acornJsx;
  }
  // ...
}
```

**Comment by afebbraro** [comment]
I also get this issue in storybook html, react and angular.

node: v10.16.3
npm: 6.13.0
my html package.json
 "@storybook/addon-a11y": "^5.3.0-beta.1",
    "@storybook/addon-docs": "^5.3.0-beta.1",
    "@storybook/addons": "^5.3.0-beta.1",
    "@storybook/html": "^5.3.0-beta.1",
    "@storybook/preset-scss": "^1.0.2",
    "@storybook/theming": "^5.3.0-beta.1",

my react package.json
"@storybook/addon-a11y": "^5.3.0-beta.1",
    "@storybook/addon-docs": "^5.3.0-beta.1",
    "@storybook/addon-jest": "^5.3.0-beta.1",
    "@storybook/addons": "^5.3.0-beta.1",
    "@storybook/react": "^5.3.0-beta.1",
    "@storybook/theming": "^5.3.0-beta.1",

my angular package.json
"@storybook/addon-a11y": "^5.3.0-beta.0",
    "@storybook/addon-docs": "^5.3.0-beta.0",
    "@storybook/addons": "^5.3.0-beta.0",
    "@storybook/angular": "^5.3.0-beta.0",
    "@storybook/preset-scss": "^1.0.2",
    "@storybook/theming": "^5.3.0-beta.0",

**Comment by shilman** [comment]
@bpeab @afebbraro Would one of you mind bisecting to see which release introduced the bug? @afebbraro I see in your PR that you're upgrading from alpha.39, so it must have been a recent change.

@ndelangen @tmeasday can we set up a single IE story in chromatic to prevent this from continually happening without breaking the bank?

**Comment by afebbraro** [comment]
@shilman , That was a great idea! It actually wasn't introduced in beta.0 as I checked and saw it happening in every version from beta.0 back to alpha.45. Looks like the bug was introduced in https://github.com/storybookjs/storybook/releases/tag/v5.3.0-alpha.45. The last working version is alpha.44 for me. 

This is the last combination that works in IE11:
```
  "@storybook/addon-a11y": "5.3.0-alpha.44",
    "@storybook/addon-docs": "5.3.0-alpha.44",
    "@storybook/addon-jest": "5.3.0-alpha.44",
    "@storybook/addons": "5.3.0-alpha.44",
    "@storybook/react": "5.3.0-alpha.44",
    "@storybook/theming": "5.3.0-alpha.44",
```

**Comment by tmeasday** [comment]
> can we set up a single IE story in chromatic to prevent this from continually happening without breaking the bank?

We'd have to create a separate chromatic project and run builds against it. That'd work but we wouldn't get a PR badge for it.

Given it is a pass/fail type situation that's probably OK though. We do something similar in Chromatic proper to smoke test FF and IE.

**Comment by ndelangen** [comment]
I'd like to run a chromatic instance on every example TBH and get that feedback in a PR.

I might write my own custom github action for this.

**Comment by bpeab** [comment]
Any updates on this issue ? I see it has been assigned, does it mean I shouldn't try to solve the issue myself and open a PR ?

**Comment by ndelangen** [comment]
@bpeab please do, if you can find a solution and help fix this issue it would be immensely appreciated !

**Comment by tmeasday** [comment]
Yes, the assignment is more about trying to setup infrastructure to makes sure we don't keep regressing, we'd definitely like a fix to the actual problem!

**Comment by bpeab** [comment]
So, I must be cominig from `addon-docs` which uses `acorn-jsx` while not transpiling it, despite being written with ES6 classes. Not resolved the issue yet since I don't understand how `babel-loader` is involved in the whole project. 

From what I understand, the `preset.ts` file is responsible extending the `webpack` configuration, am I wrong ?

**Comment by shilman** [comment]
@patricklafrance I think you added the acorn dep. Do you think it would be easier to switch over to the babel parser/generator than to figure out this bug? As you noted in our chat, it certainly seems like a better long-term solution.

**Comment by patricklafrance** [comment]
Well it's not that hard but it would take time. The inspection logic and the code generation would have to be rewritten using babel instead.

Since I never use babel parser / generator I don't know if it support exactly the same feature set as acorn.

The docs code also used an acorn walker, I dont know if babel have one.

Maybe acorn-jsx could be transpiled? https://github.com/acornjs/acorn-jsx/issues/98

**Comment by bpeab** [comment]
Well, that was the proposal in my last message. Transpiling it would fix the issue but I can't seem to find how Storybook handle transpilation yet. I tried to add the necessary property to the `preset.ts` rules involved in `addon-docs` but it doesn't seem to work. I perhaps don't understand where I should define it. Any hints ?

**Comment by patricklafrance** [comment]
@bpeab can't help with that but I agree that's the way to go. IMO we should be able to introduce code using ES6 features in SB.

@shilman I was in a hurry when I wrote my previous answer.

Here's a detailled answer on why we can't just swap acorn for babel without expecting to do a few changes:

1- acorn follow the estree specs and generate an AST accordingly. Babel claims to follow the estree specs but with a few deviations. Meaning it would requires to make sure the "few" deviations are handled by the inspection code. There is also the JSX code, I don't know if the generated AST for JSX follow any specs at all.

2- As for the code generation... I am not sure about the available formatting options with babel generator. Currently, the code that is generated for the "summary" is handled by a "compact" options available with escodegen. I dont know if babel generator offer a similar option. Even if it's available, there is a good chance the formatted output would have a few difference for either the "summary" or the "detail" and would requires the tests to be updated.

3- I guess babel traverse could replace acorn walk but I don't know if they offer a similar features set. For example, the depth of a property value is currently calculated using the "ancestor" feature of acorn walk, I don't know if babel traverse offer a similar feature.

**Comment by shilman** [comment]
@patricklafrance Fair enough

@Hypnosphi do you know how to fix the transpilation issue described here?

**Comment by Hypnosphi** [comment]
@bpeab Can you please show the code that you tried to add to `preset.ts`? Or maybe even open a PR?

**Comment by bpeab** [comment]
So far, I only identified the origin of the issue but haven't found any way to resolve it.

I'll try once I have some more time but from my understanding, we should make use of `babel-loader` and its `preset-env` to transpile `acorn-jsx`. I imagine it would take place inside the `preset.ts` file where the `webpack` configuration is extended. Something like `exclude: /node_module/\(?!acorn)/`...

**Comment by Hypnosphi** [comment]
It probably should be a separate `babel-loader` rule  with `modules: 'commonjs'` because `https://github.com/acornjs/acorn-jsx/blob/master/index.js` uses commonjs

**Comment by bpeab** [comment]
@Hypnosphi Also `@babel/plugin-transform-modules-commonjs` as plugin. It works for me on one of my Storybook projects (via `.storybook/webpack.config.js`. I'll try to make the change on the Storybook repository and submit a PR if successful. 

Thanks all for your help.

**Comment by Hypnosphi** [comment]
@bpeab 
> @babel/plugin-transform-modules-commonjs

This one should be disabled, because https://github.com/acornjs/acorn-jsx/blob/master/index.js is already commonjs

**Comment by shilman** [comment]
Good golly!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-beta.14 containing PR #9021 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by tmeasday** [comment]
In order to avoid this happening again, let's run an example app in IE on Chromatic: https://github.com/storybookjs/storybook/issues/9039

**Comment by lmaze** [comment]
I encounter this bug again. If I add `@storybook/addon-docs`, the Storybook no longer works on IE11. acorn-jsx is not transpiled and causes a syntax error. I use the latest version of Storybook and its addons (5.3.9).

**Comment by RCopeland** [comment]
@lmaze I saw the same thing, but only in the dev mode, once i deployed (npm run build-storybook) i didnt see it.

**Comment by tmeasday** [comment]
> I saw the same thing, but only in the dev mode, once i deployed (npm run build-storybook) i didnt see it.

Could this be due to your `browserslist` in `package.json`? Vanilla CRA apps do not work in IE in dev mode, but do in prod for this reason.

**Comment by lmaze** [comment]
I checked everything several times and added targets for IE11 in my `package.json` and my Babel configuration to be sure that all the files are transpiled correctly. I even added a `babel-loader` to my storybook `webpack.config.js` file to force the transpilation of the `acorn-jsx` and `acorn` libraries. Maybe I missed something but I still get the same error in dev mode or in build mode.

For me it looks like a bug, `addon-docs` should come with all the libraries transpiled. Otherwise it may be a configuration error on my part but my configuration is quite simple and without this addon all is working fine in IE11 :(

@shilman Is it possible to reopen this bug?

**Comment by RCopeland** [comment]
@tmeasday hey thanks, i tried it out with and without a browerslist entry, but got the same error. I also tried with a .browserslistrc file in the root.
Here's a repro repo: https://github.com/RCopeland/storybook-html-test
build-storybook then deploy works fine, 
npm run storybook gives me the error in IE 11 (acorns-jsx has classes)

**Comment by lmaze** [comment]
@RCopeland I tried with your example repo. It is exactly the same problem I encounter. When I test with IE11 your Storybook example built locally I also have a syntax error problem (I open the `index.html` directly via the "Open in browser" menu of IntelliJ which launches a local server). No problem on your deployed link however.

**Comment by bpeab** [comment]
I tried with the reproduction repository you gave and everything work just fine by me on IE11.

**Comment by ndelangen** [comment]
Thanks for testing the repro @bpeab 

You weren't able to find any IE11 problems on his repro? neither build or dev-mode?

---

I was able to find 2 issues before on our own official-example.

The webpack config patch I posted resolves them.

My PR to emotion should go through soon hopefully; addressing 1 issue.

The graphiql issue seems lower-priority to me (given the install-base of the addon-graphql and it's non-critical nature). I think the graphiql authors aren't sure what to support or not.

@RCopeland 
I'll run your example on my machine as well, and see if I can reproduce the problem in IE11 on browserstack. Thank you for taking the time and effort to create this repro for us.

**Comment by bpeab** [comment]
Neither build or dev-mod were giving me problems on IE11 (tested with BrowserStack) and I tried multiple times with differents OS. Everything was running smoothly, at least, with the repro. Also changed the node versions to see if It had any impact but, there again, no problem. 

Perhaps if @lmaze and @RCopeland could share their systems configs, I'd be able to investigate further.

**Comment by lmaze** [comment]
@bpeab Thanks for the tests and for the help. Here is my system config:
- OS : Windows 10 Enterprise N - Version 1903 (Build 18362.592).
- Node : Version 12.14.1 x64 (The last version of LTS)

Do not hesitate to tell me if I can give you more information or do more tests.

We also build our Storybook with a Docker image on Linux. I will also try with this configuration to see if there is a problem.

**Comment by ndelangen** [comment]
These screenshots are taken of the repro repo?

**Comment by lmaze** [comment]
@ndelangen The 2 screenshots from https://github.com/storybookjs/storybook/issues/8884#issuecomment-578861017 have been taken with the repro repo. Screenshots of @RCopeland should be too as it is the same screenshot with the same error.

**Comment by ndelangen** [comment]
I'm going to look into this today / tomorrow

**Comment by ndelangen** [comment]
I'm looking at sbh.robcopeland.me in browserstac IE11:
<img width="1919" alt="Screenshot 2020-01-28 at 17 46 26" src="https://user-images.githubusercontent.com/3070389/73285358-3084ef00-41f6-11ea-9386-47c6ef221750.png">

0 console errors.

What am I doing wrong?

**Comment by ndelangen** [comment]
Then I run your repro locally, share it publicly using `ngrok` and test that in browserstack IE11:

<img width="961" alt="Screenshot 2020-01-28 at 17 52 56" src="https://user-images.githubusercontent.com/3070389/73285980-257e8e80-41f7-11ea-9b01-2937c4376240.png">

Again, 0 console errors.

I'm unsure what to do.

**Comment by bpeab** [comment]
@Imaze, @RCopeland: Could you please run Webpack in verbose mode and share the output with us ? This issue seems really weird to me and I can't really investigate further with the informations you've already shared...

**Comment by RCopeland** [comment]
@ndelangen I'm also not seeing console errors in IE11 on sbh.robcopeland.me, its only in the dev command (npm run storybook) when I run it locally. When you view the ngrok shared version on browserstack, do you see the class keyword in the vendors bundle? 

@bpeab Here's my output from --debug-webpack

```` npm run storybook -- --debug-webpack

> sbh@1.0.0 storybook C:\Users\copel\Development\storybook-html-test
> start-storybook -p 6006 "--debug-webpack"

info @storybook/html v5.3.8
info 
info => Loading presets
info => Loading presets
info => Loading config/preview file in "./.storybook". 
info => Adding stories defined in ".storybook\main.js".
Manager webpack config
{
  name: 'manager',
  mode: 'development',
  bail: false,
  devtool: 'none',
  entry: [
    'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\core\\dist\\server\\common\\polyfills.js',      
    'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\core\\dist\\client\\manager\\index.js',
    'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\addon-docs\\dist\\register.js'
  ],
  output: {
    path: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\core\\dist\\public',
    filename: '[name].[chunkhash].bundle.js',
    publicPath: ''
  },
  cache: {},
  plugins: [
    DllReferencePlugin {
      options: {
        context: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\node_modules',
        manifest: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\core\\dll\\storybook_ui-manifest.json'
      }
    },
    HtmlWebpackPlugin {
      options: {
        template: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\core\\dist\\server\\templates\\index.ejs',
        templateContent: false,
        templateParameters: [Function: templateParameters],
        filename: 'index.html',
        hash: false,
        inject: false,
        compile: true,
        favicon: false,
        minify: 'auto',
        cache: true,
        showErrors: true,
        chunks: 'all',
        excludeChunks: [],
        chunksSortMode: 'none',
        meta: {},
        base: false,
        title: 'Webpack App',
        xhtml: false,
        alwaysWriteToDisk: true
      },
      childCompilerHash: undefined,
      childCompilationOutputName: undefined,
      assetJson: undefined,
      hash: undefined,
      version: 4
    },
    CaseSensitivePathsPlugin {
      options: {},
      logger: {
        log: [Function: bound consoleCall],
        warn: [Function: bound consoleCall],
        dir: [Function: bound consoleCall],
        time: [Function: bound consoleCall],
        timeEnd: [Function: bound consoleCall],
        timeLog: [Function: bound consoleCall],
        trace: [Function: bound consoleCall],
        assert: [Function: bound consoleCall],
        clear: [Function: bound consoleCall],
        count: [Function: bound consoleCall],
        countReset: [Function: bound consoleCall],
        group: [Function: bound consoleCall],
        groupEnd: [Function: bound consoleCall],
        table: [Function: bound consoleCall],
        debug: [Function: bound consoleCall],
        info: [Function: bound consoleCall],
        dirxml: [Function: bound consoleCall],
        error: [Function: bound consoleCall],
        groupCollapsed: [Function: bound consoleCall],
        Console: [Function: Console],
        profile: [Function: profile],
        profileEnd: [Function: profileEnd],
        timeStamp: [Function: timeStamp],
        context: [Function: context],
        [Symbol(kBindStreamsEager)]: [Function: bound ],
        [Symbol(kBindStreamsLazy)]: [Function: bound ],
        [Symbol(kBindProperties)]: [Function: bound ],
        [Symbol(kWriteToConsole)]: [Function: bound ],
        [Symbol(kGetInspectOptions)]: [Function: bound ],
        [Symbol(kFormatForStdout)]: [Function: bound ],
        [Symbol(kFormatForStderr)]: [Function: bound ]
      },
      pathCache: {},
      fsOperations: 0,
      primed: false
    },
    DefinePlugin { definitions: {} },
    DefinePlugin {
      definitions: {
        'process.env': {
          NODE_ENV: '"development"',
          NODE_PATH: '""',
          PUBLIC_URL: '""'
        },
        NODE_ENV: '"development"'
      }
    },
    ContextReplacementPlugin {
      resourceRegExp: /graphql-language-service-interface[/\\]dist/,
      newContentResource: undefined,
      newContentRecursive: undefined,
      newContentRegExp: /\.js$/
    },
    NormalModuleReplacementPlugin {
      resourceRegExp: /core-js/,
      newResource: [Function]
    }
  ],
  module: {
    rules: [
      {
        test: /\.(mjs|jsx?)$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              cacheDirectory: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\.cache\\storybook',
              presets: [
                [
                  'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\preset-env\\lib\\index.js',
                  {
                    shippedProposals: true,
                    useBuiltIns: 'usage',
                    corejs: '3'
                  }
                ]
              ],
              plugins: [
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\plugin-proposal-object-rest-spread\\lib\\index.js',
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\plugin-proposal-class-properties\\lib\\index.js',
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\plugin-syntax-dynamic-import\\lib\\index.js',
                [
                  'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\babel-plugin-emotion\\dist\\babel-plugin-emotion.cjs.js',
                  { sourceMap: true, autoLabel: true }
                ],
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\babel-plugin-macros\\dist\\index.js'
              ]
            }
          }
        ],
        include: [ 'C:\\Users\\copel\\Development\\storybook-html-test' ],
        exclude: [
          'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules'
        ]
      },
      {
        test: /\.css$/,
        use: [
          'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\style-loader\\dist\\cjs.js',
          {
            loader: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\css-loader\\dist\\cjs.js',
            options: { importLoaders: 1 }
          }
        ]
      },
      {
        test: /\.(svg|ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani|pdf)(\?.*)?$/,
        loader: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\file-loader\\dist\\cjs.js',
        query: { name: 'static/media/[name].[hash:8].[ext]' }
      },
      {
        test: /\.(mp4|webm|wav|mp3|m4a|aac|oga)(\?.*)?$/,
        loader: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\url-loader\\dist\\cjs.js',
        query: { limit: 10000, name: 'static/media/[name].[hash:8].[ext]' }
      }
    ]
  },
  resolve: {
    extensions: [ '.mjs', '.js', '.jsx', '.json' ],
    modules: [ 'node_modules' ],
    alias: {
      '@emotion/core': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@emotion\\core',
      '@emotion/styled': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@emotion\\styled',
      'emotion-theming': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\emotion-theming',
      '@storybook/addons': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\addons',
      '@storybook/api': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\api',
      '@storybook/channels': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\channels',
      '@storybook/components': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\components',
      '@storybook/core-events': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\core-events',       
      '@storybook/router': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\router',
      '@storybook/theming': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\theming',
      '@storybook/ui': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\ui',
      'prop-types': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\prop-types',
      react: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\react',
      'react-dom': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\react-dom'
    }
  },
  recordsPath: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\.cache\\storybook\\records.json',
  performance: { hints: false },
  optimization: { splitChunks: { chunks: 'all' }, runtimeChunk: true }
}
info => Using default Webpack setup.
Preview webpack config
{
  mode: 'development',
  bail: false,
  devtool: '#cheap-module-source-map',
  entry: [
    'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\core\\dist\\server\\common\\polyfills.js',      
    'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\core\\dist\\server\\preview\\globals.js',       
    'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\addon-docs\\dist\\frameworks\\common\\config.js',
    'C:\\Users\\copel\\Development\\storybook-html-test\\.storybook\\generated-entry.js',
    'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\webpack-hot-middleware\\client.js?reload=true&quiet=true'   
  ],
  output: {
    path: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\core\\dist\\public',
    filename: '[name].[hash].bundle.js',
    publicPath: ''
  },
  plugins: [
    VirtualModulesPlugin {
      _staticModules: {
        'C:\\Users\\copel\\Development\\storybook-html-test\\.storybook\\generated-entry.js': '\n' +
          "              import { configure } from '@storybook/html';\n" +
          '              module._StorybookPreserveDecorators = true;\n' +
          '\n' +
          "              configure([require.context('../stories', false, /^\\.\\/(?:(?!\\.)(?=.)[^\\\\/]*?\\.stories\\.(js|mdx))$/)\n" +
          '              ], module);\n' +
          '            '
      }
    },
    HtmlWebpackPlugin {
      options: {
        template: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\core\\dist\\server\\templates\\index.ejs',
        templateContent: false,
        templateParameters: [Function: templateParameters],
        filename: 'iframe.html',
        hash: false,
        inject: false,
        compile: true,
        favicon: false,
        minify: 'auto',
        cache: true,
        showErrors: true,
        chunks: 'all',
        excludeChunks: [],
        chunksSortMode: 'none',
        meta: {},
        base: false,
        title: 'Webpack App',
        xhtml: false,
        alwaysWriteToDisk: true
      },
      childCompilerHash: undefined,
      childCompilationOutputName: undefined,
      assetJson: undefined,
      hash: undefined,
      version: 4
    },
    DefinePlugin {
      definitions: {
        'process.env': {
          NODE_ENV: '"development"',
          NODE_PATH: '""',
          PUBLIC_URL: '"."'
        },
        NODE_ENV: '"development"'
      }
    },
    WatchMissingNodeModulesPlugin {
      nodeModulesPath: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules'
    },
    HotModuleReplacementPlugin {
      options: {},
      multiStep: undefined,
      fullBuildTimeout: 200,
      requestTimeout: 10000
    },
    CaseSensitivePathsPlugin {
      options: {},
      logger: {
        log: [Function: bound consoleCall],
        warn: [Function: bound consoleCall],
        dir: [Function: bound consoleCall],
        time: [Function: bound consoleCall],
        timeEnd: [Function: bound consoleCall],
        timeLog: [Function: bound consoleCall],
        trace: [Function: bound consoleCall],
        assert: [Function: bound consoleCall],
        clear: [Function: bound consoleCall],
        count: [Function: bound consoleCall],
        countReset: [Function: bound consoleCall],
        group: [Function: bound consoleCall],
        groupEnd: [Function: bound consoleCall],
        table: [Function: bound consoleCall],
        debug: [Function: bound consoleCall],
        info: [Function: bound consoleCall],
        dirxml: [Function: bound consoleCall],
        error: [Function: bound consoleCall],
        groupCollapsed: [Function: bound consoleCall],
        Console: [Function: Console],
        profile: [Function: profile],
        profileEnd: [Function: profileEnd],
        timeStamp: [Function: timeStamp],
        context: [Function: context],
        [Symbol(kBindStreamsEager)]: [Function: bound ],
        [Symbol(kBindStreamsLazy)]: [Function: bound ],
        [Symbol(kBindProperties)]: [Function: bound ],
        [Symbol(kWriteToConsole)]: [Function: bound ],
        [Symbol(kGetInspectOptions)]: [Function: bound ],
        [Symbol(kFormatForStdout)]: [Function: bound ],
        [Symbol(kFormatForStderr)]: [Function: bound ]
      },
      pathCache: {},
      fsOperations: 0,
      primed: false
    },
    ProgressPlugin {
      profile: false,
      handler: undefined,
      modulesCount: 500,
      showEntries: false,
      showModules: true,
      showActiveModules: true
    },
    DefinePlugin { definitions: {} },
    NormalModuleReplacementPlugin {
      resourceRegExp: /core-js/,
      newResource: [Function]
    }
  ],
  module: {
    rules: [
      {
        test: /\.(mjs|jsx?)$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              cacheDirectory: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\.cache\\storybook',
              presets: [
                [
                  'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\preset-env\\lib\\index.js',
                  {
                    shippedProposals: true,
                    useBuiltIns: 'usage',
                    corejs: '3'
                  }
                ]
              ],
              plugins: [
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\plugin-proposal-object-rest-spread\\lib\\index.js',
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\plugin-proposal-class-properties\\lib\\index.js',
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\plugin-syntax-dynamic-import\\lib\\index.js',
                [
                  'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\babel-plugin-emotion\\dist\\babel-plugin-emotion.cjs.js',
                  { sourceMap: true, autoLabel: true }
                ],
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\babel-plugin-macros\\dist\\index.js'
              ]
            }
          }
        ],
        include: [ 'C:\\Users\\copel\\Development\\storybook-html-test' ],
        exclude: [
          'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules'
        ]
      },
      {
        test: /\.md$/,
        use: [
          {
            loader: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\raw-loader\\dist\\cjs.js'
          }
        ]
      },
      {
        test: /\.html$/,
        use: [
          {
            loader: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\html-loader\\index.js'
          }
        ]
      },
      {
        test: /\.js$/,
        include: /node_modules\/acorn-jsx/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              presets: [
                [
                  'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\preset-env\\lib\\index.js',
                  { modules: 'commonjs' }
                ]
              ]
            }
          }
        ]
      },
      {
        test: /\.(stories|story).mdx$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              cacheDirectory: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\.cache\\storybook',
              presets: [
                [
                  'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\preset-env\\lib\\index.js',
                  {
                    shippedProposals: true,
                    useBuiltIns: 'usage',
                    corejs: '3'
                  }
                ]
              ],
              plugins: [
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\plugin-proposal-object-rest-spread\\lib\\index.js',
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\plugin-proposal-class-properties\\lib\\index.js',
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\plugin-syntax-dynamic-import\\lib\\index.js',
                [
                  'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\babel-plugin-emotion\\dist\\babel-plugin-emotion.cjs.js',
                  { sourceMap: true, autoLabel: true }
                ],
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\babel-plugin-macros\\dist\\index.js',
                '@babel/plugin-transform-react-jsx'
              ]
            }
          },
          {
            loader: '@mdx-js/loader',
            options: {
              compilers: [ [Function: compiler] ],
              remarkPlugins: [ [Function: slug], [Function: externalLinks] ]
            }
          }
        ]
      },
      {
        test: /\.mdx$/,
        exclude: /\.(stories|story).mdx$/,
        use: [
          {
            loader: 'babel-loader',
            options: {
              cacheDirectory: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\.cache\\storybook',
              presets: [
                [
                  'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\preset-env\\lib\\index.js',
                  {
                    shippedProposals: true,
                    useBuiltIns: 'usage',
                    corejs: '3'
                  }
                ]
              ],
              plugins: [
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\plugin-proposal-object-rest-spread\\lib\\index.js',
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\plugin-proposal-class-properties\\lib\\index.js',
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@babel\\plugin-syntax-dynamic-import\\lib\\index.js',
                [
                  'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\babel-plugin-emotion\\dist\\babel-plugin-emotion.cjs.js',
                  { sourceMap: true, autoLabel: true }
                ],
                'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\babel-plugin-macros\\dist\\index.js',
                '@babel/plugin-transform-react-jsx'
              ]
            }
          },
          {
            loader: '@mdx-js/loader',
            options: {
              remarkPlugins: [ [Function: slug], [Function: externalLinks] ]
            }
          }
        ]
      },
      {
        test: /\.(stories|story)\.[tj]sx?$/,
        loader: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\@storybook\\source-loader\\dist\\server\\index.js',
        options: { inspectLocalDependencies: true },
        enforce: 'pre'
      },
      {
        test: /\.css$/,
        sideEffects: true,
        use: [
          'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\style-loader\\dist\\cjs.js',
          {
            loader: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\css-loader\\dist\\cjs.js',
            options: { importLoaders: 1 }
          },
          {
            loader: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\postcss-loader\\src\\index.js',
            options: {
              ident: 'postcss',
              postcss: {},
              plugins: [Function: plugins]
            }
          }
        ]
      },
      {
        test: /\.(svg|ico|jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|cur|ani|pdf)(\?.*)?$/,
        loader: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\file-loader\\dist\\cjs.js',
        query: { name: 'static/media/[name].[hash:8].[ext]' }
      },
      {
        test: /\.(mp4|webm|wav|mp3|m4a|aac|oga)(\?.*)?$/,
        loader: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\url-loader\\dist\\cjs.js',
        query: { limit: 10000, name: 'static/media/[name].[hash:8].[ext]' }
      }
    ]
  },
  resolve: {
    extensions: [ '.mjs', '.js', '.jsx', '.json' ],
    modules: [ 'node_modules' ],
    alias: {
      'babel-runtime/core-js/object/assign': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\core-js\\es\\object\\assign.js',
      react: 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\react',
      'react-dom': 'C:\\Users\\copel\\Development\\storybook-html-test\\node_modules\\react-dom'
    }
  },
  optimization: {
    splitChunks: { chunks: 'all' },
    runtimeChunk: true,
    minimizer: [
      TerserPlugin {
        options: {
          test: /\.m?js(\?.*)?$/i,
          chunkFilter: [Function: chunkFilter],
          warningsFilter: [Function: warningsFilter],
          extractComments: true,
          sourceMap: true,
          cache: true,
          cacheKeys: [Function: cacheKeys],
          parallel: true,
          include: undefined,
          exclude: undefined,
          minify: undefined,
          terserOptions: { mangle: false, keep_fnames: true }
        }
      }
    ]
  },
  performance: { hints: false }
}
webpack built 3e1fd99bd4e977e031d2 in 8582ms
╭────────────────────────────────────────────────────╮
│                                                    │
│   Storybook 5.3.8 started                          │
│   18 s for manager and 17 s for preview            │
│                                                    │
│    Local:            http://localhost:6006/        │
│    On your network:  http://192.168.1.147:6006/    │
│                                                    │
│   A new version (5.3.9) is available!              │
│                                                    │
│   Read full changelog here: https://git.io/fhFYe   │
│                                                    │
╰────────────────────────────────────────────────────╯

**Comment by bpeab** [comment]
Thanks for sharing.

I honestly don't understand why it doesn't transpile for you. The output you've shared match mine perfectly (apart from paths obviously). Assets are correctly transpiled on my side...

I'll keep investigating but I am slowly running out of ideas.

**Comment by tmeasday** [comment]
I was intrigued here, I've done the following (on my MacOS machine).

1. Cloned the example repo
2. Ran `npm i`
3. Ran `npm run storybook`
4. Looked at the file http://localhost:6006/vendors~main.99b14d9013ecfef0933d.bundle.js

I see this snippet, which is clearly compiled differently from [@RCopeland's version](https://github.com/storybookjs/storybook/issues/8884#issuecomment-579271745).

<img width="767" alt="image" src="https://user-images.githubusercontent.com/132554/73321009-3e3d8180-4295-11ea-8670-81694583459c.png">

---

Some interesting facts:

1. I'm running `npm run storybook` on a MacOS machine, not a windows one, as were both @bpeab and @ndelangen AFAICT. So my suspicion is the bundle is compiled differently on windows.

2. The code in question comes from inside `acorn-jsx/index.js`, a node module that shouldn't be compiled by Storybook (should it?). So the root issue seems to be the fact that that repo is not compiled in a way to be compatible with IE11. A change similar to the webpack patch that @ndelangen mentioned should help with this.

But why is it getting compiled already in MacOS @ndelangen?

**Comment by lmaze** [comment]
@bpeab My output from `--debug-webpack` is exactly similar to the one published by @RCopeland (apart from paths). I attach my problematic file under IE11 (with Storybook in dev mode) if you want to check too ([vendors-main.bundle.js.txt](https://github.com/storybookjs/storybook/files/4127058/vendors-main.bundle.js.txt))

**Comment by tmeasday** [comment]
Oh, OK read the above and I saw this PR:#9021. There is a bug in here:

https://github.com/storybookjs/storybook/blob/b28056354caf3fa347a728bb28a587a9733e0b8c/addons/docs/src/frameworks/common/preset.ts#L49

We need to use `path.join()`, `\/` won't work on windows..

**Comment by ndelangen** [comment]
@lmaze would you be able to open a PR fixing this?

**Comment by lmaze** [comment]
@ndelangen I will try to do the PR next Monday (if no one has pushed it before).

**Comment by shilman** [comment]
Great Caesar's ghost!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.19 containing PR #9790 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by caspardue** [comment]
Ran into the issue running on Windows using addon-docs. As PR #8884 seems to be for version 6 I've fixed the issue with [patch-package](https://github.com/ds300/patch-package) and the following patch:

```diff --git a/node_modules/@storybook/addon-docs/dist/frameworks/common/preset.js b/node_modules/@storybook/addon-docs/dist/frameworks/common/preset.js
index d9330f8..39af58f 100644
--- a/node_modules/@storybook/addon-docs/dist/frameworks/common/preset.js
+++ b/node_modules/@storybook/addon-docs/dist/frameworks/common/preset.js
@@ -39,6 +39,8 @@ var _remarkSlug = _interopRequireDefault(require("remark-slug"));
 
 var _remarkExternalLinks = _interopRequireDefault(require("remark-external-links"));
 
+var path = require("path);
+
 function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { "default": obj }; }
 
 function _toConsumableArray(arr) { return _arrayWithoutHoles(arr) || _iterableToArray(arr) || _nonIterableSpread(); }
@@ -91,7 +93,7 @@ function webpack() {
     module: Object.assign({}, module, {
       rules: [].concat(_toConsumableArray(module.rules || []), [{
         test: /\.js$/,
-        include: /node_modules\/acorn-jsx/,
+        include: new RegExp(`node_modules\\${path.sep}acorn-jsx`),
         use: [{
           loader: 'babel-loader',
           options: {
```

**Comment by ndelangen** [comment]
@caspardue Would you be able to put that in a PR?

**Comment by shilman** [comment]
Boo-yah!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.18 containing PR #9790 that references this issue. Upgrade today to try it out!

**Comment by edmulraney** [comment]
@shilman i'm still getting the same issue as above on 5.3.18

**Comment by shilman** [comment]
Hmm this was def merged. @lmaze any idea what's going on in 5.3.18?

**Comment by timohermans** [comment]
Updating to `@next` replaces the error with the following error:

SCRIPT1002: Syntax error

which points to:

```
const ANY = Symbol('SemVer ANY')
// hoisted class for cyclic dependency
class Comparator {
  static get ANY () {
    return ANY
  }
```

**Comment by daneah** [comment]
@timohermans I'm seeing the same on `6.0.0-beta.1`

**Comment by shilman** [comment]
@daneah @timohermans what do you see what you navigate to:

https://next--storybookjs.netlify.app/official-storybook/?path=/story/addons-a11y-basebutton--default

It's running beta.1 (`next` branch to be specific) and showing up fine in browserstack IE11.

I think the major problems are fixed in Storybook now. Let's get to the bottom of what's going wrong for you.

**Comment by tooppaaa** [comment]
@timohermans This is definitely an issue that was fixed recently. Above links is working for me in IE 11. Is the manager showing up for you ?

**Comment by daneah** [comment]
@shilman @tooppaaa those both seem to work—I see the problem specifically when using the web components flavor.

**Comment by tooppaaa** [comment]
Relates to #10486

**Comment by daneah** [comment]
Apologies, I missed that issue quite entirely. Will have a look!

**Comment by timohermans** [comment]
@shilman I can confirm the link you sent is working on my IE11. I will try to update storybook to the same version as yours and see what happens

**Comment by tooppaaa** [comment]
@timohermans Please hold for the next beta. We found an issue in the way the dll that ensure IE 11 compatibility was generated.
#10644 should resolve it (see the resolution comment as well)

**Comment by timohermans** [comment]
Thanks guys for all your hard work.

Is there a migration guide from 5.3 to 6.0? I can't seem to find it. Or maybe a quick rundown?

**Comment by tooppaaa** [comment]
You can follow [this guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md)

**Comment by shilman** [comment]
@timohermans [MIGRATION.md](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md) is the raw version, and I usually write a more conversational version as part of the release, like this one for 5.0: https://medium.com/storybookjs/storybook-5-migration-guide-d804b38c739d

**Comment by justinbayctxs** [comment]
I ran into this and agree this is not completely fixed on the v5 release. Looking at #9790, I tried tweaking that file in node_modules locally and could not get changes to take effect. I worked around this by force-compiling acorn-jsx in our 'main' storybook config since we're in full-control mode for TypeScript support (and other tweaks). Maybe full-control mode is a factor?

**Comment by beaolivei** [comment]
I updated my storybook to v.6.0.19. It works well in Chrome but it is never finishing loading when I open it in ie11 (I am using Browserstack for it). The console throws no errors, I am struggling to understand why this is happening. Is anyone else still having problems with storybook v.6 in IE11?

**Comment by tooppaaa** [comment]
Isn't it just slow ? It's IE 11 ;)

**Comment by beaolivei** [comment]
No ;)

**Comment by lacolaco** [comment]
I'm in the same situation with 6.0.21 and 6.0.26. Because the build outputs contains ES class syntax IE 11 throws an error.

**Comment by activenode** [comment]
Same on my side

**Comment by tooppaaa** [comment]
Working on a fix https://github.com/storybookjs/storybook/pull/12811

**Comment by annewanghy** [comment]
after I follow the doc in https://storybook.js.org/docs/react/configure/babel and https://storybook.js.org/docs/react/essentials/introduction#disabling-addons,
ie error cames from this package
```js
const wrapAnsi16 = (fn, offset) => function () {
	const code = fn.apply(colorConvert, arguments);
	return `\u001B[${code + offset}m`;
};
```
