### ISSUE TITLE
storybook not working (IE11 & chromium)

### ISSUE THREAD

**Issue by helabenkhalfallah** [storybookjs/storybook#9242]
**Describe the bug**
Runing storybook on chrome works perfectly.
Howerver not on IE 11 and chromium.

**IE 11 :** 
![image](https://user-images.githubusercontent.com/1331451/71410945-9d312a80-2647-11ea-9115-83f176efc268.png)

![image](https://user-images.githubusercontent.com/1331451/71411156-8dfeac80-2648-11ea-8335-6a11b79ae706.png)

**Chromium:**
![image](https://user-images.githubusercontent.com/1331451/71410976-bc2fbc80-2647-11ea-909b-8240758587ba.png)

**To Reproduce**
Launch storybook on IE11 or chromium.

**Expected behavior**
Storybook should works on IE11 and chromium.

**Code snippets**
storybook webpack config : 

```
// Export a function. Accept the base config as the only param.
module.exports = async ({ config }) => {
  config.module.rules.push({
    test: /\.scss$/,
    use: [
      // Creates `style` nodes from JS strings
      'style-loader',
      // Translates CSS into CommonJS
      'css-loader',
      // Compiles Sass to CSS
      'sass-loader',
    ],
  });
  config.module.rules.push({
    test: /\.(js|jsx)$/,
    exclude: /node_modules\/(?!(my-core-lib)\/).*/,
    use: {
      loader: 'babel-loader',
      options: {
        presets: [
          '@babel/preset-react',
          [
            '@babel/preset-env'
          ],
        ],
        plugins: [
          "@babel/plugin-transform-arrow-functions",
          "@babel/plugin-proposal-object-rest-spread",
          "@babel/plugin-proposal-optional-chaining",
          "@babel/plugin-syntax-dynamic-import",
          "@babel/plugin-proposal-class-properties",
          "@babel/plugin-transform-react-jsx"
        ]
      }
    },
  });
  config.resolve.extensions.push(".js", ".jsx");

  // Return the altered config
  return config;
};
```

**addon.js :** 
```
import 'storybook-readme/register';
import '@storybook/addon-options/register';
import '@storybook/addon-actions/register';
```

**storybook config :** 

```
import { addDecorator, configure } from '@storybook/react';
import { withInfo } from '@storybook/addon-info';
import { setConsoleOptions } from '@storybook/addon-console';

// setup storybook page css
import './index.css';

// set console options
setConsoleOptions({
  panelExclude: [],
});

// settings
addDecorator(
  withInfo({
    maxPropsIntoLine: 1,
    name: 'React Components',
    url: 'xxx',
    goFullScreen: false,
    showStoriesPanel: true,
    showAddonPanel: true,
    showSearchBox: false,
    addonPanelInRight: true,
    sortStoriesByKind: true,
    inline: true,
    header: false,
    source: true,
    styles: (stylesheet) => {
      const style = {
        ...stylesheet,
        infoBody: {
          padding: '10px',
        },
      };
      return style;
    },
  }),
);

const req = require.context('..', true, /\.jsx$/);
function loadStories(){
  req.keys().forEach((filename) => req(filename));
}

configure(loadStories, module);
```

I tried to use babel config like useBuiltIns & coreJS & module. but the same issue.
I also tried suggested solution on others thread.

**System:**

```
Environment Info:
  System:
    OS: Windows 10 10.0.17134
    CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
  Binaries:
    Node: 10.13.0 
    npm: 6.4.1 
  Browsers:
    Edge: 42.17134.1098.0
```

Storybook version : 

```
    "@storybook/addon-actions": "=5.2.6",
    "@storybook/addon-console": "=1.2.1",
    "@storybook/addon-info": "=5.2.6",
    "@storybook/addon-knobs": "=5.2.6",
    "@storybook/addon-links": "=5.2.6",
    "@storybook/addon-options": "=5.2.6",
    "@storybook/addons": "=5.2.6",
    "@storybook/react": "=5.2.6",
```

Thanks.

**Comment by shilman** [comment]
@ndelangen Another IE issue 🤦‍♂

**Comment by pocka** [comment]
Probably https://github.com/zloirock/core-js/issues/736 ?
The issue was fixed in `core-js@3.6.1`, so please try upgrading. (And this might solve our CI error)

**Comment by helabenkhalfallah** [comment]
OK I try. Thanks :)

**Comment by helabenkhalfallah** [comment]
Hello @pocka , 
I updated to storybook 3.6.8 and I have :

**Comment by helabenkhalfallah** [comment]
![image](https://user-images.githubusercontent.com/1331451/71523684-5141e800-28ca-11ea-9266-bc59648dc48f.png)
![image](https://user-images.githubusercontent.com/1331451/71523690-5bfc7d00-28ca-11ea-8d2d-32ba699138e3.png)

**Comment by helabenkhalfallah** [comment]
I tried also : delete package lock, delete node module, npm install again.

**Comment by pocka** [comment]
@helabenkhalfallah 
Can't reproduce in a simple react app (non-CRA) even with core-js@3.5.0... could you provide a minimal repro repo?

**Comment by zloirock** [comment]
Most likely it's an error in the Babel config https://github.com/zloirock/core-js/issues/514

**Comment by helabenkhalfallah** [comment]
Hello, I removed all my stories and I started from scratch, but always the same issue.
Here is my webpack config : 

```
module.exports = async ({ config }) => {
  config.module.rules.push({
    test: /\.scss$/,
    use: [
      // Creates `style` nodes from JS strings
      'style-loader',
      // Translates CSS into CommonJS
      'css-loader',
      // Compiles Sass to CSS
      'sass-loader',
    ],
  });
  config.module.rules.push({
    test: /\.(js|jsx)$/,
    exclude: /node_modules\/(?!(core-module)\/).*/,
    use: {
      loader: 'babel-loader',
      options: {
        presets: [
          '@babel/preset-react',
          [
            '@babel/preset-env',
            {
              modules: false,
              useBuiltIns: 'entry',
              corejs: 3,
              targets: {
                browsers: [
                  'chrome >= 41',
                  'ie >= 9',
                  'firefox >= 36',
                  'and_ff >= 36',
                  'android >= 4.4',
                  'iOS >= 8',
                  'last 1 samsung versions',
                ],
              },
            },
          ],
        ],
        babelrc: false,
        plugins: [
          "@babel/plugin-transform-arrow-functions",
          "@babel/plugin-proposal-object-rest-spread",
          "@babel/plugin-proposal-optional-chaining",
          "@babel/plugin-syntax-dynamic-import",
          "@babel/plugin-proposal-class-properties",
          "@babel/plugin-transform-react-jsx"
        ]
      }
    },
  });
  config.resolve.extensions.push(".js", ".jsx");

  // Return the altered config
  return config;
};
```

Addons.js : 

```
import 'storybook-readme/register';
import '@storybook/addon-options/register';
import '@storybook/addon-actions/register';
```

config.js : 

```
import { addDecorator, configure } from '@storybook/react';
import { withInfo } from '@storybook/addon-info';
import { setConsoleOptions } from '@storybook/addon-console';

// setup storybook page css
import './index.css';

// set console options
setConsoleOptions({
  panelExclude: [],
});

// settings
addDecorator(
  withInfo({
    maxPropsIntoLine: 1,
    name: 'React Components',
    url: 'url',
    goFullScreen: false,
    showStoriesPanel: true,
    showAddonPanel: true,
    showSearchBox: false,
    addonPanelInRight: true,
    sortStoriesByKind: true,
    inline: true,
    header: false,
    source: false,
    styles: (stylesheet) => {
      const style = {
        ...stylesheet,
        infoBody: {
          padding: '10px',
        },
      };
      return style;
    },
  }),
);

const req = require.context('..', true, /\.jsx$/);
function loadStories(){
  req.keys().forEach((filename) => req(filename));
}

configure(loadStories, module);
```

I tried suggested solution in others thread for babel, but same issue.

```
SCRIPT5022: Exception levée mais non décelée
vendors~main.ca0fbf9b7d8efbd365f9.bundle.js (138086,55)

/***/ "../../node_modules/core-js/internals/internal-state.js":
/*!*************************************************************************************************************************!*\
  !*** XXX/node_modules/core-js/internals/internal-state.js ***!
  \*************************************************************************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

var NATIVE_WEAK_MAP = __webpack_require__(/*! ../internals/native-weak-map */ "../../node_modules/core-js/internals/native-weak-map.js");

var global = __webpack_require__(/*! ../internals/global */ "../../node_modules/core-js/internals/global.js");

var isObject = __webpack_require__(/*! ../internals/is-object */ "../../node_modules/core-js/internals/is-object.js");

var createNonEnumerableProperty = __webpack_require__(/*! ../internals/create-non-enumerable-property */ "../../node_modules/core-js/internals/create-non-enumerable-property.js");

var objectHas = __webpack_require__(/*! ../internals/has */ "../../node_modules/core-js/internals/has.js");

var sharedKey = __webpack_require__(/*! ../internals/shared-key */ "../../node_modules/core-js/internals/shared-key.js");

var hiddenKeys = __webpack_require__(/*! ../internals/hidden-keys */ "../../node_modules/core-js/internals/hidden-keys.js");

var WeakMap = global.WeakMap;
var set, get, has;

var enforce = function enforce(it) {
  return has(it) ? get(it) : set(it, {});
};

var getterFor = function getterFor(TYPE) {
  return function (it) {
    var state;

    if (!isObject(it) || (state = get(it)).type !== TYPE) {
      throw TypeError('Incompatible receiver, ' + TYPE + ' required');
    }

    return state;
  };
};

```

If I use my components inside a separated project, everything works perfectly.

**Comment by zloirock** [comment]
One more time - please, check your Babel config - it should not transpile `core-js` - it's ~99% cases of errors in this line.

**Comment by helabenkhalfallah** [comment]
> One more time - please, check your Babel config - it should not transpile `core-js` - it's ~99% cases of errors in this line.
> 
> > exclude: /node_modules/(?!(core-module)/).*/,
> 
> is incorrect regex for this case.

core-module is my core module, I know that it should not transpile core-js. 
I updated the code.

**Comment by helabenkhalfallah** [comment]
I check my babel again, thank.

**Comment by afebbraro** [comment]
I noticed that https://monorepo.storybook.now.sh/ is not loading in IE11. My instance of SB isn't loading either in IE11 on windows 10.
`"@storybook/addon-a11y": "^5.3.0-rc.7",
    "@storybook/addon-docs": "^5.3.0-rc.7",
    "@storybook/addons": "^5.3.0-rc.7",
    "@storybook/angular": "^5.3.0-rc.7",
    "@storybook/preset-scss": "^1.0.2",
    "@storybook/theming": "^5.3.0-rc.7",`

**Comment by beth-panx** [comment]
I am having the same issue with IE11 on windows 10. Below is storybook versions.
```
    "@babel/core": "^7.7.5",
    "@storybook/addon-a11y": "^5.3.0-beta.31",
    "@storybook/addon-actions": "^5.3.0-beta.31",
    "@storybook/addon-docs": "^5.3.0-beta.31",
    "@storybook/addon-knobs": "^5.3.0-beta.31",
    "@storybook/addon-links": "^5.3.0-beta.31",
    "@storybook/addon-storysource": "^5.3.0-beta.31",
    "@storybook/storybook-deployer": "^2.8.1",
    "@storybook/web-components": "^5.3.0-beta.31",
    "@webcomponents/webcomponentsjs": "^2.4.0",
    "babel-loader": "^8.0.6",
    "babel-polyfill": "6.26.0"
```

However I was able to get storybook to work on Edge by adding the webcomponent polyfill (@webcomponents/webcomponentsjs/webcomponents-bundle.js') in preview.js

**Comment by afebbraro** [comment]
Hey all! Wondering if anyone found a workaround for this for the react/angular/html storybooks? Still experiencing the new 5.3.3 not working in Edge or IE.

**Comment by ndelangen** [comment]
Found some problem kinda caused by this:
https://calendar.google.com/calendar?cid=OGQwdTcwc25vc2NmZDhsNmdpazZvNzNrMjBAZ3JvdXAuY2FsZW5kYXIuZ29vZ2xlLmNvbQ

**Comment by ndelangen** [comment]
I'm seeing 2 errors in the manager, 0 in the preview.

1 error is related to emotion. The emotion plugin seems to add a property to an object that already has that exact property. A duplicate property is a fatal error in IE11 😭 

the second error seems to do with some code in node_modules not being IE11 friendly, graphiql has dependencies on some packages that have destructuring in them.

---

I have opened a PR with babel-emotion-plugin to address problem 1.

The other problem I am trying to find a proper solution for still

**Comment by ndelangen** [comment]
I'm able to get it to work right now by changing the webpack config:

```js
// main.js
module.exports = {
  webpackFinal: async (config, { configType }) => ({
    ...config,
    module: {
      ...config.module,
      rules: [
        ...config.module.rules.slice(1),
        {
          test: /\.(mjs|jsx?|tsx?)$/,
          use: [
            {
              loader: 'babel-loader',
              options: {
                cacheDirectory: `.cache/storybook`,
                presets: [
                  [
                    '@babel/preset-env',
                    { shippedProposals: true, useBuiltIns: 'usage', corejs: 3 },
                  ],
                  '@babel/preset-typescript',
                  configType === 'PRODUCTION' && [
                    'babel-preset-minify',
                    { builtIns: false, mangle: false },
                  ],
                  '@babel/preset-react',
                  '@babel/preset-flow',
                ].filter(Boolean),
                plugins: [
                  '@babel/plugin-proposal-object-rest-spread',
                  '@babel/plugin-proposal-class-properties',
                  '@babel/plugin-syntax-dynamic-import',
                  // ['babel-plugin-emotion', { sourceMap: true, autoLabel: true }],
                  'babel-plugin-macros',
                  '@babel/plugin-transform-react-constant-elements',
                  'babel-plugin-add-react-displayname',
                  [
                    'babel-plugin-react-docgen',
                    { DOC_GEN_COLLECTION_NAME: 'STORYBOOK_REACT_CLASSES' },
                  ],
                ],
              },
            },
          ],
          exclude: [/node_modules/, /dist/],
        },
        {
          test: /\.js$/,
          use: [
            {
              loader: 'babel-loader',
              options: {
                presets: [
                  [
                    '@babel/preset-env',
                    { shippedProposals: true, useBuiltIns: 'usage', corejs: 3 },
                  ],
                ],
              },
            },
          ],
          include: [/node_modules\/graphql-/],
        },
      ],
    },
  }),
}
```

**Comment by ndelangen** [comment]
related?:
https://github.com/storybookjs/storybook/issues/7540

**Comment by ndelangen** [comment]
related: https://github.com/storybookjs/storybook/issues/8884

**Comment by ndelangen** [comment]
Waiting for emotion-js/emotion#1731 to be released

**Comment by WirthAware** [comment]
We having similar issues running storybook/react in IE 11. 
We tried newest v5.3.17 also new alpha version v6.0.0-alpha.29. 
We also tried to run storybook from scratch w/o any addition just initialize storybook and tried out in IE 11. 
But we was not able to run it in IE 11. 

![image](https://user-images.githubusercontent.com/137501/77919486-89780e80-729d-11ea-9086-cf1492714134.png)

![image](https://user-images.githubusercontent.com/137501/77919572-a4e31980-729d-11ea-991b-4f2c32fb7a35.png)

With storybook v5.x it breaks at this line 
```
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const callAll = (...fns) => (...args) => fns.forEach(fn => fn && fn(...args));
...
```

We also tried use babel, babel/preset-env options corejs ... but nothing seems to work. 


System:
```
Environment Info:
  System:
    MacOS: 10.14.6
    CPU: 2,8 GHz Intel Core i7
  Binaries:
    Node: v13.12.0 
    npm: 6.14.4 
  Browsers:
    IE: 11 (Windows 10) -- Tested on Browserstack
```

**Comment by ndelangen** [comment]
@WirthAware that looks like there's come code in node_modules (perhaps `semver`?) that's ES6. If that's the case, what needs to happen for IE11 support is to pass the dependency thru babel-loader, (which will transform the ES6 to ES5)

**Comment by WirthAware** [comment]
@ndelangen but it also happen with a clean and fresh installation of storybook w/o any other dependency. Already tried some babel reconfiguration, also babel transformer but nothing seems to work

**Comment by ndelangen** [comment]
working on this..

**Comment by ndelangen** [comment]
<img width="1918" alt="Screenshot 2020-04-02 at 10 54 31" src="https://user-images.githubusercontent.com/3070389/78229543-6da87e80-74d0-11ea-9972-d1d729c3b37d.png">

got it working!

(dll must be enabled)

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.31 containing PR #10281 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by katywatkins** [comment]
@WirthAware Were you able to resolve that syntax error? I've been running into the exact same error in a fresh install and haven't been able to resolve it.

**Comment by helabenkhalfallah** [comment]
I tried this version but IE11 still not working : 
`"@storybook/react": "=6.0.0-beta.38",`

![image](https://user-images.githubusercontent.com/1331451/86169310-b72d5780-bb19-11ea-9552-ac369de16fbe.png)

**Comment by helabenkhalfallah** [comment]
The same thing for : 
`"@storybook/react": "=6.0.0-alpha.31",`

![image](https://user-images.githubusercontent.com/1331451/86172306-7126c280-bb1e-11ea-84a8-ed6272a7d1b2.png)

**Comment by shilman** [comment]
@ndelangen @tooppaaa any idea what's going on here?

**Comment by katywatkins** [comment]
@helabenkhalfallah have you tried updating all of the Storybook packages to 6.0.0-beta.38? I was struggling with the error you're seeing for a long time. beta.16+ resolved it for me, but I've been updating everything to beta versions, not just Storybook/react.

**Comment by helabenkhalfallah** [comment]
@katywatkins I tried now : 

```
    "@storybook/addon-a11y": "^6.0.0-beta.38",
    "@storybook/addon-actions": "^6.0.0-beta.38",
    "@storybook/addon-console": "^1.2.1",
    "@storybook/addon-info": "^5.3.19",
    "@storybook/addon-knobs": "^6.0.0-beta.38",
    "@storybook/addon-links": "^6.0.0-beta.38",
    "@storybook/addon-options": "^5.3.19",
    "@storybook/addon-viewport": "^6.0.0-beta.38",
    "@storybook/addons": "^6.0.0-beta.38",
    "@storybook/react": "^6.0.0-beta.38",
```

I can't update @storybook/addon-info, @storybook/addon-console and @storybook/addon-options, npm fail.

I get the same error.

I tried also remove node module, package lock, dist and reinstall.

![image](https://user-images.githubusercontent.com/1331451/86213988-d6a89c80-bb7a-11ea-8642-8cd525597a75.png)

This is also my storybook config file : 

```
import { addDecorator, configure } from '@storybook/react';
import { withInfo } from '@storybook/addon-info';
import { setConsoleOptions } from '@storybook/addon-console';
import { withA11y } from '@storybook/addon-a11y';

// setup storybook page css
import './index.css';

// set console options
setConsoleOptions({
  panelExclude: [],
});

// settings
addDecorator(
  withInfo({
    maxPropsIntoLine: 1,
    name: 'React SG Components',
    url: 'https://sgithub.fr.world.socgen/AppliDigitalClient/bddf_npm_sg-components_plus',
    goFullScreen: false,
    showStoriesPanel: true,
    showAddonPanel: true,
    showSearchBox: false,
    addonPanelInRight: true,
    sortStoriesByKind: true,
    inline: true,
    header: false,
    source: false,
    styles: (stylesheet) => {
      const style = {
        ...stylesheet,
        infoBody: {
          padding: '10px',
        },
      };
      return style;
    },
  }),
);

addDecorator(withA11y);

const req = require.context('..', true, /\.jsx$/);
function loadStories(){
  req.keys().forEach(function (filename) {
      req(filename);
  });
}

configure(loadStories, module);
```

When deploying storybook (storybook build and deploy bundle) it works in IE but local dev not.

It's hard to deploy each time to test little thing :( :( 

Thank you for your help.

**Comment by shilman** [comment]
Good catch @katywatkins. Please try removing `@storybook/addon-info` @helabenkhalfallah

**Comment by helabenkhalfallah** [comment]
Okay @shilman I try now this, thank you 👍

**Comment by helabenkhalfallah** [comment]
Unfortunately not : 

I removed everything : 

stories index : 

```
import React from 'react';
import {
  storiesOf,
} from '@storybook/react';
import {
  withKnobs,
} from '@storybook/addon-knobs';
import { INITIAL_VIEWPORTS } from '@storybook/addon-viewport';

// stories
const stories = storiesOf('SG Components UI Kit', module);

// prepare story board
stories
  .addParameters(
    {
      options: {
        theme: {},
      },
      viewport: {
        viewports: INITIAL_VIEWPORTS,
      },
    }
  )
  .addDecorator(withKnobs);
```

addonjs => empty

config.js : 

```
import { addDecorator, configure } from '@storybook/react';
import { setConsoleOptions } from '@storybook/addon-console';
import { withA11y } from '@storybook/addon-a11y';

// setup storybook page css
import './index.css';

// set console options
setConsoleOptions({
  panelExclude: [],
});

addDecorator(withA11y);

const req = require.context('..', true, /\.jsx$/);
function loadStories(){
  req.keys().forEach((filename) => req(filename));
}

configure(loadStories, module);
```

package.json, info removed : 

```
    "@storybook/addon-a11y": "=6.0.0-beta.38",
    "@storybook/addon-actions": "=6.0.0-beta.38",
    "@storybook/addon-console": "=1.2.1",
    "@storybook/addon-knobs": "=6.0.0-beta.38",
    "@storybook/addon-links": "=6.0.0-beta.38",
    "@storybook/addon-options": "=5.3.19",
    "@storybook/addon-viewport": "=6.0.0-beta.38",
    "@storybook/addons": "=6.0.0-beta.38",
    "@storybook/react": "=6.0.0-beta.38",
```

remove all node modules and reinstall.

![image](https://user-images.githubusercontent.com/1331451/86275668-e86a5e00-bbd3-11ea-9cf3-06522699f993.png)

**Comment by tooppaaa** [comment]
@helabenkhalfallah What is the exact issue in the console ? I've seen above it was about semver but I don't recognize where `getterFor`

@storybook/addon-options is deprecated since 5.x, could you try to remove it and see how it goes ?

**Comment by helabenkhalfallah** [comment]
Yes @tooppaaa I will do it now ! thank you 👍

**Comment by helabenkhalfallah** [comment]
The same error  : 
I have delete node modules, package lock and reinstall.

![image](https://user-images.githubusercontent.com/1331451/86288591-72252600-bbea-11ea-90ac-25cb39ec43ae.png)
![image](https://user-images.githubusercontent.com/1331451/86288611-7d785180-bbea-11ea-88a0-1d18ba5b9556.png)
![image](https://user-images.githubusercontent.com/1331451/86288645-8832e680-bbea-11ea-8a8a-96fcbf8353c4.png)

![image](https://user-images.githubusercontent.com/1331451/86288714-a26cc480-bbea-11ea-8972-8929dad6a0b7.png)
![image](https://user-images.githubusercontent.com/1331451/86288731-aac4ff80-bbea-11ea-87fb-5c432ebf1036.png)

![image](https://user-images.githubusercontent.com/1331451/86288790-cfb97280-bbea-11ea-9ee7-6785881e70fb.png)
![image](https://user-images.githubusercontent.com/1331451/86288818-de078e80-bbea-11ea-80eb-2c41d424bf6d.png)
![image](https://user-images.githubusercontent.com/1331451/86288862-f24b8b80-bbea-11ea-89f3-57b0703d44e6.png)
![image](https://user-images.githubusercontent.com/1331451/86288929-1018f080-bbeb-11ea-949e-b1d65b1defe7.png)

**Comment by helabenkhalfallah** [comment]
Chrome :

![image](https://user-images.githubusercontent.com/1331451/86289291-be249a80-bbeb-11ea-90de-b1d5c941c864.png)


IE 11 : 

![image](https://user-images.githubusercontent.com/1331451/86289358-dc8a9600-bbeb-11ea-9846-2fff55c693f8.png)

**Comment by tooppaaa** [comment]
Thanks for this.
The manager is correctly displayed, meaning it's not a storybook issue.

I can try to look a bit more, do you have a public reproduction of this issue ?

**Comment by helabenkhalfallah** [comment]
@tooppaaa Unfortunately not, it is an internal project  :( :( 
I removed everything from the storybook.
I will try in a separated project from scratch.
I will let you in, thank you so much :) :)

**Comment by impulsivetomato** [comment]
I was able to fix the issue using the following

```js
module.exports = {
  addons: ['@storybook/addon-docs', '@storybook/addon-knobs'],
  stories: ['../src/**/*.stories.@(js|mdx)', '../stories/*.js'],
  webpackFinal: async (config) => {

    config.module.rules = [
      ...config.module.rules,
      {
        test: /\.js$/,
        include: /node_modules\/@react-leaflet|react-leaflet/,
        loader: 'babel-loader',
        options: {
          babelrc: false, 
          presets: ['@babel/preset-env'],
        },
      },
    ];

    return config;
  },
};

```

**Comment by ijain3** [comment]
@WirthAware Were you able to find the fix?

**Comment by wapophis** [comment]
Same error has been happening to my install using transpilation on a web-components type project. 
Following the guide defined in the readme.md of this app, fails when you store your app project in any path which contains a src folder ej: /usr/src/workspace. When using this paths seems than core-js gets transpiled too by bable-loader with the regexp specified.
