### ISSUE TITLE
Unexpected 'componentname' when component has non leaf children

### ISSUE THREAD

**Issue by hasparus** [storybookjs/storybook#9314]
Hi there 👋

**Describe the bug**
A component can't be a folder _(have non leaf children)_ in docs mode.

**To Reproduce**

1. Create stories in following manner
    
    ```jsx
    // src/RichTextEditor/index.story.jsx
    
    export default { title: 'RichTextEditor' };
    
    export const story = () => (
      <RichTextEditor>
        <EmojiButton>One</EmojiButton>
        <ImageButton>Two</ImageButton>
      </RichTextEditor>
    );
    ```

    ```jsx
    // src/RichTextEditor/EmojiButton/index.story.jsx
    
    export default { title: 'RichTextEditor/EmojiButton' };
    
    export const story = () => <EmojiButton />;
    ```

2. In dev mode, stories of `RichTextEditor` will gladly live alongside `EmojiButton`.
    In docs mode, the app crashes with an error:
    ```
    Error: Unexpected 'richtexteditor': {"isComponent":true,"nonLeafChildren":["richtexteditor-emojibutton"]}
    ```
    thrown from https://github.com/storybookjs/storybook/blob/ad7f5692864670fdaf78c380c799ca46ea185df8/lib/ui/src/containers/nav.js#L134-L141

**Expected behavior**
I'd expect `RichTextEditor` stories to be collapsed into an index page.

![image](https://user-images.githubusercontent.com/15332326/71728330-1b0de680-2e3d-11ea-9122-a4d6fadea957.png)

**System:**
```
    OS: Windows 10 10.0.18362
    CPU: (8) x64 Intel(R) Core(TM) i7-4710HQ CPU @ 2.50GHz
    Node: 13.3.0
    Yarn: 1.19.2
    npm: 6.9.0
```

**Additional context**

@shilman already works on this 🙇 

**Workaround**

Create an index page explicitly.

```jsx
// src/RichTextEditor/index.story.jsx
export default { title: 'RichTextEditor/RichTextEditor' };
```

**Comment by shilman** [comment]
Egads!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-rc.11 containing PR #9321 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by hasparus** [comment]
Hey @shilman, it still fails for me with the same error. Isn't the order of collapsing wrong? In my case, the parent still has non-leaf children, because nobody collapsed them yet.

**Comment by shilman** [comment]
@hasparus can you share a repro repo?

**Comment by hasparus** [comment]
some more info:

The parent is a component.  (`item.isComponent === true`)
![image](https://user-images.githubusercontent.com/15332326/71910143-afe04f00-3171-11ea-87c2-c48a58c29863.png)

---

I worked around it to get a satisfying result for my case

![image](https://user-images.githubusercontent.com/15332326/71910118-9c34e880-3171-11ea-9d8f-007c25dc7540.png)

![image](https://user-images.githubusercontent.com/15332326/71910099-8fb09000-3171-11ea-896d-1821dd4aeafe.png)

**Comment by shilman** [comment]
Thanks @hasparus! @ndelangen and I are going to pair on this tomorrow 💯

**Comment by shilman** [comment]
Gadzooks!! I just released https://github.com/storybookjs/storybook/releases/tag/v5.3.0-rc.12 containing PR #9356 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.
