### ISSUE TITLE
Import order wrongly causing "Element type is invalid" errors in stories

### ISSUE THREAD

**Issue by chrisdunnbirch** [storybookjs/storybook#9516]
**Description**

When using a component import/export entry-point for terse imports throughout the application the order of imports can cause unexpected errors in Storybook only; not in the `yarn start` environment or compiled application. The error is:

`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

Imagine we have a `components/` directory, in which we have an import/export entry-point `index.js` and each component has its own directory `A/` and `B/`.

`src/components/index.js`:
```
// This order causes no errors in `yarn start` but causes an error in the story for component A
import { A } from "./A";
import { B } from "./B";
// This order causes no errors anywhere
// import { B } from "./B";
// import { A } from "./A";

// It doesn't matter in which order we export (A,B or B,A), only the order of the import causes the error
export { A, B };
```

This behaviour only appears to affect a component if it itself imports another component which appears below itself in the import/export entry-point.

For example in the above example component A itself imports component B to use within its render, and the only way to avoid the error in the story for component A is to remove component B from it or to swap the order of the imports in src/components/index.js.

Reproduction repo below for simpler demonstration.

**To Reproduce**

I understand that the description may be a little confusing to follow so I have created a barebones CRA + Storybook + 2 components reproduction repository which also causes the error.

Reproduction: https://github.com/chrisdunnbirch/storybook-import-bug

1. Clone `git@github.com:chrisdunnbirch/storybook-import-bug.git`
2. Run `yarn install`
3. Run `yarn storybook`
4. Check `A > Story` in Storybook (should render with above error)
  a. Run `yarn start` (should render as expected: "AB")
5. Comment lines 4-5 and uncomment lines 8-9 in `src/components/index.js`
6. Check `A > Story` in Storybook (should render as expected: "AB")

**Expected behavior**

The story renders without error, as expected based on the behaviour of the `yarn start` environment and compiled application.

**System**

I first noticed this in a large TypeScript project which at the time had `5.3.0-rc.10` installed and the issue is still present in `5.3.6`. The example reproduction repo above is the absolute barebones CRA + Storybook + 2 components with no TypeScript.

**Additional context**

It is worth noting that I have added a `.env` with `NODE_PATH=src` to recreate the behaviour of absolute imports that the CRA TypeScript preset allows by default.

**Comment by atanasster** [comment]
@chrisdunnbirch thanks a lot for the detailed report and reproduction sample. 
It is a strange issue, not sure whats the root cause.

However, wouldn't it be better practice to isolate your stories anyway
Ie 
`import { A } from ‘./index’`

**Comment by atanasster** [comment]
As a reference point, Here is a similar use case as yours, and i am avoiding circular references inside the repo:

https://github.com/atanasster/grommet-controls/blob/master/src/components/Avatar/doc/Avatar.stories.tsx

**Comment by chrisdunnbirch** [comment]
> However, wouldn't it be better practice to isolate your stories anyway
> Ie
> `import { A } from ‘./index’`

Maybe it is, I don't really know. It seems to make sense that that is a good idea.

There are often cases where I need to import multiple components for use in a story and whereever possible I prefer to keep my code clean. For example `import { A, D, M, N } from "components";` is much cleaner than:

```
import { A } from "./";
import { D } from "../D";
import { M } from "../M";
import { N } from "../N";
```

Regardless of what is best practice, I've been using Storybook for around a year and this error is still wrongly appearing and should be fixed.

**Comment by chrisdunnbirch** [comment]
@atanasster I'm not sure what you mean by library, do you mean internally within Storybook? I think I'm confused because in my specific case our components are not in a separate library, they are in the same project as the application itself so "internally in the library" and "users of the library" is the same thing.

To clarify, do you mean that any component which is exported from `src/components/index.js` should never `import ... from "components"`?

**Comment by atanasster** [comment]
ah, sorry for confusing. 
Yes, I meant that if A is exported from 'src/components/index.js', it should not import from that same file but instead do a relative import.

**Comment by chrisdunnbirch** [comment]
Webpack should figure everything out for you but yeah that seems like a sensible approach in general.

It is worth noting again, for anyone readin now, that the error doesn't appear in either the development or production application. It only appears in Storybook (wrongly I believe).

**Comment by shilman** [comment]
Yeah, I think something changed in 5.3 (maybe in `preset-cra`? cc @mrmckeb) that is causing these kinds of idiosyncrasies to show up all of a sudden.

**Comment by nocarroll** [comment]
I am experiencing this issue as well after upgrading from Storybook 3.4.11 to 5.2.8

For now, I have worked around the issue by importing each component from its directory rather than the component index file I had defined.

### Before
```jsx
import { MyButton, MyIcon, MyColourPicker } from '../';

```

### After
```jsx
import MyButton from '../../../MyButton';
import MyIcon from '../../../MyIcon';
import MyColourPicker from '../../../MyColourPicker';
```

In my project, I believe the issue is caused by `MyIcon` being a dependency of `MyColourPicker` as well as being imported as a sibling component.

As the OP has said, this worked fine in previous versions and works outside of SB as well.

**Comment by mrmckeb** [comment]
Hi @nocarroll, can you provide details about your Storybook config? Could there be duplicate Babel plugins/presets?

**Comment by nocarroll** [comment]
Hi @mrmckeb here are the babel and storybook related packages in my `package.json`

```json
	"@babel/core": "7.3.4",
    "@babel/plugin-proposal-class-properties": "7.10.1",
    "@babel/preset-env": "7.3.4",
    "@babel/preset-react": "7.0.0",
    "@storybook/addon-actions": "5.3.19",
    "@storybook/addon-info": "5.3.19",
    "@storybook/addon-knobs": "5.3.19",
    "@storybook/addon-options": "5.3.19",
    "@storybook/addons": "5.3.19",
    "@storybook/react": "5.3.19",
    "babel-eslint": "10.0.2",
    "babel-loader": "8.1.0",
    "babel-plugin-import": "1.11.0",
```

and this is my `.babelrc`

```
{
    "presets": [
        [
            "@babel/preset-env",
            {
                "modules": false,
                "targets": {
                    "browsers": [
                        "last 2 versions"
                    ]
                }
            }
        ],
        "@babel/preset-react"
    ],
    "plugins": [
        [
            "@babel/plugin-proposal-class-properties",
            {
                "spec": true
            }
        ],
        [
            "import",
            {
                "libraryName": "antd",
                "style": "css"
            }
        ]
    ],
    "env": {
        "test": {
          "presets": ["@babel/preset-env", "@babel/preset-react"]
        }
    }
}
```

The `.babelrc` is unchanged from when I was running Storybook 3.4.11 except for swapping `"transform-class-properties"` for `"@babel/plugin-proposal-class-properties"`

I think the spec option is not actually read by the plugin but I included it since it's still in my WIP branch for upgrading to Storybook 5.

**Comment by mrmckeb** [comment]
Hi @nocarroll, I can definitely see presets/plugins that would be duplicates in this setup. Is this a project Babel config or for Storybook?

@shilman We'll probably need to add some automatic filtering of duplicate plugins/presets in future... I'm not sure of the best way to do that now though.

**Comment by nocarroll** [comment]
The babel config is for our Storybook app only.

Would this have been an incorrect setup under v3 as well?

**Comment by mrmckeb** [comment]
@nocarroll I would need to look, but basically you're including a bunch of presets that are now included by default. By doing that, both get loaded and that's why the app is breaking. Maybe try without a Babel config, and see if it builds? If not, add the presets you think are missing? That would probably be the easiest path IMO!

**Comment by nocarroll** [comment]
@mrmckeb interesting, I saw the same thing happening with webpack loaders after upgrading v3 -> v5, though I managed to figure out that removing the custom declarations solved the issue in that case.

I'll try your suggestion, thanks for the replies.

**Comment by shilman** [comment]
@mrmckeb i think we can detect & warn?

**Comment by nocarroll** [comment]
@mrmckeb Just to follow up, I removed the presets from my `.babelrc` keeping only the test setup and the loader for `antd`. The app runs fine like this, which is great, but I'm still getting the same error as before when importing from the component index file (as detailed in https://github.com/storybookjs/storybook/issues/9516#issuecomment-647451558)

```
// .babelrc
{
    "plugins": [
        [
            "import",
            {
                "libraryName": "antd",
                "style": "css"
            }
        ]
    ],
    "env": {
        "test": {
          "presets": ["@babel/preset-env", "@babel/preset-react"]
        }
    }
}

```

### Error when importing from shared component index
![image](https://user-images.githubusercontent.com/13739271/85411771-ad778300-b560-11ea-9bc6-566426e6d395.png)

**Comment by mrmckeb** [comment]
Interesting - sorry you're still hitting this @nocarroll. Are you able to share a small reproduction? Even privately?

**Comment by nocarroll** [comment]
@mrmckeb I'll see about putting something together. It likely won't be for a few days since it's not blocking my work at the moment.

**Comment by mrmckeb** [comment]
No problem, if it's by the weekend - that's perfect as I have a lot more free time then ;)

**Comment by vajdagabor** [comment]
I am having a similar issue after copying over my components into a new project and installing a fresh StoryBook. The SB version in **both projects** is 5.3.19. One works perfectly with the same components and structure, and the other is failing with `Element type is invalid` error, only in StoryBook (the app is fine).

The way I import the modules is very similar to what @chrisdunnbirch described. The issue is only with a `Button` component that imports a `Progress` component. All other modules work fine, even those that import other components. The syntax is the same in every module.

## Directory structure

```
components
+--- index.js
+--- button
     +--- button.js
     +--- button.stories.js
     +--- index.js
+--- progress
     +--- progress.js
     +--- progress.stories.js
     +--- index.js
…
```

## Button module

```js
// components/button/button.js

import React from 'react'
import { Progress } from '..'

export function Button({ inProgress = false, label }) {
  return (
    <button>
      <span>{label}</span>
      {inProgress && <Progress />}
    </button>
  )
}
```

```js
// components/button/index.js

export { Button } from './button'
```

## Progress module

```js
// components/progress/progress.js

import React from 'react'

export function Progress() {
  return (
    <svg viewBox="0 0 50 10">
      <circle cx="5" cy="5" r="5" />
      <circle cx="25" cy="5" r="5" />
      <circle cx="45" cy="5" r="5" />
    </svg>
  )
}
```

```js
// components/progress/index.js

export { Progress } from './progress'
```

## Top level index

```js
// components/index.js

export { Button } from './button'
export { Progress } from './progress'
…
```

## The story

The failing story file looks like this:

```js
// components/button/button.stories.js

import React from 'react'
import { Screen, Section, Button } from '..'

export default {
  title: 'Button',
  component: Button,
}

export const Basic = () => (
  <Screen>
    <Section>
      <Button label="Register" />
      <Button label="Register" inProgress />
    </Section>
  </Screen>
)
```

## Workaround 1

If I import the `Button` to the story more directly, it works…

```js
// components/button/button.stories.js

import { Button } from './button'
import { Screen, Section, Button } from '..'
…
```

…but only if I also remove the export from the top-level index file:

```js
// components/index.js

// export { Button } from './button'
export { Progress } from './progress'
…
```

## Workaround 2

Another, simpler way is to change how the `Button` module imports `Progress`:

```js
// components/button/button.js

…
import { Progress } from '../progress'
…
```

## Workaround 3

It also works if the story doesn’t activate the the `Progress` module (so it doesn’t get rendered):

```js
// components/button/button.stories.js

import React from 'react'
import { Screen, Section, Button } from '..'

export default {
  title: 'Button',
  component: Button,
}

export const Basic = () => (
  <Screen>
    <Section>
      <Button label="Register" />
      // <Button label="Register" inProgress />
    </Section>
  </Screen>
)
```

## Replicating the button

I wanted to see what happens if I create a new `Button` module with the same code 
but different name (`Butt`). The stories failed for both (they both existed in the project at the same time, so that I saw two errored stories while the rest were all good).

I also renamed `Butt` to `Label`, but the error stayed.

## Changing Progress to another component

It seems it doesn’t matter if `Button` imports `Progress` or another component.
The error happened with other components too. For example:

```js
// components/button/button.js

import React from 'react'
import { Section } from '..'

export function Button({ inProgress = false, label }) {
  return (
    <button>
      <span>{label}</span>
      {inProgress && <Section />}
    </button>
  )
}
```

**Comment by Jack-Works** [comment]
Also having this problem on Storybook 6

**Comment by henrykuzmick** [comment]
I'm having this issue too, I've also noticed that if you build the storybook it works fine, it's just the development environment that fails.

**Comment by GLosch** [comment]
Has there been any update on this? I'm experiencing what looks like the same issue. Storybook 6.1.20, babel ^7, webpack 5.24.0

**Comment by GLosch** [comment]
storybook version 6.2.1 resolves this issue for me

**Comment by renemonroy** [comment]
I have version 6.2.2 and still gets this issue.
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/106011/113495014-70ef9500-94ab-11eb-8a30-ac5958304aee.png">

**Comment by BrenoMazieiro** [comment]
Still happening :'(

**Comment by gaurav5430** [comment]
FYI, I was facing a similar issue, but it was not due to import order, more details here:
https://github.com/storybookjs/storybook/issues/7390#issuecomment-875855974

**Comment by marcusglowe** [comment]
This was solved for us by setting [`sideEffects` in our package.json](https://webpack.js.org/configuration/optimization/#optimizationsideeffects)

**Comment by omril1** [comment]
This was solved for me by adding `import 'reflect-metadata';` at the top of the storybook entrypoint (preview.js/ts).
Without this some modules were being imported as empty modules.

**Comment by whodoeshua** [comment]
It's still happening at storybook@6.3.7. And the situation is totally same with what @gaurav5430 said.

The issue will always showed when I refresh the browser and dismiss after HRM work.

**Comment by cosmy81** [comment]
I have the same problem. 
`import {Title} from "components";`
doesn't work
`import {Title} from "components/index.js";`
doesn't work

`import Title from "components/Title";`
works

But this issue makes impossible to me to use storybook on my project, because I've written a lot of components using everywhere this notation (which is the correct way to write clean code):
`import { Text, Title } from "components";
`

**Comment by ashleynexvelsolutions** [comment]
@cosmy81 Any chance you might have gotten this resolved or found a workaround aside from `import Title from "components/Title";`?
