### ISSUE TITLE
Addon-docs: Options for vue-docgen-api

### ISSUE THREAD

**Issue by pocka** [storybookjs/storybook#9615]
**Is your feature request related to a problem? Please describe.**
For now, we can't pass options to vue-docgen-api. It's necessary when you use a module alias (e.g. `@` for a project root) and import files with it in a component file.

**Describe the solution you'd like**
Add a property something like `vueDocgenOptions` to addon-docs' preset option.

```js
// main.js
module.exports = {
  addons: [
    {
      name: '@storybook/addon-docs',
      options: {
        // naming could get better, someone help me :(
        vueDocgenOptions: { alias: { '@': path.resolve(__dirname, '../src') }}
      }
    }
  ]
}
```

**Describe alternatives you've considered**
I assume we need to pass options mostly because of alias, so retrieving `resolve.alias` from webpack config and passing it would also be good (both having options and doing this is better, of course).

**Are you able to assist bring the feature to reality?**
Yes

**Additional context**
https://github.com/vue-styleguidist/vue-styleguidist/issues/739

**Comment by shilman** [comment]
Ermahgerd!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-alpha.9 containing PR #9699 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

**Comment by leandromatos** [comment]
@shilman Apparently the problem is still happening.

Here's an example: https://codesandbox.io/s/agitated-monad-x8qzw?file=/nuxt.config.js

A message still appears in the terminal:

```sh
Neither '@ / mixins / SomeMixin.js.vue' nor 'terminal @ / mixins / SomeMixin.js.js (x)' or '@ / mixins / SomeMixin.js / index.js (x) 'or' @ / mixins / SomeMixin.js / index.ts (x) 'could be found in' / sandbox / components' 
```

**Comment by wickkidd** [comment]
Per @leandromatos' comment, [`options.vueDocgenOptions`](https://github.com/storybookjs/storybook/blob/v6.1.11/addons/docs/src/frameworks/vue/preset.ts#L9) is `undefined`. The `options` object is there, but `vueDocgenOptions` isn't part of it. 

Also, [`webpackConfig.resolve.alias`](https://github.com/storybookjs/storybook/blob/v6.1.11/addons/docs/src/frameworks/vue/preset.ts#L8) doesn't include any modifications you make in `main.js` even if you declare `@storybook/addon-docs` after `webpackFinal`. Granted, this may be intentional, but if not it makes me think that the issue may be something along the lines of order of execution. Even if the vanilla `webpackConfig` is desired here, `main.js` would still have to be parsed first for `vueDocgenOptions` to even exist. /$0.02

FWIW, having [`webpackConfig.resolve.alias`](https://github.com/storybookjs/storybook/blob/v6.1.11/addons/docs/src/frameworks/vue/preset.ts#L8) include `alias` modifications from `webpackFinal` in `main.js` would preclude having to set `vueDocgenOptions` at all for the purpose of setting the `docgenOptions.alias` given that the `docgenOptions.alias` is being set to [`webpackConfig.resolve.alias`](https://github.com/storybookjs/storybook/blob/v6.1.11/addons/docs/src/frameworks/vue/preset.ts#L8) anyway. Just a thought.

**Comment by pocka** [comment]
The primary purpose of inheriting `webpackConfig.resolve.alias` is for other presets, e.g. vue-cli, Nuxt.
Since we can't refer to the final `resolve.alias` object sits in your webpack config, you need the `vueDocgenOptions.alias` option when you're using custom aliases.
