### ISSUE TITLE
Addon-docs: Add code syntax highlighting to Description

### ISSUE THREAD

**Issue by liamross** [storybookjs/storybook#9825]
**Describe the bug**
Any markdown code fenced code snippets do not render correctly in the docs page.

This is for all version 6.0 alphas.

If you add the markdown to the component it doesn't work:

```jsx
/**
 * Hey there
 *
 * ```jsx
 * <div></div>
 * ```
 */
export const Component = () => {
};
```

If you add it to a separate md file and use `extractComponentDescription` in `preview.js` it doesn't work:

```md
Hey there

```jsx
<div></div>
.```
```

Result:

<img width="357" alt="Screen Shot 2020-02-11 at 1 26 01 PM" src="https://user-images.githubusercontent.com/24969218/74280833-296bdf80-4cd2-11ea-8dd0-2f506fd53084.png">

**To Reproduce**
1. Add any markdown fenced code snippet to your docs

**Expected behavior**

What it looks like when written inside of mdx docs:

<img width="1040" alt="Screen Shot 2020-02-11 at 1 26 30 PM" src="https://user-images.githubusercontent.com/24969218/74280846-2d97fd00-4cd2-11ea-9988-da6d30460e37.png">

**System:**
```bash
  System:
    OS: macOS 10.15.3
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.7 - /usr/local/bin/npm
  Browsers:
    Chrome: 80.0.3987.87
    Firefox: 72.0.2
    Safari: 13.0.5
  npmPackages:
    @storybook/addon-actions: ^6.0.0-alpha.9 => 6.0.0-alpha.9
    @storybook/addon-docs: ^6.0.0-alpha.9 => 6.0.0-alpha.9
    @storybook/addon-google-analytics: ^6.0.0-alpha.9 => 6.0.0-alpha.9
    @storybook/addon-info: ^6.0.0-alpha.2 => 6.0.0-alpha.2
    @storybook/addon-knobs: ^6.0.0-alpha.9 => 6.0.0-alpha.9
    @storybook/addon-links: ^6.0.0-alpha.9 => 6.0.0-alpha.9
    @storybook/addon-viewport: ^6.0.0-alpha.9 => 6.0.0-alpha.9
    @storybook/addons: ^6.0.0-alpha.9 => 6.0.0-alpha.9
    @storybook/preset-typescript: ^1.2.0 => 1.2.0
    @storybook/react: ^6.0.0-alpha.9 => 6.0.0-alpha.9
    @storybook/storybook-deployer: ^2.8.1 => 2.8.1
```

**Comment by shilman** [comment]
Ooh-la-la!! I just released https://github.com/storybookjs/storybook/releases/tag/v6.0.0-beta.29 containing PR #11183 that references this issue. Upgrade today to try it out!

You can find this prerelease on the `@next` NPM tag.

Closing this issue. Please re-open if you think there's still more to do.

**Comment by hadnet** [comment]
I'm trying to use the ts(x) syntax highlighting in the comment block, like this:

<img width="358" alt="Screen Shot 2020-11-20 at 3 06 55 PM" src="https://user-images.githubusercontent.com/13828833/99834714-63f88780-2b42-11eb-9231-072a8195066e.png">

 but I got this in description: 
<img width="709" alt="Screen Shot 2020-11-20 at 3 08 24 PM" src="https://user-images.githubusercontent.com/13828833/99834765-75da2a80-2b42-11eb-9b0f-fef617db39e7.png">

I'm using SB v6.1. How can I resolve this in order to works correctly?

**Comment by imekachi** [comment]
Still have this issue on `storybook@6.3.4`

![image](https://user-images.githubusercontent.com/5445243/125041975-8df7bd80-e0c3-11eb-9e53-d4821b9ae13e.png)
![image](https://user-images.githubusercontent.com/5445243/125040492-ee85fb00-e0c1-11eb-89a5-01e17ee211ae.png)
![image](https://user-images.githubusercontent.com/5445243/125041885-73254900-e0c3-11eb-99b6-2e2b89ea3f7a.png)


I've tried \`\`\`jsx, \`\`\`js, or plain \`\`\`, nothing works, did I do something wrong?

**Comment by m-demydiuk** [comment]
I have the same issue as @imekachi . My code block is shown in one line.

**Comment by zecka** [comment]
Has anyone found a solution here?

**Comment by lukket** [comment]
In my case, it did not work if there was no empty line before the code snippet.

---


> Lorem ipsum:
> \```json
> {
>   "foo": "bar"
> }
> \```


<img width="395" alt="image" src="https://github.com/storybookjs/storybook/assets/2588942/0cf5d6cd-d977-4b4d-9b63-ddb71d99113d">

> Lorem ipsum:
> 
> \```json
> {
>   "foo": "bar"
> }
> \```

<img width="393" alt="image" src="https://github.com/storybookjs/storybook/assets/2588942/be59df26-e76d-436b-8861-86e843016247">
